### ISSUE TITLE
DynamicResource is unsubscribing from the resource changes after it gets null/unset value once.

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/Avalonia#10110]
**Describe the bug**

In https://github.com/AvaloniaUI/Avalonia/pull/8166#issuecomment-1399403636 it was noticed that if some resources are defined only in one of many theme variants, DynamicResource stops working after switching between from variant with resource to the variant without the resource and back.
After some debugging, I found out that this issue is reproducible with plain DynamicResource without any theme variants as well.

**To Reproduce**

```csharp
[Fact]
public void Dynamically_Changing_Referenced_Resources_Works_With_DynamicResource()
{
    var xaml = @"
<UserControl xmlns='https://github.com/avaloniaui'
     xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml'>
  <UserControl.Resources>
    <Color x:Key='color'>Red</Color>
    <SolidColorBrush x:Key='brush' Color='{DynamicResource color}' />
  </UserControl.Resources>
</UserControl>";

    var userControl = (UserControl)AvaloniaRuntimeXamlLoader.Load(xaml);

    Assert.Equal(Colors.Red, ((ISolidColorBrush)userControl.FindResource("brush")!).Color);

    userControl.Resources.Remove("color");
    Assert.Equal(default, ((ISolidColorBrush)userControl.FindResource("brush")!).Color);
    
    userControl.Resources.Add("color", Colors.Blue);
    Assert.Equal(Colors.Blue, ((ISolidColorBrush)userControl.FindResource("brush")!).Color);
}
```

**Additional context**

If resource wasn't found, DynamicResource returns Unset value, which is expected.
But BindingEntryBase when [receiving unset value clears current binding value.](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/PropertyStore/BindingEntryBase.cs#L137-L142)
This code makes me think that it is an expected behavior. Still, I don't think that's how DynamicResource supposed to work.

Also, I tried to reproduce with simple subject and ToBinding set on the control, pushing unset value to the subject, but it was working perfectly.

**Desktop (please complete the following information):**

- Version: latest master

**Comment by amwx** [comment]
I'm wondering if this is related to #10039 especially since `Color` is a value type

Regardless, I agree I don't think this is correct. I would think `DynamicResource` should be kept alive even if its source disappears (as it could be a momentary thing) and should only terminate when its target (the brush) is terminated. FWIW, the simple example in the unit test works in WPF.

**Comment by amwx** [comment]
@maxkatz6 Seems the issue is still not fixed. [This branch](https://github.com/amwx/FluentAvalonia/tree/HCTest) is using nightly `11.0.999-cibuild0029961-beta` (from this evening). Loading the HighContrast theme on startup or switching to it still doesn't work - all the brushes are still saying Transparent

<img src="https://user-images.githubusercontent.com/40413319/218636698-c38036d4-0a7a-4224-8545-0c0a951ba3c6.png" width="500" />

The light and dark themes have the brushes that the HighContrast theme uses but not the colors (they're set to magenta to distinguish they shouldn't be used in those themes - same as WinUI). So I copied the colors over to the light & dark dictionaries and it seems to be working fine (minus TextBoxes, but that an unrelated issue)

<img src="https://user-images.githubusercontent.com/40413319/218637094-a1ed4418-cbc5-45dd-bc51-0a0dfe654598.png" width="500" />

I'll just add the colors to light/dark dictionaries as a workaround but I'm still not sure why this is happening.
