### ISSUE TITLE
ListBoxItem.IsSelected Binding does not work anymore with preview5

### ISSUE THREAD

**Issue by llfab** [AvaloniaUI/Avalonia#10249]
**Describe the bug**
I am binding a ListBoxItem's IsSelected property to my data model of the item as follows:
```
          <ListBox SelectionMode="Single, Toggle" 
                   Items="{TemplateBinding Items}" 
                   SelectedItem="{Binding SelectedItem, RelativeSource={RelativeSource TemplatedParent}}"
                   ScrollViewer.HorizontalScrollBarVisibility="Disabled"
                   ScrollViewer.VerticalScrollBarVisibility="Auto">
            <ListBox.Styles>
              <Style Selector="ListBoxItem">
                <Setter Property="IsEnabled" Value="{Binding IsSelectable}" />
                <Setter Property="IsSelected" Value="{Binding IsSelected}" />
                ...
```

Originally I even had 
```
<Setter Property="IsSelected" Value="{Binding Path=IsSelected, Mode=TwoWay}" />
```
to receive the changed selection directly in the items data model. 

This has worked in preview4 but is not working anymore in preview5. As I checked in the Debugger, the IsEnabled property works nicely and the property getter in the data model is called. For IsSelected neither the getter nor the setter (if used with TwoWay) is called. 

**To Reproduce**
as above

**Expected behavior**
Getter and setter for the data model property should be called

**Desktop (please complete the following information):**

- OS: Windows 10
- Version [11.0.0-preview5]

**Comment by grokys** [comment]
This is no longer working because it's dependent on the order in which the style is applied in respect to the `ListBox` setting the `IsSelected` property. Before #8600, the style was applied before `SelectingItemsControl.MarkContainerSelected` was called but now they're called in the reverse order.

Not sure what we should do here. If we want this to work, we'd have to think about how best to do it without being dependent on in which order `IsSelected` is set. But do we want to explicitly support this use-case? We already have quite a few ways to get selection status from the view model layer to the view layer:

- `SelectingItemsControl.SelectionModel`
- `SelectingItemsControl.SelectedItems`
- Implementing `ISelectable` on the (view)model

Is there any reason you can't use any of the existing explicitly supported mechanisms @llfab ?

**Comment by llfab** [comment]
No, there is no reason. In fact, we already changed to ```SelectedItem```. I believe the ```IsSelected``` was a good fit the the VM/M implementation that we used but it was just a minor change to go to your proposed way. If ```IsSelected``` cannot or shall not be used anymore, maybe that is worth mentioning it in docu.

**Comment by llfab** [comment]
If ```IsSelected``` creates "order problems" I would actually not support that. ```SelectedItem(s)``` will always be sufficient.

**Comment by grokys** [comment]
Ok, great. Yeah I'll add that to the list of things we need to document for 11.0.

**Comment by llfab** [comment]
However, ```IsSelected``` within the control (just not as binding) does work and should continue to work because you need that to apply the correct style, right?

**Comment by grokys** [comment]
Going to reopen this as it's going to cause problems as people expect this to work.
