### ISSUE TITLE
BclStorageFolder.GetItemsAsync Not Async

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUI/Avalonia#10290]
I was looking at the BclStorageFolder code.

I notice that the async methods, particularly GetItemsAsync that can return hundreds or thousands of elements, is not async at all.

https://github.com/AvaloniaUI/Avalonia/blob/cdc7bf396c3ecdedeec630967d7deb64525c62cf/src/Avalonia.Base/Platform/Storage/FileIO/BclStorageFolder.cs#L69

This probably could be implemented better.

I'm also noting that BclStorageFile.CanOpenWrite always returns true; but there doesn't seem to be reliable way of knowing it other than opening the file and catching the error.

https://github.com/AvaloniaUI/Avalonia/blob/cdc7bf396c3ecdedeec630967d7deb64525c62cf/src/Avalonia.Base/Platform/Storage/FileIO/BclStorageFile.cs#L24

Using Avalonia11-preview5

**Comment by maxkatz6** [comment]
> I notice that the async methods, particularly GetItemsAsync that can return hundreds or thousands of elements, is not async at all.

There is no async API in the BCL to get items. So it can't be really implemented better. 
Having async interface API not necessary means it always will start an async IO operation. Heavily depends on the platform backend. 

> I'm also noting that BclStorageFile.CanOpenWrite always returns true; but there doesn't seem to be reliable way of knowing it other than opening the file and catching the error.

Here I agree, that API isn't quite clear. CanOpenWrite currently indicates if platform supports open write.
Should it check permissions? Which bcl API it should use internally?

**Comment by mysteryx93** [comment]
If you call `EnumerateFiles`, you can start processing each item as they are returned. Currently, the ToArray forces all items to be loaded in memory first before returning, making it basically useless for very large folders.

if you really want async, you can do Task.Run until the first result comes back. That would make a difference with an external hard drive that needs a few seconds to boot up on first access.

As for CanOpenWrite... I was looking at that yesterday. There is no better approach to it than trying to open the file and catching any error... which wouldn't make much sense when used like this.

```c#
if (file.CanOpenWrite)
    var write = await file.OpenWriteAsync();
```

**Comment by mysteryx93** [comment]
To make `GetItemsAsync` useful, it should return `IEnumerable` instead of `IReadOnlyList`.

Use `EnumerateFileSystemInfos` instead of querying files and directories separately.

Then while being at it, why not offer SearchPattern and SearchOption.

Something similar to this should work.

```c#
public IEnumerable<IPathInfo> EnumeratePathInfos(string searchPattern, SearchOption searchOption) => _info.EnumerateFileSystemInfos(searchPattern, searchOption)
        .Select<FileSystemInfo, IPathInfo>(x => x is System.IO.FileInfo f ? new FileInfo(f) : new DirectoryInfo((System.IO.DirectoryInfo)x));
```

It's still not an async method but allows processing the data as it comes.

If we wrap EnumerateFileSystemInfos inside Task.Run, then it should be async until the first item and then allow looping through the IEnumerable.

**Comment by maxkatz6** [comment]
> As for CanOpenWrite... I was looking at that yesterday. There is no better approach to it than trying to open the file and catching any error... which wouldn't make much sense when used like this.

Makes sense. I think we should remove CanOpenRead and CanOpenWrite. Especially, as I just noticed, it ended up returning "true" always on all platforms.

**Comment by maxkatz6** [comment]
With this API we are going from the common denominator between platforms.

> People would write their own IO classes for more advanced scenarios.

That's what I would say as well. If needed, people can branch their code on desktop platforms and using .NET API directly (or even platform API directly) for the efficiency, and possibly converting paths to IStorageFile with TryGetFileFromPath (if needed). And on non-supported platforms like browsers, they can fallback to slower GetItemsAsync.

> if you really want async, you can do Task.Run until the first result comes back. That would make a difference with an external hard drive that needs a few seconds to boot up on first access.

Normally, I would say that async APIs that just call Task.Run internally have a quite bad reputation. As it ends up being useless, since developers could use Task.Run by themselves if they need. Otherwise, it's just a waste to thread-pool.
But in current situation, when that's depends on interface implementation, some backends might even require UI thread, which makes `Task.Run(() => folder.GetItemsAsync())` quite dangerous operation.

> public Task<IEnumerable<IDialogStorageItem>> GetItemsAsync()

I think this idea makes sense.
Alternatively, it can be `IAsyncEnumerable<IDialogStorageItem>` which we can even fully support on the browser backend (!). And just wrap over EnumerateFiles on desktop.

**Comment by maxkatz6** [comment]
Added these two API changes to the list of this issue https://github.com/AvaloniaUI/Avalonia/issues/9876

**Comment by mysteryx93** [comment]
> I would say that async APIs that just call Task.Run internally have a quite bad reputation

Why? I think it's worse to have an async method that "magically" doesn't behave async. In what context does it need to be run in the UI thread and running from different thread is dangerous?

**Comment by maxkatz6** [comment]
> In what context does it need to be run in the UI thread and running from different thread is dangerous?

It's not about BCL implementation. On the browser you simply cannot start a new thread, for example. Some of the Android APIs require main thread as well, but I don't think it's applicable here.

I mentioned Task.Run as there is basically two ways to ensure it is async even if some implementations are not.
Either run Task.Run inside of sync backend (like BCL) in the framework code, or always run all GetItemsAsync call inside of Task.Run (regardless of the backend) in the user code.
And in this context, second option is more dangerous that the first one.

**Comment by mysteryx93** [comment]
Here we're talking about the BCL implementation. I think it's fine to have async handled differently for each platform, and shouldn't be up to the calling user to figure that out per platform.

**Comment by maxkatz6** [comment]
So far I am thinking about implementing `IAsyncEnumerable<IStorageItem>` API instead of current one.
On BCL it won't be async, but at least it won't also load all items in the memory as you said.
And on Browser it can be both async and lazy.

We can technically do pinvokes to get truly async and lazy implementation, which is supported in Windows AFAIK, but not in the .NET API. But I don't have much knowledge about low level IO on windows.
