### ISSUE TITLE
`OnOpenGlInit` will be called twice

### ISSUE THREAD

**Issue by jcyuan** [AvaloniaUI/Avalonia#10371]
**Describe the bug**
just found that the method `OnOpenGlInit` in my class extended from `OpenGlControlBase` will be called twice while being initialized (in both my project and the OpenGL demo in the official Control Gallery), here is the calling stack:

![1676569145555](https://user-images.githubusercontent.com/850854/219446541-99a979bb-d512-4a32-83d9-d4ee31c3dd5f.png)
1st

![1676569173576](https://user-images.githubusercontent.com/850854/219446591-c33ac5d7-1cc1-4fdd-906e-d838b73ba70a.png)
2nd

**Desktop:**
- OS: Windows
- Version: 10

**Additional context**
Renderer: ANGLE NVIDIA GeForce GTX 1080 D3D11, OpenGL ES 3.0

**Version**
11.0.0-preview5

**Comment by Gilfoylex** [comment]
Can someone explain why this is happening?

**Comment by jcyuan** [comment]
> Can someone explain why this is happening?

because the async init called twice (something similar with that), you can simply use a bool tag in the init method to avoid the second calling before this will be fixed.

**Comment by wannkunstbeikor** [comment]
Is it planned to fix this issue, since it seems like a simple fix, just need to remove one of the calls to `OnOpenGlInit` going of the older code prior to this [commit](https://github.com/AvaloniaUI/Avalonia/commit/d714f37fce8b01b38f2ad61fc2bd2d7fb981b88a) the one in `EnsureInitializedCore` was not there, so I would guess this one needs to be removed. But from what I can tell it does not really matter which one gets removed, since `EnsureInitializedCore` is only called by `InitializeAsync` and after that call nothing is done except calling `OnOpenGlInit`.

**Comment by wannkunstbeikor** [comment]
I can try to make a PR, but what kind of tests should I add for this?

**Comment by CalvinWilkinson** [comment]
I can confirm that this is happening as well.
