### ISSUE TITLE
ListBoxItems not drawing correctly when bound collection updates in 11-preview5

### ISSUE THREAD

**Issue by agnauck** [AvaloniaUI/Avalonia#10399]
**Describe the bug**
After updating to preview5 ListBoxItems are not always getting displayed correctly when the bound collection is changing.
In the sample below the collection is getting filtered using a search text.
When scrolling items out of the view they seem to redraw correctly when they appear again

**Expected behavior**
After collection changes the items should be drawn correctly

**Screenshots**
![list-bug](https://user-images.githubusercontent.com/1344950/219974925-3f1a72de-57a3-4662-be3e-93aeb94884fd.gif)

**Desktop (please complete the following information):**
- OS: Windows 11
- 11.0.0-preview5

**Comment by maxkatz6** [comment]
Can you provide a minimal sample project?

**Comment by agnauck** [comment]
I have created a minimal sample project, see here:
https://github.com/agnauck/AvaloniaListBoxBug1

**Comment by agnauck** [comment]
yes it seems to be related to the VirtualizingStackPanel rewrite.
When virtualization is disabled it works as expected.

**Comment by grokys** [comment]
This is a threading bug. Dynamic data sends multiple change updates[^1] on a background thread, which are dispatched to the UI thread with `Normal` priority, but this priority is lower than `Layout` priority so what happens is:

- Collection changed
- Layout
- Collection changed
- Layout
- Collection changed
- Layout
- [...]

`VirtualizingStackPanel` maintains its own mapping of Items -> Containers, and updates that mapping when a `CollectionChanged` event is received, but it also expects that mapping to be up-to-date when a layout is performed.

I think the fix is to dispatch `CollectionChanged` events to the UI thread at a higher priority than `Layout` here: 

https://github.com/AvaloniaUI/Avalonia/blob/31a691c55032e5be69776f4279612a516c415bcc/src/Avalonia.Controls/Utils/CollectionChangedEventManager.cs#L144

[^1]: WPF can't handle adds/removes of more than one item so dynamic data has to send a `CollectionChanged` for each item added/removed individually)
