### ISSUE TITLE
TreeDataTemplate does not generate children [11-preview5]

### ISSUE THREAD

**Issue by stevemonaco** [AvaloniaUI/Avalonia#10398]
**Describe the bug**
I am using `TreeDataTemplate` to show a generated tree in a `TreeView`. Starting in 11-preview5, only the root nodes are shown. Same behavior under nightly (11.0.999-cibuild0030252-beta).

Below is the most relevant XAML. I am using compiled bindings and there are no warnings in the VS Output window. The node `Children` collections are populated in the debugger. Collections are created once in the constructor and are never replaced. IIRC, there were no `TreeViewItem` node children in 11-preview5+ in DevTools, only for the root nodes.

```xml
<TreeView Items="{Binding Items}">
    <TreeView.DataTemplates>
        <TreeDataTemplate DataType="vm:BranchNodeViewModel" ItemsSource="{Binding Children}">
            <TextBlock Text="{Binding Children.Count, StringFormat=[BranchNode - Children: {0}]}" />
        </TreeDataTemplate>
        <TreeDataTemplate DataType="vm:LeafNodeViewModel" ItemsSource="{Binding Children}">
            <TextBlock Text="[LeafNode]" />
        </TreeDataTemplate>
    </TreeView.DataTemplates>
</TreeView>
```

**To Reproduce**
1. [Clone this repro](https://github.com/stevemonaco/AvaloniaTreeDataTemplateRepro)
2. Run the app to see the top `Grid` `TreeView` works under 11-preview4
3. Update to 11-preview5 (or nightly), fixup `IControl` -> `Control` in `ViewLocator`, run the app, and see it no longer generates children.

**Expected behavior**
I expect that the nodes with children are expandable.

**Screenshots**
The repro has a `TreeDataTemplate` generated hierarchy on the top pane and the bottom pane has one that defines a hierarchy manually via `TreeViewItem`.

11-preview4 correctly has expanders and children for the templated-generated pane:
![image](https://user-images.githubusercontent.com/1782158/219969528-a2e860d8-22fc-40ca-b757-1f0f842aa3a9.png)

11-preview5 (and nightly) do not:
![image](https://user-images.githubusercontent.com/1782158/219969696-a24ad4fe-b6ea-4eee-aab1-a9c56f900fdb.png)

**Desktop (please complete the following information):**
- OS: Windows 10
- Version: 11-preview4 (working), 11-preview5 (not working), 11.0.999-cibuild0030252-beta (not working)

**Comment by mightypanda** [comment]
Hello,
After migrating to 11-preview5 i experimented this behaviour, while preview4 is working.
In my hierarchical datamodel, the ItemsSource ObservableCollection getter is never accessed.
I worked-around it creating a wrapper HierarchyItem object that just redirect Items to the underlying observable collection.

**Comment by timunie** [comment]
I found a workaround: https://github.com/stevemonaco/AvaloniaTreeDataTemplateRepro/pull/1

The reason seems to be that only `ItemTemplate` is respected since preview5. If this is a bug or intended, I cannot say.

**Comment by stevemonaco** [comment]
Thanks. This workaround to add an `ItemTemplate` also works in my real application.

```xml
<TreeView.ItemTemplate>
    <TreeDataTemplate DataType="vm:NodeViewModel" ItemsSource="{Binding Children}">
        <ContentControl Content="{Binding}" />
    </TreeDataTemplate>
</TreeView.ItemTemplate>
```

**Comment by timunie** [comment]
👀

**Comment by grokys** [comment]
Ok, I see what's happening. If one removes the view locator in `App.axaml` in the repro then it starts working.

The cause is the following:

- [PanelContainerGenerator](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Presenters/PanelContainerGenerator.cs#L139) prepares the item before adding it to the logical tree
- When `ItemsControl` tries to find the data template, it first tries to find it [relative to the `TreeViewItem`](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/ItemsControl.cs#L387)
- If there is no `ViewLocator` in `App.axaml` then `hic.FindDataTemplate(item)` returns null, so it then tries to find it relative to the `TreeView` (the code after the `??`)
- If there is a `ViewLocator` in `App.axaml` though, this data template is found and used, meaning that the code after `??` is never executed
