### ISSUE TITLE
Tmds.DBus

### ISSUE THREAD

**Issue by tmds** [AvaloniaUI/Avalonia#10605]
hi, I'm the maintainer of Tmds.DBus.

I noticed you've cloned the library: https://github.com/AvaloniaUI/Tmds.DBus.
And from the changes I wonder if you're forking the code?

If you're forking the code, I wonder if there are changes we can make upstream, which make the fork unnecessary?

cc @kekekeks

**Comment by timunie** [comment]
I think it was done in https://github.com/AvaloniaUI/Avalonia/pull/9810 probably. Let me add @affederaffe as he was the author of the PR.

**Comment by kekekeks** [comment]
@tmds We are concerned about `Nerdbank.Streams` dependency pulling way too many additional libraries. This dependency wasn't there previously in `Tmds.DBus` package. As a UI toolkit, we have to keep the list of dependencies minimal, we've even removed a dependency on System.Reactive because it pulls extra deps when targeting `net6-windows10`.

Also, we don't see why a DBus library needs  `System.Security.Principal.Windows` dependency.


In the fork I've removed dependencies on those: https://github.com/AvaloniaUI/Tmds.DBus/commit/c6900b5b13c56a6e36462030dbeaca5865e055e8

I doubt that such changes would be accepted to the upstream, so the current plan is to include `Tmds.DBus.Protocol` as source code with public types made internal.

**Comment by maxkatz6** [comment]
@tmds I have a recommendation. Instead of `RuntimeInformation.IsOSPlatform(OSPlatform.Windows)` it's better to use `OperatingSystem.IsWindows()` (available starting net6).
This way, .NET compiler will be able to trim this whole dependency (which is still referenced but implicitly now) on non-windows runtime identifiers.

**Comment by tmds** [comment]
@kekekeks can you make a PR with your change that removes the dependency on `Nerdbank.Streams` and its dependencies?

**Comment by maxkatz6** [comment]
@tmds done https://github.com/tmds/Tmds.DBus/pull/189

**Comment by tmds** [comment]
The desired changes are now available on the 0.14.0 version which I've just uploaded to nuget.org.
