### ISSUE TITLE
Clarification in license file is needed

### ISSUE THREAD

**Issue by mwisnicki** [AvaloniaUI/Avalonia#10634]
Main [license ](https://github.com/AvaloniaUI/Avalonia/blob/master/licence.md) file should probably warn that it doesn't cover whole project and some parts are now [proprietary](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Rendering/Composition/License.md).

**Comment by kekekeks** [comment]
I believe it's planned to be MIT again once 11.0 is out.

**Comment by Ilariel** [comment]
Whether it is temporary or not the main licensing should certainly be clarified since even on NuGet the license is just MIT and even I noticed that hidden proprietary code accidentally only after spending considerable time on doing research on the source.

Especially since this part of the proprietary license could be interpreted as "Only official Avalonia binary packages"
> This code may be used free of charge by any application that consumes Avalonia binary packages as a direct or indirect dependency.

which certainly limits my usage for example if I have to build my own version of Avalonia.Base which could be or could be not against the terms.

**Comment by kekekeks** [comment]
You can build your own version as long as the code lives in `Avalonia.Something.dll`

**Comment by MichalPetryka** [comment]
> I believe it's planned to be MIT again once 11.0 is out.

Is making this code MIT again still planed for 11.0?

**Comment by teo-tsirpanis** [comment]
With #11992 the proprietary license was withdrawn and Avalonia is entirely MIT.
