### ISSUE TITLE
[11.0.0-preview5+] Can't debug in VSCode on .NET 6

### ISSUE THREAD

**Issue by psyGamer** [AvaloniaUI/Avalonia#10859]
**Describe the bug:**
When using v11.0.0-preview5 onward, debugging a .NET 6 application with Visual Studio Code no longer allows you to inspect variables. It gives me the following error:
`error CS1705: Assembly 'AvaloniaTest' with identity 'AvaloniaTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' which has a higher version than referenced assembly 'System.Private.CoreLib" mit Identität "System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'`

**To Reproduce:**

1. Clone this repo: https://github.com/psyGamer/AvaloniaTest
2. Create a breakpoint somewhere (for me it was the constructor of MainWindow)
3. Start the debugger in VSCode and hit the breakpoint
4. No variables are shown and typing `this` in the debug console throws the error

**Expected behavior**
Be able to inspect the variables like in v11.0.0-preview4 and before.

**Desktop:**

- OS: Arch Linux

**Aditional Context:**
Switching to .NET 7 solves this problem, however changing the .NET version just for debugging isn't really an option.

**Comment by ivanjx** [comment]
maybe has something to do with the sdk version avalonia is using here https://github.com/AvaloniaUI/Avalonia/blob/master/global.json

**Comment by maxkatz6** [comment]
Not sure if it's an Avalonia bug.

**Comment by robloo** [comment]
I have the same issue when trying to debug code in the ColorPicker project. It makes things very difficult.

I never filed an issue for it because I expected it to be an SDK or VS issue -- however, it still hasn't been resolved. Also note that he issue occurs in Rider as well so definitely an SDK or Avalonia issue.

**Comment by heuristicAL** [comment]
Just chiming in here to mention that I also get the same issue, it also seems to crop up only in solutions referencing Avalonia.

**Comment by maxkatz6** [comment]
Just in case, this issue is solved when you switch from .NET 6 to .NET 7 target framework. 
preview4 was the first version to be built with .NET 7 SDK on ours CI, and we need it for a newer platform features-set.
Note, that Avalonia still targets .NET 6 and .NET Standard 2.0.

It's not clear, why it exactly happens with Avalonia libraries (and if does it happen with other built with .NET 7 SDK but used with .NET 6 target framework). And if it's an issue in SDK or Avalonia itself.

If anybody knows possible reason or related issue in .NET repositories, let us know.

**Comment by maxkatz6** [comment]
Possible reason is that Cecil from XAML compiler adds system.private.corelib 7.0 in 6.0 build.

![image](https://github.com/AvaloniaUI/Avalonia/assets/3163374/6f421413-fc78-4ad0-a0f7-7dd7e5ac5bb2)

**Comment by heuristicAL** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/10859#issuecomment-1543417002

That's a good find @maxkatz6 . Any idea WHY it's added and if it's needed? Might have just been an oversight?
