### ISSUE TITLE
DataGrid rows are getting mixed up when scrolling

### ISSUE THREAD

**Issue by ashotjanibekyan** [AvaloniaUI/Avalonia#10948]
My View looks like this

```
    <Grid RowDefinitions="Auto,*">
        <Label Grid.Row="0" Content="{Binding Greeting}" />
        <DataGrid
            Grid.Row="1"
            Items="{Binding Rows}"
            VerticalScrollBarVisibility="Visible"
            RowBackground="#EEEEEE">
            <DataGrid.Columns>
                <DataGridTextColumn Width="auto" Header="Index" Binding="{Binding Index, Mode=OneTime}" />
                <DataGridTextColumn Width="auto" Header="Name" Binding="{Binding Name, Mode=OneTime}" />
                <DataGridTextColumn Width="auto" Header="Value" Binding="{Binding Value, Mode=OneTime}" />
            </DataGrid.Columns>
        </DataGrid>
    </Grid>
```

Where Rows is an ObservableCollection of Row objects. The index should go from 1 to 200 but when scrolling, rows are getting mixed up (see the attached screen recording; https://youtu.be/iXFgCA1w0t8).

**Desktop (please complete the following information):**

- OS: Windows
- Version 22H2

**Comment by workgroupengineering** [comment]
It is a known container recycling issue,turn off recycling or change binding mode to OneWay.

**Comment by ashotjanibekyan** [comment]
@workgroupengineering Thanks a lot, changing the binding mode to OneWay solved the issue. But I don't understand what do you mean by "turn off recycling", how do I do that?

**Comment by maxkatz6** [comment]
Not sure if it's an issue, as this behavior seems to be "expected" with OneTime bindings. I would even add validation to disallow users to use OneTime in here.

In short, "OneTime" will do exactly what it should - get values to the container one time. But since containers (cells) are reused in the datagrid instead of creating a new one for each row, it won't work properly, it needs to be dynamic OneWay.
