### ISSUE TITLE
Listbox extreme memory usage and low performance when nested and in a tab control

### ISSUE THREAD

**Issue by thevortexcloud** [AvaloniaUI/Avalonia#10968]
**Describe the bug**
In version 11 preview 6: A list box with thousands of items seems to spiral out of control with memory usage when nested inside another list box, and switching between tab items. Once it gets stuck in this state; memory usage climbs from the initial ~200mb to >2gb and the frame rate of the window drops to single digits.

**To Reproduce**

1. Run the attached minimal repo.
2. Switch to the "Other tab".
3. Switch back to the "Main" tab (this may take several seconds).
4. Observe extreme degradation of performance when attempting to scroll through the list box again

[AvaloniaIssues.zip](https://github.com/AvaloniaUI/Avalonia/files/11187223/AvaloniaIssues.zip)

**Expected behavior**
The list box should behave like it did when the window first loaded, with a high frame rate and relatively low memory usage.

**Screenshots**

Memory profile graph from Rider:
![image](https://user-images.githubusercontent.com/110272833/230814724-6c08df41-4e16-41e6-9386-36527add0dc7.png)

**Desktop (please complete the following information):**

- OS: Linux, Ubuntu 22.04
- Version 11.0.0 Preview 6

**Additional context**
This issue does not occur in 0.10.19 and memory usage remains rock solid.  

Also according to Rider the highest memory usage is coming from `ServerCompositionDrawListVisual`. However my experience with Rider's profiling tools is extremely minimal so I am not entirely sure how to interpret the results. 

I am also happy to do a screen capture of the issue if it helps.

**Comment by jp2masa** [comment]
Did you try setting `MaxHeight` on the inner `ListBox`?

**Comment by jp2masa** [comment]
Is there any particular reason for not using a `VirtualizingStackPanel` in the outer `ListBox`?

Still, this seems to be a bug related to fluent theme, it works fine on simple theme.

**Comment by timunie** [comment]
I wonder how 11.0.5 behaves here. We had some fixes for lists

**Comment by timunie** [comment]
Only if you have the time to. You provide a sample, so I can also check on my own

**Comment by maxkatz6** [comment]
Coming from #13152, it doesn't seem like this sample has any memory leaks:
![image](https://github.com/AvaloniaUI/Avalonia/assets/3163374/39fdfd36-29d1-4abe-8825-7616a7812c9b)

GC has no problems with collecting objects after multiple tab switches.

**Comment by maxkatz6** [comment]
Specifically this code does look very un-optimal, where huge horizontal lists are not virtualized because of the outer horizontal scroll-viewer. On top of that outer lists have disabled virtualization (StackPanel is used instead of VirtualizedStackPanel in the ItemsPanel). Which makes RAM usage not surprising at all.

Replacing StackPanel with VirtualizingStackPanel, and removing `ScrollViewer.HorizontalScrollBarVisibility="Visible"` solves both virtualization issues, and the application becomes way more responsible.

I assume, the initial intention was to synchronize scrolls of inner lists, it can be done in another way with bindings or code behind/behavior - https://github.com/AvaloniaUI/Avalonia/discussions/8046

**Comment by maxkatz6** [comment]
> I wonder if this is a Linux specific issue

You can check with any decent memory profiler what exactly holds objects in the memory in your case. 
I usually use dotMemory, not sure if Visual Studio can show that easily.

**Comment by MrJul** [comment]
I had a look at this. While the initial example is indeed not optimal, there's a real underlying bug: as you noticed, every virtualized element is realized instead of only the visible ones. This explains the huge memory consumption and the huge time needed to switch between tabs.

----

Minimal repro:

```xaml
<TabControl>
  <TabItem Header="Tab 1">
    <ScrollViewer>
      <ListBox x:Name="ListBox1" Height="200" Margin="24,4000,24,24" />
    </ScrollViewer>
  </TabItem>
  <TabItem Header="Tab 2" />
</TabControl>
```

```csharp
ListBox1.ItemsSource = Enumerable.Range(0, 10000).ToList();
```

Switch from Tab 1 to Tab 2 and back.

----

I've got a fix ready for it. I'll open a PR.
