### ISSUE TITLE
Issue with FilePicker on Mozilla Firefox if called in AsyncRelayCommand

### ISSUE THREAD

**Issue by dbriard** [AvaloniaUI/Avalonia#11041]
**Describe the bug**
I think I already read about this bug, but I cannot find it... so here it is:

On WASM with Mozilla Firefox, if you close the file picker without selecting a file (cancel), the file picker will never show again. This is really problematic.

**To Reproduce**

1. Implement a OpenFile button that call OpenFilePickerAsync() 
2. Run in WASM with Firefix
3. Click Open, the file picker is displayed, then cancel without selecting a file.
4. Click Open again... nothing append... 
5. (same issue with SaveFilePickerAsync)

**Expected behavior**
Cancelling a FilePicker must not make FilePicker to never display again with Firefox.

**Desktop (please complete the following information):**

- OS: WASM and **Mozilla Firefox** (Windows 10)
- Version 11 preview 6

**Additional context**
Works fine with Edge and Chrome.

**Comment by dbriard** [comment]
Hum... in fact I found what caused the issue and a workarpound but I don't understand why.

```
SaveCommand = new **Async**RelayCommand(Open); // Issue with Firefox
public async **Task** Open() 
    {
            var options = new FilePickerOpenOptions()
            {
                Title = "Open file",
                FileTypeFilter = new List<FilePickerFileType> { FilePickerFileTypes.ImageAll }
            };
            var result = await GetStorageProvider().OpenFilePickerAsync(options);
```
            
```
SaveCommand = new RelayCommand(Open); // No more issue!
public async **void** Open() 
    {
            var options = new FilePickerOpenOptions()
            {
                Title = "Open file",
                FileTypeFilter = new List<FilePickerFileType> { FilePickerFileTypes.ImageAll }
            };
            var result = await GetStorageProvider().OpenFilePickerAsync(options);
```

**Comment by kekekeks** [comment]
That's firefox limitation, it doesn't provide a proper file picker API, so we have to create a `<form><input .../>` and simulate a click. There is no event for "user cancelled the action" unfortunately.

**Comment by kekekeks** [comment]
In your case the problem was in AsyncRelayCommand disabling itself until the Task is completed, which doesn't happen if use cancels the action.

**Comment by maxkatz6** [comment]
Yes, we can't do much here.

**Comment by dbriard** [comment]
@maxkatz6 @kekekeks Thanks guys! I didn't needed **Async**RelayCommand in the first place, but the explanation make sense!

**Comment by Der-Floh** [comment]
@maxkatz6 @kekekeks 

I also had this issue and traced and fixed the root cause in the [native-file-system-adapter](https://github.com/jimmywarting/native-file-system-adapter/pulls). The PR is open there but still needs to complete / merge.

**The root cause and fix have been fully traced — here's the complete status.**

### Root cause

Firefox doesn't implement the native [File System Access API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_API), so Avalonia falls back to the [`native-file-system-adapter`](https://github.com/jimmywarting/native-file-system-adapter) polyfill, which simulates pickers via a hidden `<input type="file">`. The polyfill only subscribes to the `change` event to resolve its internal Promise — which only fires when the user *selects* a file. On cancel, no event fires, the Promise hangs indefinitely, and any `AsyncRelayCommand` awaiting it is permanently stuck.

### Why the existing polyfill commit doesn't help

Commit [`23662ab`](https://github.com/jimmywarting/native-file-system-adapter/commit/23662abfc58184bcb14ee8ca2f32269f6362d278) in the upstream polyfill was meant to fix this by also subscribing to `oncancel`, but contains a typo that makes it a no-op — `onchange` is assigned twice instead of assigning both `onchange` and `oncancel`:

```js
// 23662ab — broken, oncancel never subscribed
input.onchange = input.onchange = resolve
```

### The fix

I've opened a PR to the upstream polyfill to correct the typo in both `showOpenFilePicker.js` and `showDirectoryPicker.js`:
**jimmywarting/native-file-system-adapter#102**

```js
// fixed
input.onchange = input.oncancel = resolve
```

The C# side in `BrowserStorageProvider.cs` is already correct — it catches `JSException` with `"The user aborted a request"` and returns an empty result, so no C# changes are needed.

### What needs to be done once the PR merges

**1. The polyfill pin in `src/Browser/Avalonia.Browser/webapp/package.json` needs updating:**
```json
"native-file-system-adapter": "github:jimmywarting/native-file-system-adapter#<merge-commit-of-pr-102>"
```

**2. one breaking change introduced between the current pin and latest upstream needs to be handled** — commit `54875b9` removes the `_preferPolyfill` backward-compat shim. Avalonia's `storageProvider.ts` passes `_preferPolyfill: preferPolyfill` to all three picker calls. The replacement is `_preferredMethods`:

```ts
// storageProvider.ts — current (broken after 54875b9)
_preferPolyfill: preferPolyfill

// replace with
_preferredMethods: preferPolyfill ? ['input'] : ['native', 'input']
```

On Firefox this is a no-op (no native API exists so the polyfill is always used), but it restores correct behaviour of `BrowserPlatformOptions.PreferFileDialogPolyfill` on Chromium.

All other commits between the current pin and latest upstream are additive and safe.

I'm going to do this all and update this Message accordingly.
Tracker:
- [x] `native-file-system-adapter`: Traced Issue
- [x] `native-file-system-adapter`: [Create PR](https://github.com/jimmywarting/native-file-system-adapter/pull/102)
- [ ] `native-file-system-adapter`: PR Merged
- [ ] `avalonia`: Update polyfill commit in package.json
- [ ] `avalonia`: Fix breaking change
- [ ] `avalonia`: Create PR
- [ ] `avalonia`: PR Merged

Ideally this Issue would be reopened.
