### ISSUE TITLE
ColorPicker Hue Slider not displayed correctly

### ISSUE THREAD

**Issue by dbriard** [AvaloniaUI/Avalonia#11059]
**Describe the bug**
The background of the hue slider of ColorPicker is not displayed correctly.
It should not change according to selected color, and should keep bright and saturated.

**To Reproduce**
1. Create a ColorPicker with SaturationValue component
2. Change the color
3. See the background of the Hue slider
4. It is changing, but this is not the normal behavior of such control.
5. It can even become pure black or pure white which is not correct.
6. The correct rendering is the one when the selected color is at top-right location.

**Expected behavior**
The Hue slider should always look like that:
![image](https://user-images.githubusercontent.com/3595443/232990295-a3bd3d5b-d76d-467c-ada6-20e151f3e612.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/3595443/232989457-89c94039-ae6d-4b53-98e4-0e421cb53201.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 11 preview 6

**Comment by robloo** [comment]
It is subjective to say this is incorrect. It actually functions as intended and what it is doing right now is mathematically correct.

If you start locking the saturation and value components I bet people will complain for the opposite reason especially with different settings (you aren't using standard component settings right now).

Can you test out the WinUI version of the control? I expect it works the same as Avalonia does right now. If so, I'm not planning to change it based on a single point of feedback.

That said, the component tab sliders do lock saturation and value components at maximum in some situations as you are asking here. You could retemplate and do as you want, it's just one setting.

**Comment by dbriard** [comment]
@robloo Hi and thanks for your answer

> Can you test out the WinUI version of the control? I expect it works the same as Avalonia does right now. If so, I'm not planning to change it based on a single point of feedback.

In fact, it do not works the same, that the point of this issue. Avalonia color picker, at least with SaturationValue componennt, do not work like any color picker I ever seen, and is not usable as the hue slider become useless when it get white or black, it is not possible to choose the hue anymore. Here are a few examples:

Avalonia with light color
![image](https://user-images.githubusercontent.com/3595443/233076869-a4769184-66ad-48e4-878f-f8ee785c74a1.png)
Avalonia with dark color
![image](https://user-images.githubusercontent.com/3595443/233076999-430dae0d-10f9-491f-8919-2248cd18d29e.png)

Blend:
![image](https://user-images.githubusercontent.com/3595443/233077108-ffd91a2a-ef70-4ee6-a9a1-34fc6c67454a.png)

UWP/WinUI:
![image](https://user-images.githubusercontent.com/3595443/233077246-df306390-9438-4d73-a30f-88c9b5e54ddd.png)

Photoshop:
![image](https://user-images.githubusercontent.com/3595443/233077364-6c5a585c-699f-459c-a9bc-ba34d59d9b6c.png)

As you can see, the normal behavior of such view is that hue slider do not change with the color.

I didn't check other views (probably they are correct) as SaturationValue is the view I always use, and I was surprise when I see the Avalonia's version of the Hue Slider.

Sure, I will look at how to change that for my app, but I am 99% sure that there is something wrong and that is is not "subjective ".

**Comment by robloo** [comment]
If WinUI functions this way, yes, it should be changed.

Is Hue the only special case like this? Or do you expect saturation or value to also lock in some conditions? (Like the components tab sliders do)

I won't have time to check WinUI for a bit myself.

**Comment by dbriard** [comment]
I checked the other modes and the issue with the Hue slider is only in SaturationValue and ValueSaturation.

In the sliders tab, there is no problem, the hue slider do not change, and never become white or black.
![image](https://user-images.githubusercontent.com/3595443/233086220-a48a95f6-0c9b-42d5-8924-eeced128f1c3.png)

**Comment by robloo** [comment]
I've been thinking about how to go about address this and it's probably going to result in an API change. `ColorSlider` currently has properties to force the Alpha component to maximum and to force the saturation and value to maximum. These properties are used to achieve the desired effect in the component sliders tab.

Originally, I was planning on using the properties again for the Hue slider in the spectrum tab. However, that slider can be more than just Hue, it can be Saturation and Value as well. Therefore, I can't just set the property to force saturation and value to maximum and forget about it -- when this property is set needs to change. This means I would have to make it a template part and then pull the logic into the `ColorView` itself. I'm not happy with that solution as:

 1. I'm trying to keep template parts to a minimum and adding one more for this breaks this rule and muddies up the design. It's harder to re-template and adds ugly complexity
 2. I never really like the slider properties to force alpha or saturation/value to maximum. They were just the best that could be thought of at the time.

So where to go from here?

I'm going to add logic in `ColorSlider` itself that can set display mode to "perceptive" or "exact" this will allow the `ColorSlider` itself to dynamically change how the spectrum is rendered based on certain conditions. "perceptive" will meet the requirements of this issue and what is currently done in the components tab. "exact" will maintain the mathematically correct calculation that is useful in RGB color model but not so much HSV. In combination with this I'm going to add the `IsAlphaVisibible` property to separately control the alpha channel transparency being shown or not.

The only open issue is whether the display mode should be two properties: one for HSV and one for RGB. The way the components tab currently works is HSV is "perceptive" and RGB is "exact". So to keep that how it is right now it might be best to allow controlling them separately. Otherwise, the RGB sliders in "perceptive" mode will always be Red/Green/Blue and never show the actual color dynamically.

**Comment by dbriard** [comment]
@robloo I did not looked at the code so much but you know when ColorComponent is Component1, and when ColorModel is HSV, and so in that configuration, the hue slider is always the same (in fact the hue slider brush never change according to any other parameter).

![image](https://user-images.githubusercontent.com/3595443/234884598-ac40fc36-b817-4e9b-a6e0-5f3fa14c96cd.png)

**Comment by robloo** [comment]
The Components tab has to handle this slightly differently from the Spectrum tab. I was just asking to confirm if the comonents tab looked as you expected.

If we only had to worry about the Hue component in the spectrum tab the existing IsSaturationValueMaxForced property can just universally be set to true. The problem is when the third component is set to Saturation or Value we don't want to actually max other components as then the slider will never match the exact color. That isn't a problem so much in the components tab but seems to be against what users expect in the spectrum tab. So styling is going to have to set this property differently based on which Components are active.

In order to make this more generic I'm still changing the property names. Though functionality will be loosely similar to what it did before only extended to handle more cases and work in RGB. There is now a perceptive mode for the control.

**Comment by dbriard** [comment]
@robloo Thank you for the fix :)
I am not sure how I can test. I upgraded to preview 8 and it doesn't seems include.
I'll try to see how nighly builds work after urgencies.

**Comment by robloo** [comment]
This is still open and the solution may change. I ran into another blocker issue from what I can tell.

**Comment by robloo** [comment]
I worked around the other issue to close this for now. The behavior will change slightly in the future but this issue is fixed.
