### ISSUE TITLE
AttachedProperty Coercion Callback is not invoked

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#11212]
**Describe the bug**
Coercion Callback is not invoked

**To Reproduce**

1. Add following code to `AvaloniaObjectTests_Coercion`

   ```csharp
        [Fact]
        public void Coerce_AttachedProperty()
        {
            var numberOfCall = 0;
            AttachedPropertyOwnerCoerce.CoerceDoubleCallback = (_) => numberOfCall++;
            var class1 = new Class1();

            class1.SetValue(AttachedPropertyOwnerCoerce.DoubleProperty, 101.1d);

            Assert.Equal(1, numberOfCall);
            Assert.Equal(100d, AttachedPropertyOwnerCoerce.GetDouble(class1));
        }

        private class AttachedPropertyOwnerCoerce
        {
            public static readonly AttachedProperty<double> DoubleProperty =
                AvaloniaProperty.RegisterAttached<AttachedPropertyOwnerCoerce, Class1, double>("Double",coerce: CoerceDouble);

            public static Action<AvaloniaObject> CoerceDoubleCallback;

            public static double GetDouble(Class1 control) => control.GetValue(DoubleProperty);
            public static void SetDouble(Class1 control, double value) => control.SetValue(DoubleProperty, value);

            private static double CoerceDouble(AvaloniaObject instance, double value)
            {
                CoerceDoubleCallback?.Invoke(instance);
                var o = (Class1)instance;
                return Math.Clamp(value, 50d, 100d);
            }
        }
   ```
3. Run `Coerce_AttachedProperty` test

**Expected behavior**
Coercion Callback is invoked

**Screenshots**
(none)

**Desktop (please complete the following information):**

- OS: any
- Version: **11.0.0-preview7**

**Additional context**
Validate Callback is invoked

**Comment by tomenscape** [comment]
[`AvaloniaProperty.RegisterAttached`](https://github.com/AvaloniaUI/Avalonia/blob/85a2fc504d9d040e2921dc9d6dc213248e1a2344/src/Avalonia.Base/AvaloniaProperty.cs#L341) creates an `AttachedProperty` object and tells it about `TOwner`. That's type which is registering the attached property, i.e. `AttachedPropertyOwnerCoerce` in the sample code above.

But when the value is set, metadata for the target `AvaloniaObject` is resolved. In this case, the target object is a `Class1`. Because `Class1` is not compatible with `AttachedPropertyOwnerCoerce`, no metadata is found and the default metadata is used. Due to #10572, this default metadata object no longer includes the coercion method.

Is it correct to create the attached property with `TOwner`? Giving it `THost` instead would fix this bug. I'm not sure why the property object would ever need to know about `TOwner`, which does not have to be an `AvaloniaObject` and is often static.

**Comment by workgroupengineering** [comment]
`AttachedPropertyOwnerCoerce` is common scenario and it use to extend the behavior of DependencyObject.
`TOwner` is where the Set* and Get methods are defined.  
What is the advantage of `TOwner` deriving from AvaloniaObject?

**Comment by tomenscape** [comment]
I'm talking above about the internal behaviour of `RegisterAttached`. There is nothing wrong with the test class you posted.

**Comment by workgroupengineering** [comment]
> I'm talking above about the internal behaviour of `RegisterAttached`. There is nothing wrong with the test class you posted.

sorry, i misunderstanding. Can you give me how to search to try and fix the problem?
