### ISSUE TITLE
IStorageProvider.OpenFilePickerAsync does not return

### ISSUE THREAD

**Issue by dirkackerman** [AvaloniaUI/Avalonia#11525]
**Describe the bug**
In some cases the file picker dialog never returns from the IStorageProvider.OpenFilePickerAsync method on Linux using the DBus file picker.

**To Reproduce**
Open a file picker with an extension starting with a numeric value:
```c#
        var storageProvider =  TopLevel.GetTopLevel(_visual)!.StorageProvider;
        var myFile    = new FilePickerFileType("My file starting with a numeric extension");
        myFile.Patterns = new []{"*.123file"};
        
        var startingLocation = (await storageProvider.TryGetWellKnownFolderAsync(WellKnownFolder.Downloads))
            ?? (await storageProvider.TryGetWellKnownFolderAsync(WellKnownFolder.Documents));

        var selection = await storageProvider.OpenFilePickerAsync(new FilePickerOpenOptions
        {
            AllowMultiple          = false,
            FileTypeFilter         = new[] { myFile },
            Title                  = "Please select a file to open",
            SuggestedStartLocation = startingLocation
        });
         
        var file = selection.SingleOrDefault();
```
Run and select a file matching your filter.

The last line `var file = selection.SingleOrDefault();` will never be reached and no exceptions are thrown. The call to `OpenFilePickerAsync` just never returns.

When cancelling or selecting a file using either a filter not starting with a number extension or just no filter at all, then the method returns.

**Expected behavior**
Either return a value, null or throw an exception but the method should not block when the file picker closes.
Ideally one would expect the file picker to work and return the selected file info, even if the filter's extension starts with a number.

**Desktop (please complete the following information):**

- OS: Linux
- Distribution: OpenSUSE Tumbleweed 20230515
- Graphics Platform: X11
- Desktop Environment: KDE Plasma 5.27.5
- Kernel: 6.3.1-2-default (64-bit)
- Version 11.0.0-preview-8

**Comment by maxkatz6** [comment]
See https://github.com/AvaloniaUI/Avalonia/issues/9383#issuecomment-1378350456

**Comment by dirkackerman** [comment]
Yes I did see that post and it help a lot in debugging the problem.

I understand that the issue with the filter may well be in KDE. Because if this I was hesitant to even load this bug. 

But is it not fair to say that even if KDE misbehaves that is should not break Avalonia? 

Blocking in a method is not a good experience. Can Avalonia not protect itself and throw or fail graciously?

**Comment by maxkatz6** [comment]
> Yes I did see that post and it help a lot in debugging the problem.

Just in case, did switching to GTK file picker help you? With an instruction from that another issue.

> But is it not fair to say that even if KDE misbehaves that is should not break Avalonia?

From what I see here, Avalonia code is pretty simple there and it passes an original value to the KDE. Though, I can't say for sure about the internals of DBus interop. See https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.FreeDesktop/DBusSystemDialog.cs#L156
What solution or fix are you suggesting to add there?

> But is it not fair to say that even if KDE misbehaves that is should not break Avalonia?

If KDE doesn't return an results, it's not something that we can handle properly. Unless we add timer, but it will only cause other problems.

The only possible problem in Avalonia code I see is this branch https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.FreeDesktop/DBusSystemDialog.cs#L126-L127 (and the same branch in SaveFilePickerAsync/OpenFilePickerAsync methods as well). It would be reasonable to complete TaskCompletionSource with an exception on that branch.

Can you try to debug this code and see if that's the place causing a problem in your case? PRs are welcomed too.

Since I am not knowledgeable with DBus or FreeDesktop enough, @affederaffe maybe can help with this part. Maybe it's possible to extract an error message from the dbus.

**Comment by maxkatz6** [comment]
@dirkackerman https://github.com/AvaloniaUI/Avalonia/pull/11526 PR should fix this issue, or at least throw a proper error.

**Comment by dirkackerman** [comment]
Thank you very much! That was quick :)

It looks like this was merged into master so I assume it will be in the next 11 release (RC I assume).

I will test when it comes out and let you know if there are issues.

**Comment by dirkackerman** [comment]
Tested on RC1.1 and it does not throw an error, its actually fixed the issue. My KDE dialog is now accepting the file extension starting with a numeric value. (I did update my OS in the mean time, don't know if that helped).

Thanks a lot!

**Comment by dfkeenan** [comment]
I am having this problem on Windows 11 with Avalonia 11.0.5.

Seems to work a few times then stops working randomly.

**Comment by timunie** [comment]
@dfkeenan don't answer closed issues. Open a new Q@A and attach a minimum sample as well as steps to reproduce
