### ISSUE TITLE
Supported Linux distros?

### ISSUE THREAD

**Issue by tanaka-takayoshi** [AvaloniaUI/Avalonia#1154]
Hello,

I failed to build on Fedora 25. Could you share which Linux distro you have tested? Also, do you have a plan to list the supported distros?

```
$ cat /etc/fedora-release 
Fedora release 25 (Twenty Five)

$ mono --version
Mono JIT compiler version 4.4.2 (Stable 4.4.2.11/f72fe45 Tue Aug  2 08:14:37 UTC 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

$ mono .nuget/nuget.exe restore Avalonia.sln
Could not load file or assembly or one of its dependencies.
  Could not load file or assembly or one of its dependencies.
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly or one of its dependencies.
File name: 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
  --- End of inner exception stack trace ---
  at NuGet.CommandLine.Program.Initialize (IFileSystem fileSystem, IConsole console) <0x41c76230 + 0x004b3> in <filename unknown>:0 
  at NuGet.CommandLine.Program.MainCore (System.String workingDirectory, System.String[] args) <0x41befbd0 + 0x004cf> in <filename unknown>:0 
---> (Inner Exception #0) System.IO.FileNotFoundException: Could not load file or assembly or one of its dependencies.
File name: 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'<---

---> (Inner Exception #1) System.IO.FileNotFoundException: Could not load file or assembly or one of its dependencies.
File name: 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'<---

```

**Comment by Icecream-Burglar** [comment]
I'm pretty sure it failed because it was looking for "WindowsBase". Which iirc, that is a WPF dependency.

**Comment by kekekeks** [comment]
To run a *compiled* app that uses Avalonia you need a 64-bit glibc-based distro with sufficiently new glibc (one of our dependencies requires 2.17, I think) that can run .NET Core 2.0 or Mono 5.2+. 

To *build* an app that uses Avalonia on Linux you either need to use legacy project format (you can create a "Console Application" from MonoDevelop or use our template for Visual Studio and go from there) or use .NET Core and VS Code.

Due to various issues with .NET Core SDK and missing dependencies you can't compile *Avalonia itself* on Linux. Or on OSX for what that matters. 

The subset of the project targeting .NET Standard and .NET Core can be built, see `samples/ControlCatalog.NetCore` project, it should work with `dotnet restore && dotnet run` out of the box,  but you can't use MonoDevelop or XamarinStudio/VisualStudioForMac, only VS Code.

**Comment by kekekeks** [comment]
Also see this [example](https://github.com/kekekeks/avalonia-net-core-example/tree/master/VS2017/src/ControlCatalog), you should be able to open and debug it on Linux using VSCode or Rider 2017.2 EAP if you have .NET Core 2.0 installed.

**Comment by kekekeks** [comment]
I also have some plans for a tool that will create RPM/DEB packages and OSX app bundle automatically from any platform. I hope to get it working before 0.6 beta release.

**Comment by tanaka-takayoshi** [comment]
@kekekeks Thanks for updating and I'm sorry to be late for my reply.
I confirmed the example app run on my Fedora just by clone & "dotnet run". I'm closing this ticket. If I have to clarify "which Linux distro can build whole Avalonia project", I'll create a new issue.
