### ISSUE TITLE
On Windows, a window's `ICON_SMALL` is not set

### ISSUE THREAD

**Issue by TomEdwardsEnscape** [AvaloniaUI/Avalonia#11569]
When Avalonia [sets a window icon on Win32](https://github.com/AvaloniaUI/Avalonia/blob/b879144acee97363bd5d98f21561197d9b28ccc3/src/Windows/Avalonia.Win32/WindowImpl.cs#L732-L733), it only sets the "big" icon. If the image being set is an ICO file, this results in the OS selecting a large (>=48px) image from within and downsizing it, with low-quality results.

The existing call that Avalonia makes should be duplicated, with the `wParam` changed to `Icons.ICON_SMALL`. This prompts the OS to select an appropriate image from the same ICO file.

A comparison gif:

![small_icon](https://github.com/AvaloniaUI/Avalonia/assets/109803929/e7d62e6b-3094-4684-a4db-4a58f43dca14)

**To Reproduce**

1. Create a .ico file with both small (16px, 24px...) icons, and visually different large (48px+) icons
2. Use the .ico file as a window icon
3. Start your application

You will see the large icon used where the small icon would be expected.

**Expected behavior**
Windows selects the appropriate small icon from a .ico file.

**Desktop (please complete the following information):**

- OS: Windows
- Version 11 preview 8

**Comment by timunie** [comment]
@tomenscape great finding. Do you think you're able to provide a PR to fix it?

**Comment by tomenscape** [comment]
I started making a branch but I have discovered that things are far more broken than I thought.

[`Avalonia.Win32.IconImpl` accepts a `System.Drawing.Icon` object.](https://github.com/AvaloniaUI/Avalonia/blob/1c927688e9bb97ce4886447dd6c693ace36a6819/src/Windows/Avalonia.Win32/IconImpl.cs#LL12C1-L12C1) The code is already broken at this point, because an `Icon` contains _only one_ image. The resolution of this image is decided when the icon is loaded from the stream.

[This currently happens in `Win32Platform`](https://github.com/AvaloniaUI/Avalonia/blob/1c927688e9bb97ce4886447dd6c693ace36a6819/src/Windows/Avalonia.Win32/Win32Platform.cs#L305), where a constructor without an icon size is used. [According to Microsoft's docs](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.icon.-ctor?view=dotnet-plat-ext-7.0#system-drawing-icon-ctor(system-io-stream)), this constructor loads the lowest resolution image from the icon.

`Avalonia.Win32.IconImpl` should be doing this:

1. Accept a `Stream` and take a copy of it
2. Use `UnmanagedMethods.GetSystemMetrics` to determine the size of a "small" (`SM_CXSMICON`/`SM_CYSMICON`) and "large" (`SM_CXICON`/`SM_CYICON`) icon
3. Create `Icon` objects using the copied stream and the integer values returned by `GetSystemMetrics`
4. Send the platform the correct icon size, or both, for tray/menu/window icons, as the platform APIs dictate
5. When a window's DPI changes, call `GetSystemMetrics` again to get new icon resolutions, create new `Icon` objects, and update the window with them

(I'm not sure how to update tray icons when DPI changes. That would require Avalonia to know which screen they are being displayed on...and can't they be displayed on multiple?)

Setting both the big and small icons does improve the scaling quality, as shown above, but remains incorrect behaviour. Since community contributions are frozen and this change is much bigger than I anticipated, I won't open a PR right now.

More reading:

https://blog.barthe.ph/2009/07/17/wmseticon/
https://learn.microsoft.com/en-us/windows/win32/api/commctrl/nf-commctrl-loadiconmetric

**Comment by tomenscape** [comment]
`GetSystemMetricsForDpi` is a fairly recent addition which requires Windows 10. Maybe we can use `UnmanagedMethods.GetSystemMetrics` (already wrapped) and multiply that by the window's DPI ourselves.

**Comment by timunie** [comment]
@tomenscape fyi win 7 will not be supported officially anymore. We are glad if it works, but there is no guarantee and no testing on this anymore.
