### ISSUE TITLE
Wrong content of ListBox after ItemSource change

### ISSUE THREAD

**Issue by nrymanov** [AvaloniaUI/Avalonia#11626]
**Describe the bug**
In a ListBox with the default settings for ItemsPanel modifications of the binded ItemsSource may lead to the some elements are not re-creaded and are shown in the list several times. 
Note: seems the presence of non-null SelectedItem is mandatory to reproduce the problem

**To Reproduce**

1. Build and run the attached project. 
[AvaloniaApplication1.zip](https://github.com/AvaloniaUI/Avalonia/files/11634133/AvaloniaApplication1.zip)

2. Click the "Step 1" button.
3. Click the "Step 2" button.
4. Carefully compare the lists on the screen.
5. Note: some elements are different!
6. Resize the window as small as possible and resise it back (to force VirtualizingStackPanel recreate items)
7. Note: the contents of the lists are identical

**Expected behavior**
The contents of the lists should not depend on used ItemPanel.

**Screenshots**
![image](https://github.com/AvaloniaUI/Avalonia/assets/110977202/0ebd1526-c20f-4012-8bba-2ae7098d894e)

**Desktop (please complete the following information):**

- OS: Windows
- Version 11.0.0-rc1.1

**Additional context**

**Comment by timunie** [comment]
great sample to test and great comparison 👍

**Comment by timunie** [comment]
Additional hint: if one resizes the window, the item is updated correctly.

**Comment by grokys** [comment]
Caused by `AutoScrollToSelectedItem`: if you set `AutoScrollToSelectedItem="False"` on the affected `ListBox` then the problem doesn't occur. What's happening is that the anchor index is updated when the item is inserted before the list of realized items is updated. When `SelectingItemsControl.AutoScrollToSelectedItemIfNecessary` tries to bring the item into view, because the realized item list isn't up-to-date with the actual state of the items, it re-realizes an item that already exists. #11418 should fix this, but I'm not totally happy with that solution as it requires on the dispatcher to delay scrolling to the selected item, which kinda feels unnecessary.
