### ISSUE TITLE
ScaleTransform doesn't work

### ISSUE THREAD

**Issue by SKProCH** [AvaloniaUI/Avalonia#11634]
**Describe the bug**
ScaleTransform (and probably other transforms) doesn't work now.

**To Reproduce**
Launch Render demo and hover abode two first borders in the Animations page - nothing happens.

**Expected behavior**
It should change size, rotate, etc.

- Version: 11.0.0-rc1.1

**Comment by MrJul** [comment]
I wanted to open a more general issue about this: the problem is that the animator isn't registered.

Fortunately the workaround is quite simple so it isn't blocking: add `_ = new TranslateTransform();` in the window's constructor, before `InitializeComponent` and animations will work fine. (You can instantiate any transform type - the base class `Transform` is what's registering the animator for all kind of transforms).

I encountered the same problem with animating a simple `Border.Background` from one color to another: most theme resources are compiled to `ImmutableSolidColorBrush`: the mutable `SolidColorBrush` is never instantiated, and the brush animator never registered. Note that in this case, an exception "no animator registered" occurs, which doesn't happen for the transforms.

More generally, I think the animator registration should be reworked: static constructors aren't guaranteed to be called, and last I checked they aren't IL trimmable at all.

**Comment by SKProCH** [comment]
@kekekeks also binding RotateTransform (and, i suppose, other transforms) to a value doesn't work. 
E.g. this works:
```
<Animation Duration="0:0:1.2" IterationCount="INFINITE">
  <KeyFrame Cue="0%">
    <Setter Property="RotateTransform.Angle" Value="0" />
  </KeyFrame>
  <KeyFrame Cue="50%">
    <Setter Property="RotateTransform.Angle" Value="100" />
  </KeyFrame>
  <KeyFrame Cue="60%">
    <Setter Property="RotateTransform.Angle" Value="200" />
  </KeyFrame>
  <KeyFrame Cue="100%">
    <Setter Property="RotateTransform.Angle" Value="300" />
  </KeyFrame>
</Animation>
```

But this doesn't work (MyValue is actually changing, i can confirm it it dev tools):
```
<Setter Property="RotateTransform.Angle" Value="{TemplateBinding MyValue}" />
```

**Comment by maxkatz6** [comment]
Fixed
