### ISSUE TITLE
Implement Shutdown for ISingleViewApplicationLifetime

### ISSUE THREAD

**Issue by cesarchefinho** [AvaloniaUI/Avalonia#11736]
**Is your feature request related to a problem? Please describe.**

We need a way to explicit terminate application execution like in IClassicDesktopStyleApplicationLifetime

**Describe the solution you'd like**

Shutdown Method for singleviews applications

**Describe alternatives you've considered**
Not Exit Application

**Additional context**

**Comment by kekekeks** [comment]
You can use `IControlledApplicationLifetime` for platforms that support shutdown. 
Currently the only platform that implements both `ISingleViewApplicationLifetime` and `IControlledApplicationLifetime` is linux framebuffer. 

Mobile platforms don't give the developer control over the application lifetime, this is by design.
