### ISSUE TITLE
Avalonia links to undefined exports on Windows

### ISSUE THREAD

**Issue by trympet** [AvaloniaUI/Avalonia#11855]
**Describe the bug**
Avalonia is linking to the following non-existent functions:
- LoadCursor
- GetClassLongPtr
- CreateWindowEx
- GetModuleHandle
- GetWindowLongPtr
- SetWindowLongPtr
- RegisterWindowMessage
- UnregisterClass
- SetClassLongPtr
- LoadLibrary
- SetWindowCompositionAttribute
There may be more..

They are stubbed by the CLR, however, this means that when building NativeAOT, the stub needs to be generated, hence the Direct PInvoke feature can not be used, since the entry point is resolved at runtime.

I propose that Avalonia explicitly links to the -W suffix for these functions.

Furthermore, `SetWindowCompositionAttribute` is an undocumented function. The application could break if the export is removed from the OS. This also breaks the Direct PInvoke feature, since it's not defined in any lib. A better approach would be to use LoadLibrary + GetProcAddress on this function.

As an aside, I would advise using the cswin32 package or the LibraryImport attribute to generate the pinvoke calls. Lots of the pinvokes use non-blittable types, hence unnecessary managed stubs. It _could_ also have a meaningful impact on speed and size :)

**To Reproduce**
1. Ensure you have an installation of the Windows SDK on your machine.
1. Create a sample Avalonia app for Windows.
1. Mark the user32 exports as DirectPInvoke in the csproj:
```xml
  <ItemGroup Condition="'$(PublishAot)' == 'true'">
    <DirectPInvoke Include="User32" />
    <DirectPInvoke Include="kernel32" />
    <DirectPInvoke Include="combase" />
    <NativeLibrary Include="User32.lib" />
    <NativeLibrary Include="OneCoreUap.lib" />
  </ItemGroup>
```
1. Publish the project: `dotnet publish -c Release -p:PublishAot=true`
1.  Observe that the linker is unable to find the exports. Here's the full error:
<details>
  <summary>Full linker error</summary>
  
  ```pwsh
ConsoleApp1.obj : error LNK2001: unresolved external symbol LoadCursor [C:\Users\trym\source\re
pos\ConsoleApp1\ConsoleApp1.csproj]
ConsoleApp1.obj : error LNK2001: unresolved external symbol CreateWindowEx [C:\Users\trym\sourc
e\repos\ConsoleApp1\ConsoleApp1.csproj]
ConsoleApp1.obj : error LNK2001: unresolved external symbol GetModuleHandle [C:\Users\trym\sour
ce\repos\ConsoleApp1\ConsoleApp1.csproj]
ConsoleApp1.obj : error LNK2001: unresolved external symbol GetWindowLongPtr [C:\Users\trym\sou
rce\repos\ConsoleApp1\ConsoleApp1.csproj]
ConsoleApp1.obj : error LNK2001: unresolved external symbol SetWindowLongPtr [C:\Users\trym\sou
rce\repos\ConsoleApp1\ConsoleApp1.csproj]
ConsoleApp1.obj : error LNK2001: unresolved external symbol RegisterWindowMessage [C:\Users\try
m\source\repos\ConsoleApp1\ConsoleApp1.csproj]
ConsoleApp1.obj : error LNK2001: unresolved external symbol UnregisterClass [C:\Users\trym\sour
ce\repos\ConsoleApp1\ConsoleApp1.csproj]
ConsoleApp1.obj : error LNK2001: unresolved external symbol SetClassLongPtr [C:\Users\trym\sour
ce\repos\ConsoleApp1\ConsoleApp1.csproj]
ConsoleApp1.obj : error LNK2001: unresolved external symbol GetClassLongPtr [C:\Users\trym\sour
ce\repos\ConsoleApp1\ConsoleApp1.csproj]
ConsoleApp1.obj : error LNK2001: unresolved external symbol LoadLibrary [C:\Users\trym\source\r
epos\ConsoleApp1\ConsoleApp1.csproj]
ConsoleApp1.obj : error LNK2001: unresolved external symbol SetWindowCompositionAttribute [C:\U
sers\trym\source\repos\ConsoleApp1\ConsoleApp1.csproj]
bin\Release\net8.0\win10-x64\native\ConsoleApp1.exe : fatal error LNK1120: 11 unresolved extern
als [C:\Users\trym\source\repos\ConsoleApp1\ConsoleApp1.csproj]
C:\Users\trym\.nuget\packages\microsoft.dotnet.ilcompiler\8.0.0-preview.5.23280.8\build\Microsoft.NETCore.Native.target
s(348,5): error MSB3073: The command ""C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.325
32\bin\Hostx64\x64\link.exe" @"obj\Release\net8.0\win10-x64\native\link.rsp"" exited with code 1120. [C:\Users\trym\sou
rce\repos\ConsoleApp1\ConsoleApp1.csproj]
  ```
  
</details>

**Expected behavior**
Avalonia explicitly use either the ansi export or the widechar export. Avalonia should not use DllImport on undocumented functions.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 11 SDK 22621
- Version 0.11.0-rc1

**Additional context**
As a workaround, linker arguments can be used to remap the non-existant exports to the widechar exports:
```xml
  <ItemGroup Condition="'$(PublishAot)' == 'true'">
    <CustomLinkerArg Include="/ALTERNATENAME:LoadCursor=LoadCursorW" />
    <CustomLinkerArg Include="/ALTERNATENAME:GetClassLongPtr=GetClassLongPtrW" />
    <CustomLinkerArg Include="/ALTERNATENAME:CreateWindowEx=CreateWindowExW" />
    <CustomLinkerArg Include="/ALTERNATENAME:GetModuleHandle=GetModuleHandleW" />
    <CustomLinkerArg Include="/ALTERNATENAME:GetWindowLongPtr=GetWindowLongPtrW" />
    <CustomLinkerArg Include="/ALTERNATENAME:SetWindowLongPtr=SetWindowLongPtrW" />
    <CustomLinkerArg Include="/ALTERNATENAME:RegisterWindowMessage=RegisterWindowMessageW" />
    <CustomLinkerArg Include="/ALTERNATENAME:UnregisterClass=UnregisterClassW" />
    <CustomLinkerArg Include="/ALTERNATENAME:SetClassLongPtr=SetClassLongPtrW" />
    <CustomLinkerArg Include="/ALTERNATENAME:LoadLibrary=LoadLibraryW" />
    <CustomLinkerArg Include="/ALTERNATENAME:SetWindowCompositionAttribute=LoadLibraryW" />
  </ItemGroup>
```

I would be happy to submit a PR to resolve this issue! :heart:

**Comment by maxkatz6** [comment]
> They are stubbed by the CLR, however, this means that when building NativeAOT, the stub needs to be generated

From my understanding, for most of these functions, we only need to choose more specific entries (like LoadCursor -> LoadCursorA/W). As it seems pretty straightforward, we will be happy to see PRs for that!

> Furthermore, SetWindowCompositionAttribute is an undocumented function

That's true. At this point, it's used only for win8 window blur. Ideally, we really want to drop all of the transparency/blur hacks that existed before win10 and only implement [direct composition](https://learn.microsoft.com/en-us/windows/win32/directcomp/directcomposition-portal)-based effects for win8+ (where [winui composition](https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/visual-layer-in-desktop-apps) is not available).  This would simplify code significantly, while still keeping older OS version feature complete. For now, it should be fine to simply remove SetWindowCompositionAttribute usage (as well as window blur support for "< win10" versions).
On newer win10 versions Avalonia uses documented WinUI Composition which allows to have better transparency and blur effects on a window already. 

> As an aside, I would advise using the cswin32 package or the LibraryImport attribute to generate the pinvoke calls

I was thinking about rewriting part of Win32 backend to use CSWin32, reducing noise in the project. But we didn't have much time for that working on 11.0 release. I want to pick it up for one of the 11.x versions, unless somebody does it first.
Note, we need to support netstandard2.0 (as well as net462 through netstandard), so I am not sure if LibraryImport works there. But should be fine since it's code generated and not a runtime feature IIRC.

Overall, I appreciate the analysis you made! Glad to see more people experimenting with static linking.
