### ISSUE TITLE
Using DrawContext.DrawLine to draw a black line draws a grey line instead

### ISSUE THREAD

**Issue by JenyaRostov** [AvaloniaUI/Avalonia#11885]
**Describe the bug**
Title
Other colors are also washed out, why is that?

**To Reproduce**
Create MVVM .net core avalonia app
Create a templated control
Override Render method with this code

`var pen = new Pen(new SolidColorBrush(new Color(255,0,0,0),1),1);`
`context.DrawLine(pen,new Point(0,50),new Point(50,50));`

**Expected behavior**
A black line

**Screenshots**
![](https://camo.githubusercontent.com/886150679bc8644e0af4856b1d7cb5ff0d96f7cf8471836b1b5fde0fa542167b/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3136393732363335373333313337383137362f313132313538373235333631333936353339322f696d6167652e706e67)

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 0.10.18

**Comment by maxkatz6** [comment]
Check UseLayoutRounding and RenderOptions.BitmapInterpolationMode properties

**Comment by JenyaRostov** [comment]
Thanks for your reply! I tried both yet still the line is gray

**Comment by timunie** [comment]
It works better for me if I add an ofset of `0.5 px` as this is the mid point of the pen. Can you try it?

```cs
public override void Render(DrawingContext context)
{
    var pen = new Pen(new SolidColorBrush(new Color(255,0,0,0),1),1);

    // Mind the added `.5` for the y-component
    context.DrawLine(pen,new Point(0,50.5),new Point(50,50.5));
}
```

**Comment by JenyaRostov** [comment]
Thank you, that works
But why does it work like that?

**Comment by dbriard** [comment]
> Thank you, that works But why does it work like that?

A draw line operation with a pen of thickness 1, for example, draw a line from x1-0.5,y1-0.5 to x2+0.5,y2+0.5 (0.5 is half stroke thickness here, and stroke is centered on the coordinates).
A pixel is not a point, but a rect from x,y to x+1,y+1
So to paint it completely using a pen, which have a stroke thickness of 1, you have to offset the coordinates by half pixel.
Otherwise, pixel is only half filled and black become gray (black multiplied by coverage percentage of the pixel).
