### ISSUE TITLE
Strange button behavior on Android platform

### ISSUE THREAD

**Issue by CreateLab** [AvaloniaUI/Avalonia#11884]
**Describe the bug**
Type text in text box, next touch button for any action.
Animation of click run, but no action handle in vm.
Action waste for close mobile keyboard.
If i close mobile keyboard for myself button work ok.

**To Reproduce**
1. Create textbox and button
2. Focused on textbox.
3. Print anything in mobile (virtual) keyboard
4. Click the button

**Expected behavior**
As i expect, if i see button animation, i believe, that button was clicked  

- OS: Android 13
- Version 11.0.0-rc1

**Comment by mosabnasri** [comment]
This problem is still happening,

On Android when the Virtual-keyboard is visible, all clicks on the app (the visible part of it) is ignored and the only thing that happens is that the keyboard is closed. 

In this case if a user wants to click on a button when the virtual-keyboard is visible he will have to click two times, the first click will hide the keyboard and the second one will work (the bidden command will execute)

ps: when the keyboard is visible the button affects will still work but without executing the button command
