### ISSUE TITLE
The avalonia browser program cannot communicate with the server

### ISSUE THREAD

**Issue by zy1075984** [AvaloniaUI/Avalonia#12142]
### Discussed in https://github.com/AvaloniaUI/Avalonia/discussions/12115

<div type='discussions-op-text'>

<sup>Originally posted by **zy1075984** July  9, 2023</sup>
I tried to communicate with the server in the avalonia browser program. I tried two methods, and neither of them worked properly, but there was no problem in the desktop program.
1.httpClient cannot be called because the ReadAsStringAsync method is blocked.
 `   private async Task GetData()

    {
        using (var httpClient = new HttpClient())
        {
            var response = await httpClient.GetAsync("https://postman-echo.com");
            response.EnsureSuccessStatusCode();
            var data = await response.Content.ReadAsStringAsync();
        }
    }`

2.JSImport cannot be called because the GetHRef method is blocked.

in *.csproj
`<AllowUnsafeBlocks>true</AllowUnsafeBlocks>`

in main.js
`const { setModuleImports, getAssemblyExports, getConfig } = 
  await dotnet.create();

setModuleImports("main.js", {
  window: {
    location: {
      href: () => globalThis.window.location.href
    }
  }
});`

in *.cs
`[JSImport("window.location.href", "main.js")]
internal static partial string GetHRef();`

3.SigalR or RestSharp are also unavailable</div>

**Comment by maxkatz6** [comment]
I don't see any issue with Avalonia here nor any errors or stacktraces at all. 
HttpClient and web sockets do work in the Browser.

**Comment by I4-PJ** [comment]
I am facing very similar issue. Not being able to invoke any communication from webassembly project. After executing ReadAsStringAsync() method, I am not receiving anything neither exception. At server side no any communication is invoked by the client. The solution works with desktop project normally.

**Comment by maxkatz6** [comment]
I am closing this issue as it doesn't seem either related or valid for the browser. Also no response since.

@I4-PJ double check that you don't have any sync over async blocking calls. And you can see in the browser dev tools tab if there is anything going to the server and back. It also can be a CORS problem, which is just how web apps are.

**Comment by jetspiking** [comment]
I encountered the same issue as @I4-PJ and @zy1075984, and after spending many hours troubleshooting, I wanted to share the solution that worked for me in case it helps others.

In your Avalonia WASM application running in the browser, you can press F12 to open the developer tools and check the Console for any errors. In my case, I encountered a Cross-Origin Resource Sharing (CORS) error. This issue arises because modern browsers enforce stricter security policies for HTTP requests made to external servers, such as REST APIs.

To resolve this, I had to configure the correct CORS policies on the server side of my REST API. This involved ensuring that the server explicitly allows cross-origin requests by setting the appropriate headers, such as Access-Control-Allow-Origin. Once properly configured, the browser was able to communicate with the API without any issues.

While this solution might seem obvious to a web developer, it wasn't immediately clear to me as someone with a primarily desktop application development background. In desktop apps, I've never had to worry about browser-specific policies like CORS. So, if you're new to web development or transitioning from desktop to web technologies like Avalonia WASM, it's worth being aware of these kinds of challenges.
