### ISSUE TITLE
Custom Circular Progress Bar working well in 0.10 but not in 0.11

### ISSUE THREAD

**Issue by flarive** [AvaloniaUI/Avalonia#12208]
Hello,

In Neumorphism Avalonia I was using a CircularProgress custom control to display circular progress bars.
This control was working well in 0.10 (CircularProgress.axaml + CircularProgress.axaml.cs)

https://github.com/flarive/Neumorphism.Avalonia/blob/main/Neumorphism.Avalonia/Styles/CircularProgress.axaml
https://github.com/flarive/Neumorphism.Avalonia/blob/main/Neumorphism.Avalonia/Styles/CircularProgress.axaml.cs

I have migrated it to Control Theme to be able to use it with Avalonia 0.11 but i can't make it work :(
The ProgressValue binding is ok but the control doesn't draw anything, i'm getting stuck on that.
The control is using Path and ArcSegment.

I have created a sample repro here showing the problem :
https://github.com/flarive/AvaloniaCircularProgress

The Circular Progress should be displayed (Progress value going from 0 to 100) but nothing is displayed.
It seems to be a binding issue because if I set ProgressValue="33" instead of ProgressValue="{Binding Progress1}" it displays.

Thanks a lot for your help !

Eviral

**Comment by flarive** [comment]
Hello...
Do you think it will be fixed soon ?
I can't release Neumorphism Avalonia for Avalonia 0.11 without that fix.. 
Tanks a lot !

**Comment by maxkatz6** [comment]
@flarive hi!

I don't think Path.Data invalidation works this way as you expect, as having bindings inside of ArcSegment inside of Path.Data figures. Though it is something that is planned to be implemented with geometries connected to the new renderer cc @kekekeks.

Why wouldn't you use Arc shape instead of Path? Arc has start and sweep angle and should be enough for neumorphism progress ring.

Or, alternatively, you can bind Path.Data to the property which you rebuild from the c# side (i.e. rebuild whole PathGeometry). Perf-wise it won't be worse, as it would anyway rebuild skia SKPath on any change.

**Comment by flarive** [comment]
Thanks a lot @maxkatz6 !
It works very well with Arc shape and it simplifies my code :)
