### ISSUE TITLE
Duplicate Chinese characters in TextBox

### ISSUE THREAD

**Issue by adirh3** [AvaloniaUI/Avalonia#12280]
**Describe the bug**
Chinese words are duplicated when using some IME input methods.

**To Reproduce**
1. install weasel IME - 
https://github.com/rime/weasel/releases/download/0.15.0/weasel-0.15.0.0-installer.exe
2. Open Control Catalog
3. Type ceshi (測試) which means "test" in Chinese, and it appears twice in search box.

**Screenshots**
https://github.com/AvaloniaUI/Avalonia/assets/27368554/e14ca6ad-5c12-4a7d-ba00-878e59341c88

**Desktop (please complete the following information):**

- OS: Windows
- Version 11.0 or current master

**Additional context**
This issue started to happen close to 11.0 release, I believe after rc1.

**Comment by Gillibald** [comment]
What is the exact input method you are using?

**Comment by yll690** [comment]
I test it in ControlCatalog.Desktop using my daily used IME '微软拼音' and encounter the same problem. It won't happen in every input. I have about 20% probability to get double words. I found here may be something to do with the Space key because if I select the candidate word using mouse or num key, I won't get double words, and if I input english word using IME and Space key, the problem will also happen.
