### ISSUE TITLE
Navigate to Source not working as of 11.0.1

### ISSUE THREAD

**Issue by tkefauver** [AvaloniaUI/Avalonia#12407]
**Describe the bug**
With an Avalonia object/property under the caret pressing 'F12' or right clicking and selecting 'Go To Definition' will show an inline tooltip saying 'Please wait..' then doesn't navigate to the Avalonia source file.

**To Reproduce**
Install Avalonia 11.0.1 or above

1. Right click project in Solution Explorer and Select 'Add New Item...'
2. Pick 'Avalonia Window' and click 'Ok'
3. Open 'Window1.axaml.cs' in Text Editor
4. Move caret to the word 'Window' in the `: Window` class declaration
5. Press F12

**Expected behavior**
The source file for `Avalonia.Controls.Window` will be opened.

**Screenshots**
![image](https://github.com/AvaloniaUI/Avalonia/assets/134575/52f4b441-9e1a-44f2-8e92-5a3a5dd37a5a)

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 11.0.1

**Additional context**
I have confirmed that other external sources navigate properly and downgrading to 11.0.0 works as expected.

This maybe unrelated but I noticed in[ 'What's Changed' for 11.0.2](https://github.com/AvaloniaUI/Avalonia/releases/tag/11.0.2) there's mentioning of Use embedded **pdb for analyzers** and build tasks by @MrJul in https://github.com/AvaloniaUI/Avalonia/pull/12336

**Comment by MrJul** [comment]
Thanks for the report!

The cause is #12216: symbol files at runtime from implementation assemblies (`lib` folder in nuget) are now external pdb files, and work fine while debugging / stepping into code.

However, we generate additional reference assemblies (`ref` folder), which are used only at build time and by the IDE. These are still using embedded pdb, but are now empty. I'll fix that.
