### ISSUE TITLE
Data validation information does not disappear from TextBox control after data is valid

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#1248]
Data validation information does not disappear from TextBox control after data is valid.

Repro:

![2017-10-27_17-52-06](https://user-images.githubusercontent.com/2297442/32113115-99b779ce-bb3f-11e7-89a4-1e03270d9ad9.gif)

Version:

Avalonia.0.5.2-build4189-alpha

**Comment by grokys** [comment]
Could you give some more information on how you're doing the validation. I just checked in `BindingTest` and the validation information goes away correctly.

**Comment by wieslawsoltes** [comment]
This is Xaml: 

https://github.com/wieslawsoltes/ColorBlender/blob/3351f2a301d819e9b393b63338e49ebf4e90751a/src/Avalonia.Controls.ColorBlender/ColorBlender.xaml#L43-L63

I do not do any data validation in my code.

**Comment by grokys** [comment]
Ok, I've looked into this, and it's because the binding is an `ElementName` binding, and `ElementName` bindings are created [with `enableDataValidation == false`](https://github.com/AvaloniaUI/Avalonia/blob/0ad1f87927cc477d482bc5b3098c2c26f023b043/src/Markup/Avalonia.Markup.Xaml/Data/Binding.cs#L218).

This is fine, except [`DefaultValueConverter`](https://github.com/AvaloniaUI/Avalonia/blob/0ad1f87927cc477d482bc5b3098c2c26f023b043/src/Markup/Avalonia.Markup/DefaultValueConverter.cs#L59) produces a `BindingNotification` error when the conversion fails in order to log a binding error.

This is picked up by `TextBox.UpdateDataValidation` and a validation error is displayed, however because data validation is disabled, the error notification is never reset.

**Comment by grokys** [comment]
@jkoritzinsky I think the solution to this is to only display errors in `TextBox` when `status.ErrorType == BindingErrorType.DataValidationError` and _not_ when `status.ErrorType == BindingErrorType.Error`. Afaics if there is a validator enabled then `DataValidationError` will always be returned for errors.

**Comment by grokys** [comment]
Hmm, actually that won't work because empty string errors are caught by `DefaultValueConverter` before the validator has chance to run.

**Comment by grokys** [comment]
Thinking more about this, I think the correct solution is to always pass `enableDataValidation` to the `ExpressionObserver`.
