### ISSUE TITLE
`quality` parameter is ignored in `Bitmap.Save` with `.jpg`

### ISSUE THREAD

**Issue by lostmsu** [AvaloniaUI/Avalonia#12493]
**Describe the bug**
The parameter does not appear to have any effect and no warning is reported.

**To Reproduce**

1. Create a new `Bitmap` (I used `WriteableBitmap`) of ~1920x1080
2. Fill it with non-trivial data
3. Call `bitmap.Save("test.jpg", quality: 10)` (I also tried 1)

**Expected behavior**
You get a low quality version of the bitmap weighting under 100KB

**Actual behavior**
You get a high quality file over 1MB in size.
It appears the resulting file is actually a PNG instead of JPEG.

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: Windows
- Version 11.0.2

**Comment by maxkatz6** [comment]
Looks like quality parameter is not passed here
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Skia/Avalonia.Skia/ImmutableBitmap.cs#L161-L171

**Comment by timunie** [comment]
@lostmsu as @maxkatz6 pointed out where the bug may be, are you willing to provide a PR for a fix? It would be very appreciated.

**Comment by kekekeks** [comment]
We kinda need to add some basic support for BitmapEncoder API

**Comment by lostmsu** [comment]
I started working on support for image formats at least for saving. PR should be out in an hour or so.

**Comment by dbriard** [comment]
Hi, this issue is closed but the PR do not seem to allow to save as Jpeg.

That would be really really really convinient if we can Save an Avalonia as Jpeg in addition to PNG, really.

My typical use case: I am doing image manipulation using my own buffer, and then I need to display it, and to save it as Jpeg. So I have to: 
1) Convert my buffer to SKBitmap to Save it as Jpeg
2) Convert again to Avalonia Bitmap to display it
I could avoid one unnecessary convertion if Avalonia allow me to save as Jpeg directly.
