### ISSUE TITLE
Expander.Header and TextBlock.Text inherits FontSize value from TabControl style

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/Avalonia#1250]
Repro:

```XAML
<UserControl xmlns="https://github.com/avaloniaui" >
    <UserControl.Styles>
        <Style Selector="TabControl">
            <Setter Property="FontSize" Value="120"/>
        </Style>
    </UserControl.Styles>
    <TabControl>
        <TabItem Header="TabItemHeader">
            <Expander Header="ExpanderHeader" IsExpanded="True">
                <TextBlock Text="TextBlock"/>
            </Expander>
        </TabItem>
    </TabControl>
</UserControl>
```

Version:

Avalonia.0.5.2-build4189-alpha

**Comment by grokys** [comment]
This is expected behavior - `FontSize` is an inherited property and so is getting inherited down to the `TextBlock`. Not sure what we can do about this? You need to either reset the `FontSize` of the `TextBlock` in the `Expander` or clear the `FontSize` on the `TabStripItem`.

Closing this for now, please let me know if I've misunderstood.

**Comment by wieslawsoltes** [comment]
I think this issue is related to https://github.com/AvaloniaUI/Avalonia/issues/1249
