### ISSUE TITLE
print function

### ISSUE THREAD

**Issue by XueDee123** [AvaloniaUI/Avalonia#12567]
**Is your feature request related to a problem? Please describe.**
Will the printing function be added? I have converted the report into pdf or pictures in the project. I know that printing can be achieved through the default pdf viewer, but silent printing is often needed. Will this function be added later? At least the printer can be called, or there are other solutions

**Describe the solution you'd like**
I hope that even if I can't implement the print preview print dialog, at least I can have an API that calls the printer and I can print pdf files

**Comment by timunie** [comment]
I think that this is not a job for Avalonia tbh as we cannot support all possible situations:
- Several printers
- All the OS which have all different requirements
- Printing in the cloud
- Different file formats
- Custom printer dialogs 
- ...

However you can quite easily implement if on your own. For Example if you only target windows you can use (yes, you can use WinForms and WPF code from Avalonia if you target Windows): 
- https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.printdialog?redirectedfrom=MSDN&view=netframework-4.8
- https://learn.microsoft.com/en-us/dotnet/desktop/wpf/documents/how-to-display-print-dialog?view=netdesktop-7.0

You can also use this blog to check how printing can be done on mobile: 
- https://codemilltech.com/xamarin-forms-e-z-print/

You may need to use a service which you inject in order to get all target platforms to work properly. But I hope you find a solution which suits your needs.

**Comment by timunie** [comment]
see also: https://github.com/AvaloniaUI/Avalonia/discussions/7763

**Comment by XueDee123** [comment]
> 另请参阅[：#7763](https://github.com/AvaloniaUI/Avalonia/discussions/7763)

Thank you for your advice, if you only use the window platform, that is too many solutions, but avalonia is for cross-platform, the printing function is still very important for the pc side, it is not the focus of avalonia. But hopefully in the future an extension library will be available to help us solve this pain point.

**Comment by timunie** [comment]
@XueDee123 I fully agree such a library would be great 👍 

If you find one anytime, share it with us :-)

**Comment by FWDAzhilay** [comment]
Hello! Have you found a way to print from the Avalonia box?

I would be grateful if you share your experience.
