### ISSUE TITLE
Cant build 0.5.1 from sources

### ISSUE THREAD

**Issue by sonarworks** [AvaloniaUI/Avalonia#1257]
Hi,

we are trying to develop one of our new applications on Avalonia, and needed to debug some stuff, so I tried building the 0.5.1 tag which corresponds to the stable nuget package from sources. The issues is that the tag references commit 3f725c808b1d4c8457f0d3204e0a071aa462cd75 in Avalonia.ReactiveUI which cannot be found in that repo. Running ` git submodule update --init --recursive` basically fails with:

    error: no such remote ref 3f725c808b1d4c8457f0d3204e0a071aa462cd75
    Fetched in submodule path 'src/Avalonia.ReactiveUI/src', but it did not contain 3f725c808b1d4c8457f0d3204e0a071aa462cd75. Direct fetching of that commit failed.

Is this an issue with that submodule? Is it possible to build 0.5.1 ? Also, what is the best strategy if we would want to use a more recent branch? Is master safe and do you merge over only working features or all the new development is done there and at times it could contain things that are not fully done?

**Comment by danwalmsley** [comment]
Hey, the last nuget release is a long way behind, lots of stuff has been fixed since then so although its called "stable" its probably not, I would recommend using either the nightly feeds https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed or building from master. I believe a new release is coming reasonably soon. Iv been using `0.5.2-build4186-alpha` for a while and its seems stable, no major unknown bugs that I can see.

**Comment by sonarworks** [comment]
Thanks for the info.

**Comment by kekekeks** [comment]
>at times it could contain things that are not fully done

In general development happens in separate branches and we only merge them to `master` after a code review. Relatively small changes and hotfixes can still go to master directly.

**Comment by danwalmsley** [comment]
@kekekeks probably a good argument for having a develop branch
