### ISSUE TITLE
Add AngleDegree and AngleRadiant to PinchEventArgs

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#13227]
## Is your feature request related to a problem? Please describe.

Detects the change in the angle of the Pinch gesture

## Describe the solution you'd like
Add AngleDegree and AngleRadiant to `PinchEventArgs`

**Comment by robloo** [comment]
We probably should check the API usage of degrees vs. radians and only use one. The other can be calculated in apps that need it.

**Comment by workgroupengineering** [comment]
> We probably should check the API usage of degrees vs. radians and only use one. The other can be calculated in apps that need it.

RotateTransform e other using degrees

**Comment by robloo** [comment]
Arc uses degrees:

https://github.com/AvaloniaUI/Avalonia/blob/bbe4ad875515aa69b916f654d0046251fcba5a05/src/Avalonia.Controls/Shapes/Arc.cs#L34-L51

Sector also uses degrees.

https://github.com/AvaloniaUI/Avalonia/blob/bbe4ad875515aa69b916f654d0046251fcba5a05/src/Avalonia.Controls/Shapes/Sector.cs#L24-L41

Check Path geometries, even in WPF degrees are used:

https://learn.microsoft.com/en-us/dotnet/api/system.windows.media.arcsegment.rotationangle?view=windowsdesktop-7.0

So I agree degrees seems to be correct from an API standpoint.

**Comment by workgroupengineering** [comment]
I saw that `Matrix` uses radians, Maybe we should use both properties

https://github.com/AvaloniaUI/Avalonia/blob/87ffbfc089bc68b491f8a33f621ab18d449136ab/src/Avalonia.Base/Matrix.cs#L205-L210

https://github.com/AvaloniaUI/Avalonia/blob/87ffbfc089bc68b491f8a33f621ab18d449136ab/src/Avalonia.Base/Matrix.cs#L217-L223

**Comment by robloo** [comment]
I think long term we need to follow the Manipulation gestures API. It seems most generic. That has degrees as well:

https://learn.microsoft.com/en-us/dotnet/api/system.windows.input.manipulationdelta?view=windowsdesktop-7.0

Degrees is by far the most common in .NET APIs and should still be used I think. Radians is only required for matrixes because of the math involved. You don't want to be doing any degree<->radian conversions in matrix algebra. Radians is the natural mathematical units and requires no conversion.

It also is very uncommon to provide the same value in an API but with two different units. There should be "one source of truth" and then convert as needed from there.

**Comment by workgroupengineering** [comment]
I understand your point. But why increase the possibility of rounding errors between radians in degrees and then return in radians given that Atan2 returns the angle in radians?
