### ISSUE TITLE
Mouse cursor on TextBox scrollbars shows as caret

### ISSUE THREAD

**Issue by jpmikkers** [AvaloniaUI/Avalonia#13249]
## Describe the bug
When a textbox is showing its scrollbars, when you hover the mouse over the scrollbars or move them, the mouse cursor is shown as a caret.

## To Reproduce

- run avalonia window containing a multiline TextBox, with enough text to have visible scrollbars
- hover the mouse cursor over the scrollbars, its displayed as a caret

## Expected behavior
Over the scrollbar the mouse should probably show as a normal pointer.

## Screenshots

https://github.com/AvaloniaUI/Avalonia/assets/10578746/daee445a-3c1f-4c88-a023-0e127cbc3c8d

## Environment

- OS: Windows 11
- Avalonia-Version: 11.0.4 and 11.0.5-rc1

## Additional context
demo solution:
[AvaTextBoxScrollBars.zip](https://github.com/AvaloniaUI/Avalonia/files/12899847/AvaTextBoxScrollBars.zip)

**Comment by cfnfy** [comment]
If you need a quick fix you can use the following style:

```
<Style Selector="TextBox /template/ ScrollViewer#PART_ScrollViewer">
     <Style Selector="^ /template/ ScrollBar">
          <Setter Property="Cursor" Value="Arrow" />
     </Style>
</Style>
```

The issue is that the Cursor property is set on the DockPanel which contains the ScrollViewer on the Fluent TextBox control style (https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Fluent/Controls/TextBox.xaml). It either needs to be set to Ibeam on a different Control (Panel or TextPresenter) or the ScrollViewer will need to be set to revert to Arrow.

There doesn't appear to be 100% consistency in use of 'Arrow' and 'Hand' when I look at other implementations, but 'Arrow' seems to be used nearly all of the time so feels like the right option here.

I'll raise a PR for this when I get a chance.

**Comment by timunie** [comment]
@cfnfy yeah a PR would be welcome for both themes probably. ❤️
