### ISSUE TITLE
SelectedValue on ComboBox throws Xamlll exception in debug mode

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#13284]
## Describe the bug
A null reference exception is thrown when a ComboBox is bound with SelectedValue only when run with the debugger.
The combobox does what it should and the value is updated.

stack:-
CompiledAvaloniaXaml.XamlIlHelpers.AvaloniaComboBoxRepro.ViewModels.MainViewModel,AvaloniaComboBoxRepro.Value!Setter(Object , Object )

## To Reproduce
[AvaloniaComboBoxRepro.zip](https://github.com/AvaloniaUI/Avalonia/files/12927562/AvaloniaComboBoxRepro.zip)

run the repro in debug mode, the exception should be thrown.

## Expected behavior
No exception

## Environment 

- OS: Windows 10
- Avalonia-Version: 11.0.2 11.0.5-rc1 11.1.999-cibuild0040934-beta

**Comment by timunie** [comment]
I guess what happens is, that during loading the SelectedValue is `null`. The issue is solved for me if I make the bound property `int?` instead of `int`. Would that help you? 

Also I think if it is only happening during debug mode, you probably can safely mute the exception and the program should continue normally.

**Comment by ahopper** [comment]
This does not stop my code working and is really just an annoyance, I reported it as it possibly indicates there should be a null check somewhere to prevent an exception being thrown and swallowed.

Thanks for the int? suggestion but that would be a bit messy in my code.

**Comment by robloo** [comment]
I ran across this issue as well and it does always throw an exception during debug. So I wouldn't really say "does not stop my code working" since it causes a crash.

There is an issue in the property store or binding system here. Null should not be assigned for non-nullable types. Instead default(T) should be used. There is definitely a bug some place.

**Comment by timunie** [comment]
@robloo the issue is still open for that reason. The binding system is currently under development. After that, this issue should be revisited.
