### ISSUE TITLE
11.0 Code Generator generates InitializeControl for all inherited (nested) usercontrols

### ISSUE THREAD

**Issue by postrondev** [AvaloniaUI/Avalonia#13412]
create controls
public partial class KeyButton : UserControl
{ }

public partial class KeySequenceButton : KeyButton
{ }

for both controls InitializeControl is generated an makes compiler fail stating InitializeComponent is hiding a already defined
and one should use use new keyword.

i have spent hours to find, that the generated code causes the trouble. 
i can inspect KeySequenceButton.g.cs, but not KeyButton.g.cs

EmitCompilerGeneratedFiles was the key to find the bug.

in 0.10.x where no code behind which is definatly a bad idea because it may contain code one do not like and cannot be reviewed.
code behind was the reason to avoid wpf a.s.o.

i ask you to fix this issue as fast as possible, because moving from 0.10.x to 11 has bricked a working app.

**Comment by timunie** [comment]
please read breaking changed guide. Basically you need to remove the reference to XamlNamesgenerator. 

https://docs.avaloniaui.net/docs/next/stay-up-to-date/upgrade-from-0.10

**Comment by postrondev** [comment]
i have NO XamlNamesgenerator in the entire project.
from my sight this is not a breaking change but a bug.

so which other idea do you have?

**Comment by postrondev** [comment]
sry. havent found XamlNamesgenerator with fulltext search.
found it using vs dependencys.
removed reference.
still the same bug

**Comment by postrondev** [comment]
my project with the controls has no reference to XamlNamesgenerator 
the bug still comes up.
any idea?

**Comment by postrondev** [comment]
would you consider an upgrade guide. 
you are describing very few "breaking changes" in your referenced document
with a link to 1000 page document the describes everything that have changed.
do you really expect your friend to spend monthes just to check, if there
projects are affected?
what i miss i an understandable reason why you have broke your framework
in that horrobla way. there are absolutly NO benefits.
however. it is like it is. you might lose a big supporter.

**Comment by timunie** [comment]
@postrondev please keep calm. There are reasons we did it that way. But I don't want to argue about it with you. No one forces you to upgrade. 

However if you find some info is missing your contribution to the docs is welcome. Not every sentence is clear enough maybe, I agree. But we need to get your feedback to understand what info exactly is misleading or missing. So once your issue is solved, you are welcome to help improving the guide. 

Now, what can we do to help you upgrading? I'd suggest you to file some sample that shows a broken user control. i will look into and try to figure out what's wrong. Deal?

**Comment by kekekeks** [comment]
`<AvaloniaNameGeneratorIsEnabled>false</AvaloniaNameGeneratorIsEnabled>`
