### ISSUE TITLE
Add Shadow and/or Glow effect to Visual

### ISSUE THREAD

**Issue by vkotov** [AvaloniaUI/Avalonia#1345]
Hello!
I'm trying to write custom theme for Avalonia, but found that there are no **DropShadow** and *Glow* effects. Is it possible to add effects for Visual class?

**Comment by grokys** [comment]
Hi @vkotov - not yet! It's something I'd like to add, but I think it may be a while yet - there are more basics to fix before adding this feature I think, unless someone comes forward with the code!

**Comment by kekekeks** [comment]
drop shadow is supported in 11.0

**Comment by tbibre** [comment]
Regarding the Glow effect, I've found an easy way to have a nice result:
- Put your control with a high blur effect (radius 25 for example)
- Stack a copy of your control on top of it

I took a look to the Effect code, but I'm struggling to make sense of it, I don't know how hard it would be to implement it as a variation of the BlurEffect that does a redraw of the original drawing after blurring. (instead of having to double each control that need glow)

Also, it seems there is a typo [in this filename](https://github.com/AvaloniaUI/Avalonia/blob/ca396294d244b587f9a931b04e2385fe53792e16/src/Avalonia.Base/Media/Effects/EffectExtesions.cs).
