### ISSUE TITLE
Can not change Foreground color for Button

### ISSUE THREAD

**Issue by vkotov** [AvaloniaUI/Avalonia#1347]
It doesn't work:
`<Button Foreground="Red">Red Text?</Button>`

It doesn't work with styles:
```
<Setter Property="Template">
    <ControlTemplate>
        <ContentPresenter Name="PART_ContentPresenter"
                                      ContentTemplate="{TemplateBinding ContentTemplate}"
                                      Content="{TemplateBinding Content}"
                                      TextBlock.Foreground="Red">
    </ControlTemplate>
</Setter>
``` 

Also can't change property with pseudoclasses:
```
<Style Selector="Button:focus">
        <Setter Property="Foreground" Value="Red" />
</Style>
```

**Comment by vkotov** [comment]
It seems my mistake. I added style:

```
<Styles xmlns="https://github.com/avaloniaui">
  <Style Selector="TextBlock">
    <Setter Property="Foreground" Value="{DynamicResource ThemeForegroundBrush}"/>
  </Style>
</Styles>
```

I found solution for reassign **Button**s text collor:

```
<Style Selector="Button TextBlock">
    <Setter Property="Foreground"
            Value="{DynamicResource ThemeButtonForegroundBrush}" />
</Style>
```

but I think `<Button Foreground="Red">Red Text?</Button>` in client code should more priority then **TextBlock.Foreground** value declared in Theme.

**Comment by grokys** [comment]
I'm not quite sure I understand correctly, but I think this is expected behavior. Try to think of the tree:

- Button Foreground=Red
  - ContentPresenter Foreground=Blue
    - TextBlock

If you change the color of the button, then it _shouldn't_ have any effect, as you're resetting the foreground in the `ContentPresenter` which is closer to the `TextBlock`.

The correct way to do this is to bind the `ContentPresenter.Foreground` in the template using a template binding:

```
<Setter Property="Template">
    <ControlTemplate>
        <ContentPresenter Name="PART_ContentPresenter"
                                      ContentTemplate="{TemplateBinding ContentTemplate}"
                                      Content="{TemplateBinding Content}"
                                      TextBlock.Foreground="{TemplateBinding Foreground}">
    </ControlTemplate>
</Setter>
```

Closing this as I think it's working correctly. Please reply if you need more explanation.
