### ISSUE TITLE
Binding ListBoxItem.IsVisible not working with VirtualizingStackPanel

### ISSUE THREAD

**Issue by tkefauver** [AvaloniaUI/Avalonia#13991]
## Describe the bug
`ListBoxItem` ignores `IsVisible` property when its scrolled into view.

## To Reproduce

1. Add a binding to `ListBoxItem.IsVisible`
2. Set the binding to `false`
3. Scroll where that item would be out of view and then back in

## Expected behavior
When `ListBoxItem.IsVisible == false` the `ListBoxItem` stays not visible.

## Environment 

- OS: Windows 11 23H2
- Avalonia-Version: 11.0.6

## Additional context
I've attached a demo that makes 100 items. The checkboxes are bound to `ListBoxItem.IsVisible`. Uncheck some and they'll disappear. Scroll down a bit then back up and they'll be back but unchecked.

Also you can uncomment the `StackPanel` for the `ItemsPanel` and see that it works fine when not `VirtualizingStackPanel `.

[ListBoxItem_IsVisible_Bug.zip](https://github.com/AvaloniaUI/Avalonia/files/13705968/ListBoxItem_IsVisible_Bug.zip)

**Comment by maxkatz6** [comment]
It seems to be an expected behavior, as virtualized stack panel manages visibility of these controls by itself. I.e. un-realized control is set to invisible until it's needed to be used somewhere else. Possibly change of value priorities might help here, but I am not sure. 
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/VirtualizingStackPanel.cs#L648

**Comment by timunie** [comment]
Typically this is a task for collection filtering. DynamicData for example helps me in such situations.
