### ISSUE TITLE
SuggestedStartLocation not Working in Linux for OpenFile/OpenFolder Pickers

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUI/Avalonia#14063]
Using Garuda Linux (arch-based and Avalonia 11.0.6

Setting SuggestedStartLocation works for SaveFile, but OpenFile goes to latest location, and OpenFolder always select Home.

and... Why does this return null on Linux? It works for Documents but not for Downloads?

`await Storage.TryGetWellKnownFolderAsync(WellKnownFolder.Downloads);`

**Comment by thevortexcloud** [comment]
`SuggestedStartLocation` does kind of imply it may not do anything, it's a suggestion. The XDG portal documentation makes that even clearer:

> Suggested folder from which the files should be opened.
>
>The portal implementation is free to ignore this option.

However it looks like support for `current_folder` was added only last month based on the commit messages. So try nightly?

https://github.com/AvaloniaUI/Avalonia/commit/0567a6dbe7dc122ba90e019320708e0cbc51b635

**Comment by thevortexcloud** [comment]
I am not 100% sure which StorageProvider is being used here, but it looks like the downloads folder comes from this bit of code:

https://github.com/AvaloniaUI/Avalonia/blob/fe671b2cebf6f0a4b55e1a3a5a55cd7969c1122a/src/Avalonia.Base/Platform/Storage/FileIO/BclStorageProvider.cs#L110-L124

Which looks like it should never return null on Linux. The worst case is it assumes `~/Downloads` is the downloads folder. Which should be correct in 99% of cases. So I am not sure what's going on here unless it's using a different storage provider.

**Comment by maxkatz6** [comment]
It's not a bug. API is pretty clear that there are no guarantees.
Especially on Linux.

@thevortexcloud yes, `XDG_DOWNLOAD_DIR` should be used on Linux. Or `~/Downloads` if `XDG_DOWNLOAD_DIR` is not set.

**Comment by mysteryx93** [comment]
This command will display a Open File dialog and select the specified file in Downloads folder; although it only  selects a target file or folder instead of setting the browsing folder, it's pretty close... It's not the same Open File dialog (GTK) as used by Avalonia though.

    zenity --file-selection --filename=/home/hanuman/Downloads/Apocalypse.jpg

https://help.gnome.org/users/zenity/stable/file-selection.html.en

> @thevortexcloud yes, `XDG_DOWNLOAD_DIR` should be used on Linux. Or `~/Downloads` if `XDG_DOWNLOAD_DIR` is not set.

This certainly looks like a bug to me!

**Comment by thevortexcloud** [comment]
Avalonia generally uses XDG Portals (which it for some reason calls dbus despite it only using dbus to trigger it), not Gnome for doing file pickers. This makes it appear far more native than using a specific tool kit to do it. EG on KDE it will show the QT/KDE picker and on Gnome it will show the GDK picker. If it's showing a GTK picker for you that's because you have the GTK portal installed. I think you can force it to always use GTK though by fiddling with these options:

https://github.com/AvaloniaUI/Avalonia/blob/fe671b2cebf6f0a4b55e1a3a5a55cd7969c1122a/src/Avalonia.X11/X11Platform.cs#L266-L276

> This certainly looks like a bug to me!

How so? The only other real option here is to throw an error. Which would be a breaking change.

**Comment by mysteryx93** [comment]
Ya it's a `CompositeStorageProvider`; it's just a wrapper that first try DBus and then GTK. It only forwards the calls. It's not showing GTK picker so it's definitely passing the calls to the DBus provider.
