### ISSUE TITLE
[ControlCatalog] PlatformInfoPage in Sample App uses private API "AvaloniaLocator.Current"

### ISSUE THREAD

**Issue by afluegge** [AvaloniaUI/Avalonia#14780]
## Describe the bug
The ControlCatalog demo application demonstrates on page PlatformInfoPage how to get runtime information from the Avalonia system.  It does so by using API that is marked private: "AvaloniaLocator.Current".

## To Reproduce
Create a vanilla Avalonia app and try to run the code in question in it.  The code will not compile as "Current" is an internal member.

## Expected behavior
The ControlCatalog page should be updated to no longer using private API.

## Environment

- OS: Windows 10/11
- Avalonia-Version: 11.0.9

## Additional context
It would be beneficial to provide a feature to get to the same information as showcased in the ControlCatalog's PlatformInfoPage.

**Comment by timunie** [comment]
> [!TIP]
> We could try to use .NET's `OperatingSystem`, or `RuntimeInformation` if .NET Framework / Standard

Thanks @MrJul

**Comment by rabbitism** [comment]
It's also impossible to get OperationSystemm detail in .netstandard 2.0 project. Hope Avalonia can expose this API or information.

**Comment by maxkatz6** [comment]
> It's also impossible to get OperationSystemm detail in .netstandard 2.0 project

RuntimeInformation exists there. We won't add these APIs, as it will duplicate everything.

**Comment by afluegge** [comment]
Well, here my 2 cent to this fix:
Adding a note to not use what is demonstrated in a demo app, that many people use as reference and addition to the docs, that the code demonstrated here is not meant to be used in production apps is understandable.  But that you still use the internal api is from my point of view not acceptable.  I would expect that you adjust the sample in a way that it does not use internal api.

**Comment by timunie** [comment]
> But that you still use the internal api is from my point of view not acceptable. I would expect that you adjust the sample in a way that it does not use internal api.

ControlCatalog is not there to be a "sample" for learning Avalonia. I know many (including myself) do it so, but we have docs and Avalonia.Samples for this purpose. samples in the source are more meant for contributors to show and test new features and thus, sometimes we need to use those APIs. Also this sample has been growing in the past and some old APIs are still in use because it never was cleaned up. That said, I think at some point in time we need kind of a stand-alone ControlCatalog that only consumes nuget packages as you as a consumer do.
