### ISSUE TITLE
Main Window flickers in incorrect location prior to rendering in v11.1.0-beta1

### ISSUE THREAD

**Issue by billhenn** [AvaloniaUI/Avalonia#15003]
### Describe the bug

When a main `Window` is opened for an app, it can briefly show its titlebar and frame in a certain location, then it moves to another location and displays fully-rendered.  This behavior was first observed in v11.1.0-beta1 and @grokys narrowed the change that caused it down to [this PR](https://github.com/AvaloniaUI/Avalonia/pull/14470).

### To Reproduce

- Follow steps here to download and open our sample solution:  https://github.com/Actipro/Avalonia-Controls#download-and-run-samples
- In the `/Samples/SampleBrowser/References/Avalonia.References.props` file, update `AvaloniaVersion` to `11.1.0-beta1`.
- Do a full solution rebuild.
- Run the app and see if you notice the ghost window flicker before the main window shows properly.
- Revert `AvaloniaVersion` back to `11.0.7` (or a later 11.0 build) and full rebuild solution and run again.  You won't see the flicker.

### Expected behavior

There should be no flicker when the main window is opened.

### Avalonia version

11.1.0-beta1

### OS

Windows

### Additional context

This flicker was observed on latest Windows 11.

**Comment by grokys** [comment]
@TomEdwardsEnscape any idea how #14470 might have caused this, and what the fix might be?

**Comment by TomEdwardsEnscape** [comment]
Looks like even though `SetWindowPos` will restore a minimised window, it will not show one that has not yet been shown. This means that a change in behaviour snuck in via #14470 when an unshown window is resized.

The problem is noticeable in the Actipro repo because their window takes a long time to open, then removes window decorations and centres itself on-screen. But it's replicable in any window if those conditions are replicated.
