### ISSUE TITLE
Composition Animation doesn't fire the first time

### ISSUE THREAD

**Issue by laolarou726** [AvaloniaUI/Avalonia#15096]
### Describe the bug

From the repro I provided ([https://github.com/laolarou726/CompositionBug](https://github.com/laolarou726/CompositionBug)), you can notice that the composition animation will not work the first time of button clicks. If you click more after the first time, everything will work as expected.

I also tried the latest nightly version of Avalonia from the nightly feed, but the issue still exists.

### To Reproduce

[https://github.com/laolarou726/CompositionBug](https://github.com/laolarou726/CompositionBug)

### Expected behavior

The animation should fire the first time of mouse clicks.

### Avalonia version

11.0.10

### OS

Windows

**Comment by laolarou726** [comment]
any updates on this one? tried latest Avalonia nightly problem is still presents

**Comment by fr1g** [comment]
@maxkatz6 @kekekeks same issue suffering and this is **not an april-first joke**
can anyone handle this and give us a patch as soon as possible? this already made a lag in the progress of new applications. 
<del> Even you can consider firing it twice for each first-time startup</del>

**Comment by MikeCodesDotNET** [comment]
@fr1g If you require prioritised bug fixes and support, I invite you to explore our [support agreements](https://avaloniaui.net/support). Otherwise, issues are addressed based on availability and project priorities.

**Comment by wladysakemi** [comment]
hey but sincerely, in my region if i got that money that you asked for as donate, here won't be me to write my codes.
I suggest you that all of you perhaps should re-order your priority and let us know your weekly plan (to be solved at least)
and yes i am unwealthy dude, i know you need donation to keep up since me too

**Comment by fr1g** [comment]
> hey but sincerely, in my region if i got that money that you asked for as donate, here won't be me to write my codes. I suggest you that all of you perhaps should re-order your priority and let us know your weekly plan (to be solved at least) and yes i am unwealthy dude, i know you need donation to keep up since me too

I saw the 1-year indie support starts at 7900 CNY and divided into per month is looks like my monthly meal cost. If I got income perhaps I will pay for my org..

**Comment by wladysakemi** [comment]
> > hey but sincerely, in my region if i got that money that you asked for as donate, here won't be me to write my codes. I suggest you that all of you perhaps should re-order your priority and let us know your weekly plan (to be solved at least) and yes i am unwealthy dude, i know you need donation to keep up since me too
> 
> I saw the 1-year indie support starts at 7900 CNY and divided into per month is looks like my monthly meal cost. If I got income perhaps I will pay for my org..

but in stalingrad 1k ewro can buy alot
and yet i also have nothing income, im still stuck in academia

**Comment by fr1g** [comment]
> > > hey but sincerely, in my region if i got that money that you asked for as donate, here won't be me to write my codes. I suggest you that all of you perhaps should re-order your priority and let us know your weekly plan (to be solved at least) and yes i am unwealthy dude, i know you need donation to keep up since me too
> > 
> > 
> > I saw the 1-year indie support starts at 7900 CNY and divided into per month is looks like my monthly meal cost. If I got income perhaps I will pay for my org..
> 
> but in stalingrad 1k ewro can buy alot and yet i also have nothing income, im still stuck in academia

where??

**Comment by MikeCodesDotNET** [comment]
@wladysakemi, we determine our priorities based on various factors, including the impact on the broader community and the needs of our paying customers. 

> perhaps should re-order your priority

Demanding we reprioritise our work because you've found an issue that impacts your app is not how collaborative open-source works. 

> let us know your weekly plan (to be solved at least)

Additionally, we do not provide individual users with weekly updates on when issues might be resolved. We're focused on development rather than generating status reports for non-paying users. If you require this level of insight, consider a support agreement.

While we strive to address issues as soon as possible, individual issue timelines are not guaranteed. If you need guaranteed service, you can purchase a support agreement.

**Comment by laolarou726** [comment]
@maxkatz6 @kekekeks Are there any temporary fixes available now? I tried to run animation twice but it still broken. Looks like the first animation successfully committed and executed but somehow the renderer does not repaint the window?

**Comment by laolarou726** [comment]
fixed by #17370
