### ISSUE TITLE
Add CustomPopupPlacementCallback support

### ISSUE THREAD

**Issue by actipro-admin** [AvaloniaUI/Avalonia#15233]
### Is your feature request related to a problem? Please describe.

WPF has a [CustomPopupPlacementCallback](https://learn.microsoft.com/en-us/dotnet/api/system.windows.controls.primitives.custompopupplacementcallback?view=windowsdesktop-8.0) delegate that can be assigned to their [Popup](https://learn.microsoft.com/en-us/dotnet/api/system.windows.controls.primitives.popup?view=windowsdesktop-8.0) and when `Popup.Placement == PlacementMode.Custom`, that delegate is used to supply dynamic options for placement via callback.  The options are returned in an array of [CustomPopupPlacement](https://learn.microsoft.com/en-us/dotnet/api/system.windows.controls.primitives.custompopupplacement?view=windowsdesktop-8.0) objects, and the one that appears first and allows the popup to fit best on screen is the one that is used.

We have a requirement where an Avalonia `Control` that has a `ToolTip` needs to display that tip in a certain location relative to the target control.  However, that relative location changes based on the current state of the target control and other controls around it at the time popup shows.  Thus, we cannot use the simple `Placement` properties on `Popup` and need the use of a dynamic callback like in WPF to allow us to alter things on the fly.

### Describe the solution you'd like

While we don't necessarily need the API to match WPF's `CustomPopupPlacementCallback` and `CustomPopupPlacement` exactly (they are slightly difficult to grasp when first learning them), we do need a callback function that can tell a popup like a `ToolTip` to display at some location relative to the target control.  

The Avalonia [Popup](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Primitives/Popup.cs) already has some slight differences and enhancements over WPF popups, so we are happy to have a discussion on API implementation for this callback feature that would fit into the Avalonia model.

**Comment by kekekeks** [comment]
The API is designed to be Wayland-compatible and is designed against `xdg_positioner` object from `xdg-shell` protocol.
 Any placement API that requires access to global screen coordinates won't be Wayland-compatible.


To position your popup relative to the top-left corner of a control use OffsetX/OffsetY properties with TopLeft anchor and BottomRight gravity.

**Comment by billhenn** [comment]
Just to clarify, the callback in WPF doesn't use screen coordinates.  It is all coordinates relative to the target element.  So a `(0,0)` placement value would mean upper left of the target control.

The WPF callback allows us to look at things like target element size, popup size, and horizontal/vertical offsets, and then return target element-relative placement options.  I would think that should be Wayland-compatible since it's not global screen coordinates.

The WPF way would not make us alter the actual `HorizontalOffset` and `VerticalOffset` values since it expected the callback result's placements to specify a target element-relative location and axis.  See the WPF [CustomPopupPlacement](https://learn.microsoft.com/en-us/dotnet/api/system.windows.controls.primitives.custompopupplacement?view=windowsdesktop-8.0) for what the result there includes.  Keep in mind that since it's using a `PlacementMode.Custom` setting for this, the `Placement` property is not even considered.

---

I admittedly don't know the nuts and bolts of how Avalonia implemented popup positioning very well but when searching around, I happened to see a `PopupPositionerParameters` class, which looks like a promising possible result for a callback.

If you guys are initializing a `PopupPositionerParameters` based on current props, what if we added a callback delegate property to `Popup` (or could be done via an event I suppose too) and if specified, it would pass in the `PopupPositionerParameters` you built but would allow us to tweak it further before it was actually used?  The callback would need to have access to the target anchor element (to see it and its size), the popup (to see it and some of its properties).

If we could alter the `PopupPositionerParameters` before it was used, that would allow us to dynamically change popup positioning based on the current state of the target element.  And if the callback wasn't specified, or it did nothing in its logic, your current default positioning parameters would be used.  Does that sound reasonable?
