### ISSUE TITLE
Binding a property in datatemplate via a named control caused memory leak

### ISSUE THREAD

**Issue by lfeng1420** [AvaloniaUI/Avalonia#15444]
### Describe the bug

When binding a property from viewmodel in datatemplate through a named control, memory leak occured. see below code:
```xaml
<ListBox x:Name="elems" ItemsSource="{Binding Elements}">
        <ListBox.ItemTemplate>
            <DataTemplate DataType="vm:Element">
                <Grid ColumnDefinitions="Auto,*,Auto">
                    <CheckBox IsChecked="{Binding IsSelected}" />
                    <TextBlock
                        Grid.Column="1"
                        VerticalAlignment="Center"
                        Text="{Binding Text}" />
                    <TextBlock
                        Grid.Column="2"
                        VerticalAlignment="Center"
                        Text="{Binding #elems.((vm:MainViewModel)DataContext).Greeting}" />
                </Grid>
            </DataTemplate>
        </ListBox.ItemTemplate>
    </ListBox>
```

if replace '#elems' with '$parent[ListBox]', everything will be fine.

### To Reproduce

1. clone this [repo](https://github.com/lfeng1420/AvaloniaApp1)
2. build project and run
3. scroll from home to end, then from end to home (see below video)

repeat step 3 multiple times, and you will see Process Memory stays high and never fall back

https://github.com/AvaloniaUI/Avalonia/assets/7549203/e5021447-8b92-4335-8253-b5323777c0c7

### Expected behavior

no memory leak occurs.

### Avalonia version

11.0.10

### OS

Windows

**Comment by timunie** [comment]
test also 11.1 beta pls

**Comment by workgroupengineering** [comment]
Same as #15443

**Comment by lfeng1420** [comment]
> test also 11.1 beta pls

i tried 11.1.0-beta1, also exists.

**Comment by lfeng1420** [comment]
> Same as #15443

oh, i'll close this issue

**Comment by BAndysc** [comment]
I am not sure it is the same leak, I think it is a different thing. I think it is better to keep it open, memory leaks are a big problem, better keep track of all repros.

**Comment by BAndysc** [comment]
This leak is caused by [`NamedElementNode`](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Data/Core/ExpressionNodes/NamedElementNode.cs#L9) keeping a strong reference via `_value`

https://github.com/AvaloniaUI/Avalonia/blob/a32a8726a36665282b8ee70985154c20fe8123f6/src/Avalonia.Base/Data/Core/ExpressionNodes/ExpressionNode.cs#L15

so it is a different problem than #15443

**Comment by lfeng1420** [comment]
> I am not sure it is the same leak, I think it is a different thing. I think it is better to keep it open, memory leaks are a big problem, better keep track of all repros.

reopen now~

**Comment by maxkatz6** [comment]
@BAndysc note, you attached file from 11.1 version, while this issue is reproduced on 11.0.

11.0.10 code doesn't seem to use strong references there: https://github.com/AvaloniaUI/Avalonia/blob/11.0.10/src/Avalonia.Base/Data/Core/ExpressionNode.cs

**Comment by BAndysc** [comment]
That's true, I didn't take a look at 11.0 branch, and also, my conclusion that the leak is caused by _`NamedElementNode` having a strong reference_ is not accurate, to say the least. I mean, it is the whole path from root which matters. A screenshot if it is any help:

![image](https://github.com/AvaloniaUI/Avalonia/assets/5689666/0ee8d47f-fd0d-4fa4-8e60-e6774512d424)

The right path shows a leak where named binding is involved, with my zero knowledge about styling and binding system, I can't tell where the leak "begins".

As a non paying user I can't influence much, but imho those leaks are quite a big problem, affecting vast majority of the user base (even if they don't know).

**Comment by timunie** [comment]
We're nit saying these leaks couldn't get a problem. So better to fix them st some point in time. If you want to help us speeding it up, you can also add your sample into src/Samples/Sandbox and try to debug it. From there you can step through the whole binding path. Again, I don't force anyone to do that, just an idea.
