### ISSUE TITLE
Flickering cursor over a Button with ToolTip in the bottom right corner

### ISSUE THREAD

**Issue by CodeDevAM** [AvaloniaUI/Avalonia#15486]
### Describe the bug

In my app I have a small `Button` in the bottom right corner that has a `ToolTip`. When the mouse comes over the button the cursor starts to flicker and the `ToolTip` does not show up. It seems to appear especially when the `Window` is maximized.

https://github.com/AvaloniaUI/Avalonia/assets/125025268/66d6a5f2-f6c8-4e6a-af73-6b1afd23e9b2

Please note that I am using Semi theme. I don't know if it is of relevance for this issue.

### To Reproduce

It is very prominent in my app but it is not that easy to reproduce in a standlone minimal example.

[ToolTipCornerIssue.zip](https://github.com/AvaloniaUI/Avalonia/files/15081165/ToolTipCornerIssue.zip)

### Avalonia version

11.0.10

### OS

Windows

**Comment by TomEdwardsEnscape** [comment]
Your video is just black for me.

Tootips have been refactored recently, can you still reproduce your issue in 11.1.0-beta2?

**Comment by CodeDevAM** [comment]
> Your video is just black for me.

It's probably due to the 4K resolution. There is a very tiny Button in the bottom right corner. I probably should have reduced the resolution of my screen for the recording.

> Tootips have been refactored recently, can you still reproduce your issue in 11.1.0-beta2?

After short test: It seems not to appear with 11.1.0-beta2.

**Comment by timunie** [comment]
@CodeDevAM if 11.1.beta resolves your issue, this ticket can be closed. Please do us a favor and always test at least beta (even better nightly) versions before opening an issue, as many things are already solved in there. Thx.

**Comment by CodeDevAM** [comment]
The problem still occurs with 11.1.0-beta2.

**Comment by TomEdwardsEnscape** [comment]
I could reproduce the issue after pasting this grid into the Sandbox project:

``` xaml
  <Grid
  ColumnDefinitions="1*, Auto"
  RowDefinitions="1*, Auto">

    <Button
			Grid.Column="1"
			Grid.Row="1"
			Content="X"
            ToolTip.VerticalOffset="0"
			ToolTip.Tip="Clear completed, failed and canceled count"/>

  </Grid>
```

Note the custom `VerticalOffset` value.

It seems to be the same issue as one [I recently worked around](https://github.com/AvaloniaUI/Avalonia/pull/15312/files#diff-6f4acaea5516b8b9832cfa8eb07eb632c79be31e5a8a86d686928661e1416225R46-R47) in #15312. At the very edge of a tooltip popup there is a region which sometimes counts as being over the popup, but does not have any hit test result. So we think there is nothing beneath the pointer end up opening and immediately closing the tooltip in a loop.

Workaround: move the cursor a bit so that the cursor isn't directly over the edge of the popup.

**Comment by timunie** [comment]
@CodeDevAM @TomEdwardsEnscape does it also happen in nightly?
