### ISSUE TITLE
When calling the external c++ dll, the  dragdrop will does not work

### ISSUE THREAD

**Issue by iqianyue** [AvaloniaUI/Avalonia#15523]
### Describe the bug

When the app  is started，dragdrop is work fine，bug when call a  c++ dll method ，the dragdrop will does not work

![code1](https://github.com/AvaloniaUI/Avalonia/assets/23432828/6c4b9e86-25d0-4ccf-9e38-44a137c2109c)
![code2](https://github.com/AvaloniaUI/Avalonia/assets/23432828/a0db5104-3342-4a23-b05f-4ec7d71eaf77)

### To Reproduce

![Snipaste_2024-04-26_16-32-43](https://github.com/AvaloniaUI/Avalonia/assets/23432828/8133524f-21bd-4e8c-8016-336d0654563d)

### Expected behavior

dragdrop stop working

### Avalonia version

11.0.10

### OS

Windows

### Additional context

windows 10

**Comment by MrJul** [comment]
We need more information and a minimal reproduction project here, as we have no idea what your `test` unmanaged method is doing.

Drag and drop not working anymore could be because you're un-initializing OLE (maybe without realizing it).

Note that we have a bunch of P/Invoke calls inside Avalonia, and they don't cause any issue.

**Comment by iqianyue** [comment]
你好，您发给我的信件已经收到。

**Comment by iqianyue** [comment]
thanks！I have problems with my c++ code
