### ISSUE TITLE
Listbox virtualized with zoom in/out (using LayoutTransformControl) issues

### ISSUE THREAD

**Issue by Whiletru3** [AvaloniaUI/Avalonia#15712]
### Describe the bug

If we use a ListBox with a LayoutTransformControl in the ListBoxItem to be able to zoom in/out, there are some issues :

1) If I slide to an item, then zoom out and scroll to the first item, there are a space left before the first item :
![EmptySpaceUpAfterDezoom](https://github.com/AvaloniaUI/Avalonia/assets/4248852/5dafc0fa-a660-4a46-8250-8c1eb97def9e)

2) If I zoom out, select an item, then zoom in (until the selected item goes out of the viewport), the selected item will be still displayed with the old position
![SelectedItemFocusedMoveAtZoom](https://github.com/AvaloniaUI/Avalonia/assets/4248852/22e6316d-7d89-49bb-b7ee-5fb50dc279c4)

3) at launch, there are one ListBoxItem realized, if I zoom out, of course more items will be realized. But if I zoom in again, the max number of ListBoxItem will remain (of course they will be empty). It should be better to flush those item.
![TooMuchListboxItemInTheRecyclerWhenDezoomZoom](https://github.com/AvaloniaUI/Avalonia/assets/4248852/a0600594-b72b-4f20-9baa-8c277c4aa7a1)

### To Reproduce

Here is the sample to reproduce :
https://github.com/Whiletru3/Avalonia/tree/VirtualizationImagesSample/samples/VirtualizationImages

### Expected behavior

The ListBox should react normally using a LayoutTransformControl

### Avalonia version

11.0.10, 11.1 

### OS

Windows, macOS

**Comment by Whiletru3** [comment]
Do you have any clue (to make a PR) for the resolution of this bug ?

**Comment by grokys** [comment]
I've opened a PR with a fix for the first 2 items in this issue:

https://github.com/AvaloniaUI/Avalonia/pull/16168

Regarding item 3: this is intentional - unrealized elements are not removed unless the number of items changes such that the number of realized and unrealized elements is greater than the item count. This is because when scrolling through items with variable heights, the number of required elements changes frequently and so they may be required later.
