### ISSUE TITLE
[DevTools] Allow Configure Inspect Hovered Control KeyBinding

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#15790]
### Is your feature request related to a problem? Please describe.

When you have multiple keyboard layouts on Windows 10-11, the "CTRL-SHIFT" key combination is associated with the action of switching keyboard layouts. This does not allow you to use Inspect Hovered Control because it is binding to the same key combination.

### Describe the solution you'd like

Allow configure InspectHoveredControl KeyBinding

**Comment by stevemonaco** [comment]
The main issues that caused me to punt on mutability of hotkeys (and why they weren't implemented in #15700 :

1. There's no settings store for DevTools. This means in-app changes only last until the next debugging launch. You could configure in code, but that effects your entire team.
2. There's no dialog system in DevTools, so that needs implemented or a workaround. In-place edits might be enough, but I do have other feature ideas where a small input dialog would be very useful. Any dialog needs to hidden from the DevTools Logical/Visual Trees, which https://github.com/AvaloniaUtils/DialogHost.Avalonia would support (being an overlay), but this doesn't warrant bringing in an external dependency, IMO.
3. Not sure if the quality / naming is good enough for `HotKeyConfiguration` to be made `public`, so I left this part malleable for any future implementer.

**Comment by workgroupengineering** [comment]
> 1. There's no settings store for DevTools. This means in-app changes only last until the next debugging launch. You could configure in code, but that effects your entire team.

To solve this problem I load DevToolsOptions from appsettings.development.json

**Comment by workgroupengineering** [comment]
Hi @maxkatz6,
Can I do a PR? Should I make [this](https://github.com/AvaloniaUI/Avalonia/blob/4153ef720befc635d0ed4ebc0bea0c251060f2df/src/Avalonia.Diagnostics/Diagnostics/DevToolsOptions.cs#L64) public or implement [this](https://github.com/AvaloniaUI/Avalonia/pull/15700#issuecomment-2109514853)?
