### ISSUE TITLE
Can't edit cells of datagrid with DataGridCollectionView in ItemsSource

### ISSUE THREAD

**Issue by BreakByBrick** [AvaloniaUI/Avalonia#15865]
### Describe the bug

Hello!

When ItemsSource of DataGrid binded to DataGridCollectionView, cell editing by double click is not working.
But when ItemsSource binded to ObservableCollection, cell editing is working.

### To Reproduce

https://github.com/BreakByBrick/Avalonia.Issue/tree/main/DataGrid.CantEditDataGridCollectionView

![image](https://github.com/AvaloniaUI/Avalonia/assets/119886555/257f411d-f4e3-4687-baba-b695adac9d66)

### Expected behavior

Double click on DataGrid cell with ItemsSource binded to DataGridCollectionView, starts cell editing.

### Avalonia version

11.0.10

### OS

Windows

**Comment by timunie** [comment]
can you please try 11.1 beta?

**Comment by Abdesol** [comment]
> can you please try 11.1 beta?

I just tested it out on the master branch. The issue is still around.

**Comment by Abdesol** [comment]
The issue persisted even when I was not using `IReadOnlyList`, because of the casting with parenthesis in the properties path internally. I have fixed that issue with the pull request I made today. 
However, using IReadOnlyList will still make it uneditable since IReadOnly sets the ReadOnly property on the data grid column. It is working for you on the observable collection one because, it first changes to IEnumerable and then to ObservableCollection, in the process losing the read-only property.

The below referenced line of code is the one ultimately checking if it should be editable or not based on the list's property: 
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls.DataGrid/DataGridDataConnection.cs#L50
