### ISSUE TITLE
Screen API refactoring

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/Avalonia#15901]
### Is your feature request related to a problem? Please describe.

Current Screens API was designed and implemented very long time ago, when Avalonia supported way less platforms.

Main problems that needs to be solved:
- API is only available on Desktop. While both Mobile and Browser provide similar capabilities.
- There is no way to compare screens. Users have to write ugly hacks comparing screen sizes. It's also a problem for XPF.
- After retrieving Screen instance, it won't reflect any changes on the actual display. Developer needs to re-retrieve this Screen to get latest information.
- No way to subscribe on screen changes.
- No screen orientation, display name, unique handle available.

Browser related nuance:
Browser returns only single active display, where web browser is located. It also doesn't include display name info by default.
If developer want to retrieve extended information, like other screens and additional info, they need to run async [Window.getScreenDetails()](https://developer.mozilla.org/en-US/docs/Web/API/Window/getScreenDetails) API. At least once. In Avalonia, it can be covered by `RequestScreenDetails`-like API.

### Describe the solution you'd like

```diff
public class WindowBase : TopLevel
{
-    public Screens Screens { get; }
+    public new Screens Screens => base.Screens!;
}
public class TopLevel
{
+    public Screens? Screens { get; }
}

public class Screen
{
+    public string? DisplayName { get; }
+    public ScreenOrientation CurrentOrientation { get; }

+    public IPlatformHandle? TryGetPlatformHandle();
}

public class Screens
{
+    public event EventHandler? Changed;
+    public Screen? ScreenFromTopLevel(TopLevel topLevel);
+    Task<bool> RequestScreenDetails();
}

+public enum ScreenOrientation
+{
+    None, // Unspecified, Unknown ?
+    Landscape,
+    Portrait,
+    LandscapeFlipped,
+    PortraitFlipped
+}
```

### Additional context

Child issues:
- [ ] https://github.com/AvaloniaUI/Avalonia/issues/15382
- [ ] https://github.com/AvaloniaUI/Avalonia/issues/11512
- [ ] https://github.com/AvaloniaUI/Avalonia/issues/15637

**Comment by maxkatz6** [comment]
Media query API can re-use the same new Screen API as well.

**Comment by kekekeks** [comment]
How would we identify a particular screen? By connector id?

**Comment by maxkatz6** [comment]
@kekekeks does it work as an answer? https://github.com/AvaloniaUI/Avalonia/issues/15382#issuecomment-2057975936

**Comment by thevortexcloud** [comment]
I think a user readable identifier would also be useful, even if it's only implemented on some platforms. EG if you can read EDID (should be possible on all desktops) you can get the manufacturer name, model number and serial number of the display. EDID however is not always the most reliable thing (EG it's very easy to spoof on Linux), but it makes it much easier to show monitors with the same model number/display name. Even if the ports they are connected to changes.

**Comment by anose001** [comment]
@maxkatz6 , @kekekeks , @simonhaines, @thevortexcloud 
I came to this thread while looking for responsive Avalonia app resources #15991 with the goal to clear up on how to properly design a UI for a range of devices using Avalonia. I found the [Avalonia Materials library](https://github.com/AvaloniaCommunity/Material.Avalonia) but no clear guidelines on how to properly approach adaptive or responsive design other than this rudimentary [example](https://github.com/AvaloniaUI/Avalonia.Xaml.Behaviors/blob/master/samples/BehaviorsTestApplication/Views/Pages/AdaptiveBehaviorView.axaml), as UI/UX across different devices is not something I have done before and I am fairly new to Avalonia.

The mobile community has thought about this problem for a little while longer it looks like. 
For example, the Android developer guide for [different screen sizes](https://developer.android.com/develop/ui/compose/layouts/adaptive/support-different-screen-sizes) suggests to "avoid using physical, hardware values for making layout decisions" ([link](https://developer.android.com/develop/ui/compose/layouts/adaptive/support-different-screen-sizes#:~:text=Avoid%20using%20physical%2C%20hardware%20values%20for%20making%20layout%20decisions.)) and instead use the actual portion of the screen that is covered by the app. They argue to think about this in terms of [window size classes](https://developer.android.com/develop/ui/compose/layouts/adaptive/window-size-classes) which they define as opinionated viewport breakpoints classifying the UI layout into size categories such as compact, medium, large, etc. They argue a little bit more on why a physical devices class should not be used to design your window layout (unless you develop for one specific device size). A very helpful read, overall touching a good amount pain points that developers face down the road. 

Their guideline on window size classes is in agreement with the guideline from the Materials Design Foundation on [how to design across window classes](https://m3.material.io/foundations/layout/applying-layout/window-size-classes#8ad6450f-8b40-4364-9eda-33eb131534ee). Guidelines and how to's like these are something that I am missing in Avalonia's official documentation as well as the communities Avalonia Materials library and I believe should rather be part of a UI framework library.

It seems like this feature request is moving along these lines if I am not mistaken?
My questions for the architects of the library then:
- Is adaptive design with different window classes the proper way to use Avalonia capabilities to design for a variety of devices and app window sizes?
- Is there a proper approach on how to rearrange a navigation bar (or even change the type of navigation control) if the window size changes from let's say compact to large?
- Last but not least, will this Screen API return the window size in term of **dp**'s, density-independent pixels, as this is the only **platform-agnostic** and **device-agnostic** measure that I have found to make the sense for designing layouts of different sizes. Or will you focus on returning a recommended window size class instead?

Since the term dp is not uniform across platforms I add [this overview](https://www.gregoryschmidt.ca/writing/when-is-a-pixel-not-a-pixel-pixels-points-dps), as px are used for Web, pts for iOS, and dps for Android.

Also, this is how Android developers retrieve the window size class `val windowSizeClass = currentWindowAdaptiveInfo().windowSizeClass` as described [here](https://developer.android.com/develop/ui/compose/layouts/adaptive/window-size-classes#:~:text=You%20can%20compute%20the%20current%20WindowSizeClass%20using%20the%20currentWindowAdaptiveInfo%20top%E2%80%91level%20function%20of%20the%20androidx.compose.material3.adaptive%20library.%20The%20following%20example%20shows%20how%20to%20calculate%20the%20window%20size%20class%20and%20receive%20updates%20whenever%20the%20window%20size%20class%20changes%3A).

Apple has a similar approach via their [UserInterfaceSizeClass](https://developer.apple.com/documentation/SwiftUI/UserInterfaceSizeClass), based on adaptive design principles.

- When developing for iOS and Android are these the approaches for window sizes recommended by Avalonia as well?

**Comment by thevortexcloud** [comment]
> Is there a proper approach on how to rearrange a navigation bar (or even change the type of navigation control) if the window size changes from let's say compact to large? I would rather try to avoid multiple views for something like this.

You can do this already with a converter and binding to the window width. Although you will have to define what counts as large/small yourself.

> Last but not least, will this Screen API return the window size in term of dp's, density-independent pixels, as this is the only platform-agnostic and device-agnostic measure that I have found to make the sense for designing layouts of different sizes. Or will you focus on returning a recommended window size class instead?

Avalonia already has device independent pixels. EG the PixelSize struct contains many methods for calculating them.

https://github.com/AvaloniaUI/Avalonia/blob/b1e96ad6ef09d012be30efcbf050f47cb4e7fbf4/src/Avalonia.Base/PixelSize.cs#L154-L184

Many things already use them.

**Comment by maxkatz6** [comment]
Completed in 11.2 nightly. Mobile support is coming later.
