### ISSUE TITLE
TextAlignment.DetectFromContent with an RTL line and TextWrapping produces a width of 0

### ISSUE THREAD

**Issue by Bip901** [AvaloniaUI/Avalonia#16009]
### Describe the bug

Consider the following text box which has 3 lines, one of them in Hebrew, a right-to-left language:
```xml
<TextBox Text="Hello&#10;שלום&#10;Really really really really long line"
		 Background="Beige"
		 HorizontalAlignment="Center"
		 MinWidth="0"
		 TextAlignment="DetectFromContent"
		 Height="68"
		 TextWrapping="Wrap"/>
```

The TextBox incorrectly measures a width of 0:

![incorrect](https://github.com/AvaloniaUI/Avalonia/assets/74911767/8e08fa7f-ae45-45bb-b939-368baed3a0b1)

(It has some width in the screenshot above due to padding, disable with `Padding="0"`)

### To Reproduce

Use the XML provided above.

### Expected behavior

The TextBox should have the same width as it has when `TextAlignment` is set to `Left`:

![correct](https://github.com/AvaloniaUI/Avalonia/assets/74911767/d0b91ae3-8072-4240-a1c6-273e8ee2b4a0)

```xml
<TextBox Text="Hello&#10;שלום&#10;Really really really really long line"
			Background="Beige"
			HorizontalAlignment="Center"
			MinWidth="0"
			TextAlignment="Left"
			Height="68"
			TextWrapping="Wrap"/>
```

### Avalonia version

11.0.10

**Comment by dbriard** [comment]
I have a similar with ContentPresenter and TextAlignment.
I am using TextAlignment="Center" in a TemplatedControl.
The control display well in designer, but when the control is used in the real app, in a view that is already visible on screen. The texts are empty.

Designer:
![image](https://github.com/AvaloniaUI/Avalonia/assets/3595443/4842a70f-6001-48ee-a3db-e2aa0c6d05c9)

App:
![image](https://github.com/AvaloniaUI/Avalonia/assets/3595443/237db183-e615-4507-ae0a-f726dbcd4a4c)

If I resize the window so that Measure of the control is called, or if I change view and get back (e.g. in a tab control), the display is now correct
![image](https://github.com/AvaloniaUI/Avalonia/assets/3595443/b3a5b74f-2857-4bf8-8950-fd82bbb49b78)

Same issue with TextAlignment="Right", but no problem with Left.

Avalonia 11.0.1 beta 2

**Comment by dbriard** [comment]
Another example of the issue with TextAlignment=Center: (no issue with HorizontalAlignment=Center)
![image](https://github.com/AvaloniaUI/Avalonia/assets/3595443/3b9d72ff-6cbc-4eaa-8447-4cc61a66a981)
I can use HorizontalAlignment instead of TextAlignement at the moment, but centering is not exactly the same. HorizontalAlignment is not perfectly centered, and don't work on multilines.


And another issue with text: not sure if it is the same bug or not but sometime the end of the text is not visible in ToolTips.
I display Bounds in a ToolTip:
![image](https://github.com/AvaloniaUI/Avalonia/assets/3595443/df55ba3f-d6d8-4a3c-af32-a6afd85fcacf)
![image](https://github.com/AvaloniaUI/Avalonia/assets/3595443/b343d2fc-8c9f-42cb-9fcc-1c7d78e41f7a)

**Comment by Bip901** [comment]
> And another issue with text: not sure if it is the same bug or not but sometime the end of the text is not visible in ToolTips.

That seems unrelated, the text is simply too long for the remaining space.
You could use a `TextWrapping` value of [`WrapWithOverflow`](https://reference.avaloniaui.net/api/Avalonia.Media/TextWrapping/) or increase the width of the ToolTip.

**Comment by dbriard** [comment]
> > And another issue with text: not sure if it is the same bug or not but sometime the end of the text is not visible in ToolTips.
> 
> That seems unrelated, the text is simply too long for the remaining space. You could use a `TextWrapping` value of [`WrapWithOverflow`](https://reference.avaloniaui.net/api/Avalonia.Media/TextWrapping/) or increase the width of the ToolTip.

I double checked and the tooltip is limited to 240 pixels wide with TextWrapping... so there is no reason that the text is truncated.
I also tried WrapWithOverflow instead of Wrap is the result is the same.

**Comment by dbriard** [comment]
Until the bug is fixed, here a ugly workaround for tooltips if someone need:


```
public class TruncatedToolTipWorkaroundConverter : IValueConverter
{
    public object? Convert(object? value, Type targetType, object? parameter, CultureInfo culture)
    {
        if (value is string s)
        {
            return s + ' ';
        }
        return value;
    }

    public object? ConvertBack(object? value, Type targetType, object? parameter, CultureInfo culture)
    {
        throw new NotImplementedException();
    }
}
```
Then in ToolTip theme:
`Content="{TemplateBinding Content, Converter={StaticResource TruncatedToolTipWorkaroundConverter}}"`

The tooltip is no more truncated at the end, but there is an additional whitespace, so small tooltips are no more centered.

**Comment by Gillibald** [comment]
This is unrelated to the original issue. Please create a new issue with a detailed reproducible.
