### ISSUE TITLE
Changing TextBlock.Text in UserControl code has no effect in UI

### ISSUE THREAD

**Issue by Feroks** [AvaloniaUI/Avalonia#1625]
I have a UserControl inside a View. UserControl has a TextBlock, which Text property is bound to code behind property. When property value is updated in code, it does not change in UI, unless some element is repainted (for example ProgressBar Value changes). This issue is present for TextBlock and TextBox. Hovering on TextBox updates the value in UI.

Tried to set value to TextBlock.Text directly, still does not update in UI. Tried Avalonia 0.6.1, 0.6.2-build5276-beta and several nightly versions in between. Still the same behavior.

Here is [repo](https://github.com/Feroks/Avalonia.Repaint) with example. I did not manage to find this issue reported. Am I using UserControls incorrectly?

**Comment by Gillibald** [comment]
Dont have time to build your project but the problem is probably due to the fact that you dont raise property change events

**Comment by Gillibald** [comment]
I have a feeling that this is related to either text alignment or alignment of the control itself. Can you try to remove the centering of your texts and text boxes? Just a guess.

**Comment by Feroks** [comment]
Removed TextAlignment and it worked! Thanks, @Gillibald 
If TextAlignment is set to Left, value is updated, but once it is Center or Right, it start to have issues.

**Comment by Gillibald** [comment]
Will have a look at it soon. Thanks for reporting.

**Comment by RoanDev** [comment]
Find a temporary solution: if you set TextBlock's Text to "" it erases text successfully. But:
```
            activeTextElement.Text = "";
            activeTextElement.Text = "123";
```
does nothing, because in that way framework's renderer skips that "empty" stage and doesnt erases a text. Playing with visibilities, "InvalidateVisual", etc gave no results.

The idea is to create 2 same TextBlocks in same position, first is visible, second is invisible. Once you need to change a text in that area you erases visible one and hides it, then set Text for second one and makes it visible. Doing it in that way will allow framework to think that first TextBlock have no more data, then this area will be erased. In the same time second TextBlock shows its Text. Once you need to change text again you have to do same thing, but now erase text for second one and hide it, then set text for first one and make it visible.
Sample:
```
        private void setDraggedFilesCount(int count)
        {
            TextBlock activeTextElement = this.DraggedFilesCountTextBlock.IsVisible ? this.DraggedFilesCountTextBlock : this.DraggedFilesCountTextBlock2;
            TextBlock nonactiveTextElement = !this.DraggedFilesCountTextBlock.IsVisible ? this.DraggedFilesCountTextBlock : this.DraggedFilesCountTextBlock2;
            activeTextElement.Text = "";
            activeTextElement.IsVisible = false;
            nonactiveTextElement.Text = Translations.RegisteredFilesTextTemplate + count;
            nonactiveTextElement.IsVisible = true;
        }
```
Example:
![ezgif com-optimize](https://user-images.githubusercontent.com/7278817/49699703-2280a300-fbdd-11e8-90ed-0d4fa0676708.gif)

**Comment by grokys** [comment]
Just taken a look at this and it's still a problem. Investigating. Sorry it took so long!

**Comment by grokys** [comment]
Interesting, this isn't actually anything to do with property changed events, the renderer is updating the wrong part of the window! If I enable drawing dirty rects you see:

![2019-03-02_18-38-05](https://user-images.githubusercontent.com/1775141/53685406-7ac9cb80-3d1a-11e9-8f5a-b0b5c294419b.gif)

**Comment by grokys** [comment]
Ok, this seems to be caused by `TextAlignment` not being respected when calculating the dirty rects.

**Comment by Gillibald** [comment]
Is that TextBox using TextAlignment=Center? Looks like the text's bounds are not shifted to the right position.

**Comment by grokys** [comment]
Yes, the problem is on this line:

https://github.com/AvaloniaUI/Avalonia/blob/bfdaea8055f7af78622cd959be9ed9222538ef2b/src/Avalonia.Visuals/Rendering/SceneGraph/TextNode.cs#L30

`TextNode` passes the bounds to the base class as a rect from `origin` to `text.Size`, which doesn't account for `TextAlignment`. There are two solutions i can think of to fix this:

- change `Size IFormattedTextImpl.Size` to be `Rect IFormattedTextImpl.Bounds`
- expose `IFormattedTextImpl.TextAlignment` and make the `TextNode` do the alignment of `Size` within `Constraint`

Which makes more sense to you?

**Comment by grokys** [comment]
Discussed this in gitter and the first option makes more sense: https://gitter.im/AvaloniaUI/Avalonia?at=5c7ac7efe1446a6ebe6fec5b
