### ISSUE TITLE
IBitmap is internal but the docs say it's public

### ISSUE THREAD

**Issue by Shadowblitz16** [AvaloniaUI/Avalonia#16263]
### Describe the bug

Description 

### To Reproduce

https://reference.avaloniaui.net/api/Avalonia.Media.Imaging/IBitmap/
![image](https://github.com/AvaloniaUI/Avalonia/assets/2453707/2cf08d11-10dd-402a-ab57-31916fae245f)

### Expected behavior

IBitmap should be public

### Avalonia version

11.0.11

### OS

Linux

### Additional context

I am trying to write a IndexedBitmap class

**Comment by rabbitism** [comment]
It is public, just not implementable.

**Comment by stevemonaco** [comment]
`IBitmap` is intended for renderer backend implementations. ie. For Skia or Direct2D base implementations. APIs annotated with `[NotClientImplementable]`, `[PrivateApi]`, ending with `Impl`, etc are internalized at build-time. Otherwise, Avalonia wouldn't be able to be distributed as packages without revealing all of its API.

`BitmapSource` is probably what you want to derive from, but it's not necessary. You can render pixel buffers with SKBitmap. So only necessary if you really need to use `<Image />` controls. In that case, you can use `WriteableBitmap` even.

Also, you should check the source code. That ref site is still on 0.10.x and shouldn't be used until it's updated.

**Comment by Shadowblitz16** [comment]
ok thankyou, and regarding the IndexedBitmap class I made a seperate discussion about it here https://github.com/AvaloniaUI/Avalonia/discussions/16264

**Comment by maxkatz6** [comment]
https://reference.avaloniaui.net/ is semi-deprecated and wasn't updated in a long time.
