### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by johannesegger** [AvaloniaUI/Avalonia#1649]
Avalonia doesn't seem to support Unicode. Is this planned for the future?

Repro steps:

```
git clone git@github.com:AvaloniaUI/avalonia-dotnet-templates.git
dotnet new --install .\avalonia-dotnet-templates\
dotnet new avalonia.app -o AvaloniaUnicodeTest
# Add unicode character to MainWindow.xaml, e.g. ▶
dotnet run
# You'll see something like □ instead of the unicode character
```

I'm using Avalonia 0.6.1 and Avalonia.Desktop 0.6.1 on Windows 10.

**Comment by wieslawsoltes** [comment]
Try saving Xaml file with UTF-8 encoding.

**Comment by johannesegger** [comment]
Notepad++ says it already *is* UTF-8 encoded.
![image](https://user-images.githubusercontent.com/237707/40938187-5f1a3c02-6841-11e8-81b6-e007d18e6fe6.png)

**Comment by Gillibald** [comment]
We dont do character matching in the current implementation. This issue has nothing to do with Encoding. The used font just dont have a glyph for that character. Maybe we can add that feature in the future.

**Comment by johannesegger** [comment]
That means I can just use another font? Super 👍  
I'm already looking forward to [custom fonts](https://github.com/AvaloniaUI/Avalonia/pull/1564) and hope this is released soon.

**Comment by Gillibald** [comment]
Custom fonts are already available in our nightly builds if you want to try it out.

**Comment by johannesegger** [comment]
Uhh that's nice, I overlooked that you have a custom NuGet feed with nightly builds, thanks.
I'll try it out soon and will close the issue if it works with a custom font.

**Comment by johannesegger** [comment]
Hm, I don't quite understand.  
I'm currently using the nightly build (0.6.2-build5340-beta) and `FontFamily.Default` is `Courier New` which should definitely support unicode characters like `▶`, so I'm not sure what's the problem.

**Comment by Gillibald** [comment]
Pls try "Segoe UI Symbol" and let me know if it works.

**Comment by johannesegger** [comment]
Nice, that works. Thanks a lot for your help.

**Comment by myblindy** [comment]
Can I recommend using setting the default font to something that can display the usual full range of Unicode characters?

**Comment by Gillibald** [comment]
The usual full range of unicode characters would be?

**Comment by kekekeks** [comment]
@myblindy there is no such font. Fonts are limited to 65536 glyphs. For more details see [this SO answer](https://stackoverflow.com/a/34734338/2231814).

**Comment by myblindy** [comment]
Yes, but you can choose a default font that displays as many as possible. `Segoe UI Symbol`, for example, is my go-to font, because it supports both the regular English characters, as well as East-Asian characters (Korean specifically is what I need). 

Also, WPF (and HTML) handles your comment specifically @kekekeks with [font fallback](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.fontfamily?view=netframework-4.7.1#font-fallback), where you can specify a list of fonts and it will try to render each character with the first font that defines it. This would have cut down my code to split korean text from emojis into string arrays to be bound to an `ItemsControl` that generates individual `TextBlock` elements for each sequence (runs are also not supported) to a simple string display.

**Comment by Gillibald** [comment]
The new text rendering infrastructure that is used by TextBlock supports the Unicode 12 spec. It does font fallback out of the box.

**Comment by myblindy** [comment]
Is that the 0.9 on Nuget? Or the nightly 0.10 builds?

**Comment by Gillibald** [comment]
Current nightly
