### ISSUE TITLE
IWindowImpl has an INTERNAL member

### ISSUE THREAD

**Issue by racerxdl** [AvaloniaUI/Avalonia#16553]
### Describe the bug

After #14909 a internal member has been added to a public interface. We currently has a custom implementation of window manager for our game engine and that is blocking us from updating the current avalonia version.

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Platform/IWindowImpl.cs#L155

Any reason why this is internal? This makes the interface non-implementable outside avalonia.

### To Reproduce

Try to implement IWindowImpl outside avalonia

### Expected behavior

Be able to implement.

### Avalonia version

11.1.x

### OS

Windows, macOS, Linux, WebAssembly, Android, iOS, Tizen

### Additional context

Is there any reason to keep that `internal` ?

**Comment by stevemonaco** [comment]
Yes, `[PrivateApi]`, `[Unstable]`, interfaces ending with Impl, etc have ref assembly patching (from `public` to `internal`). This allows Avalonia to be written in packages while restricting use of certain APIs outside of the team.

However, since you are integrating with a game engine, perhaps making a new Avalonia Platform, you do need access to those APIs. You can put `<AvaloniaAccessUnstablePrivateApis>true</AvaloniaAccessUnstablePrivateApis>` into your csproj. However, there is no guarantee of support or lack of breaking changes. I suggest isolating these usages in a separate project so that you don't unknowingly use private APIs in your broader code base.

**Comment by racerxdl** [comment]
> Yes, `[PrivateApi]`, `[Unstable]`, interfaces ending with Impl, etc have ref assembly patching (from `public` to `internal`). This allows Avalonia to be written in packages while restricting use of certain APIs outside of the team.
> 
> However, since you are integrating with a game engine, perhaps making a new Avalonia Platform, you do need access to those APIs. You can put `<AvaloniaAccessUnstablePrivateApis>true</AvaloniaAccessUnstablePrivateApis>` into your csproj. However, there is no guarantee of support or lack of breaking changes. I suggest isolating these usages in a separate project so that you don't unknowingly use private APIs in your broader code base.

We do have `<AvaloniaAccessUnstablePrivateApis>true</AvaloniaAccessUnstablePrivateApis>` enabled, but the issue is that we can't implement because that one method is declared as `internal`.

**Comment by stevemonaco** [comment]
Aha, I understand. This does appear to be an oversight in the PR to me.

**Comment by maxkatz6** [comment]
Yes, internal modifier should be removed. If you can send a PR, it should be backportable to the next patch release.

> internal member has been added to a public interface

Just in case, we don't treat these interfaces as public. Which should be clear from all the extra steps making them usable outside.
