### ISSUE TITLE
GestureRecognizers Additional Option

### ISSUE THREAD

**Issue by olivier-rmds** [AvaloniaUI/Avalonia#16691]
### Is your feature request related to a problem? Please describe.

I've noticed some changes were made to gesture recognizers a while ago so that a button would not prevent the scrolling gesture, however the problem I'm facing is sort of the reverse of what that "solves" which is that my pullGesturRecognizers prevents some button presses from working 90% of the time. I would rather the buttons work fine all the time and the scrolling or pulling only works in places that have no button, obviously that's not everyone's opinion so this is why an option for this would be really nice.

### Describe the solution you'd like

I would like if GestureRecognizers had an option like a parameter or a property that allowed to decide if the recogniser should be prioritised or not over the button press, since code was added to prevent buttons from preceding gestures I'd Imagine that code could depend on this property.

### Describe alternatives you've considered

- Alternative feature 1: have the ability to change the area, width and heigth, in which the gesture is effective, that would probably also need a way to tell from which corner/side of the screen this specified area starts.

- Alternative feature 2: have the ability to declare some sort of sensitivity threshold that says if your scroll or pull isn't at least x lenght then prioritise the button press.

- Alternative feature 3: have some sort of panel/grid that considers things like pull gesture area and places controls such as buttons in places where they don't interfere.

Notice: I have no Idea how some of these would get implemented or if they would even be possible.

### Additional context

[Previous "Fix" done regarding a similar yet different issue](https://github.com/AvaloniaUI/Avalonia/issues/11522)

**Comment by emmauss** [comment]
We have `Pointer.IsGestureRecognitionSkipped`. This prevents the pointer from triggering any gesture if the pointer has not yet been captured by a gesture recognizer. You can get the current pointer by handling/overriding the Pointer event of the control you want to ignore gestures on.
As for your suggestions;
1. We already have gesture thresholds for most gesture where until the gesture progresses beyond a certain point(where it is no longer a Tap, but a Drag), the gesture will bot block input to controls. Its up to the control author to define their own zones that detects gestures.
2. Because each gesture is unique(Scroll isn't Pull, and Pull isn't Pinch), we can't have a universal property to control how sensitive gestures are. We do have a property to control when a Scroll gesture starts, but not for Pull. Due to the possibility of multiple gesture being hosted on a control, and that when a gesture starts, it blocks all other gestures, having configurable thresholds on each will cause conflicts in which gesture should start at which point.
2. We already have gesture thresholds for most gesture where until the gesture progresses beyond a certain point(where it is no longer a Tap, but a Drag), the gesture will bot block input to controls.
3. If you need a specific control that uses pull gesture to trigger an event, like a Refresh, we have RefreshContainer
