### ISSUE TITLE
TextBox AcceptsReturn completely broken

### ISSUE THREAD

**Issue by drlagos** [AvaloniaUI/Avalonia#1674]
Avalonia Version 0.6.1, Windows 7

MainWindow.xaml:
```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="DxEditor">
    <TextBox AcceptsReturn="true">
        Hello World!
    </TextBox>
</Window>
```

Run the app, press enter on the textbox. 
Caret doesn't move to the line below, just adds what looks like 2 spaces.
(The actual text is modified correctly)

The next keypress does add a newline, but the caret is misaligned by 2 spaces and on the wrong line.
If you actually write text (like abc), it appears in the real position (so one line below the caret)
The caret is moved to the right position.

Push up to navigate to the first line, then move to the right, the caret will jump to the line below just before reaching the ! character (so you can't add something in from of the !). You can place the caret after the ! if you use the mouse.

I wish I could help fix this but I have no knowledge of low level GUI programming.

**Comment by jmacato** [comment]
can you try the nightly builds? it has improved that since then iirc

**Comment by drlagos** [comment]
Not at the moment unfortunately, have to focus on a separate project.
I will give it a try at later on, thank you.

**Comment by ivanatpr** [comment]
I also ran into this issue a few days ago while playing with NetCore/Skia on Windows. I confirmed it was still there where running against the current master and found a solution that seemed to work, which is to add an extra blank line whenever the last line ended with a newline character, and submitted a pull request for it.

There was also a separate issue where the line widths weren't being calculated correctly because the code was using an uninitialized (for the current line) value for line.Start. This seemed to solve a few additional minor oddities I noticed when playing around with the textbox control and now it behaves as expected.

**Comment by jmacato** [comment]
Confirmed repro of this bug and #1675 fixed it; Thanks @ivanatpr for your contribution :+1:  
Please recheck this @drlagos if theres any issues still

**Comment by drlagos** [comment]
Seems to work now, thank you!

**Comment by Filostrat** [comment]
@jmacato  
Good day. I faced the same problem, AcceptsReturn="True" doesn't work for me. I write like this, but it doesn't take me to the next line when I press enter
Avalonia version 11.2.3

<TextBox Grid.Column="1"
 Text="{Binding CheckHeader}"
 AcceptsReturn="True"
  AcceptsTab="True"
 TextWrapping="Wrap"
 Height="100"/>
