### ISSUE TITLE
11.2.0-beta1 - XAML compiler error when using binding in style setter

### ISSUE THREAD

**Issue by pavelovcharov** [AvaloniaUI/Avalonia#16754]
### Describe the bug

Using Avalonia v11.2.0-beta1 I get a compiler error ```AVLN1000 Avalonia: String '' was not recognized as a valid Boolean``` when using a binding as a style setter value.

This used to work in v11.1.3. 

### To Reproduce

Add style as shown below

```
        <Style Selector="Border.Test">
            <Setter Property="IsVisible">
                <Setter.Value>
                    <MultiBinding Converter="{x:Static BoolConverters.And}">
                        <Binding Path="Test"></Binding>
                        <Binding Path="Test1"></Binding>
                    </MultiBinding>
                </Setter.Value>
            </Setter>
        </Style>
```

### Expected behavior

No compiler error should be thrown, binding should work

### Avalonia version

11.2.0-beta1

**Comment by workgroupengineering** [comment]
This issue was introduced by PR #16153. 

Possible ways to solve it can be:

1. Trim textValue before invoke `XamlTransformHelpers.TryGetCorrectlyTypedValue` at [this](https://github.com/AvaloniaUI/Avalonia/blob/2d516027602698b1aa817f46edc62fd9d337c66a/src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlSetterTransformer.cs#L87) line
2. Replace Boolean.Parse with Boolean.TryParse at [this](https://github.com/kekekeks/XamlX/blob/7b8f6099a1c2240b9fa5bbf7a8a6954e99c4e556/src/XamlX/TypeSystem/TypeSystemHelpers.cs#L159) line of XamlX
3. Implement XamlAstTrivia and ingnore when xml:space is undefinited or default 


my favorite is option 3 but it's probably the longest
