### ISSUE TITLE
How to get Containers right after setting ItemsControl.Items

### ISSUE THREAD

**Issue by tedypranolo** [AvaloniaUI/Avalonia#1677]
When I set ItemsControl.Items= someList, it seems that ItemContainerGenerator generates the containers asynchronously. What is the best way to wait for complete materialization, so I can access the containers?
Right now I'm using Materialized event, and have to check ItemContainerGenerator.Containers.Count to make all item has been materialized. This seems less than ideal, is there a better way to do this?

**Comment by grokys** [comment]
Hi @tedypranolo,

It might be helpful to know your use-case for this - why are you needing to access the containers? There is no better way currently that doing what you say, partly because the items may be virtualized and so containers may _never_ be created for all items.

Again, knowing your use case might help us suggest a different approach or add an API for what you're trying to do.

**Comment by tedypranolo** [comment]
I was generating checkboxes based on a collection and trying to set their IsChecked. I guess I should have created a proper ViewModel and bind to the IsChecked property. Thank you for the clarification.
