### ISSUE TITLE
Properties set in a style cannot be overridden in control template

### ISSUE THREAD

**Issue by wsadcg** [AvaloniaUI/Avalonia#17270]
### Describe the bug

If I assign a style class to a control, I won't be able to override the properties defined in the style.

### To Reproduce

See below:
```
<StackPanel Orientation="Horizontal" Spacing="50" HorizontalAlignment="Center">
	<StackPanel.Styles>
		<Style Selector="Button.default">
			<Setter Property="Background" Value="Red"/>
		</Style>
	</StackPanel.Styles>
	
	<!--Left Button-->
	<Button Classes="default" Width="100" Height="100" Background="Blue"/>

	<!--Right Button-->
	<ContentControl>
		<ContentControl.Template>
			<ControlTemplate>
				<Button Classes="default" Width="100" Height="100" Background="Blue"/>
			</ControlTemplate>
		</ContentControl.Template>
	</ContentControl>
</StackPanel>
```
![ex1](https://github.com/user-attachments/assets/d26e0c7f-e5d2-44d0-b6d5-4bec1832dcc2)

These two buttons use the same style selector, but I cannot override the background color for the right button in control template.

### Avalonia version

11.1.4

### OS

Windows

**Comment by stevemonaco** [comment]
This is expected, even if it's unintuitive. Check DevTools and examine the priorities of each `Button.Background`.

The style is a conditional activator because of the `.default` class selector, so it has `StyleTrigger` priority.

The left `Button.Background` has a `LocalValue`. This is higher priority than `StyleTrigger`, so the style setter (Red) isn't the applied setter.

The right Button is inside of a `ControlTemplate`. This makes the `Background` setter have a priority of `Template`. This is a lower priority than `StyleTrigger`, so the style setter (Red) is the applied setter.

See https://docs.avaloniaui.net/docs/guides/styles-and-resources/setter-precedence

**Comment by wsadcg** [comment]
> This is expected, even if it's unintuitive. Check DevTools and examine the priorities of each `Button.Background`.
> 
> The style is a conditional activator because of the `.default` class selector, so it has `StyleTrigger` priority.
> 
> The left `Button.Background` has a `LocalValue`. This is higher priority than `StyleTrigger`, so the style setter (Red) isn't the applied setter.
> 
> The right Button is inside of a `ControlTemplate`. This makes the `Background` setter have a priority of `Template`. This is a lower priority than `StyleTrigger`, so the style setter (Red) is the applied setter.
> 
> See https://docs.avaloniaui.net/docs/guides/styles-and-resources/setter-precedence

Oh! Thank you very much.
