### ISSUE TITLE
Avalonia.Threading.Dispatcher.UIThread.Invoke + Parallel.Invoke work error

### ISSUE THREAD

**Issue by creidian** [AvaloniaUI/Avalonia#17278]
### Describe the bug

Using Parallel.Invoke to perform multiple control refreshes will cause the UI to get stuck, and the Avalonia.Threading.Dispatcher. UIThread.Invoke function is used during the refresh。

### To Reproduce

![image](https://github.com/user-attachments/assets/d822e050-bb63-4b9a-887b-2a50a52248a7)

![image](https://github.com/user-attachments/assets/310f7cc9-b4d7-4036-a563-f063765def33)

### Avalonia version

11.2.0-rc1

### OS

Windows

**Comment by kekekeks** [comment]
1) Parallel.Invoke spawns a thread
2) non-UI thread calls Dispatcher.Invoke and _waits_ for a UI thread to execute a callback
3) Parallel.Invoke waits for (2) to complete
4) UI thread is waiting for Parallel.Invoke to complete
5) nobody is running the event loop on the UI thread because you've blocked it by calling Parallel.Invoke, so the callback from (2) will never get executed

You've created a deadlock in your code, never do a synchronous wait on the UI thread

**Comment by kekekeks** [comment]
You can offload Parallel.Invoke on a non-UI thread by wrapping it into Task.Run or smth
