### ISSUE TITLE
Elmish pattern support

### ISSUE THREAD

**Issue by xperiandri** [AvaloniaUI/Avalonia#1803]
It would be nice to be able to develop Elm architecture apps with Avalonia like [Elmish.XamarinForms](https://github.com/fsprojects/Elmish.XamarinForms/)

**Comment by jmacato** [comment]
It's a great architecture to play with (upon my cursory look at least) but this is something that the community will provide for themselves. I also dont see any technical challenges for Avalonia with regards to Elm/Model-View-Update architecture so i guess someone can take a shot at this? :)

**Comment by Ma3yTa** [comment]
example of DSL https://github.com/Dolfik1/AvaloniaDSL/blob/master/DSL/Main.fs
please provide ``model-view-update`` example

**Comment by cmeeren** [comment]
That will likely be a bigger undertaking than I can commit to at the moment.

It would probably be fairly easy - perhaps even trivial - to port Elmish.WPF, since Avalonia is similar to WPF. Anyone is welcome to have a go. If there are sufficient similarities that the `Binding` and `ViewModel` code could be reused 100% (and likely that it would continue to be the case in further development), I could consider extracting that to its own library. In any case, just as a start and proof of concept, a fork of Elmish.WPF could be made and adjusted to Avalonia. Refactoring can come later.

However, I don't really like Elmish with static views because of its significant limitations compared to dynamic views. Dynamic views, on the other hand, require a lot more work to implement. There are important performance considerations in order to ensure the view creation and reconciliation/updating is as efficient as possible, 3rd party controls must be supported, and a code generator might be needed to make the dynamic view code maintanable (similar to [Fabulous](https://github.com/fsprojects/Fabulous)).

**Comment by Lleutch** [comment]
I completely agree with @cmeeren on each point raised.
Static views have their own limitations compared to dynamic ones. So I would go for implementing a dynamic DSL instead. 
In addition a simple PoC might be a good starting point to show others the benefit of it (no need to worry about diff algorithm on tree for the moment, and things like that...)
And same as @cmeeren, I won't be able to undertake such a task for the moment.
However, you can contact me anytime, and I might be able to help out.

**Comment by cmeeren** [comment]
Regarding a DSL for dynamic views - there are several directions to take:
* List-based like Fable.React and [Fabulous.SimpleElements](https://github.com/Zaid-Ajaj/fabulous-simple-elements)
* Constructor-/overload-/optional arg-based like [Fabulous](https://fsprojects.github.io/Fabulous/views.html)
* CE-based like [AvaloniaDSL](https://github.com/Dolfik1/AvaloniaDSL/blob/master/DSL/Main.fs)

Aside from the syntax difference, when you delve deep enough into it, I'm sure all come with their own pros and cons regarding technical limitations too.

---

> In addition a simple PoC might be a good starting point to show others the benefit of it (no need to worry about diff algorithm on tree for the moment, and things like that...)

I agree, a PoC might be a good starting point. I just want to note that sooner or later, performance will become a concern if it is ever supposed to be a viable way of creating real-life complex apps, so it might be prudent to have performance at the back of the mind even in the PoC stage, to ensure one doesn't end up with an implementation that is fundamentally inefficient.

---

> And same as @cmeeren, I won't be able to undertake such a task for the moment.
> However, you can contact me anytime, and I might be able to help out.

**Comment by Ma3yTa** [comment]
https://github.com/JaggerJo/Avalonia.FuncUI

**Comment by xperiandri** [comment]
@Ma3yTa looks amazing!

**Comment by kekekeks** [comment]
This doesn't belong to the core avalonia repo, feel free to implement your own wrapper
