### ISSUE TITLE
Setting ScrollViewer Offset stops ability of ScrollViewer to scroll.

### ISSUE THREAD

**Issue by thezaza101** [AvaloniaUI/Avalonia#1853]
Added code to make sure ScrollViewer always scrolled to the bottom when the content of its child TextBlock changed. Invoking the event handler seems to stop the user from being able to scroll the ScrollViewer via the UI. 

MainWindow.xaml.cs:

```
            var tbRaw = this.Get<TextBlock>("tbRawOutput");
            tbRaw.PropertyChanged += (s,e) => {
                var svRaw = this.Get<ScrollViewer>("svRawOutput");
                svRaw.Offset = new Vector(svRaw.Offset.X, svRaw.Extent.Height -svRaw.Viewport.Height);
            };
```

MainWindow.xaml:
```
<ScrollViewer Width="880" Name="svRawOutput" VerticalContentAlignment="Bottom">
	<TextBlock Classes="Code" Name="tbRawOutput" Text="{Binding RawOutput}" HorizontalAlignment="Left" VerticalAlignment="Bottom" />
</ScrollViewer>	
```

[code.](https://github.com/thezaza101/sc_ANN/tree/master/ui/Views)

**Comment by grokys** [comment]
This is because you're setting the offset of the `ScrollViewer` whenever _any_ property on the `TextBlock` changes. This causes the offset to be set when the `TextBlock` is repositioned by the `ScrollViewer` by setting `Bounds`, effectively undoing the scroll.

You need to fix the `PropertyChanged` handler to only listen for changes in the `TextBlock.Text` property.

Closing this as it appears not to be an Avalonia problem.
