### ISSUE TITLE
DeferredRenderer breaking changes

### ISSUE THREAD

**Issue by kekekeks** [AvaloniaUI/Avalonia#1920]
Scene rebuild logic in DeferredRenderer was changed in a breaking way.

Before it was working like that:
1) post update scene signal to the UI thread if needed
2) render the last known scene on timer thread

Now it works like this:
1) post update scene signal to the UI thread if needed
2) *wait* for the scene to update
3) continue on a *random* thread from the pool.

This might also screw the logic on windowing backends that expect rendering to happen on a certain thread in a certain time frame. Basically it makes it impossible to properly use `CVDisplayLink`/`CADisplayLink` on OSX/iOS.

I don't see the reason why it was changed and think that this change should be reverted.

I also consider this to block 0.7 release.

@grokys @jkoritzinsky @jmacato @nc4rrillo

**Comment by grokys** [comment]
For context, this is the relevant code:

https://github.com/AvaloniaUI/Avalonia/blob/4b05d49fd41e3bc03a80c1be0fa84a2bc7a2577a/src/Avalonia.Visuals/Rendering/RenderLoop.cs#L95-L101

The change was introduced in #1715. That PR also seems to have caused the scene to get cloned on every frame (rather than just when it is dirty):

https://github.com/AvaloniaUI/Avalonia/blob/4b05d49fd41e3bc03a80c1be0fa84a2bc7a2577a/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs#L398

Previously `UpdateScene` was only called if there was something to update:

https://github.com/AvaloniaUI/Avalonia/pull/1715/files#diff-1e124f5c02282534aff2b846c3f3b2baL429
