### ISSUE TITLE
Binding to UserControl.IsVisible and setting DataContext breaks binding

### ISSUE THREAD

**Issue by jp2masa** [AvaloniaUI/Avalonia#2071]
When binding `IsVisible` (didn't check other properties) of an `UserControl` (didn't check other controls) and setting the `DataContext`, the `IsVisible` binding won't work. Not setting the `DataContext` works fine.

## Example

View:

```xaml
<StackPanel>
  <ToggleButton IsChecked="{Binding ShowUC}" />
  <UserControl DataContext="{Binding MyDataContext}" IsVisible="{Binding ShowUC}">
    Hello World!
  </UserControl>
</StackPanel>
```

View Model:

```cs
private bool _showUC;

public bool ShowUC
{
    get => _showUC;
    set => this.RaiseAndSetIfChanged(ref _showUC, value);
}

public object MyDataContext { get; } = new object();
```

Is this a bug or am I missing something?

Any help would be appreciated.

**Comment by ahopper** [comment]
The DataContext is used for all the other bindings on the control so it does not work because ShowUC is not a property of MyDataContext. $parent.DataContext.ShowUC should work

**Comment by jp2masa** [comment]
That works, but I feel that the behavior is not really intuitive... I would expect all bindings, except the ones in templates, to use the root element `DataContext` as the default one, but WPF has the same behavior, so I'm probably missing the point.

**Comment by LazaroOnline** [comment]
I was having this issue when I found the solution stated above which worked fine.

However, here and in the Avalonia-UI documentation, I find a lack of context in the examples/solutions.
I see lines of code that doesn't fully explain where they belong and I end up having to try different slightly different variations because every dot and comma does matter.

So I will add here the full working example for this issue as a reference for others.

Fixed Example:
MyView.axaml:
```xaml
<Window ...
  xmlns:views="clr-namespace:MyProject.Views;assembly=MyProject" />

...
<StackPanel>
  <ToggleButton IsChecked="{Binding ShowUC}" />
  <views:UserControl DataContext="{Binding MyDataContext}" IsVisible="{Binding $parent.DataContext.ShowUC}">
    Hello World!
  </views:UserControl>
</StackPanel>
```
MyViewModel.cs:
```c#
private bool _showUC;

public bool ShowUC
{
    get => _showUC;
    set => this.RaiseAndSetIfChanged(ref _showUC, value);
}

public object MyDataContext { get; } = new object();
```
