### ISSUE TITLE
ListBox virtualization scroll to end with differing item height sometimes fails

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#2144]
There is a repro here https://github.com/ahopper/Avalonia/tree/repro-VirtualizedStackPanel-fails-with-differing-item-heights which has a modified virtualization demo. Scrolling to the end using the mouse wheel stops on item197. Using the down arrow causes item198 to be selected but not displayed.
Possibly relates to #1402

**Comment by grokys** [comment]
I've been looking into this for quite a while and going back and forth on the best way forward. The problem is essentially this:

- A container is recycled for an item that is larger than the previously displayed item
- Because the size has changed a layout pass is queued
- When the layout pass executes, the selected item is bumped out of the view

I think the best immediate course of action would be to simply remove recycling from the virtualization implementation. Longer-term I think item virtualization will need to be rewritten: it has fundamental flaws when it comes to differently-sized items.

However I notice that UWP's controls are being open-sourced over at https://github.com/microsoft/microsoft-ui-xaml. Maybe we could take their implementations and port them to C#?

In particular [`ItemsRepeater`](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.itemsrepeater?view=winui-2.2) has already been [open-sourced](https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/Repeater/ItemsRepeater.h) and I like this approach a _lot_ more than the WPF `ItemsControl`/`ListBox` etc controls that we're currently using.
