### ISSUE TITLE
MonoGame Support

### ISSUE THREAD

**Issue by Mike-E-angelo** [AvaloniaUI/Avalonia#216]
This has been discussed in the awesome [Gitter Chat](https://gitter.im/Perspex/Perspex) but it appears this has not been captured as an issue.  It would be highly valuable to enable Perspex support within a MonoGame scene.  MonoGame has 3D rendering capabilities and while it has much support to render UI, the actual UI framework support is non-existent.  There are a few frameworks out there, namely [EmptyKeys](emptykeys.com), but it is a closed-source (obfuscated, even) and others are paid.

It would be awesome and highly valuable to leverage Perspex and introduce it into MonoGame's rendering pipeline.

**Comment by Cyral** [comment]
:+1:  This would be great

**Comment by Michael-DST** [comment]
Oh and while we're at it, having integration/support with/for this would be awesome, too:
http://blog.xamarin.com/3d-game-engine-for-android-ios-and-net/

:angel: :angel: :angel:

**Comment by ilexp** [comment]
Rather than picking a select few game engines to embed Perspex into, maybe it would be preferable to provide a generic interface that allows to plug Perspex into anything that provides user input and accepts a set of vertices and some shading instructions along with it.

This way, it could be embedded into any graphics framework, game engine or library and wouldn't be tied to something as specific as MonoGame.

**Comment by MikeCodesDotNET** [comment]
This is unlikely to happen in the short-term from anyone on the core team. PRs are welcome though!
