### ISSUE TITLE
State of offscreen rendering

### ISSUE THREAD

**Issue by eladmaimoni** [AvaloniaUI/Avalonia#2174]
By offscreen rendering I mean:

- The ability to render a Xaml tree to an external target (such as a direct3d texture)
- The ability to configure Avalonia to run its loop without a windowing system.
- The ability to configure Avalonia to use client provided rendering resources such as the rendering device & context instead of creating its own.

After playing a bit with the framework, It seems as if there is some kind of preparation for this. namely the
Avalonia.Controls.Embedding.Offscreen namespace (yet its classes are private / abstract).

Is there a structural way to achieve this? can some one guide me as to how this could be added / achieved? 
-

**Comment by Gillibald** [comment]
Our current interop sample isn't working. When I have time I will have a look at it. In general it should be possible to bring your own implementation of the the needed interfaces just have a look at the current D2D implementation. I can't give you more info about how to fulfill all your requirements. Maybe someone else can help you more. 
https://github.com/AvaloniaUI/Avalonia/tree/master/samples/interop/Direct3DInteropSample

**Comment by drywolf** [comment]
@elad8a Did you find a working solution for this ?
I am currently trying to do something very much like you described.
I have a native (C++) OpenGL application which also [hosts a .NET core runtime](https://docs.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting) which then runs an Avalonia UI app that should be rendered to the original C++ OpenGL context.

**Comment by elad8a** [comment]
@drywolf in my case I use d3d11. As far as I remember I managed to get it to work by tweaking the avalonia source code. It was far from perfect and I ended up abandoning avolonia in favour of NoesisGUI (which is pretty much built for these scenarios)

**Comment by drywolf** [comment]
I see,
thanks

**Comment by mightypanda** [comment]
Hello,
Are there any updates on this topic?
Also rendering to a memory image would be a useful scenario when realtime speed is not so much needed.

**Comment by kekekeks** [comment]
There is a headless platform now. You can also implement your own ITopLevelImpl

**Comment by Samuel-B-D** [comment]
@kekekeks You say
> You can also implement your own ITopLevelImpl

however, `ITopLevelImpl` is marked with `[Unstable]`, and trying to implement it result in an `This interface or abstract class is -not- implementable by user code !` error...

I'm not quite sure how the headless platform can help offscreen rendering within an Avalonia Application running on an actual platform?

I'm currently working around this by using a window positioned outside screen boundaries, but this is a pretty big unnecessary overhead when simply needing to layout and/or render components offscreen...

**Comment by kekekeks** [comment]
>TopLevelImpl is marked with [Unstable], and trying to implement it result in an This interface or abstract class is -not- implementable by user code ! error...

Yes, you need to enable private API usage via `<AvaloniaAccessUnstablePrivateApis>true</AvaloniaAccessUnstablePrivateApis>`

**Comment by Samuel-B-D** [comment]
> > TopLevelImpl is marked with [Unstable], and trying to implement it result in an This interface or abstract class is -not- implementable by user code ! error...
> 
> Yes, you need to enable private API usage via `<AvaloniaAccessUnstablePrivateApis>true</AvaloniaAccessUnstablePrivateApis>`

That's good to know, thanks!

**Comment by Samuel-B-D** [comment]
Any plans to either stabilize this, or make the already existing but private `OffscreenTopLevelImpl` top-level public?

I unsuccessfully tried to use the Headless Platform; it was intermitently working, but even calls wrapped in `session.Dispatch` sometime threw "call from the wrong thread" exceptions, probably due to both an actual platform (X11 in my case) and the headless platform co-existing and Avalonia relying on some amount of global state?

In the end I have a working implementation of what I'm trying to do using an empty implementation of `TopLevel` using an empty implementation of `ITopLevelImpl`, but I wonder how much that will break in Avalonia 12...

**Comment by maxkatz6** [comment]
@Samuel-B-D you can't mix headless platform and real windowing system. Purpose of headless is to provide lightweight fake windowing, for scenarios where it might be needed (testing, or special scenarios like VNC). There are no plans to change that soon.
We had an idea to implement `HeadlessWindow` class to simplify usage with headless tests though.


You still should be able to render any visual/window offscreen even with 11.0 versions.
 
```csharp
// Init:
// EmbeddableControlRoot  can be technically replaced with Window class, without calling Show on it.
using var embeddableRoot = new EmbeddableControlRoot { Width = 200, Height = 200 };
embeddableRoot.Content = new Calendar();
embeddableRoot.Prepare();

// Option 1: use sync RenderTargetBitmap, no GPU API access, but easiest and fastest option. Also existed in Avalonia for a long time.
var renderTargetBitmap = new RenderTargetBitmap(PixelSize.FromSize(embeddableRoot.Bounds.Size, scale: 1));
renderTargetBitmap.Render(embeddableRoot);
renderTargetBitmap.Save("E:/rtb.png");

// Option 2: use async compositor APIs, which are fully integrated with GPU APIs, like OpenGL. Enabling you to render OpenGLControl or equivalent this way.
embeddableRoot.StartRendering(); // need to start compositor rendering first
var compositionVisual = ElementComposition.GetElementVisual(embeddableRoot)!;
var snapshot =
    await compositionVisual.Compositor.CreateCompositionVisualSnapshot(compositionVisual, scaling: 1);
snapshot.Save("E:/comp.png");
```

**Comment by Samuel-B-D** [comment]
@maxkatz6 `new EmbeddableControlRoot` throw on Linux, there is no provided Impl for it.
`XEmbedPlug` is able to create one and I can access it afterward with either reflection or with TopLevel.GetTopLevel after assigning it a content, but even if we don't embed it in anything, it is still a quite heavyweight control for such an usecase :/

**Comment by lindexi** [comment]
My solution follows the approach described by @kekekeks: implement a custom `ITopLevelImpl` interface, which turned out to be less complicated than I expected.

Implementation Steps:

1. As suggested by @kekekeks, first add the `<AvaloniaAccessUnstablePrivateApis>true</AvaloniaAccessUnstablePrivateApis>` property to your `.csproj` project file to resolve build issues. See https://github.com/AvaloniaUI/Avalonia/issues/2174#issuecomment-3025009870

3. Create an `OffscreenTopLevelImpl` class that inherits from `Avalonia.Controls.Embedding.Offscreen.OffscreenTopLevelImplBase`:

```csharp
class OffscreenTopLevelImpl : OffscreenTopLevelImplBase, ITopLevelImpl
{
    public override IEnumerable<object> Surfaces { get; } = [];
    public override IMouseDevice MouseDevice { get; } = new MouseDevice();
}
```

3. Pass the custom `OffscreenTopLevelImpl` instance to the constructor of `EmbeddableControlRoot`. **Important note**: Be sure to set a valid `ClientSize` for the `OffscreenTopLevelImpl` instance, otherwise you will get a blank rendered output.

The rest of the workflow follows the guide shared by @maxkatz6, sample code is provided below (https://github.com/AvaloniaUI/Avalonia/issues/2174#issuecomment-3030306384 ) :

```csharp
var imageFilePath = Path.Join(Path.GetTempPath(), $"{Path.GetRandomFileName()}.png");

await Dispatcher.UIThread.InvokeAsync(async () =>
{
    var taskCompletionSource = new TaskCompletionSource();

    // https://github.com/AvaloniaUI/Avalonia/issues/2174#issuecomment-3030306384
    var offscreenTopLevelImpl = new OffscreenTopLevelImpl()
    {
        ClientSize = new Size(1000, 600)
    };
    var embeddableControlRoot = new EmbeddableControlRoot(offscreenTopLevelImpl);
    embeddableControlRoot.Width = 1000;
    embeddableControlRoot.Height = 600;
    var mainView = new MainView();
    mainView.Loaded += (sender, args) =>
    {
        using var renderTargetBitmap = new RenderTargetBitmap(new PixelSize(1000, 600));
        renderTargetBitmap.Render(mainView);
        renderTargetBitmap.Save(imageFilePath);
        taskCompletionSource.SetResult();
    };
    embeddableControlRoot.Content = mainView;

    // Prepare for offscreen rendering
    embeddableControlRoot.Prepare(); // Calling this method fires the Loaded event
    embeddableControlRoot.StartRendering();

    await taskCompletionSource.Task;

    embeddableControlRoot.StopRendering();
    embeddableControlRoot.Dispose();
});

return imageFilePath;
```

You can find the full source code of my project at https://github.com/lindexi/lindexi_gd/tree/e70a7aaaccbe74fd5301433b1122d52d54dd2024/Workbench/KuhallyediNujewinem
