### ISSUE TITLE
 CompositeCollection Analogue

### ISSUE THREAD

**Issue by luxaritas** [AvaloniaUI/Avalonia#2225]
Could an analogue to [`System.Windows.Data.CompositeCollection`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.data.compositecollection?view=netframework-4.7.2) be implemented into Avalonia? From the little bit of digging I did, it doesn't appear to be in `Avalonia.Data`, `Avalonia.Data.Core`, or `Avalonia.Collections`

**Comment by Gillibald** [comment]
This should be open source soon. Then you should be able to use it in your projects.

**Comment by grokys** [comment]
I've never actually used `CompositeCollection` so I'm not sure how well it works, but my advice would be to use [`DynamicData`](https://github.com/RolandPheasant/DynamicData) for things like this.

ReactiveUI used to have their own collections but they decided to deprecate them and point people to DynamicData because the cost of maintaining them was too high and wasn't their core competence. I'd probably feel the same about Avalonia tbh.

**Comment by ashelleyPurdue** [comment]
Hi!  Why was this proposal rejected?  What is the recommended alternative for people who need to bind to a combination of two lists?

**Comment by timunie** [comment]
See comments right above your post, use DynamicData or any other suitable library https://github.com/AvaloniaUI/Avalonia/issues/2225#issuecomment-452709141
