### ISSUE TITLE
Binding to $parent in listbox item generates binding errors initially

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#2258]
To repro

modify MainWindow in VirtualizationDemo so the data template is
```
 <ListBox.ItemTemplate>
                <DataTemplate>
              <!--      <TextBlock Text="{Binding Header}" TextWrapping="Wrap"/>-->
                    <TextBlock Text="{Binding $parent[ListBox].Bounds.Width}" TextWrapping="Wrap"/>
                </DataTemplate>
            </ListBox.ItemTemplate>
```
This will create 
```
Binding: Error in binding to "Avalonia.Controls.TextBlock"."Text": "Null value in expression '$parent[ListBox, 0]'."
```
in the vs output window.  The error is shown 86 times which is odd in itself as only 30 item are shown.  The app shows the correct result of the binding so it eventually works.

maybe related to #1099

**Comment by aguahombre** [comment]
I have a related problem when using styling to change the ListBoxItem ContentTemplate for the SelectedItem in a ListBox. The example below changes the selected item in the ListBox to a ComboBox from a TextBlock so that the value change be modified.

`<Style Selector="ListBox#SortCriteria ListBoxItem:selected /template/ ContentPresenter">
  <Setter Property="ContentTemplate">
	<DataTemplate DataType="local:SortCriteriaModel">
		<ComboBox Items="{Binding $parent[ListBox].DataContext.SortProperties}" SelectedItem="{Binding Property, Mode=TwoWay}"/>
	</DataTemplate>
  </Setter>
</Style>	
	
<DataTemplate DataType="local:SortProperty">
  <TextBlock Text="{Binding}"/>
</DataTemplate>

<ListBox Name="SortCriteria" Items="{Binding SortCriteria}" />

public enum SortProperty { None, A, B, C };

public class SortCriteriaModel : ReactiveObject
{
	private SortProperty _property;
	public SortProperty Property { get => _property; set => this.RaiseAndSetIfChanged(ref _property, value); }
}
`

This example does not work as the $parent binding above causes errors

> Null value in expression '$parent[ListBox, 0]'

and the selected ListBox row displays a ComboBox with no selection.
Other unselected ListBox rows show the text block with the correct selection.
If I select another row, the de-selected row always changes to None.

I suspect this is because the ComboBox is detached from the visual tree when the template changes and this causes the Items property to become null and in turn causes the SelectedItem to change to the default(SortProperty) value; i.e. None.

My question is should a $parent binding work from a DataTemplate?

I also tried changing the Binding to #SortCriteria.DataContext.SortProperties but with same result.
 
I can make things work by adding the SortProperties to the SortCriteriaModel, but this doesn't seem the correct place to put it; see below:

`<Style Selector="ListBox#SortCriteria ListBoxItem:selected /template/ ContentPresenter">
  <Setter Property="ContentTemplate">
	<DataTemplate DataType="local:SortCriteriaModel">
		<ComboBox Items="{Binding SortProperties}" SelectedItem="{Binding Property, Mode=TwoWay}"/>
	</DataTemplate>
  </Setter>
</Style>	
	
<DataTemplate DataType="local:SortProperty">
  <TextBlock Text="{Binding}"/>
</DataTemplate>

<ListBox Name="SortCriteria" Items="{Binding SortCriteria}" />

public class SortCriteriaModel : ReactiveObject
{
	private SortProperty _property;
	public SortProperty Property { get => _property; set => this.RaiseAndSetIfChanged(ref _property, value); }
	
	public static IList<SortProperty> SortProperties { get; } = Enum.GetValues(typeof(SortProperty)).Cast<SortProperty>().ToList();
}
`

**Comment by aguahombre** [comment]
For some reason the formatting of the code is messed up so here pngs instead 

![image](https://user-images.githubusercontent.com/17591364/58323138-fff4e600-7e1a-11e9-9395-94d413c0d0dc.png)

And the second one

![image](https://user-images.githubusercontent.com/17591364/58323092-dcca3680-7e1a-11e9-85fa-99b23696c632.png)

**Comment by Sorien** [comment]
@aguahombre https://help.github.com/en/articles/creating-and-highlighting-code-blocks

**Comment by waliarubal** [comment]
When will this issue be fixed as I am too facing it. `{Binding $parent[UserControl].DataContext.InvokeObjectCommand}` is failing for me i.e. giving the issue in console.

**Comment by ahopper** [comment]
I also still see this. Just to be clear it does not stop anything working for me. It nags at me through years of rigorously eliminating binding errors in wpf by watching for these errors:)

**Comment by ahopper** [comment]
The repro at the top no longer does this and I've not seen the error in my code for a while
