### ISSUE TITLE
ToolTip with large image gets shown offscreen

### ISSUE THREAD

**Issue by ReIaxo** [AvaloniaUI/Avalonia#2311]
```       
<Button ToolTip.Tip="Some text">Button mit ToolTip</Button>
            <Button>
              Button with Image ToolTip
              <ToolTip.Tip>
                  <DockPanel>
                    <Image Source="Page01.jpg"/>
                    <TextBlock>Further informations ...</TextBlock>
                  </DockPanel>
              </ToolTip.Tip>
            </Button>
```

The ToolTip of the first button works as expected. The second one only works in the Designer in VisualStudio.

**Comment by grokys** [comment]
I just tried this on current master and it appears to work. Is this still a problem for you if you update to the latest Avalonia CI package (at this time `0.7.1-cibuild0001534-beta`)?

**Comment by ReIaxo** [comment]
Yes, the Problem is still present. Here is a simple repro.

[AvaloniaApplication1.zip](https://github.com/AvaloniaUI/Avalonia/files/2920272/AvaloniaApplication1.zip)

**Comment by grokys** [comment]
Ok, that repro works for me, with a caveat. The image is _huge_, and it looks like the code that tries to align the popup on the screen is having trouble, so it's placing the popup on my second monitor (to the left).

Could you try adding a width/height to the image e.g. `<Image Source="resm:AvaloniaApplication1.Assets.Page01.jpg" Width="100" Height="100"/>`  and confirm it now displays the image?

If so, this issue is about popup positioning; i'll look into that.

**Comment by ReIaxo** [comment]
Yes, that works. I already thought, that it is something about the size of the image. I should have written ithere, but I only wrote it in the chat, Sorry for that.

**Comment by ahopper** [comment]
There appears to be a general issue with popups that have larger content than fits on the screen not showing. I had someone report this when a previous x11 backend scaled everything too big and popups failed to show.

**Comment by grokys** [comment]
Ok, I've updated the title. cc:ing @danwalmsley as I believe you wrote the popup positioning code?

**Comment by grokys** [comment]
Ah actually, this should be the same issue as #2277, so closing this and will track the problem there,
