### ISSUE TITLE
Look into removing MemberSelector

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#2333]
`MemberSelector` was mainly added in order to support `TabControl` and since this was rewritten, `MemberSelector` should not strictly be needed. In addition, it has problems (#483) in some cases because it was written for a single specific use-case.

WPF and UWP have `DisplayMemberPath` which has subtly different semantics. We should look into replacing `MemberSelector` with `DisplayMemberPath` in order to gain greater compatibility.

**Comment by kekekeks** [comment]
A point to consider: in WPF/UWP it's some kind of a "magic string" which leads to runtime-only resolve via reflection. Since I'd like to have everything compiled at some point, I don't think we need to adopt the same API (we could still have the magic string in XAML, but the property type should be `Binding` or something like that.)
