### ISSUE TITLE
Black area inside window with Height<38 or Width<46 when HasSystemDecorations="False"

### ISSUE THREAD

**Issue by OronDF343** [AvaloniaUI/Avalonia#2401]
Similar to #2166 - possibly an edge case of the same issue

Repro updated [here](https://bitbucket.org/orondf343/avaloniatesting).

Screenshots on Windows 7:
This window has a Height of 34. The window should have a white border all around it, with a colored background.
Shown against white background:
![](https://i.pixxxels.cc/1XwjBvrB/t2.png)
Shown against black background:
![](https://i.pixxxels.cc/ZR1Q6Gp0/t1.png)
Changing the height to 38 or higher fixes the issue.

**Comment by grokys** [comment]
This seems to be caused by Windows having a minimum window size, returned by calling [`GetSystemMetrics`](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-getsystemmetrics) with `SM_CYMAXTRACK` . On my machine, that size is 56 pixels (I have a 150% scaling monitor). Windows disallows a window height smaller than that, resulting in a black margin.

I'm not sure if there's a way to override this for individual windows, need to investigate further.

**Comment by FG-rgb** [comment]
Same Problem here. I want to draw on the screen, therefore I need a window with Height = 3 and SystemDecorations=None. The window is now to large. Are there news when this get fixed?

**Comment by bars43ru** [comment]
Faced with the same problem. Implemented my WindowImpl based on Avalonia. Win32. WindowImpl with redefinition of values in MINMAXINFO when processing WM_GETMINMAXINFO. This didn't solve my problem, I have a minimum window size of 46x39 with no system decorations. Do you have any ideas how I can create a window with the size of 1x1 without system decorations?

**Comment by bars43ru** [comment]
Maybe someone will need it. I solved the problem as part of my task by setting the window style WS_OVERLAPPED & ~WS_CAPTION, by calling SetWindowLongPtr

**Comment by danwalmsley** [comment]
@bars43ru you can create a popup (which is a window).. of any size.
