### ISSUE TITLE
Implement an API to check if CapsLock is on

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#2422]

**Comment by yahiheb** [comment]
Bumping.

**Comment by maxkatz6** [comment]
KeyEventArgs has KeyModifiers property - https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Input/KeyEventArgs.cs#L12
Some other events like PointerPressed also have KeyModifiers for convinince.

Global "keyboard state" is not planned. If developers need one, they can listen for KeyDown and KeyUp events and track state.

**Comment by LazaroOnline** [comment]
@maxkatz6 
Tracking KeyDown/KeyUp to know the state of CapsLock is unfeasable because the user can change it while the focus is in another window, and it won't tell you if it was already locked when the app started...

For example to show a warning text next to a password input to let the user know CapsLock is active, before he even presses anything.

**Comment by maxkatz6** [comment]
@LazaroOnline if you need a Windows only solution - you can call Win32 API by PInvokes. As far as I know, there is no public API for equivalent macOS option. Modern Linux (Wayland) also enforces app isolation, without access to the system state, not allowing such APIs (i.e. keylogging is not allowed on wayland by design like polling global keyboard state).
It would be unfeasible to implement an API that only works on single platform.
