### ISSUE TITLE
TextBox Watermark not showing

### ISSUE THREAD

**Issue by AzyIsCool** [AvaloniaUI/Avalonia#2474]
![image](https://user-images.githubusercontent.com/21204235/56815784-0bfc8080-683a-11e9-8a2b-5d8eeec0021d.png)

```xaml
                <TextBlock FontSize="14" VerticalAlignment="Center" x:Name="labPower" Text="Power:" Grid.Row="2"
                           Margin="0,0,5,0" />
                <TextBox FontSize="10" Grid.Row="2" Grid.Column="1" Watermark="0 - 255"
                         x:Name="txtPower" Width="100" FontWeight="Bold" />

```

happens on Windows and Linux

repo with code: https://github.com/AzyIsCool/HATE

**Comment by Wyvernius** [comment]
Have you tried setting Foreground to black?

**Comment by AzyIsCool** [comment]
Not until now but still no luck.

**Comment by grokys** [comment]
This is happening because you're setting `TextBlock.Foreground` to `White` in this style:

https://github.com/AzyIsCool/HATE/blob/fef8d482c5ea2f32b35eeeac8d42a11f47cdb5ca/HATE/MainWindow.xaml#L13

This isn't a good idea. `TextBlock` is a primitive by which _all_ text in an Avalonia application is drawn, including `TextBox`'s watermark.

If you want to set the foreground for the window to white, just set `Foreground="White"` on the `Window`, e.g.:

```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Foreground="White">
```

**Comment by AzyIsCool** [comment]
Ah thanks, forgot that Foreground was in Window and I was so used to doing it that way from WPF
