### ISSUE TITLE
Setting x:Name/Name in UserControl causes rendering issues

### ISSUE THREAD

**Issue by vflame** [AvaloniaUI/Avalonia#2512]
Whenever the viewmodel is changed (e.g., for navigation), the associated view does not render properly after the first initialization if the x:Name or Name property is assigned to the UserControl root element

See attached for demo of bug. Clicking back and forth between the two buttons should toggle "View1" and "View2". Instead, fails to render after the first time when the x:Name/Name property is set on the UserControl root element.

[AvaloniaApplication2.zip](https://github.com/AvaloniaUI/Avalonia/files/3169847/AvaloniaApplication2.zip)

**Comment by kekekeks** [comment]
I think that happens because B2View registers itself in parent's name scope.

@grokys

**Comment by grokys** [comment]
Yeah that is because of our parent name scope registration, as described here: https://github.com/AvaloniaUI/Avalonia/blob/b4577a1631755b391f3768e00264ac86c4300507/src/Avalonia.Styling/StyledElement.cs#L685-L693

> If we have e.g. a named UserControl in a window then we want that control
> to be findable by name from the Window, so register with both name scopes.
> This differs from WPF's behavior in that XAML manually registers controls 
> with name scopes based on the XAML file in which the name attribute appears,
> but we're trying to avoid XAML magic in Avalonia in order to made code-
> created UIs easy. This will cause problems if a UserControl declares a name
> in its XAML and that control is included multiple times in a parent control
> (as the name will be duplicated), however at the moment I'm fine with saying
> "don't do that".

I think we need to reconsider how controls are registered with namescopes (see also: https://github.com/AvaloniaUI/Avalonia/issues/1572).

First solution that comes to mind is that controls created by the XAML engine don't automatically register themselves with name scopes, the XAML engine would have to handle that. Controls created in code would automatically register themselves with a single parent name scope.

We could detect a XAML (or other markup) engine by recording whether `BeginInit`/`EndInit` have been called.

**Comment by kekekeks** [comment]
Compiler generates its own name scope registration code.
