### ISSUE TITLE
Marshal controls between processes

### ISSUE THREAD

**Issue by yakiro-nvg** [AvaloniaUI/Avalonia#2556]
I want to render plugin from a separated process,

Likes [Baktun](https://www.codeproject.com/Articles/516431/Baktun-Shell-Hosting-WPF-Child-Windows-in-Another) shell.

From what I know, it seems not trivial since we need to use OS compositor, which is just far from portable. OSX provides IOSurface from 10.6. While on Windows we could use Hwnd. Not sure about Linux though.

Is it available with Avalonia, is there any suggestion or obstacle?

**Comment by kekekeks** [comment]
We are currently using a TCP connection for our XAML previewer. See RemoteWidget and RemoteServer classes.

**Comment by yakiro-nvg** [comment]
RemoteWidget using bitmap streaming so it sounds not very performant.

**Comment by kekekeks** [comment]
It is, but that's the most portable solution. There were plans to use shared memory (CPU memory) for transferring bitmap data, but it wasn't implemented due to manpower limitations.

You can implement your own [ITransport](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Remote.Protocol/ITransport.cs) if you with to utilize more performant way of data transfer. 

PRs are also always welcome.

**Comment by yakiro-nvg** [comment]
Yes, it's the most portable solution.

However, I'm developing on OSX which uses GPU acceleration so reading back to CPU wasn't an option for me, that seems too much overhead. I also have tried AvalonStudio window resizing and I must say that I loved it. GPU performance is simply outstanding.

I still thinking about hardware composition on GPU in this case, which requires more than [ITransport](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Remote.Protocol/ITransport.cs) currently provides. We need to render the RemoteServer to an IOSurface, sharing its handle over TCP and bind it as a texture on the RemoteWidget.
