### ISSUE TITLE
AutoScrollToSelectedItem on ListBox not working

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#2569]
Setting AutoScrollToSelectedItem="True" on a ListBox has no affect when SelectedIndex is changed through binding.

**Comment by lenonk** [comment]
I'm having a similar issue, but it only seems to happen when I have a ListBox bound to to a collection of ObservableCollection<string>, and I add strings with identical content.  

```xaml
            <ListBox AutoScrollToSelectedItem="True"
                   Grid.Row="1"
                   ScrollViewer.HorizontalScrollBarVisibility="Disabled"
                   SelectedIndex="{Binding SIndex}"
                   Items="{Binding LogItems}">
                <ListBox.ItemTemplate>
                    <DataTemplate>
                        <TextBlock Text="{Binding .}" TextWrapping="Wrap" />
                    </DataTemplate>
                </ListBox.ItemTemplate>
            </ListBox>
```
```c#
        public void Log(string s) {
            var lines = s.Split('\n');
            foreach (var line in lines) {
                if (!string.IsNullOrWhiteSpace(line)) {
                    LogItems.Add($"{DateTime.Now.ToString("HH:mm tt")}: {line}");
                    SIndex = LogItems.Count - 1;
                }
            }
        }
```

**Comment by lenonk** [comment]
Here's a video of the behavior.  I add several identical lines, and nothing happens, but as soon as the time changes, it scrolls to the line with the new time stamp, then stops scrolling again.
[Myrina 2019-12-01 15-11-47.zip](https://github.com/AvaloniaUI/Avalonia/files/3908719/Myrina.2019-12-01.15-11-47.zip)

**Comment by lenonk** [comment]
I dug around some, and I found the following:

In SelectingItemsControl.cs:1059
```c#
 if (AutoScrollToSelectedItem && _selectedIndex != -1)
 {
     ScrollIntoView(_selectedItem);
 }
```

Which eventually calls either ItemVirtualizerSimple:ScrollIntoView, or ItemVirtualizerNone:ScrollIntoView, I'm not sure which, but doesn't really matter:
```c#       
public override void ScrollIntoView(object item)
{
    if (Items != null)
    {
        var index = Items.IndexOf(item);

        if (index != -1)
        {
            ScrollIntoView(index);
        }
    }
}
```
If you passed in _selectedIndex instead of _selectedItem, and modified ScrollIntoView() like this:
```c#      
public override void ScrollIntoView(object item)
{
    if (Items != null)
    {
        var index = Items.IndexOf(item);
        if (item.GetType() == typeof(int))
        {
            index = (int)item;
        }
        
        if (index != -1)
        {
            ScrollIntoView(index);
        }
    }
}
```

I think the bug would be fixed, but that may also be naive.  I don't have anywhere near the experience you guys have.

**Comment by lenonk** [comment]
I just realized the issue that my solution would cause if you had, say, a ListBox of integers.  There probably needs to be a separate utility function for scrolling to a specified index.

**Comment by Kermalis** [comment]
Wouldn't
```cs
 if (AutoScrollToSelectedItem && _selectedIndex != -1)
 {
     ScrollIntoView(_selectedItem);
 }
```

Just become
```cs
 if (AutoScrollToSelectedItem && _selectedIndex != -1)
 {
     ScrollIntoView(_selectedIndex); // Index here
 }
```

?

**Comment by lenonk** [comment]
Yes, that's what I was implying, but then you have to support passing an index into `ScrollIntoView()`, because `Items.IndexOf(4)` is not going to return the 4th element.  It's going to return an element with a value that matches 4.  Furthermore, what if your backing list is of type int?

Imagine a list with elements:
3
4
3
4

And you pass in `_selectedIndex == 4`.  With the code I suggested, the passed value will always be treated as an index, and not a value that should be searched for via `IndexOf()`, which would be even more broken than it is today.  Not to mention any other controls that also call `ItemVirtualizerSimple::ScrollIntoView()`.

That's why I said I think this requires a separate utility function that expects an index and nothing else.  There's no way that I know of, other than adding another parameter to scroll into view, to separate an index from an integer value.

**Comment by Kermalis** [comment]
`ScrollIntoView(object item)` calls `ScrollIntoView(int index)`, so I'm saying SelectingItemsControl should just call the index version instead of the object version

**Comment by lenonk** [comment]
For some reason I was under the impression that it couldn't.  I could be wrong about that.  If so, great, that's an easy fix.

**Comment by Kermalis** [comment]
I just looked and SelectingItemsControl actually doesn't have a definition for the int index version, which is why it's using the object version and introducing this bug. It should also have an index version (I don't see why it shouldn't)

**Comment by lenonk** [comment]
I don't either, and that's much better than my solution.  I also don't see a reason why it couldn't call ItemVirtualizerSimple::ScrollIntoView(int)

**Comment by lenonk** [comment]
Is there going to be a problem with ambiguity between the two versions?

**Comment by Kermalis** [comment]
If `ScrollIntoView(int index)` exists and you are trying to call `ScrollIntoView(object item)` with an int item, then you'd just do:
```cs
int item = 10;
ScrollIntoView((object)item);
```

It will notify the compiler that it should use the object version.

**Comment by lenonk** [comment]
Sounds like a solution then.

**Comment by grokys** [comment]
I think `ScrollIntoView` needs to accept an index, not an object.
