### ISSUE TITLE
[XamlIl] Preserve whitspace

### ISSUE THREAD

**Issue by Gillibald** [AvaloniaUI/Avalonia#2619]
We need a way to preserve whitespaces if needed to be able to define inlines in XAML

If we have something like this:
```
<StackPanel Orientation="Vertical" Spacing="8">
    <TextBlock>A simple TextBlock with unformatted text.</TextBlock>
    <TextBlock>
        A <Run Classes="code">TextBlock</Run> with <Run FontWeight="Bold">differing</Run>
        <Run FontStyle="Italic">styles</Run> <Run FontSize="24">and fonts</Run>.
    </TextBlock>
    <TextBlock>
        A <Run Classes="code" Foreground="Gray">TextBlock</Run> with <Run Foreground="Red">differing</Run>
        <Run Foreground="Green">colors</Run>.
    </TextBlock>
    <TextBlock>
        A <Run Classes="code">TextBlock</Run> with <Run Foreground="Orange" FontStyle="Italic" Text="{Binding}"/>.
    </TextBlock>
    <TextBlock>
        A <Run Classes="code">TextBlock</Run> with a <LineBreak/> line break.
    </TextBlock>
</StackPanel>
```
We need to preserve whitespaces. Portable.Xaml was patched to support this by decorating the InlinesCollection with a special attribute.

This is the current result:

![XamlIlPreserveWhitespace](https://user-images.githubusercontent.com/5928797/58960192-f23e4980-87a6-11e9-8f8f-0c9514adf1d1.png)

Can be tested with: https://github.com/AvaloniaUI/Avalonia/pull/2423

**Comment by FoggyFinder** [comment]
any updates? workarounds?

**Comment by Kir-Antipov** [comment]
If anyone will face this problem, here's little trick to force whitespace preserving: use `\u200f\u200f\u200e\u0020\u200e` instead of regular space (`\u0020`):

 - `\u200f` - [Right-to-left mark ](https://en.wikipedia.org/wiki/Right-to-left_mark)
 - `\u200f` - [Right-to-left mark ](https://en.wikipedia.org/wiki/Right-to-left_mark)
 - `\u200e` - [Left-to-right mark ](https://en.wikipedia.org/wiki/Left-to-right_mark)
 - `\u0020` - space (` `)
 - `\u200e` - [Left-to-right mark ](https://en.wikipedia.org/wiki/Left-to-right_mark)

**Comment by shartte** [comment]
XAML specification for white space: https://docs.microsoft.com/en-us/dotnet/desktop/xaml-services/white-space-processing

Avalonia also doesn't collapse white space in WPF like WPF does.

**Comment by shartte** [comment]
See https://github.com/kekekeks/XamlX/pull/43
