### ISSUE TITLE
Published Avalonia Application - Executable opens Command Prompt

### ISSUE THREAD

**Issue by colinparks** [AvaloniaUI/Avalonia#2643]
I've made a very simple UI using Avalonia in Visual Studio (displays a textblock that says Hello World oriented in the center of the window). When I publish it using .Net Core 2.2 for Windows 10, the executable that is published opens Command Prompt to run the program. 

For debugging, this is fine, but being required to keep Command Prompt open to keep the program running is a problem for users down the line. Is there a way to change this so that the program may run without the need for Command Prompt to open and stay open?

**Comment by Gillibald** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/1705

**Comment by x2bool** [comment]
Or you could also use .NET Core 3.0 and:

```
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>
</Project>
```

**Comment by colinparks** [comment]
Thank you x2bool, the WinExe was what I was missing to get it to work with the solution in #1705. This issue can be closed now since it has been solved.

**Comment by hhyyrylainen** [comment]
Is there a way to do this from Linux? 
I've had `<OutputType>WinExe</OutputType>` in my csproj since the start, I just tested on Windows for the first time and noticed a command prompt window opening. I can't add `Microsoft.NET.Sdk.WindowsDesktop` as I then can't build on non-windows. Is there anything I'm missing? Or do I need to get a tool to hack the generated executable afterwards to not be marked as a non-GUI application? 
It seems [NSubsys](https://www.nuget.org/packages/NSubsys) didn't work for me, but I didn't try very hard as that library is archived on Github.
