### ISSUE TITLE
If Button.Content is an Image, the Image.Stretch property gets ignored

### ISSUE THREAD

**Issue by Kermalis** [AvaloniaUI/Avalonia#2686]
Broken:
![image](https://user-images.githubusercontent.com/29823718/60133237-01436680-976b-11e9-86bd-e20972fe578c.png)
```xaml
        <Button Width="60" Height="30" Background="White" BorderBrush="#A2A2A2" BorderThickness="4">
          <Image Stretch="None" Source="{Binding Source='Add', Converter={x:Static infrastructure:ObjectToTextBitmapConverter.Instance}, ConverterParameter=MenuBlack, Mode=OneWay}"/>
        </Button>
```

Workaround that does not stretch:
![image](https://user-images.githubusercontent.com/29823718/60133247-086a7480-976b-11e9-9705-45fb3d01c659.png)
```xaml
        <Button Width="60" Height="30" Background="White" BorderBrush="#A2A2A2" BorderThickness="4">
          <StackPanel>
            <Image Source="{Binding Source='Add', Converter={x:Static infrastructure:ObjectToTextBitmapConverter.Instance}, ConverterParameter=MenuBlack, Mode=OneWay}"/>
          </StackPanel>
        </Button>
```

The image is actually 15 pixels tall:
![image](https://user-images.githubusercontent.com/29823718/60133486-71ea8300-976b-11e9-84e9-8356c87d6af6.png)
The white in this would actually be transparent, but it shouldn't matter. The button should have enough space to place the image without the stackpanel helping

**Comment by grokys** [comment]
The problem here is that you have the default vertical padding in the `Button` of 4, plus the border thickness of 4, which is 16 pixels top + bottom. That leaves only 14 pixels for the image.

Surrounding the image in a `StackPanel` is taking advantage of the behavior of `StackPanel` where controls are given as much space as they want in the direction of the stack ([this behavior is from WPF](https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Stack.cs#L568)). What will happen is this case is that your image will be drawn one pixel outside the bounds given to it, causing the padding inside the button to be uneven.

The best thing to do here would be to take advantage of our layout system an not fix your control sizes: let them size to their preferred height.
