### ISSUE TITLE
You have a non-HTTPS site

### ISSUE THREAD

**Issue by ArmelliniFederico** [AvaloniaUI/Avalonia#2713]

**Comment by kekekeks** [comment]
We don't collect any login or personal data, cookies, js storage, etc, etc. I don't see why we would need encryption, it won't bring any benefits. On the other hand enforcing the site to work over HTTPS only potentially blocks access from countries with heavy internet censorship.

**Comment by grokys** [comment]
https://doesmysiteneedhttps.com/

**Comment by ArmelliniFederico** [comment]
I'd also add https://whynohttps.com/
@kekekeks , go check bottom links. 
If you can say even 1 argument against those security experts, you are right. But I'm sorry, I know you are wrong.

**Comment by x2bool** [comment]
If I am right, avaloniaui.net is hosted as a static website on github pages, which means enabling Let's Encrypt certificates is as simple as using a checkbox in the project's settings.

<img width="678" alt="image" src="https://user-images.githubusercontent.com/892945/60741297-8ac81500-9f71-11e9-91fc-e5a69fea01c2.png">

**Comment by kekekeks** [comment]
@ArmelliniFederico I might be wrong, but unfortunately not everyone has a privilege of living in a censorship-free country.

Some examples:

Time to first byte from mainland China to east coast USA:
HTTP: 0.4s
HTTPS: 5s + frequent disconnects on CSS/script/image load

From Russia to @HankG's [blog](www.nequalsonelifestyle.com): connection timeout or TLS error

That happens because analyzing and filtering HTTPS requires more resources and complex DPI which not all ISP's can afford.

So, by switching a static site to HTTPS for "I just like HTTPS" reasons we'd potentially remove the access from entire countries.

**Comment by ArmelliniFederico** [comment]
> for "I just like HTTPS" reasons

Now I'm 100% sure you didn't read anything we linked to you.

> Time to first byte from mainland China to east coast USA:
> HTTP: 0.4s
> HTTPS: 5s + frequent disconnects on CSS/script/image load

I haven't asked you to disable HTTP, just to enable HTTPS

**Comment by kekekeks** [comment]
>I haven't asked you to disable HTTP, just to enable HTTPS

Ah, sure, here you go: https://avaloniaui.net/

**Comment by ArmelliniFederico** [comment]
Thanks, we can close this ✌
