### ISSUE TITLE
Binding to $parent in ItemsControl item generates error.

### ISSUE THREAD

**Issue by FrozenShade666** [AvaloniaUI/Avalonia#2745]
Similar to https://github.com/AvaloniaUI/Avalonia/issues/2258

My code:
```
  <ContextMenu>
	<ItemsControl Items="{DynamicResource EvaluationMethods}">
	  <ItemsControl.ItemTemplate>
		<DataTemplate>
			<MenuItem Header="{Binding ., Converter={StaticResource WeightEvaluationMethodFormatter}}"
					  Command="{Binding $parent[ItemsControl].DataContext.ChangeMethod}"
					  CommandParameter="{Binding .}"
				>
			</MenuItem>                  
		</DataTemplate>
	  </ItemsControl.ItemTemplate>
	</ItemsControl>            
  </ContextMenu> 
```

Output:

`Binding: Error in binding to "Avalonia.Controls.MenuItem"."Command": "Null value in expression '$parent[ItemsControl, 0]'."`

Avalonia version 0.8.0
.NET Core 2.1

**Comment by FrozenShade666** [comment]
In the above example the command is working despite the error.

The following code creates Context menu, but neither the command nor the converter works:

```
<Border.ContextMenu>      
  <ContextMenu Items="{DynamicResource EvaluationMethods}">
	<ContextMenu.ItemTemplate>
	  <DataTemplate>
		<MenuItem Header="{Binding ., Converter={StaticResource WeightEvaluationMethodFormatter}}"
				  Command="{Binding $parent[v:UtilityEvaluatorView].DataContext.ChangeMethod}"
				  CommandParameter="{Binding .}"
				>
		</MenuItem>
	  </DataTemplate>
	</ContextMenu.ItemTemplate>
  </ContextMenu> 
</Border.ContextMenu>
```

**Comment by grokys** [comment]
I don't think the problem here is with `$parent` bindings not working: the problem seems to be a misunderstanding of how to create menus from templates. We're inherited a slightly confusing syntax from WPF unfortunately where adding a `MenuItem` to a `DataTemplate` causes two menu items to be created: see [this question](https://stackoverflow.com/a/1312902/6448) on stackoverflow for how it manifests itself in WPF. 

The solution (as with WPF) is to bind your commands using a style. To see how to do this properly check out the documentation: http://avaloniaui.net/docs/controls/menu#dynamically-creating-menus.

I'm going to close this issue, because I've tried using `$parent` in `MenuItem` command bindings and everything seems to work. Please let me know if you continue to have problems.

**Comment by FrozenShade666** [comment]
Thanks for explanations.
