### ISSUE TITLE
DatePicker, Position of the calendar

### ISSUE THREAD

**Issue by DogWalker3400** [AvaloniaUI/Avalonia#2763]
Please help:

I inserted a Datepicker at the bottom of a window. When I try to open the calendar, its position is always under the input box of the Datepicker and only a fraction if its content is visible. Is there a possibility to control the position of the calendar? 

Thanks!

**Comment by kekekeks** [comment]
Try 
```xml

<Window.Styles>
    <Style Selector="Popup">
        <Setter Property="ObeyScreenEdges" Value="True"
    </Style>
</Window.Styles>
```

**Comment by DogWalker3400** [comment]
Thank you!

I am using it in an Avalonia user control: Yes it works, but at the third click 😊 First Click on the calendar icon: Same position (under the Datepicker). Second click on the icon to close the calendar. Third click on the calendar: YES, Right Position!

Raspbian, .net Core 2.0, with Windows .net core 2.0 there is no effect, the calendar is always opening beneath the Datepicker.


________________________________
Von: Nikita Tsukanov <notifications@github.com>
Gesendet: Tuesday, July 23, 2019 12:41:23 PM
An: AvaloniaUI/Avalonia <Avalonia@noreply.github.com>
Cc: DogWalker3400 <m_raab@live.com>; Author <author@noreply.github.com>
Betreff: Re: [AvaloniaUI/Avalonia] DatePicker, Position of the calendar (#2763)


Try

<Window.Styles>
    <Style Selector="Popup">
        <Setter Property="ObeyScreenEdges" Value="True"
    </Style>
</Window.Styles>

**Comment by kekekeks** [comment]
I guess we need to implement https://github.com/AvaloniaUI/Avalonia/issues/2405 which should solve issues with popups on small screens

**Comment by kekekeks** [comment]
@danwalmsley 
`ObeyScreenEdges` code tries to snap inside the screen bounds after already trying to reposition the window in https://github.com/AvaloniaUI/Avalonia/blob/8e2413d19809a1e94dba774be3fe7cbcddefe384/src/Avalonia.Controls/Primitives/Popup.cs#L237

Then it tries to read it back from the platform impl, but window is not yet moved due to the asynchronous nature of X11 protocol. So it reads the current (not yet moved) coordinates of the popup. We could use the same hack as we currently use for window size and assume that window manager won't touch windows with override_redirect, but I'd rather don't move the window to the wrong position in the first place.

**Comment by kekekeks** [comment]
Working on it.

Popups:
![popups](https://user-images.githubusercontent.com/1067584/61993047-a5704400-b06e-11e9-9c40-4f55efd37ee1.gif)


Tooltips:

![popups2](https://user-images.githubusercontent.com/1067584/61993050-a99c6180-b06e-11e9-9d20-a40785804409.gif)
