### ISSUE TITLE
Grid column widths not obeying ColumnDefinitions using *

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#2862]
Here is an example of a simple Grid in WPF
```
<Window x:Class="WpfApp2.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="400">
  <Grid>
    <Grid.ColumnDefinitions>
      <ColumnDefinition Width="*"/>
      <ColumnDefinition Width="*"/>
    </Grid.ColumnDefinitions>
    <TextBlock Grid.Column="0" Text="0123456789 0123456789 0123456789 0123456789" Background="LightBlue" />
    <TextBlock Grid.Column="1" Text="Hello" Background="Beige"/>
  </Grid>
</Window>
```

![image](https://user-images.githubusercontent.com/17591364/63259380-1d98e680-c276-11e9-90ab-257fb8552cc5.png)

And the same grid in Avalonia 0.8.999-cibuild0003548-beta
```
```
![image](https://user-images.githubusercontent.com/17591364/63259445-55a02980-c276-11e9-9770-bc80ba40fa8c.png)

As you can see, the Avalonia Grid does not restrict the first TextBlock to half the available width.

Also adding
``` <TextBlock Grid.Column="0" Text="0123456789 0123456789 0123456789 0123456789" Background="LightBlue" TextWrapping="Wrap" />``` 
has no affect in Avalonia, producing the same image above.

Whereas in WPF, I get

![image](https://user-images.githubusercontent.com/17591364/63259677-f5f64e00-c276-11e9-89b5-8efaa49b7115.png)

**Comment by Kermalis** [comment]
This also applies to `RowDefinitions` (and for both you get the bug with `*` as well as `1*`, `2*`, etc.)

**Comment by grokys** [comment]
Strange, when I use the above XAML in the designer, indeed it gets laid out wrong:

![image](https://user-images.githubusercontent.com/1775141/66301541-9a038980-e8f7-11e9-8bcb-6f65f0ed0c4d.png)

However running the application results in the correct layout:

![image](https://user-images.githubusercontent.com/1775141/66301563-a4258800-e8f7-11e9-9aa5-92cc15106f11.png)

Is this what you are seeing? Trying to work out what's going on here now.

**Comment by aguahombre** [comment]
Yes, I see the same

**Comment by grokys** [comment]
Ok, this is a design-time only problem.

The problem is that `DesignWindowLoader` always sets `SizeToContent = WidthAndHeight` at design time:

https://github.com/AvaloniaUI/Avalonia/blob/217e0d5f7bab1131210d452587ddb3a6ced2cc2d/src/Avalonia.DesignerSupport/DesignWindowLoader.cs#L72

This causes the `Window` to be measured with infinity:

https://github.com/AvaloniaUI/Avalonia/blob/217e0d5f7bab1131210d452587ddb3a6ced2cc2d/src/Avalonia.Controls/Window.cs#L535-L543

Which causes grid to set `sizeToContentU= true`:

https://github.com/AvaloniaUI/Avalonia/blob/217e0d5f7bab1131210d452587ddb3a6ced2cc2d/src/Avalonia.Controls/Grid.cs#L237

Which results in `treatStarAsAuto = true`:

https://github.com/AvaloniaUI/Avalonia/blob/217e0d5f7bab1131210d452587ddb3a6ced2cc2d/src/Avalonia.Controls/Grid.cs#L853-L861
