### ISSUE TITLE
Window Activate not work on Win7

### ISSUE THREAD

**Issue by MonkAlex** [AvaloniaUI/Avalonia#2975]
If window in any not focused state: minimized, other app in front, then i try to use code from WPF:
```
        var mainWindow = lifetime.MainWindow;
        if (mainWindow != null)
        {
          mainWindow.Show();
          mainWindow.Activate();
          if (mainWindow.WindowState == WindowState.Minimized)
            mainWindow.WindowState = WindowState.Normal;
        }
```
Work only for minimized state, bring to front not work.
Related #2398, but i check on windows7
Linux not checked.

**Comment by cocacola89** [comment]
I can confirm indeed that this issue is reproducible on latest nightly build.

As far as my investigation went: `SetActiveWindow` function  which is used in `Avalonia.Win32.WindowImpl`does nothing and exits with `S_OK` Win32 error code.

After some google-ing I've come across `SetForegroundWindow` function that some folks were referring to. 

I've checked WPF source - it appears that WPF also uses `SetForegroundWindow` function.

I've tried manually calling `SetForegroundWindow` function in Avalonia app with window's HWND - that causes window to flash on the taskbar (same effect as calling `Window.Activate()` in WPF app). 

As a temporary workaround I can suggest using an extension method like this:

```CSharp
internal static class WindowExtensions
{

    private static readonly bool IsWin32NT = Environment.OSVersion.Platform == PlatformID.Win32NT;

    [DllImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    private static extern bool SetForegroundWindow(IntPtr hWnd);

    public static void ActivateWorkaround(this Window window)
        {
            if (ReferenceEquals(window, null)) throw new ArgumentNullException(nameof(window));

            // Call default Activate() anyway.
            window.Activate();

            // Skip workaround for non-windows platforms.
            if (!IsWin32NT) return;
            
            var platformImpl = window.PlatformImpl;
            if (ReferenceEquals(platformImpl, null)) return;

            var platformHandle = platformImpl.Handle;
            if (ReferenceEquals(platformHandle, null)) return;

            var handle = platformHandle.Handle;
            if (IntPtr.Zero == handle) return;

            try
            {
                SetForegroundWindow(handle);
            }
            catch
            {
                // ignored
            }
        }
}
```

**Comment by MonkAlex** [comment]
@cocacola89 its work, thanks.

Can u create PullRequest?

**Comment by cocacola89** [comment]
> @cocacola89 its work, thanks.
> 
> Can u create PullRequest?

Done [#3048](https://github.com/AvaloniaUI/Avalonia/pull/3048).
Decided to leave old call to `SetActiveWindow()` as a fallback option.

Unfortunately, I could not test it properly as I didn't have a setup for building Avalonia itself and quick and dirty setup resulted in some build-time errors. Anyway, affected assemblies build just fine.

Some thoughts for test cases:
 - should test if activation callbacks fire and fire only once.
 - should test what leads to `SetForegroundWindow()` failing and decide on leaving a fallback option or removing it completely.
