### ISSUE TITLE
Bind radiobutton to enum

### ISSUE THREAD

**Issue by v0vc** [AvaloniaUI/Avalonia#3016]
Please explain, how to correct bind radiobutton to enum in avalonia ci builds?
In 0.8.2 i used to work with EnumBooleanConverter : IValueConverter, but can't reproduce this flow in ci versions.

Thanks!

**Comment by v0vc** [comment]
Not actual, found example in SpiroNet project, may be helpful

**Comment by derekantrican** [comment]
For people referencing this in the future, I believe this is what @v0vc is referring to: https://github.com/wieslawsoltes/SpiroNet/blob/master/src/SpiroNet.Editor.Avalonia/Converters/EnumToBooleanConverter.cs

**Comment by derekantrican** [comment]
Actually, after some trouble I came across this better option: https://stackoverflow.com/a/2908885/2246411

Converter:

```csharp
public class EnumToBooleanConverter : IValueConverter
{
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
    {
        return value?.Equals(parameter);
    }

    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
    {
        return value?.Equals(true) == true ? parameter : BindingOperations.DoNothing;
    }
}
```

Usage:
```xml
<RadioButton Content="Day of Month" Margin="5"
			 IsChecked="{Binding MonthRepeat, Converter={StaticResource EnumBoolConverter}, ConverterParameter={x:Static base:MonthRepeat.ByDayOfMonth}}"/>
<RadioButton Content="Day of Week" Margin="5"
			 IsChecked="{Binding MonthRepeat, Converter={StaticResource EnumBoolConverter}, ConverterParameter={x:Static base:MonthRepeat.ByWeekDay}}"/>
```

**Comment by Coding-Enthusiast** [comment]
In case someone landed here from search like me, here is what I've managed to do.  

The idea is to simply use a `ListBox` but change its style to represent its items as `RadioButton`s. And the `ListBox.Items` is bound to a list of items (`IEnumerable<enum>`) in VM that can be easily set from enums using `System.EnumGetValues(Type enumType)` method.  
I use a `Style` because changing `DataTemplate` of the `ListBox` and setting the `Content` broke everything, in this stype:

The **benefit** of this approach is that you don't need to create a separate `RadioButton`s for each enum and it needs a lot less code.

Here is the style that can be added to `App.xaml` or `Window` or `UserControl` resources (it uses a class name (RadioButtonListBox) to avoid affecting other normal listboxes):  

```xaml
<!--Use Classes="RadioButtonListBox" in any ListBox to represent its items as RadioButtons-->
<Style Selector="ListBox.RadioButtonListBox">
  <Setter Property="BorderBrush" Value="Transparent"/>
</Style>
<Style Selector="ListBox.RadioButtonListBox ListBoxItem">
  <Setter Property="Template">
    <Setter.Value>
      <ControlTemplate>
        <Border Background="Transparent">
          <RadioButton Content="{TemplateBinding ContentPresenter.Content}"
                       VerticalAlignment="Center"
                       IsChecked="{Binding Path=IsSelected,RelativeSource={RelativeSource TemplatedParent},Mode=TwoWay}"/>
        </Border>
      </ControlTemplate>
    </Setter.Value>
  </Setter>
</Style>
```
With that style now any `ListBox` anywhere can be changed to show `RadioButtons` easily like this:
```xaml
<ListBox Items="{Binding ListOfEnums}"
         SelectedItem="{Binding SelectedItem}"
         Classes="RadioButtonListBox"/>
```
Here is a preview:  
![radiobutton](https://user-images.githubusercontent.com/20510382/111145441-7db05580-859d-11eb-8343-c8e6ccb4423e.jpg)  

In case you want to see my full code on GitHub: [View](https://github.com/Autarkysoft/Denovo/blob/217d4354cc35874b8c9a744ae2ad17ca6fde0c95/Src/Denovo/Views/EciesView.axaml) and [ViewModel](https://github.com/Autarkysoft/Denovo/blob/217d4354cc35874b8c9a744ae2ad17ca6fde0c95/Src/Denovo/ViewModels/EciesViewModel.cs) and [App.xaml](https://github.com/Autarkysoft/Denovo/blob/217d4354cc35874b8c9a744ae2ad17ca6fde0c95/Src/Denovo/App.xaml) containing my styles.
