### ISSUE TITLE
Avalonia does not look native on windows?

### ISSUE THREAD

**Issue by Shadowblitz16** [AvaloniaUI/Avalonia#3023]
is there a way to make Avalonia look native on windows 7 and windows 7 classic?
![image](https://user-images.githubusercontent.com/2453707/65394995-9db8dd00-dd49-11e9-8a6d-6f0f7d8f02b2.png)

**Comment by Gillibald** [comment]
You have to use custom theming to achieve the native look. Same applies to WPF. That's the joy of lookless controls. You can style them in any way you want.

**Comment by Shadowblitz16** [comment]
isn't there built in themes?

**Comment by jmacato** [comment]
@Shadowblitz16 we plan to do that but that's like further away from the future unless someone volunteers to implement that sooner.

**Comment by grokys** [comment]
If you're wanting to use native controls, [Eto.Forms](https://github.com/picoe/Eto) might be a better option for you.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/AvaloniaUI/Avalonia/issues/3023#issuecomment-534017538

@jmacato, is it being tracked?

**Comment by maxkatz6** [comment]
"Native Windows look" can't be defined as a single idea. Because Windows doesn't have a single "native" theme. Is it WinUI/Fluent? Current WinForms? Something else? Original issue was referring about `windows 7 theme`, which isn't the main windows styling idea for...13 years now. 

Current default Avalonia Fluent theme is based from Windows 10 Fluent. Making it "native-look" there, even though it doesn't `reveal` buttons effect (so, 10.0.10240 look and feel?).
[FluentAvalonia](https://github.com/amwx/FluentAvalonia) third party theme follows Windows 11 Fluent styles, making it feel native on Win11.

You can also refer for [Classic.Avalonia](https://github.com/BAndysc/Classic.Avalonia) for true Windows look.
Or [Aero Theme for Avalonia](https://github.com/Splitwirez/avalonia-aero-theme) following Win7 styles.

There are no plans to make Avalonia look more "windows". But there is enough of third party themes.

**Comment by RokeJulianLockhart** [comment]
> "Native Windows look" can't be defined as a single idea. Because Windows doesn't have a single "native" theme. Is it WinUI/Fluent? Current WinForms? Something else?

@maxkatz6, it can. It's WinUI3's implementation of Microsoft's current version of the Fluent Design guidelines (which can be made stable by referring to specific commits of their documentation). The underlying toolkit isn't particularly important anymore, since XAML Islands exist.

WinUI2 could also be a target, since its *appearance* should match WinUI3's identically if everyone's doing their job properly. Ultimately, the documentation defines the styles to adhere to.

**Comment by maxkatz6** [comment]
>  It's WinUI3's implementation of Microsoft's current version of the Fluent Design guidelines (which can be made stable by referring to specific commits of their documentation). The underlying toolkit isn't particularly important anymore, since XAML Islands exist.

https://github.com/amwx/FluentAvalonia it is then. Compatible with latest Avalonia versions.
