### ISSUE TITLE
ItemsRepeater w/ non-uniform item height bugs out when scrolled on.

### ISSUE THREAD

**Issue by jmacato** [AvaloniaUI/Avalonia#3041]
When the data source of ItemsRepeater has varying/non-uniform heights, whenever you scroll the ItemsRepeater with StackLayout option, the scroll might get stuck up or at least the scrollbars will not respond on any scroll commands (scrollwheel or drag).  This only resets when the containing layout is refreshed through window resize.

**Comment by grokys** [comment]
This seems to be caused by the infinite loop protected introduced in #2297: it seems to result in `Track` never getting measured after a certain point.

**Comment by agnauck** [comment]
Scrolling is still getting stuck for me quite often. I have items with variable height, and do not supply the item height. The height calculates automatically based on content.

Here is a sample which reproduces the issue. When scrolling up and down for a while the scroller gets stuck. When resizing the window a little the scrollbar starts working again.
https://github.com/agnauck/AvaloniaBug1

First I thought the problem is related to a high number of items. But in my application this happens on a regular basis, also with very low number of items (5-10).
A ListBox control works fine with the same data and data templates.
