### ISSUE TITLE
Deferred Renderer can go into endless loop if Disposed VisualNodes remain in tree.

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#3115]
I can repro this in Wasabi wallet, also had reports from other users on UI freezing in recent builds.

**Comment by danwalmsley** [comment]
![image](https://user-images.githubusercontent.com/4672627/66865541-57911b00-ef8f-11e9-9372-5e800b5810a9.png)

**Comment by grokys** [comment]
Worked out what's happening here:

- Parent `VisualNode` node has two children
- The first control of the parent is made invisble
- `SceneBuilder.Update` is called on the parent node
- The first node is skipped [because it's invisible](https://github.com/AvaloniaUI/Avalonia/blob/1d87c047ff69fb609f64f7d2166017c65e1d8ba9/src/Avalonia.Visuals/Rendering/SceneGraph/SceneBuilder.cs#L161)
- The second node is added to the parent node's `Children` collection, at index 0 this time. Now the parent has two instance of the the second node in its `Children`
- `VisualNode.TrimChildren` is called to trim the node at index 1. Unfortunately it's the same as the node at index 0, causing an active node to get disposed
