### ISSUE TITLE
Touch scrolling not working after ComboBox selection on Linux X11

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#3156]
Avalonia 0.9.0 preview1 on Linux X11
After using a ComboBox to select an item using touch, all ScrollViewer controls stop working with touch. Specifically the ScrollGestureRecognizer used by the ScrollViewer stops working.

I monitored  the TouchDevice input using
```Avalonia.Input.InputManager.Instance.PreProcess.OfType<Avalonia.Input.Raw.RawTouchEventArgs>().Subscribe(r => System.Console.WriteLine($"{r.Type} {r.TouchPointId}"));```

and can see that when closing the ComboBox after a selection I get a RawPointerEventType.TouchBegin event but no corresponding RawPointerEventType.TouchEnd event.

This will cause the TouchDevice to retain an orphaned pointer in it's ```_pointers``` dictionary. All subsequent touch events generated by the TouchDevice will be non-primary pointers. This stops the ScrollGestureRecognizer working as it looks for primary pointer events.

The missing RawPointerEventType.TouchEnd events occurs because the  XiEventType.XI_TouchEnd event occurs after the X11Window for the ComboBox Popup is closed. The XI2Manager.OnEvent method discards the XiEventType.XI_TouchEnd as the event's window handle no longer exists in it's _clients dictionary.

The TouchDevice needs to receive the RawPointerEventType.TouchEnd event after the ComboBox Popup is closed and the touch is ended.

**Comment by kekekeks** [comment]
TouchDevice is created on per-window basis, so it couldn't retain pointers from another window. Controls, however, might be affected by this, since for reasons now long forgotten *every single event from child popup goes through the parent*.
If we remove that, keyboard navigation through menus stops working completely, because, apparently, keyboard events are still being sent to the main window by the OS.

I've already hit this wall in https://github.com/AvaloniaUI/Avalonia/pull/2559

Not sure what to do with this particular issue though. I guess we should trigger PointerCaptureLost for all known pointers on window close and ignore any pointer events that come afterwards.

**Comment by aguahombre** [comment]
Are you sure?
It looks to me as though the X12Manager creates a single TouchDevice that processes events from all windows.
There is only one X12Manager instance?

**Comment by kekekeks** [comment]
>creates a single TouchDevice

That should be changed to per-window model then.

**Comment by kekekeks** [comment]
Please, check if PR resolves your issue
