### ISSUE TITLE
Bubble RaiseEvent stops when handler removes control from the visual tree

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#3176]
I have found that an event bubbling up the visual tree fails if a control's event handler removes the control from the visual tree.

This causes a problem when the event is a PointerReleased event and the parent control is has a gesture recognizer tracking the pointer; the recognizer never receives the PointerReleased event to terminate the gesture.

The problem lies in the ```HierarchyTraverser.Traverse``` method
```
            public void Traverse(IInteractive target)
            {
                _preTraverse.Execute(target, _args);

                IInteractive parent = target.InteractiveParent;

                if (parent != null)
                {
                    Traverse(parent);
                }

                _postTraverse.Execute(target, _args);
            }
```

The parent control is loaded after the pre-traverse event is processed and will be null if the handler removes the target from the visual tree.

Loading the parent before executing the event would allow the routed event to continue bubbling to the root.

```
            public void Traverse(IInteractive target)
            {
                IInteractive parent = target.InteractiveParent;

                _preTraverse.Execute(target, _args);

                if (parent != null)
                {
                    Traverse(parent);
                }

                _postTraverse.Execute(target, _args);
            }
```
Is there a good reason why it was implement like this?

I think WPF implementation builds the whole route as a list before it traverses it so would not stop if an element in the route is removed from the visual tree.

**Comment by MarchingCube** [comment]
I remember changing this in this PR (https://github.com/AvaloniaUI/Avalonia/pull/3067). Previous implementation was quite bad memory wise as it allocated quite a lot due to LINQ and iterator block usage.

Old implementation was also getting parent after doing traversal. I didn't write the initial implementation, but WPF does indeed build whole event route upfront.

We could change this implementation to traverse into a list first and then invoke handlers. This should allow us to remove elements from the hierarchy and still keep old traversal path.

On the other hand I am not sure how correct this is since you are traversing stale hierarchy with this approach and new parent nodes will not receive any events. Maybe somebody from @AvaloniaUI/core has better idea about what behavior is better in this case.
