### ISSUE TITLE
Implement ColorTransition

### ISSUE THREAD

**Issue by zeroskyx** [AvaloniaUI/Avalonia#3210]
Greetings,

Avalonia currently supports the following transitions (from [the documentation](https://avaloniaui.net/docs/animations/transitions)):

- DoubleTransitions: For double target properties
- FloatTransitions: For float target properties
- IntegerTransitions: For int target properties

Unfortunately there is currently no support for `ColorTransition` that would make smooth color changes possible as in WPF or UWP.

Keep up the amazing work!

**Comment by kekekeks** [comment]
Currently blocked by brush->visual invalidation and property paths

**Comment by grokys** [comment]
I think brush -> visual invalidation should work fine, is there something I'm not aware of?

**Comment by daniel-lerch** [comment]
I wanted to use color transitions to animate the background of a button on hover because I didn't find a way to animate the mouse leave event with keyframe animations. So I wrote a [`SolidColorBrushTransition`](https://github.com/daniel-lerch/vocup/blob/20af850b3316ef546f37d7e60645993f7df15f25/src/Vocup.Avalonia/Controls/SolidColorBrushTransition.cs) which creates a new brush for every frame. Unfortunately, it can't be used from XAML but from C# it works and runs smoothly even in debug mode.

**Comment by maxkatz6** [comment]
BrushTransition is already released. Closing as done.

**Comment by maxkatz6** [comment]
It also soon will support gradients https://github.com/AvaloniaUI/Avalonia/pull/6183
