### ISSUE TITLE
Negated binding does not call converter in version 0.9 Preview 7

### ISSUE THREAD

**Issue by lenonk** [AvaloniaUI/Avalonia#3231]
With the xaml below, the converter is only called by the TextBlock containing IsVisible="{Binding Name ....}, and not by the one containing IsVisible="{Binding !Name ...}"

``` xaml
            <DataGridTemplateColumn Header="Name">
              <DataGridTemplateColumn.CellTemplate>
                <DataTemplate>
                  <StackPanel>
                   <TextBlock IsVisible="{Binding Name, Converter={StaticResource StringToBoolConverter}}" Text="{Binding Name}" />
                   <TextBlock IsVisible="{Binding !Name, Converter={StaticResource StringToBoolConverter}}" Text="No Name Specified" />
                  </StackPanel>
                </DataTemplate>
              </DataGridTemplateColumn.CellTemplate>
            </DataGridTemplateColumn>
```

**Comment by lenonk** [comment]
Also doesn't seem to work in 0.8.3

**Comment by grokys** [comment]
The problem here is that the `!` (not) is applied to the string value before the converter gets hit.

If the value of `Name` isn't convertable to `bool` (i.e. it's not `"true"` or `"false"`) then the whole binding errors out, meaning that the converter doesn't get called.

I think I'm going to mark this as expected behavior because it seems correct to me
: `!Name` should produce a boolean value, and that value should be passed to the converter. If the value cannot be converted to a boolean then `!Name` is in error.

**Comment by lenonk** [comment]
That seems highly non-intuitive to me, and seems to defeat the entire purpose of the converter.  If the value of the string could be converted to a boolean without the converter, then why would I need a converter?  *Especially* since the version without the negation works.  They should either both fail, or both work.  The lack of consistency is bad.

Perhaps there's a better solution to what I'm trying to do.  If the string is null or whitespace, I want a textblock to appear that says "No Name Specified".  Even if there is a better solution, intuitively, the negation should be applied to the result of the converted value if a converter exists, because that's the way the non-negated version works.

**Comment by grokys** [comment]
Yeah I understand, but I ask you to think about it like this:

Our property `StringValue` is `"foo"`. If you have a version without negation or a converter, it obviously won't work.

`IsVisible="{Binding StringValue}"`

Here, '"foo"` can't be converted to a bool, so the binding fails. Now you add a converter:

`IsVisible="{Binding StringValue, Converter={StaticResource FooToBoolConverter}"`

The converter is added so that it takes as its input the output of the binding, so in pseudocode it goes `boundValue => Converter.Convert(boundValue)`

Now lets take out the converter again, and add the `!` operator:

`IsVisible="{Binding !StringValue}"`

Here again, '"foo"` can't be converted to a bool, so the binding fails. Now you add a converter to this:

`IsVisible="{Binding !StringValue, Converter={StaticResource FooToBoolConverter}}"`

What should be passed to the converter? Remember that `!StringValue` cannot be done, and the converter takes as its input the output of the binding.

> Perhaps there's a better solution to what I'm trying to do. If the string is null or whitespace, I want a textblock to appear that says "No Name Specified".

The most obvious solution would be to write your converter so that it takes the `string` value and outputs the value you need, without the `!`.

**Comment by lenonk** [comment]
That's the solution that I ended up with as a workaround.  It works, but seems...I don't know...wrong.  I guess I'm having problems seeing the point of converters given that the converter takes the output of the binding.  That seems backwards to me, it seems that the binding should be the output of the converter.

Maybe an alternate solution would be to allow passing parameters to the converter.  Or maybe I'm trying to shoehorn functionality that was never intended out of converters.

**Comment by grokys** [comment]
> it seems that the binding should be the output of the converter

The final binding value that is sent to the property _is_ the output of the converter, but _something_ needs to be sent to the converter, and that something can only come from the `Path` part of the binding (i.e. `Name` or `!Name` in this case). I think what you're asking for is the converter to be inserted between the `!` and the `Name`, which would be confusing in different ways!

> an alternate solution would be to allow passing parameters to the converter.

There's already `ConverterParameter` for that! :D

**Comment by lenonk** [comment]
>  I think what you're asking for is the converter to be inserted between the ! and the Name, which would be confusing in different ways!
yes, that seems intuitive to me.

> There's already ConverterParameter for that! :D
I wasn't aware of these dark arts! :D

That sounds like what I actually want, but then I'm confused as to what I would put in the IsVisible tag above.

Can I just: 
```
IsVisible="{Binding Converter={StaticResource FooToBoolConverter}"
```
Then add whatever xaml is needed for ConverterParameter?

**Comment by grokys** [comment]
> I wasn't aware of these dark arts! :D

It's the same in pretty much all XAML frameworks, so I wouldn't exactly call it a dark art ;)

>  I'm confused as to what I would put in the IsVisible tag above.

You could take advantage of the built-in [`StringConverters`](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Data/Converters/StringConverters.cs) for that:

```
<TextBlock IsVisible="{Binding Name, Converter={x:Static StringConverters.IsNotNullOrEmpty}}" Text="{Binding Name}" />
<TextBlock IsVisible="{Binding Name, Converter={x:Static StringConverters.IsNullOrEmpty}}" Text="No Name Specified" />
```

**Comment by lenonk** [comment]
Nice, that looks like exactly what I'm looking for.  Keep in mind, this is the first XAML framework I've ever worked with.  I've been a C++ developer in Unix for the last 25 years.  ALL of this XAML stuff is dark arts to me! :D

**Comment by grokys** [comment]
Yeah, and we need a lot more documentation for this stuff! I will add info about the built-in converters to the docs.

**Comment by lenonk** [comment]
Thanks for helping me out, and for spending the, I'm sure, vast amounts of time you spend on this project.

It's awesome to finally have a good way to write xplat UI and code.

**Comment by grokys** [comment]
Thanks for the kind words @lenonk, it really is appreciated!
