### ISSUE TITLE
ViewModelBase made internal in 0.9

### ISSUE THREAD

**Issue by ThadHouse** [AvaloniaUI/Avalonia#3239]
https://avaloniaui.net/docs/binding/binding-to-commands shows using ViewModelBase as an easy way to get INotifyPropertyChanged. This worked in 0.8, but seems to be replaced in 0.9. Is there a replacement, or just manually implement INotifyPropertyChanged?

**Comment by kekekeks** [comment]
I don't think it was intended to be a part of the public API, since it lives in Avalonia.Diagnostics and is used internally in devtools. 

If you need the behavior from 0.8, just copy-paste the code from https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Diagnostics/ViewModels/ViewModelBase.cs

**Comment by HankG** [comment]
@ThadHouse a ViewModelBase gets generated with each project however nowadays it's simply extending ReactiveObject so everything should work as documented out of the box still.
