### ISSUE TITLE
WindowStartupLocation.CenterScreen incorrect on Retina OSX

### ISSUE THREAD

**Issue by jpobst** [AvaloniaUI/Avalonia#3404]
Avalonia NuGet 0.9.1.

Attempting to use `Window.WindowStartupLocation = CenterScreen` on Retina OSX positions the window partially offscreen to the upper left.

MacBook Pro 15 inch 2018
OSX Mojave 10.14.6
Resolution: 2880 x 1800 (Retina)

### Repro:
```
dotnet new avalonia.app -o MyApp
```

Add `WindowStartupLocation="CenterScreen"` to `MainWindow.xaml`.

### Cause:
This seems to be related to the `Screen`.

On OSX:
```
Screen.WorkingArea: { 0, 55, 1680, 972 }
```

Same laptop on HiDPI (200%) Windows 10:
```
Screen.WorkingArea: { 0, 0, 2880, 1720 }
```

Because the scaled window size (`{2048, 1600}`) is larger than the `Screen.WorkingArea`, the `CenterRect` ends up positioning the window with a negative location: `{ -184, 23 }`.

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Window.cs#L511

**Comment by kekekeks** [comment]
The problem is that some of our x-plat code just assumes that screen coordinates are reported in pixels while OSX uses *scaled* coordinates for window positions unlike Windows and Linux. 

It's not really possible to emulate win32 behavior with multi-monitor configurations, e. g.

![изображение](https://user-images.githubusercontent.com/1067584/71781468-6d3b3d00-2fe0-11ea-9b9e-2bb75cef4562.png)


what is the "physical" coordinate of the orange cross (x: 120, y: 160 in logical space).
