### ISSUE TITLE
Could you clarify about the FontFamily API?

### ISSUE THREAD

**Issue by rstm-sf** [AvaloniaUI/Avalonia#3472]
Hello!

Could you clarify about the `FontFamily` API?

To begin with, I'm new to using avalonia / wpf and therefore some things are not known to me.

According to the documentation, we pass the name of the font, but if we look at the xaml-examples, we can also pass the URI in the name (it is not obvious):
https://github.com/AvaloniaUI/Avalonia/blob/dbc66b7787f1667d8f26da6c630cd83ffbb41f4c/samples/ControlCatalog/Pages/TextBoxPage.xaml#L43-L54

Using ctor/method in c# code it is more obvious to use the following  for custom fonts:
https://github.com/AvaloniaUI/Avalonia/blob/c4708e2b927a6dc202ca169bb6722208d5d8ed56/src/Avalonia.Visuals/Media/FontFamily.cs#L27-L33

https://github.com/AvaloniaUI/Avalonia/blob/c4708e2b927a6dc202ca169bb6722208d5d8ed56/src/Avalonia.Visuals/Media/FontFamily.cs#L139-L148

But they will work if we specify the `name` (or`s`) through the `#` symbol (see [this](https://github.com/AvaloniaUI/Avalonia/blob/c4708e2b927a6dc202ca169bb6722208d5d8ed56/src/Avalonia.Visuals/Media/FontFamily.cs#L112-L137) method) -- it's bug?

Example: 
work
```c#
FontFamily.Parse("#Source Sans Pro", new URI("avares://ControlCatalog/Assets/Fonts"));
```
don't work
```c#
FontFamily.Parse("Source Sans Pro", new URI("avares://ControlCatalog/Assets/Fonts"));
```

And from here the next question: Why do we need to pass a URI if we can simply write the following:
```c#
FontFamily.Parse("avares://ControlCatalog/Assets/Fonts#Source Sans Pro"));
```

Thanks and kind regards!

**Comment by Gillibald** [comment]
As you can see in the example there a situation when you want to specify a font location relative to the current context.

`"/Assets/Fonts/SourceSansPro-Italic.ttf#Source Sans Pro"` where the current context is `"avares://ControlCatalog"`

This translates to:
`"avares://ControlCatalog/Assets/Fonts#Source Sans Pro"`

If you are constructing a `FontFamily` in code you don't have to deal with `FontFamily.Parse` or `new FontFamily(string s, Uri baseUri)` because it is always clear in which context you are working.

For custom fonts you just write:
`new FontFamily("avares://ControlCatalog/Assets/Fonts#Source Sans Pro")` 

For system fonts:
`new FontFamily("Arial")`

`FontFamily.Parse("Source Sans Pro", new URI("avares://ControlCatalog/Assets/Fonts"));` isn't working because you try to load a system font that isn't installed on the system. The base Uri is ignored if you don't specify the name with `#Name`

**Comment by rstm-sf** [comment]
Ok, thanks for the answer!

We can reflect your answer somewhere in the documentation (it was more difficult for me to understand why #Name)? Or is it already written somewhere and I missed it?

**Comment by kekekeks** [comment]
We are reusing WPF syntax https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.fontfamily?view=netframework-4.8#specifying-fonts-in-alternate-directories

**Comment by rstm-sf** [comment]
> We are reusing WPF syntax https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.fontfamily?view=netframework-4.8#specifying-fonts-in-alternate-directories

Thanks for the link!
