### ISSUE TITLE
DataGrid ScrollViewer issue

### ISSUE THREAD

**Issue by VoteForPedro** [AvaloniaUI/Avalonia#3548]
DataGrid bound to ObservableCollection ignores property changes. 
In my case, issue occured when vertical scroll appears. If i do some scroll - it works as expected.  
Also it works well when container does not have vertical scroll.
![data-grid-refresh](https://user-images.githubusercontent.com/7259290/74243882-95aa0b80-4cf1-11ea-99b7-8fd46cf88435.gif)
[AvaloniaDataGridRefreshIssue.zip](https://github.com/AvaloniaUI/Avalonia/files/4186074/AvaloniaDataGridRefreshIssue.zip)

**Comment by sdoroff** [comment]
This issue is actually being caused by your example code. The custom implementation of `DataGridItem.Equals` prevents rows from updating when their `DataContext` changes because `==` returns true. There are some complicated internals surrounding how rows are recycled that causes this to only occur in `DataGrids` with visible vertical `ScrollBars` that have not yet been scrolled.
