### ISSUE TITLE
Allow for wrapping keyboard navigation in ItemsControl

### ISSUE THREAD

**Issue by MarchingCube** [AvaloniaUI/Avalonia#3743]
Currently when reaching first element in a `ListBox` and pressing arrow up nothing happens. This is fine in most of the cases but I would like to have an option to wrap the selection as well. That means when we are at the first element and we press arrow up - we go to the last element. Works in a similar way on the last element.

We already have most of the code for that since `ItemsControl.GetNextControl` supports wrapping. 

Also, do we have an API for requesting directional navigation from the outside of the control? WPF has something like https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.movefocus?view=netframework-4.8#System_Windows_FrameworkElement_MoveFocus_System_Windows_Input_TraversalRequest_

**Comment by grokys** [comment]
We removed the WPF API for directional navigation, because it was really fiddly and didn't really work that well - directional navigation has enough gotchas to kind of need to be implemented in the controls themselves.

Having said that, we should probably expose a property to control this. My feeling is just to go with something like `ItemsControl.WrapSelection` instead of trying to make something generic, unless you can think of other controls this would apply to?
