### ISSUE TITLE
OnTemplateApplied usage is tricky and bug prone

### ISSUE THREAD

**Issue by MarchingCube** [AvaloniaUI/Avalonia#3744]
While developing custom controls you end up overriding `OnTemplateApplied` quite often. But implementing it correctly needs some attention since it is very easy to introduce bugs. Example

```csharp
public override void OnTemplateApplied(...)
{
    base.OnTemplateApplied(...)

    // Resolve your controls
}
```

This will work, unless somebody subscribes to `TemplateApplied` event and tries to interact with your control. Then you will quickly figure out that template was not fully applied yet and calling base method will raise the event already.

So you will move your resolution after call to the base method like so:

```csharp
public override void OnTemplateApplied(...)
{
    // Resolve your controls

    base.OnTemplateApplied(...)
}
```

Now you have to be careful what do you call before base call since your parent class wasn't setup yet. So calling any virtual method or setting a property is a minefield.

After discussion with @grokys we think that we need more extension points here:
- `OnApplyTemplate` to actually apply your template and resolve controls
- `OnTemplateApplied` to actually raise the events and do setup **after** the template has been applied

`ApplyTemplate` will first call `OnApplyTemplate` and then `OnTemplateApplied`.

You can now safely call `base.OnApplyTemplate` as a first statement and initialize your control without worrying.

**Comment by grokys** [comment]
Yeah, I think there are two options here:

1. Add `OnApplyTemplate` as mentioned by @MarchingCube 
- PRO: We now follow WPF's API
- CON: Could be confusing because we now have `ApplyTemplate`, `OnApplyTemplate` and `OnTemplateApplied`. If we do this might be worth marking `OnTemplateApplied` obsolete, and then making it private in a future version?
2. Make `ApplyTemplate` call `TemplateApplied` itself after the call to `OnTemplateApplied`
- PRO: Less API confusion from various methods with similar names
- CON: `OnX` methods usually raise the event (though not always)

I think option 1 is probably better on balance because it follow's WPF's API. Thoughts?
