### ISSUE TITLE
Adding previous child in TreeView Crashes

### ISSUE THREAD

**Issue by Voulz** [AvaloniaUI/Avalonia#3746]
Hello!
In Avalonia 0.9.7, re-adding an item in a TreeView to a Parent that was previously removed creates an exception in `TreeContainerIndex.Add` in the line `this._containerToItem.Add(container, item);`

To Reproduce (In Avalonia 0.9.7):
- Add Parent1 instance
- Add Child1 instance (child of Parent 1)
- Expand Parent1 instance
- Remove Child1 instance
- RemoveParent1 instance
- Add again the same Parent1 instance
- Add again Child1 instance (child of Parent 1)
- Expand Parent1 instance ==> Crash

I would expect that the children containers don't get properly cleaned up when the Parent is removed.

Source code:
[Source code](https://github.com/Voulz/Avalonia-TreeViewBug)

![GIF](https://github.com/Voulz/Avalonia-TreeViewBug/blob/master/TreeViewBug.gif?raw=true)

**Comment by grokys** [comment]
Thanks @Voulz - do you think you could try using our [nightly builds](https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed)? There have been quite a few fixes to `TreeView` recently on master.

**Comment by Voulz** [comment]
Hi @grokys , I tried the nightly build on this sample project and on the more complex App that I am making and everything seems to work fine!

On a side note, it took me a while to make the nightly build running, would be good to add that there is a prerelease check box that need to be checked in VS (yeah, took me a while to even see there is such a checkbox that is not in a location I would expect to find it), that I need to target `netcore 3.1` (else `AppBuilder` wasn't found), and I also needed a reference to `Avalonia.Diagnostics` (else `AttachDevTools` wasn't found).

**Comment by grokys** [comment]
Great! Yeah, sorry about the trouble in upgrading to `master`, as you've discovered there have been a couple of breaking changes. For future reference, you can find a list of them [on the wiki](https://github.com/AvaloniaUI/Avalonia/wiki/Breaking-Changes) but looks like that hasn't been updated with the `Avalonia.Diagnostics` change yet. I think needing to target `netcore3.1` is a bug though, we should still work on anything that supports `netstandard2.0`.

Anyway, glad your problem is fixed on master, I will close this issue.
