### ISSUE TITLE
Porting DoubleTappedRoutedEventArgs 

### ISSUE THREAD

**Issue by pr8x** [AvaloniaUI/Avalonia#3756]
The WPF `DoubleTapped` event hands out `DoubleTappedRoutedEventArgs` that allows you to get the current position. Our `DoubleTapped` merely gives a `RoutedEventArgs`. It would be great to port the behavior from WPF.

**Comment by DameonL** [comment]
This is related to issue #3240
A simple approach would be to update the Tapped/DoubleTapped events to use PointerEventArgs rather than RoutedEventArgs in Gestures.cs/InputElement.cs, copying the relevant information from the PointerEventArgs already created and passed to RoutedEventArgs. I can create a pull request for this if you guys would like.

**Comment by maxkatz6** [comment]
I will keep it open for now, because this commit should be reverted once we will be fine with breaking changes
https://github.com/AvaloniaUI/Avalonia/pull/5340/commits/6c608c6d0d67a8da67b030c7b2fe25992811e940
