### ISSUE TITLE
Cannot style slider

### ISSUE THREAD

**Issue by leoshusar** [AvaloniaUI/Avalonia#3807]
Hi, I have a problem with styling slider. I tried multiple selectors and setters and nothing worked.

Here is my last try:
```
<Style Selector="Slider /template/ Border#TrackBackground">
    <Setter Property="BorderThickness" Value="2" />
    <Setter Property="BorderBrush" Value="White" />
</Style>

<Style Selector="Slider /template/ Track">
    <Setter Property="Height" Value="10" />
</Style>

<Style Selector="Slider /template/ Thumb Ellipse">
    <Setter Property="Width" Value="20" />
    <Setter Property="Height" Value="20" />
</Style>
```

and the only things that are working are `BorderThickness` and `BorderBrush`. Thumb is untouched and that track height doesn't work too.
Basically I want to style it like [this](https://i.imgur.com/dHtdoMm.png). Is it anyhow possible?
Thank you!

**Comment by maxkatz6** [comment]
Yes, it's possible,  but you might need to re-create whole template just like you would do in WPF.
Currently Avalonia styles are not powerful enough to allow to override values defined in the template with local value priority.
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Default/Slider.xaml#L27

###### Yes, this issue is old, and most likely not actual anymore. But I just found it, and was able to answer.
