### ISSUE TITLE
ListBox initial selection not scrolled into view

### ISSUE THREAD

**Issue by aguahombre** [AvaloniaUI/Avalonia#4100]
0.9.999-cibuild0008173-beta
I have found a couple of probably related issues with the new selection handling code so I have included them both in this issue report. 

The first issue is that AutoScrollToSelectedItem="True" does not scroll the initial SelectedItem into view when creating the window. Here is a code:

```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450" Height="100" Width="300"
        x:Class="AvaloniaApplication4.MainWindow"
        Title="AvaloniaApplication4">
  <Grid RowDefinitions="*,Auto">
    <ListBox Items="{Binding Items}" SelectedItem="{Binding Selected}" AutoScrollToSelectedItem="True"/>
    <StackPanel Grid.Row="1" Orientation="Horizontal">
      <Button Content="B" Command="{Binding B}" Width="80"/>
      <Button Content="K" Command="{Binding K}" Width="80"/>
    </StackPanel>
  </Grid>
</Window>
```

```
using System.Collections.ObjectModel;
using System.ComponentModel;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace AvaloniaApplication4
{
    public class MainWindow : Window
    {
        public MainWindow()
        {
            AvaloniaXamlLoader.Load(this);
            DataContext = new MyViewModel();
        }
    }

    public class MyViewModel : INotifyPropertyChanged
    {
        private string _selected = "J";
        public event PropertyChangedEventHandler PropertyChanged;

        public ObservableCollection<string> Items { get; } = new ObservableCollection<string>(new string[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L" });

        public string Selected
        {
            get => _selected;
            set { _selected = value; PropertyChanged.Invoke(this, new PropertyChangedEventArgs(nameof(Selected))); }
        }
        public void K() => Selected = "K";
        public void B() => Selected = "B";
    }
}
```
![image](https://user-images.githubusercontent.com/17591364/84241065-d88cbc00-aaf6-11ea-8f75-5f0d6ee00e72.png)
I would expect the ListBox to display with item "J" scrolled into view as this is the initial ```Selected``` value. Manually scrolling the ListBox reveals that item "J" is selected.

The second issue is that by moving the DataContext assignment before the Load displays no initial selection (and does not scroll into view). The rest of the code being identical to above.
```
        public MainWindow()
        {
            DataContext = new MyViewModel();
            AvaloniaXamlLoader.Load(this);
        }
```
![image](https://user-images.githubusercontent.com/17591364/84241723-c9f2d480-aaf7-11ea-85d3-b8df45bfb4d6.png)
I would expect that this would also select item "J" and scroll it into view.

**Comment by grokys** [comment]
Taken a look at these:

## Not scrolling to initial selection

Yeah, this isn't implemented. Question is when this should be done: the selected item can't be scrolled into view until the `ListBox` is added the the visual tree, but the `ListBox` could be added to the visual tree multiple times. It obviously shouldn't scroll to the selected item each time, because then a `ListBox` in e.g. a `TabControl` would lose its scroll position when switching tabs. On the other hand, if the selected index is changed after it's been shown the first time and then hidden: the next time it's shown it _should_ be scrolled.

Need to think about this a bit.

## Assigning DataContext after load

This is happening because you have a two-way binding to `SelectedItem`. What happens is:

- The `ListBox` is created, the `SelectedItem` binding is set up
- The binding fails because there's no `DataContext`, so `ListBox.SelectedItem` is null
- Because it's a two-way binding, `null` is written back to your view model
