### ISSUE TITLE
Failed to run Wizard

### ISSUE THREAD

**Issue by Toorah** [AvaloniaUI/Avalonia#4158]
I was following the tutorial at: https://avaloniaui.net/docs/tutorial/creating-a-view
When it asked me to create a new item I did as asked, however I get the following error when doing so:
![image](https://user-images.githubusercontent.com/8051137/85347393-b46aab00-b4f8-11ea-9b95-7b55933a6cd2.png)
this is then followed by:
![image](https://user-images.githubusercontent.com/8051137/85347424-c5b3b780-b4f8-11ea-90c7-84de74886597.png)

Win 10 x64
VS Community 2019 V16.6.2
.NET Framework V4.8.03752
Avalonia v0.9.10

**Comment by Toorah** [comment]
Additional Info:
I managed to make it work somehow, but a few things I've observed:

When I first create a new Item User Control, it only shows me the *.xaml.cs file, without the actual XAML:
![image](https://user-images.githubusercontent.com/8051137/85351172-60b18f00-b503-11ea-91c9-8ea00569d68d.png)

In the CSPROJ I then found these lines:
![image](https://user-images.githubusercontent.com/8051137/85351216-77f07c80-b503-11ea-97ad-f483fb72ca94.png)

By removing these lines, the XAML file became visible, though the structure is still not correct (as in, the *.xaml.cs is not _under_ the *.xaml file)
![image](https://user-images.githubusercontent.com/8051137/85351290-a9694800-b503-11ea-8412-2163a82ee3e9.png)

**Comment by grokys** [comment]
Hi @Toorah, sorry about these problems.

Yeah recent VS updates have completely broken our extension unfortunately. We're planning to move to our own file extension (see https://github.com/AvaloniaUI/Avalonia/issues/4102) but this is going to take a little bit of time.

I think your solution was the correct one, the `*.xaml.cs` file not being under the `.xaml` file should be fixed with a VS restart if I'm not mistaken.
