### ISSUE TITLE
Implement TextChanged event for TextBox

### ISSUE THREAD

**Issue by KvanTTT** [AvaloniaUI/Avalonia#418]

**Comment by grokys** [comment]
I've looked into this, but the `TextChanged` event is quite complex and a lot of it relates to rich text edit controls, which we don't have yet. For this reason I'm going to delay implementing this.

If you want something similar for now, just do:

    textBox.GetObservable(TextBox.TextProperty).Subscribe(text => { /* Will be called with Text each time it's changed */ });

**Comment by mat1jaczyyy** [comment]
What's the status on this?

**Comment by mat1jaczyyy** [comment]
My use case is running custom input validation while the user is typing. I also want to deny the input if it's determined invalid, restoring the TextBox to the state before the Text has Changed. I can store the old value in a string outside the TextBox for this purpose, and change the Text Property from inside my handler method.

However, if I attempt to use the Observable workaround above, I'm unable to set the Text from inside the subscribed method (I've set it, but it does not update). This is possible in WPF with the TextChanged event.

**Comment by worldbeater** [comment]
@mat1jaczyyy worth looking at [ReactiveUI](https://github.com/reactiveui) framework and the MVVM pattern. Using the `Binding` markup extension with `TwoWay` binding mode and `WhenAnyValue` will definitely do what you are willing to achieve, see [an example](https://github.com/worldbeater/Camelotia/blob/master/Camelotia.Presentation/ViewModels/HostAuthViewModel.cs#L25). For complex scenarios which support validation messages take a look at [ReactiveUI.Validation](https://github.com/reactiveui/ReactiveUI.Validation).

**Comment by mat1jaczyyy** [comment]
I've managed to make my use case work by resetting the Text via a Dispatcher Invoke, but thanks for the suggestions!

**Comment by robloo** [comment]
This one surprised me quite a bit. TextChanged is such a fundamental event it really needs to be added ASAP. It looks like it's required for IME so I imagine it will come sooner rather than later.

>I've looked into this, but the TextChanged event is quite complex and a lot of it relates to rich text edit controls, which we don't have yet. For this reason I'm going to delay implementing this.

For IME, yes it's a bit complex. However, for the initial implementation I don't understand why this is difficult. The control knows when it is changing its Text property. Just re-route all code changing the Text property internally to go to an OnTextChanged method that updates the property and raises the event at the same time.

**Comment by maxkatz6** [comment]
> TextChanged is such a fundamental event it really needs to be added ASAP

Not sure about IME, but usually it's more than enough to subscribe on property changed event. Or get observable from the event directly. It will do the same what you have described above.

**Comment by robloo** [comment]
> Not sure about IME, but usually it's more than enough to subscribe on property changed event. Or get observable from the event directly. It will do the same what you have described above.

Yes, I know. But we've all become accustomed to a TextChanged event since VB6 or so. Loosing it is a shock coming over from other frameworks. Reactive programming concepts are also overkill for something quite simple. Property changed listener is more straightforward, still, seems like a good set of text events is better.
