### ISSUE TITLE
TabControl styling not completely possible

### ISSUE THREAD

**Issue by floppyman** [AvaloniaUI/Avalonia#4232]
### Issue
Between the TabStrip and TabContent of the TabControl there is a line of 4 pixels which cannot be removed, the gap exists in both the light and dark theme.

### Thing tried to fix the issue

- Setting the margin and padding to 0 on TabControl and all TabItem
- Using different style selectors to try and target the element with the 4 pixel top margin
- TabControl > Border > DockPanel /template/ ContentPresenter#PART_SelectedContentHost
- TabControl DockPanel /template/ ContentPresenter#PART_SelectedContentHost
- DockPanel /template/ ContentPresenter#PART_SelectedContentHost
- DockPanel /template/ ContentPresenter

But non of the options with success.

Visually on the tab control in the documentation it does not have any gap: http://avaloniaui.net/docs/controls/tabcontrol

### Visual example of the Gap under TabItems in the TabStrip

![2020_07_06_12_51_02_Window](https://user-images.githubusercontent.com/932288/86586067-9fc1f480-bf87-11ea-81f9-3793ef7eaf96.png)

As you can see on the picture, there is a 4 pixel gap under the gray tab item, as confirmed by the Visual Tree, however the styling does not allow for this value to be changed.

It might be me that has overseen something, however i would appreciate any options to try an fix this.
It is minor, but nevertheless style breaking.

**Comment by VisualMelon** [comment]
The default theme specifies the padding for different values of `TapStripPlacement`: you can override it by providing a selector that is as specific (or more) specific, e.g. what I did was:

    <Style Selector="TabControl[TabStripPlacement=Bottom]">
      
      <Setter Property="Padding" Value="0"/>
    </Style>

Naturally, this needs to be qualified for each position, as the theme qualifies it for each position in order to place the padding on the correct edge of the tab control: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Default/TabControl.xaml.

**Comment by floppyman** [comment]
Thank you, That worked perfectly. 👍 
I knew i was missing something obvious. :-)
