### ISSUE TITLE
Unable to bind an attached property in XAML.

### ISSUE THREAD

**Issue by SparkyTD** [AvaloniaUI/Avalonia#4283]
I am trying to use a binding in an attached property, but the setter function doesn't get called. If I just put a constant string instead of the binding, it works.

Here's the class with the attached property:
```
public class MyClass // (namespace ns)
{
    public static readonly StyledProperty<string> TestProperty = 
        AvaloniaProperty.RegisterAttached<MyClass, Control, string>("Test");

    public static void SetTest(Control control, string value)
    {
        Console.Out.WriteLine("SetTest: " + value);
    }
}
```

And this is how I'm trying to use it:
```
<TextBlock 
        Text="{Binding SomeProperty, ElementName=window}" 
        ns:MyClass.Test="{Binding SomeProperty, ElementName=window}"/>
```
where `SomeProperty` is a valid property with a value.

I would expect the `SetTest` function to be called, but nothing happens. If I change the `{Binding}` expression to a string, the function is called as expected.

I'm using Avalonia 0.10.0-preview1.
This is a simple project that reproduces the issue: [AttachedBindingBug.zip](https://github.com/AvaloniaUI/Avalonia/files/4914589/AttachedBindingBug.zip)

**Comment by grokys** [comment]
Bindings don't call the setter methods on attached properties, like they don't call the setters on regular Avalonia properties because the setters can only be used to set the local value.

This is the same as other XAML frameworks (for which I'll add a few links below) so, unless I'm misunderstanding will close.

https://stackoverflow.com/questions/43319127/setter-of-bindable-property-never-fires
https://stackoverflow.com/questions/4225373/setters-not-run-on-dependency-properties
https://stackoverflow.com/questions/2568860/why-attached-property-set-and-get-static-methods-are-not-called-in-xaml
