### ISSUE TITLE
Compiled bindings can't infer item type for ItemsRepeater

### ISSUE THREAD

**Issue by jp2masa** [AvaloniaUI/Avalonia#4292]
The `AvaloniaXamlIlDataContextTypeTransformer` defines that a control that displays items implements `IItemsPresenterHost`, but `ItemsRepeater` doesn't, so inference doesn't work.

https://github.com/AvaloniaUI/Avalonia/blob/d2cc57a6bd84d2d31a1ea1ba66ad7b09df26567b/src/Markup/Avalonia.Markup.Xaml/XamlIl/CompilerExtensions/Transformers/AvaloniaXamlIlDataContextTypeTransformer.cs#L80-L82

## Suggestion

Not sure if it would bring some problems, but matching with the `Items` property would work, i.e. replace this:

https://github.com/AvaloniaUI/Avalonia/blob/d2cc57a6bd84d2d31a1ea1ba66ad7b09df26567b/src/Markup/Avalonia.Markup.Xaml/XamlIl/CompilerExtensions/Transformers/AvaloniaXamlIlDataContextTypeTransformer.cs#L82

with this:

```cs
if (parentObject != null && parentObject.Type.GetClrType().GetAllProperties().Any(p => p.Name == "Items"))
```

Other alternatives would be introducing a new interface or use some attribute, but I think it would bring more problems.

**Comment by jkoritzinsky** [comment]
I don't like the idea of assuming that every control that has an `Items` property displays those items in its content. I'd prefer the interface route (which is why I picked `IItemsPresenterHost` initially since it covered all cases at the time) since that way, the behavior is more controllably opt-in/opt-out-able.
