### ISSUE TITLE
Segmentation fault with custom skia control

### ISSUE THREAD

**Issue by merschformann** [AvaloniaUI/Avalonia#4319]
I implemented a custom skia control like shown here: https://github.com/AvaloniaUI/Avalonia/blob/release/0.9.9/samples/RenderDemo/Pages/CustomSkiaPage.cs

Currently, I am experiencing segmentation fault errors when running it on Ubuntu 20.04 (nvidia 440 driver). The same code works fine on Windows (Windows 10, same machine).
I put together a minimal example suffering from these issues for reproduction here: https://github.com/merschformann/avalonia-skia-minimal (reproduction steps in readme)

Am I doing something wrong or is this a bug? Any help would be highly appreciated, as I would love to use avalonia and the more direct rendering approach for my project.

Thanks for your support!
And in general, thanks for your great work and all the effort!

P.S. What I intend to do is somewhat shown here: https://github.com/merschformann/avalonia-move-visualizer

**Comment by kekekeks** [comment]
1) can't reproduce with Intel GPU using your example
2) CAN reproduce with `primusrun` with `NVIDIA 430.26` using your example
3) can't reproduce with `primusrun` with `NVIDIA 430.26` using our RenderDemo.

The crash seem to happen in NVIDIA driver.

**Comment by kekekeks** [comment]
Crash happens inside SKCanvas::Flush

**Comment by merschformann** [comment]
I would have preferred to do it in the samples project of avalonia itself, but it does not build for me right now (following these steps: https://github.com/AvaloniaUI/Avalonia/blob/master/Documentation/build.md - error MSB4018: The "GenerateExtensionHeaders" task failed unexpectedly).

Instead, I copied the `CustomSkiaPage` into my minimal example. It works first, but exposes the same behavior when only adding the following line: https://github.com/merschformann/avalonia-skia-minimal/blob/5bf1f4231396ca7a28aac6a686f5ec5e511f8010/Pages/CustomSkiaPage.cs#L91 (comment out the line to see it working, `DrawCircle` behaves the same).
Except for the one line the example matches the original `CustomSkiaPage`.
It seems to be only about certain shapes or angles.

However, is this a problem that should be reported to https://github.com/mono/SkiaSharp instead?

Again, thank you for the support! I would really love to see this fly. =)

**Comment by kekekeks** [comment]
>However, is this a problem that should be reported to https://github.com/mono/SkiaSharp instead?

Probably. I couldn't repro it with OpenTK though.

**Comment by merschformann** [comment]
I directly reported it to nvidia (see here: https://forums.developer.nvidia.com/t/getting-a-segmentation-fault-in-libnvidia-glcore-so-440-100-on-ubuntu-20-04/142538/1 )

I tested a bit more. It does occur for me with a range of nvidia drivers on Ubuntu 20.04 (including the latest 450.57 release).
It does **not** occur with the nouveau drivers or on Windows 10 though.
As there seems to be different behavior between drivers, I hope nvidia linux driver support is the correct address to shed some light on it.

Thanks again!

**Comment by kekekeks** [comment]
Please, check if https://github.com/AvaloniaUI/Avalonia/pull/4424 helps.

**Comment by merschformann** [comment]
I tested the previously failing functionality from within the `CustomSkiaPage` example. It seems to work perfectly now.

I would like to check the same again (before finally confirming success) after there is a release I can target from my main project. Just in case I left some functionality untested. However, I am pretty sure this resolves the problems I have been having.

Thank you very much for your support. This really helps me a lot! :)

**Comment by capdj** [comment]
Tested this on my app - using the latest cibuild does indeed fix the problem one of my users had, where their (Linux, NVidia) system would regularly crash out with segfaults. So that is good!

Unfortunately, another one of my users, who was previously having no problems, is now experiencing regular crashes - that user is running an Intel GPU on Linux. They're seeing crashes with both:

[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has
not been called
[xcb] Aborting, sorry about that.
VTableAvalonia: ../../src/xcb_io.c:259: poll_for_event: Assertion
`!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)

and just

Segmentation fault (core dumped)


That said: This *may* not be due to the #4424 fix - I upgraded my app from cibuild 8766 to 9704 in order to get this fix, so of course something else could have changed in between, I suppose. But of course it's a little suspicious that this changes the way the rendering works with threads, and then a user immediately gets a graphics crash that mentions threading :(

Searching online suggests that this xcb/xlib issue shows up in all sorts of apps, and does look like a bug in xcb/xlib, so it's unlikely to be Avalonia actually doing anything wrong. But as with the NVidia crashes, if it's possible to work around it so we can run Avalonia apps reliably that would be ideal...

Since I haven't seen this on my PC, I can't test any suggested workarounds easily, but I can get my testers to try things out - will take a day or two to do so, however.

**Comment by merschformann** [comment]
I moved to _0.10.0-preview3_ and everything seems to be working fine now.
Since this particular problem seems to be resolved, I will close the issue.

I would suggest to move above mentioned problems into a new issue @capdj ?

Again, many thanks for your assistance! This helped me out a lot. :)
