### ISSUE TITLE
Incorrect wrapping in textbox

### ISSUE THREAD

**Issue by CreateLab** [AvaloniaUI/Avalonia#4327]
![image](https://user-images.githubusercontent.com/33497292/87880315-74182300-c9f9-11ea-8f4a-78c170eedfb6.png)
![image](https://user-images.githubusercontent.com/33497292/87880317-77131380-c9f9-11ea-9723-e5b9893f3d2d.png)

I set auto in grid definition, but grid "eats" char 'e' in next line, but as I think Window should be longer

**Comment by danwalmsley** [comment]
@CreateLab what version are you using?

**Comment by CreateLab** [comment]
I check it in 9.6.1 & 10 prev with old default theme. But with new theme all is ok.

**Comment by danwalmsley** [comment]
@Gillibald any idea whats wrong with the default theme here?

**Comment by jtbrower** [comment]
### TextBox is not wrapping at All
_Before I give the details of this problem, I just want to say that I have high hope for Avalonia and my journey from WPF to Avalonia has been enjoyable.  I have a lot more working here than I did over with WinUI._

I have attempting to use the TextBox control and no matter what I place it in or whether I have the width of it set, it will not wrap the text.  Since this is the primary control for data entry, I see this as a high priority issue that needs addressed.  For any end user entering paragraphs into a TextBox, it makes it tough to read.

Below you will find both a sample program and a screenshot.  The sample program's Main Window's xaml is commented with details.  Please note that the sample program is using the Default libraries that are included with the Visual Studio Avalonia Template.  However, I first noticed the problem using 0.10.0-preview5.

### System Details
Avalonia 0.9.11 (In Test App) but in my own application I use Avalonia version 0.10.0-preview5 
Windows 10 Pro for WorkStations, Build 19041.vb_release.191206-1406

### Here is a Sample Program
Reminder, the sample app is using the default versions from the Visual Studio template, but the problem also exists in the latest preview version.

[TextBoxTextWrapProblem.zip](https://github.com/AvaloniaUI/Avalonia/files/5180445/TextBoxTextWrapProblem.zip)

### Screenshot
![image](https://user-images.githubusercontent.com/3423706/92337266-16559e00-f06e-11ea-89c0-d743b464531c.png)

**Comment by jp2masa** [comment]
It probably doesn't wrap because of https://github.com/AvaloniaUI/Avalonia/issues/4594#issuecomment-685134360.

**Comment by jtbrower** [comment]
@jp2masa 

> It probably doesn't wrap because of [#4594 (comment)](https://github.com/AvaloniaUI/Avalonia/issues/4594#issuecomment-685134360).

Thank you very much, that's exactly the fix I needed.

**Comment by ThereGoesMySanity** [comment]
@CreateLab UseLayoutRounding="False" might fix this.

**Comment by Gillibald** [comment]
Fixed in master
