### ISSUE TITLE
Fluent Button FontSize is ignored

### ISSUE THREAD

**Issue by adirh3** [AvaloniaUI/Avalonia#4353]
`                     <Button
                            FontSize="1"
                            Height="30"
                            Width="30"
                            Content="Test"
                            />
                        <Button
                            FontSize="30"
                            Height="30"
                            Width="30"
                            Content="Test"/>`
![image](https://user-images.githubusercontent.com/27368554/88312765-3712a000-cd1b-11ea-8514-97b7ea9a3762.png)
Seems like FontSize is not changing the size of Content for Buttons when using the Fluent theme

**Comment by FoggyFinder** [comment]
works fine to me. Do you use some non-standard font?

**Comment by adirh3** [comment]
> works fine to me. Do you use some non-standard font?

My bad, just noticed the issue was because of this Style:
` <Style Selector="TextBlock">
                <Setter Property="FontSize" Value="12" />`
Shouldn't the style get ignored if the FontSize is specified in the control?

**Comment by dlukach** [comment]
Hey can we reopen this issue. I believe a standard control should overwrite a global style. The problem is, the textblock in the button's content control is isolated from the button itself, so when setting a TextBlock global font style, the button gets locked into the same font no matter what its font property is set for the button. A quick workaround is to do add a template binding to the button.xaml TextBlock.FontSize in the content control. I feel this would benefit many users who define global default styles.
