### ISSUE TITLE
segmentation fault on mac in updateLayer

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#4366]
I've had a couple of mac users report crashes using 0.9.999-cibuild0009369-beta 
here is a .crash file

[SparkSDR_2020-07-23-073709_Js-MacBook-Pro-15.zip](https://github.com/AvaloniaUI/Avalonia/files/4975982/SparkSDR_2020-07-23-073709_Js-MacBook-Pro-15.zip)

**Comment by kekekeks** [comment]
https://github.com/AvaloniaUI/Avalonia/blob/master/native/Avalonia.Native/src/OSX/window.mm#L1313 - it seems that `_parent` is null here.

Are you, by chance, closing your window from a dispatcher callback with default priority?  
It can and will crash on OSX in certain scenarios, since we are running jobs with >=DispatcherPriority.Render priority from certain OSX callbacks.

**Comment by ahopper** [comment]
I'm not aware any windows are being closed when it crashes unless they are tooltips, no other windows are opened by my app when running normally.

**Comment by ahopper** [comment]
There are also the windows used by dropdowns, none are closed explicitly in my code.  I'm thinking of releasing a version using OverlayPopups on mac, would that help confirm the cause and be a work around?

I can't make it crash on my mac but that is a very old 2 core machine so may reduce the chance of odd timing issues.

**Comment by ahopper** [comment]
No reports of this recently
