### ISSUE TITLE
Selection model throws exception in carousel when all items are removed

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#4409]
https://github.com/AvaloniaUI/Avalonia/tree/repro/carousel-not-materializing-content

Repro here on carousel page... press the red squares to remove all 3 tabs...with debugger captureing all exceptions... you will see its tries to access element 0 of an empty array / list.

This causes carousel to end up not materializing the content.

Iv attempted unit tests on both selectionmodel and carousel and failed.

@grokys

**Comment by grokys** [comment]
Seems to be called by event ordering. By the time the auto-selection runs, the `ItemsSourceView.OnItemsSourceChanged` event hasn't yet been fired, meaning `ItemsSourceView._cachedSize` isn't updated to the new size of the underlying collection. It's never been clear to me why `ItemsSourceView` caches the size; I suspect it's due to the performance characteristics of WinRT and can be removed in Avalonia.
