### ISSUE TITLE
(Tutorial) ReactiveCommands in ViewModel constructor don't work

### ISSUE THREAD

**Issue by Rhywun** [AvaloniaUI/Avalonia#4475]
I am following the tutorial on macOS 10.15.5 and .NET Core 3.0. All is well until the [final page](http://avaloniaui.net/docs/tutorial/adding-new-items-2) which adds the functionality for the OK and Cancel buttons in the constructor of the AddItemViewModel class. There are two problems upon running:

1. The "OK" button remains disabled when I enter text in the Description field.
2. The "Cancel" button results in a blank window instead of returning to the TodoListView.

![Screen01](https://user-images.githubusercontent.com/1157174/89887224-e6fd5f80-db9b-11ea-9780-7c96a42f94f8.png)

Repro [here](https://github.com/Rhywun/avalonia-todo).

Thanks

**Comment by FoggyFinder** [comment]
1. You wrote `Command="{Binding OK}"` instead of `Command="{Binding Ok}"`

https://github.com/Rhywun/avalonia-todo/blob/master/Views/AddItemView.xaml#L13

2. You didn't initialize `List` property

`Content = new TodoListViewModel(db.GetItems());`

while it should be

`Content = List = new TodoListViewModel(db.GetItems());`

https://github.com/Rhywun/avalonia-todo/blob/master/ViewModels/MainWindowViewModel.cs#L14

**Comment by Rhywun** [comment]
Thank you!! Everything works now.

Ugh I remember typing in #2 and I thought it was a misprint :)
That kind of double assignment rubs me the wrong way.

Might I suggest providing the source code for the tutorial on the website? I didn't find it in the framework's samples/ directory either. It might help others by providing a way to diff any changes.

**Comment by rstm-sf** [comment]
Hello! Link is already present:

> You can find the code for the completed application [here](https://github.com/grokys/todo-tutorial).
https://avaloniaui.net/docs/tutorial/

**Comment by Rhywun** [comment]
Great, thanks! I missed it.

Closing

**Comment by FoggyFinder** [comment]
> Thank you!! Everything works now.

Happy to help. Btw, there are also places where you can ask Qs about Avalonia:

* Chat in gitter: https://gitter.im/AvaloniaUI/Avalonia

* Chat in discord: https://aka.ms/dotnet-discord

* Ask on SO: [avalonia](https://stackoverflow.com/questions/tagged/avalonia)

* Ask on TopAnswers: [C#](https://topanswers.xyz/csharp)

* Maybe even on recently created [CoDidact.Software Development](https://software.codidact.com) 

First two are probably preferable since they have "official" (mention in ReadMe) support.

I do think it would better than raise issues especially in case of something simple. Avalonia has reached the good shape and answering questions is area where community can help easily.

To emphasize: this is only my personal position and maintainers may think differently. 

My arguments are the following:

* Questions distract from working on fixing bugs, implementing new features etc.

* It might be annoying for watchers to receive notifications about something simple like "WebView ??" again and again.

* Sometimes issues don't recive any response anyway

* and even when the answer is provided issue is not always marked as "closed" therefore reports about possibly crucial bugs go down and down.

**Comment by Rhywun** [comment]
"Chat" is not my favorite format but I will take it under consideration. Thanks
