### ISSUE TITLE
Designer fails with non-public event handlers.

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#4480]
Currently the designer needs event handlers to be public in order for them to be seen. If you use non-public event handler methods, the code works at runtime, only the designer fails.

**Comment by kekekeks** [comment]
That happens because we are emitting a separate assembly using System.Reflection.Emit rather than patching the existing one.

A potential workaround would be to emit [undocumented `IgnoresAccessChecksTo` attribute](https://www.strathweb.com/2018/10/no-internalvisibleto-no-problem-bypassing-c-visibility-rules-with-roslyn/)  on our dynamic assembly.

**Comment by rstm-sf** [comment]
Is this issue outdated already?

**Comment by kekekeks** [comment]
Was fixed by #4985
