### ISSUE TITLE
Unexpected behavior of styles

### ISSUE THREAD

**Issue by Takoooooo** [AvaloniaUI/Avalonia#4490]
This works for 0.9.12 and for last master also.
If ill place styles in this order 
![image](https://user-images.githubusercontent.com/53405089/90320132-b4aa8400-df46-11ea-90fc-435d643de89a.png)
only last style will work,but if ill reorder them as in screenshot 
![image](https://user-images.githubusercontent.com/53405089/90320143-e15e9b80-df46-11ea-8f5f-4fe0c58011c8.png)
it would work without any issues. @worldbeater assumed what pressed has higher priority,pressed also calls pointerover and because of that it has higher priority,but i think clearer would be to make it work dont relaying on order(as it works at UWP\WPF).
gist to give it a try https://gist.github.com/Takoooooo/0a423cc8963a513d7cc82302a8cbb1b7

**Comment by maxkatz6** [comment]
I believe it is expected for CSS styling.
When you press button, it should have both :pointerover and :pressed classes. And because your :pointerover is defined after :pressed, it overrides the value.

In HTML+CSS it works in same way. With stylesheet below button in pressed state will be blue instead of red, because mouse hovers it.
```css
button:active { background: red }
button:hover { background: blue }
```
