### ISSUE TITLE
Direct Property GetValue does not return expected value

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Avalonia#4509]
In this code
https://github.com/AvaloniaUI/Avalonia/blob/f80737aa01a8232bcc8623aeb0e8aa65c4f854b4/tests/Avalonia.Base.UnitTests/AvaloniaObjectTests_Metadata.cs#L62-L76

if you create an instance of Class 1, the value of the Direct property will be null instead of the expected value "foo".

**Comment by grokys** [comment]
This is expected behavior: direct properties can be thought of as simply adding metadata to standard CLR properties, and if you want a CLR property to have a default value then you just need to set the default value of the field. so you should be doing:

```
private string _direct = "foo";
```

Did yo notice that for styled properties it's called "DefaultValue" whereas for direct properties it's called "UnsetValue"?

This is because the value in the case of direct properties _it's not intended to supply a default value_. The unset value is only used when calling `ClearValue` with a direct property (i.e. unsetting the value).

**Comment by workgroupengineering** [comment]
Thanks for the clarification. If I wanted to create a read-only property like WPF what should I do?

**Comment by grokys** [comment]
If you want to create a read-only property you can create a direct property but supply only a getter. You can see an example here:

https://github.com/AvaloniaUI/Avalonia/blob/cbd5a4c59afd83c7deccbb88f7a8ebd7192964fb/src/Avalonia.Visuals/Visual.cs#L30-L31
