### ISSUE TITLE
Broken ComboBoxItem border

### ISSUE THREAD

**Issue by kaminova** [AvaloniaUI/Avalonia#4768]
Right border of ComboBoxItem is broken when item's content is too long:
![cbbug](https://user-images.githubusercontent.com/45092470/94548483-13a32e80-0251-11eb-8b20-061b0e07b18b.gif)

Repro:
  ```
<ComboBox SelectedIndex="0">
      <ComboBox.Styles>
        <Style Selector="ComboBox /template/ Popup#PART_Popup">
          <Setter Property="Width" Value="{Binding $parent.Bounds.Width}" />
        </Style>
        <Style Selector="ComboBoxItem">
          <Setter Property="BorderBrush" Value="Red" />
          <Setter Property="BorderThickness" Value="1" />
        </Style>
      </ComboBox.Styles>
      <ComboBoxItem>ComboBoxItem ComboBoxItem ComboBoxItem</ComboBoxItem>
      <ComboBoxItem>ComboBoxItem ComboBoxItem ComboBoxItem</ComboBoxItem>
      <ComboBoxItem>ComboBoxItem ComboBoxItem ComboBoxItem</ComboBoxItem>
    </ComboBox>
```

**Comment by pr8x** [comment]
TBH I think the default width of the `ComboBox` Popup should match its width.

**Comment by kaminova** [comment]
then the popup will change it's width while scrolling when `VirtualizationMode` is on, that's not good

**Comment by maxkatz6** [comment]
If you are setting Width property that can be too small, you also need to set TextBlock TextWrapping as well.

**Comment by grokys** [comment]
The problem seems to be that you're explicitly setting the width of the `Popup` to be the width of the `ComboBox` in a style

```
      <Style Selector="ComboBox /template/ Popup#PART_Popup">
        <Setter Property="Width" Value="{Binding $parent.Bounds.Width}" />
      </Style>
```

If you remove this style then the dropdown displays at the correct width:

![image](https://user-images.githubusercontent.com/1775141/94687830-11ae9d80-032d-11eb-882c-c0724b9e4999.png)

**Comment by grokys** [comment]
It appears that the problem is that the border gets cut off when the combo box popup width is limited. This actually seems to be caused by a bug in the `ComboBox` template, in that the `ScrollViewer` in the `Popup` has its `HorizontalScrollBarVisibility` property set to `Hidden` instead of `Disabled` and so is giving infinite width to the `ComboBoxItem`s.
