### ISSUE TITLE
It's necessary a "selectionchanged" pseudoclass

### ISSUE THREAD

**Issue by PieroCastillo** [AvaloniaUI/Avalonia#4782]
Well, I'm going to tell you my opinion, I make controls and styles for avalonia, and I'd want to execute an animation when the control (for example, the TabControl) changes its selected item or content, really, I think that would be helpful.

**Comment by maxkatz6** [comment]
I am not sure about idea of pseudoclasses for events.
If you need to execute animation you can use :selected and :not(:selected) selectors.
So, animation will start in moment of switching between styles with these two selectors.

**Comment by PieroCastillo** [comment]
> I am not sure about idea of pseudoclasses for events.
> If you need to execute animation you can use :selected and :not(:selected) selectors.
> So, animation will start in moment of switching between styles with these two selectors.

mmm, I already tried it and doesn't work as I want, what I what is execute an animation in a control with ItemsPresenter and ContentPresenter, for example the TabControl

**Comment by danwalmsley** [comment]
Pseudoclasses are for current state, not for events...

you probably need to use transitions, to go between 1 state or the other... i.e.

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Fluent/TitleBar.xaml#L41-L52


It maybe that your animation requirements otherwise are beyond the current capabilities of Avalonia...

A new composition engine is currently being built that matches UWPs composition apis, and this allows for much more complex animations.

Can you describe an example animation that you would like?

**Comment by maxkatz6** [comment]
@PieroCastillo I think animation should be started, when Content was changed, not when tab selection was changed.
Also take a look at this https://github.com/AvaloniaUI/Avalonia/pull/4790

**Comment by PieroCastillo** [comment]
> @PieroCastillo I think animation should be started, when Content was changed, not when tab selection was changed.
> Also take a look at this #4790

yes , you're right, but I wanna that with the content control and/or content presenter

**Comment by worldbeater** [comment]
There is also a `TransitioningContentControl` that is a regular `ContentControl`, but can animate the `.Content` when it changes.
