### ISSUE TITLE
Cannot select template element of MenuItem

### ISSUE THREAD

**Issue by lprc** [AvaloniaUI/Avalonia#4804]
Hi, I want to change the color of the rightArrow of a MenuItem:

![rightArrow](https://files.gitter.im/547b1838db8155e6700d97d7/ucJe/grafik.png)

The style is defined in the default Theme as follows:

https://github.com/AvaloniaUI/Avalonia/blob/0d6f5fb6c94e3f4a56756bb97038d15e1ae8a304/src/Avalonia.Themes.Default/MenuItem.xaml#L54-L59

and it is altered in the same place e.g. like this:
https://github.com/AvaloniaUI/Avalonia/blob/0d6f5fb6c94e3f4a56756bb97038d15e1ae8a304/src/Avalonia.Themes.Default/MenuItem.xaml#L141-L143

Based on my foundings I tried to change the color in my app like this:
```
<Style Selector="MenuItem /template/ Path#rightArrow">
	<Setter Property="Fill" Value="Green"/>
</Style>
```

However that does not seem to work. Is that a bug or did I do something wrong here? Thanks!

**Comment by maxkatz6** [comment]
It is because "Fill" is set in MenuItem template with "LocalValue" priority. And you can't override that priority with a style.
See: https://github.com/AvaloniaUI/Avalonia/issues/2789

As a workarounds:
1. Use Fluent theme (it has same issue with priorities, but "Fill" isn't hardcoded there.
2. Set custom value for ThemeForegroundBrush per control. However it will affect all children that use this resource in this control. Something like:
```xaml
<Menu>
    <Menu.Resources>
       <SolidColorBrush x:Key="ThemeForegroundBrush" Color="Green" />
    </Menu.Resource>
</Menu>
```
3. Redefine template.

**Comment by maxkatz6** [comment]
For now I am closing this issue, because we have another for that problem - https://github.com/AvaloniaUI/Avalonia/issues/2789
