### ISSUE TITLE
KeyUp is not triggered for e.g. Space and Alt Keys

### ISSUE THREAD

**Issue by lprc** [AvaloniaUI/Avalonia#4821]
I have a Button which lets the user set a hotkey. When it's pressed, a KeyUp-Listener is attached to it. With the first KeyEvent it is released again. However the listener is not triggered for e.g. the Space and the Alt Keys. It seems like, as usually in windows applications, the Alt key shows menu hotkeys and focuses the first menu item and the space key issues a button press which has focus. 

Is there a way to disable this behaviour (and maybe restore it after my listener has finished)? I want my listener to have the highest priority regarding KeyUp events while actually being attached to the button.

I also tried to attach the listener to the main window instead of the button with no appeal. Thanks!

Edit:
Code-behind:
```
public void SetKey(object sender, RoutedEventArgs e)
        {
            // Waits for input hotkey
            keyButton.Content = "Waiting for input...";

            // add keylistener
            if (!IsListening)
                keyButton.KeyUp += changeKeyListener;
        }

        private void changeKeyListener(object sender, KeyEventArgs e)
        {
            Key = Util.KeyToChar(e.Key, e.KeyModifiers);
            IsListening = true;
            if (Key == '\x00')
                keyButton.Content = "Invalid char. Try again.";
            else
            {
                // remove listener
                keyButton.KeyUp -= changeKeyListener;
                IsListening = false;
                keyButton.Content = Key.ToString();
            }
        }
```
XAML:
```
<Button Name="btnKey" Click="SetKey">
	Press to change key.
</Button>
```

**Comment by Enigmatrix** [comment]
This is because of the KeyDown event for Button consuming the event by setting Handled=true. https://github.com/AvaloniaUI/Avalonia/blob/acc9f03e34d12ac6f3f1a2196b2aa14d8d135a73/src/Avalonia.Controls/Button.cs#L281-L300

To put it another way, if you have `<Button><TextBox/></Button>`, you can never enter spaces into the text box (but you can enter other characters), spaces trigger the button press instead. Is it possible to set the event as Handled=false in future versions of Avalonia? The above example works in WPF out-of-the-box. While we can subclass Button and override the `OnKeyDown` method, it's harder to do it when it's 3 layers deep inside a style.
