### ISSUE TITLE
FocusManager.Focus(null) does not clear focus

### ISSUE THREAD

**Issue by pr8x** [AvaloniaUI/Avalonia#4906]
Calling `FocusManager.Focus(null)` will not correctly clear the focus:

[repro_focusmanager_focus_null.patch.txt](https://github.com/AvaloniaUI/Avalonia/files/5416068/repro_focusmanager_focus_null.patch.txt)

Calling `FocusManager.SetFocusedElement(Scope, null)` seems to work. Not sure what is intended here actually. Should the focus be entirely clearable?

**Comment by grokys** [comment]
Happens because setting the focused element to `null` causes the focus manager to try to set focus to the topmost focus scope:

https://github.com/AvaloniaUI/Avalonia/blob/4003b1e40d2c17bb51ed48c58189da0dc33d8817/src/Avalonia.Input/FocusManager.cs#L75-L76

However in this case, we're already in the topmost focus scope, so we probably need a check for `scope != Scope` there.
