### ISSUE TITLE
Unable to use a ContextMenu with absolute position

### ISSUE THREAD

**Issue by FG-rgb** [AvaloniaUI/Avalonia#4911]
It isn't possible to position a ContextMenu absolute on a screen.
There is **always** a relative position to the owner/parent of it.
In WPF it is possible to position absolute, e.g.:
```
ContextMenu.Placement = PlacementMode.AbsolutePoint;
ContextMenu.HorizontalOffset = cursorPosition.X;
ContextMenu.VerticalOffset = cursorPosition.Y;
ContextMenu.IsOpen = true;
```

**Comment by kekekeks** [comment]
That is intended since absolute positioning isn't exactly cross-platform. What exactly do you need it for?

**Comment by FG-rgb** [comment]
I try to implement a NotifyIcon in SystemTray, with a ContextMenu.
The ContextMenu should be open at the position of the NotifyIcon, but that's actually not possible.
I'm working on a Wrapper ContextMenuWindow, but it's not very ellegant...

**Comment by kekekeks** [comment]
Well, what you are trying to show is not a popup (which is something attached to a parent window).

You can probably just show a borderless window and manually enable WS_POPUP style with SetWindowLong

**Comment by FG-rgb** [comment]
Ah ok. I currently open a new Helper-Window every time. That works fine, but I think it is a memory waste.
Can I reopen a window with that?

**Comment by kekekeks** [comment]
You can hide the window instead of closing it.

**Comment by FG-rgb** [comment]
Ups, of course. Thank you ;-)

**Comment by FG-rgb** [comment]
Works now.
Btw. ShowInTaskbar = false does not work when:
The window is a top-level unowned window, and is visible.
Therefore I used:
SetWindowLong with WS_EX_TOOLWINDOW.
Like described here:
https://stackoverflow.com/questions/8243588/c-sharp-hiding-an-application-from-the-taskbar

**Comment by FG-rgb** [comment]
I have a last question:
If I resure the Window with different content, e.g. for ContextMenu or Tooltip Text, I have to calculate the position by size, to ensure the window is on screen. Therefore I need the correct size of the window. In this case I call Measure(new Size(double.PositiveInfinity, double.PositiveInfinity));
, before Window.Show() is called, and then calculate and set the position. This is ok, but If I change the content of the window, and the content is larger or smaller as the content before, I see the old size is reused. My observation is that I have to call Show() and Hide() and than Measure again, to apply a content size changed. Is there another way of doing that?

I hope it is understandable :-)

**Comment by efef77** [comment]
I confirm the need to have an explicit pointer placement strategy like statet by [FG-rgb] above.
Reason: My drawing application has a skia view doing lowlevel graphics with editing interaction.
For that i trigger the `ContextMenu` explicitly calling `Open( )` desireing the menu near the pointer position.
Unfortunaltely the matching `Open(...)` variant with the parameter `requestedByPointer` cant be called and also cant be overwritten since ist is private.

The real issue resides inside the method code:
`_popup.Placement = !requestedByPointer && Placement == 
PlacementMode.Pointer ? PlacementMode.Bottom : Placement;`
For me this leverages out the meaning of the `Pointer`-placement strategy
(which is still found in Avalonia 11.0.0 rc 1.1)

Lacking the possibility to call the private `Open(...)` variant i had to do a subclassing with event-postprocessing
like this - but it is an ugly approach compared to legal overwriting:

```
/// <summary>
/// Workaround for removing the fallback behaviour regarding 'Placement' 
/// </summary>
public class ContextMenuExt : ContextMenu
{
    public ContextMenuExt() {
        Opened += (_s, _e) => {
            if (Placement == PlacementMode.Pointer) {
                // !!! public Open(...) versions change internal 'Placement' from 'Pointer' to 'Bottom'
                // !!! we must use event to restore internal setting to 'Pointer'
                ((Popup)Parent).Placement = PlacementMode.Pointer;
            }
        };
    }

    // public override void Open() => base.Open(); //  ==> Opened postprocessing

    protected override Type StyleKeyOverride => typeof(ContextMenu);
}
```

Would be fine if the dev team would change the API of the `ContextMenu.Open(...)` method(s) to make that workaround unnecessary.
Thanks.
