### ISSUE TITLE
What is NonPumpingWaitProvider?

### ISSUE THREAD

**Issue by stepangovorko** [AvaloniaUI/Avalonia#4955]
Could someone explain me please what NonPumpingWaitProvider is for?
And what will be if I turn it off by setting AvaloniaSynchronizationContext.AutoInstall to false?

I need this because I have a dead lock on application exit related to NonPumpingWaitProvider.Wait() method. Unfortunately I can`t reproduce it in clean environment, but it is fixed by setting AvaloniaSynchronizationContext.AutoInstall to false.

**Comment by kekekeks** [comment]
>Could someone explain me please what NonPumpingWaitProvider is for?

It is required to prevent .NET from calling PeekMessage/DispatchMessage while trying to take a lock via `Monitor.Enter`. That causes reentrancy in all kinds of places which leads to segfaults.

> And what will be if I turn it off by setting AvaloniaSynchronizationContext.AutoInstall to false?

That is not recommended.

>I need this because I have a dead lock on application exit related to NonPumpingWaitProvider.Wait() method.

Do you have a stack trace?

**Comment by jhofinger** [comment]
That is interesting, because I experience reproducible hangs on https://github.com/AvaloniaUI/Avalonia/blob/master/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs#L489 (which calls the NonPumpingWaitProvider, according to dnspy). Sometimes the same hang happens even with the Control Catalog on master, right on startup, but unfortunately it's quite random. Could that be related?

I'm on current Windows 10.

**Comment by kekekeks** [comment]
>(which calls the NonPumpingWaitProvider, according to dnspy).

Yes, Monitor.Enter calls [WaitForMultipleObjectsEx](https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-waitformultipleobjectsex) internally, that's a normal phenomena. The only thing that's changed by `NonPumpingWaitProvider` is `bAlertable` argument being set to `false` (CLR sets it to `true`).

The hang you are experiencing is most likely a deadlock caused by something else.

**Comment by jhofinger** [comment]
Here's what I see in dnspy:

![grafik](https://user-images.githubusercontent.com/12698538/97545173-e0c49580-19ca-11eb-9ca0-edeea404dffa.png)

(I didn't find a way to swith the interface to English. "Übergang von verwaltet zu nativ" = "Transition from managed to native")

**Comment by kekekeks** [comment]
So it is stuck waiting for the renderer lock to be released. Inspect other threads and see if those are waiting for something too.

**Comment by jhofinger** [comment]
So the symptoms are a bit different in Control catalog and my own app.

**Control catalog:** 
The stack trace looks like this (directly in Visual Studio): 
![grafik](https://user-images.githubusercontent.com/12698538/97554664-5fbfcb00-19d7-11eb-86dc-b4079516cb6f.png)
This happens about 50% of the time I start it, right at startup. It never recovers, 0% CPU load, white window. Visual Studio doesn't show anything else.

However, it only happens when I start it with a debugger attached. Starting the exe directly is fine.


**My own app**
My app opens files in different tabs. If I open a tab with a certain template (let's call it the problematic tab) first, loading another tab takes about 20 times slower than if the problematic tab is not open. 

Everytime I break it, the renderer thread is doing something inside SkiaApi, but it seems to do work and not wait. I don't get any debug messages during that time.  That's where the screenshot in my last comment came from.

The problematic tab itself uses a few complicated templates, and removing these seem to fix the problem - but rendering the tab itself is nearly instant.

**Comment by stepangovorko** [comment]
@kekekeks Here is my stack trace:

```
[Managed to Native Transition]
UnmanagedMethods.WaitForMultipleObjectsEx() at C:\BuildAgent\work\e03a15a4c8b887b9\src\Windows\Avalonia.Win32\Interop\UnmanagedMethods.cs:line 1406
NonPumpingWaitProvider.Wait() at C:\BuildAgent\work\e03a15a4c8b887b9\src\Windows\Avalonia.Win32\NonPumpingWaitProvider.cs:line 11
AvaloniaSynchronizationContext.Wait() at C:\BuildAgent\work\e03a15a4c8b887b9\src\Avalonia.Base\Threading\AvaloniaSynchronizationContext.cs:line 64
SynchronizationContext.InvokeWaitMethodHelper()
[Managed to Native Transition]
GC.WaitForPendingFinalizers()
GC.GetTotalMemory()
IJetHostEx.<>c.<PumpOutLeftovers>b__1_0() at C:\Work\dotnet-products\Platform\Core\Shell\Shell\Src\Application\Environment\Infra\IJetHostEx.cs:line 70
ReentrancyGuard.AllowNestedExecution() at C:\Work\dotnet-products\Platform\Core\Shell\Core\Src\Concurrency\ReentrancyGuard.cs:line 244
IJetHostEx.PumpOutLeftovers() at C:\Work\dotnet-products\Platform\Core\Shell\Shell\Src\Application\Environment\Infra\IJetHostEx.cs:line 67
LifetimeDefinition.Destruct() at /opt/buildAgent/work/b0c387553c046bbb/rd-net/Lifetimes/Lifetimes/LifetimeDefinition.cs:line 439
LifetimeDefinition.Terminate() at /opt/buildAgent/work/b0c387553c046bbb/rd-net/Lifetimes/Lifetimes/LifetimeDefinition.cs:line 390
ReentrancyGuard.Execute() at C:\Work\dotnet-products\Platform\Core\Shell\Core\Src\Concurrency\ReentrancyGuard.cs:line 335
JetEnvironment.<>c__DisplayClass9_0.<InternalDestroy>b__0() at C:\Work\dotnet-products\Platform\Core\Shell\Shell\Src\Application\Environment\Infra\JetEnvironment.cs:line 234
ILoggerEx.Catch() at C:\Work\dotnet-products\Platform\Core\Shell\Core\Src\Logging\ILoggerEx.cs:line 335
ILoggerEx.Catch() at C:\Work\dotnet-products\Platform\Core\Shell\Core\Src\Logging\ILoggerEx.cs:line 246
ILoggerEx.CatchAsAlgorithmError() at C:\Work\dotnet-products\Platform\Core\Shell\Core\Src\Logging\ILoggerEx.cs:line 432
JetEnvironment.InternalDestroy() at C:\Work\dotnet-products\Platform\Core\Shell\Shell\Src\Application\Environment\Infra\JetEnvironment.cs:line 234
JetEnvironment.CreateAndRun() at C:\Work\dotnet-products\Platform\Core\Shell\Shell\Src\Application\Environment\Infra\JetEnvironment.cs:line 148
JetHostItems.CreateAndRun() at C:\Work\dotnet-products\Platform\Core\Shell\Shell\Src\Application\Environment\Infra\JetHostItems.cs:line 26
LauncherTabWell.RunApplication() at C:\Work\dotnet-products\Platform\Standalone\TabWell.Avalonia\Src\Shell\Host\LauncherTabWell.cs:line 76
LauncherTabWell.Main() at C:\Work\dotnet-products\Platform\Standalone\TabWell.Avalonia\Src\Shell\Host\LauncherTabWell.cs:line 46
[Native to Managed Transition]
RuntimeMethodInfo.UnsafeInvokeInternal()
RuntimeMethodInfo.Invoke()
LauncherManagedCore.Msil.ILauncherManagedCore.InvokeManagedMethod()
[Application Domain Transition]
[Native to Managed Transition]
[Managed to Native Transition]
Launcher.RunClr_LoadAndRun_Invoke_Managed()
Launcher.RunClr_LoadAndRun_Invoke()
Launcher.RunClr_LoadAndRun()
Launcher.RunClr()
Launcher.Run()
[Native to Managed Transition]
```

Here is the body of PumpOutLeftovers:
```
    public static void PumpOutLeftovers()
    {
      ReentrancyGuard.Current.AllowNestedExecution("PumpOut", () => // Lift guard to let in orphaned Queues
      {
        JetDispatcher.PumpMessagesOnce();
        GC.GetTotalMemory(true);
        JetDispatcher.PumpMessagesOnce();
        GC.GetTotalMemory(true);
        JetDispatcher.PumpMessagesOnce();
      });
    }
```
The dead lock is reproducable in 100% of cases on App shutdown.

**Comment by kekekeks** [comment]
The stack trace from the control catalog gets stuck on `GC.WaitForPendingFinalizers();` too.

@MarchingCube

**Comment by kekekeks** [comment]
I guess that instead of using a different `WaitForMultipleObjectsEx` we need to set a special flag that would make our WndProc to work in a special mode that forwards *everything* except for WM_PAINT to `DefWindowProc` (and ignores WM_PAINT itself)

**Comment by kekekeks** [comment]
@stepangovorko are you, by chance, using some COM interop that wants STA on the main thread?
