### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jinyuttt** [AvaloniaUI/Avalonia#5031]
Is the update slower this year?

**Comment by vanillajonathan** [comment]
Yeah, and what about .NET 5, [MAUI](https://github.com/dotnet/maui), System.Xaml and open sourced [WPF](https://github.com/dotnet/wpf)?

**Comment by danwalmsley** [comment]
Yes its taking longer than we hoped... but we run on volunteers mostly so its difficult.

We have 2 remaining issue to solve for 0.10

**Comment by jinyuttt** [comment]
Yes, everyone has their own work.

**Comment by maxkatz6** [comment]
@vanillajonathan 
> .NET 5

It already works with Avalonia 0.9 and 0.10 preview.

> MAUI

It's not related to Avalonia, only as an alternative at some point.
NET 6 mobile support is more exciting and will really help with mobile support in Avalonia.

> System.Xaml

Instead we have https://github.com/kekekeks/XamlX with better performance.

> open sourced WPF

Open sourced WPF already helped in making Avalonia better ;)

**Comment by vanillajonathan** [comment]
@maxkatz6 Thanks for the brief explanation!

It would be nice with a blog post that goes more in depth what those means. Like if .NET 5 brings any benefit to Avalonia, if it will be possible to embed MAUI widgets within Avalonia apps, or vice versa, or if there will be any compatibility or interoperability. Why XamlX is used over System.Xaml and if System.Xaml will be used in the future, and if there compatibility suffers due to using third-party XamlX instead of official upstream System.Xaml, what ways Avalonia have benefited from the open sourcing of WPF, and if there are further benefits in the future, etc.

**Comment by robloo** [comment]
> It would be nice with a blog post that goes more in depth what those means. Like if .NET 5 brings any benefit to Avalonia

I'm sure .net 5 benefits will be elaborated on. I do think most benefits will happen instead with .net6 as mentioned. The problem is .net 5 did not unify the xamarin/mono code like originally planned. Now .net 6 will be what truly runs everywhere including macOS, iOS and Android. Until then, Avalonia likely needs to stay with .net Standard 2.1 for 1 more year.

> if it will be possible to embed MAUI widgets within Avalonia apps, or vice versa, or if there will be any compatibility or interoperability. 

Microsoft develops Maui and its a completely separate framework from Avalonia. They are both c# but thats where the similarities stop. Avalonia renders its own controls. Maui will still largely use platform native controls. This just doesn't make sense at all from a technical or project level. 

> Why XamlX is used over System.Xaml and if System.Xaml will be used in the future, and if there compatibility suffers due to using third-party XamlX instead of official upstream System.Xaml,

The same team created XamlX and it is actually far bettet than System.Xaml in both architecture and implementation. Microsoft's Xaml tooling has become really poor since WPF. Microsoft is going to end up rewriting their Xaml stack soon I think and they were even interested in XamlX and what the Avalonia team managed to do.

> what ways Avalonia have benefited from the open sourcing of WPF, and if there are further benefits in the future, etc.

Grid was ported over from WPF to solve some bugs and make it feature complete. A lot of work with text formatting is using the WPF code as base now. Really a lot of opportunities in the future with pulling over controls and features not in Avalonia already.

**Comment by vanillajonathan** [comment]
Thank you @robloo ! 🙏️
