### ISSUE TITLE
Avalonia Window does strange things

### ISSUE THREAD

**Issue by FG-rgb** [AvaloniaUI/Avalonia#5033]
Hello, actually I have the following Problem:

Operating system is Windows 10
I'm opening an Avalonia Window absolute positioned on the Screen.
If I open the Avalonia Window in a special situation (while the user moves the Webbrowser(e.g. Chrome)),
the movement of the Chromebrowser is aborted, and the Avalonia Window is closed automatically (you see a short flicker on the Desktop).

I think there is a Problem with this Window.
Does someone has observed something similar?
Or do there is an Avalonia "ToolWindow", or "PopupWindow"?
I only want to inform a user, but this message have to be in the lower right corner of the PrimaryScreen.

**Comment by FG-rgb** [comment]
I've retested the code, using a WPF-Window. No problems.

**Comment by FG-rgb** [comment]
Additional Info I see:
If the window is closed via CancellationToke.Register method, I see:
4 Times 'Exception thrown: 'System.ArgumentNullException' in System.Private.CoreLib.dll'
in Debug Output.

**Comment by workgroupengineering** [comment]
I am not an expert but I think there is some instruction crashing the video card driver. The flicker could be caused by restoring the vga driver state.
Try updating vga drivers, if it continues try disabling graphics acceleration inc chrome.

The ArgumentNullException probably depends on the invalid state of the drivers, to try to test in VS press Ctrl + Alt + E and enable debugger blocking with ArgumentNullException.

Another test i can do is use some tools that trace opengl to understand what the driver is wrong. I found [this](http://apitrace.github.io/) but have never used it.

**Comment by FG-rgb** [comment]
Hi, thank you for your help.
I found something out,
Because my window needs an owner for window,ShowDialog(owner) I'm simply using new Window() as owner,
that seems be be the problem.

If I create an owner window, open it, and let it open, while using my described scenario, there is NO problem.
I now try a workaround, by set position of owner outside of all screens, and open it there...

**Comment by FG-rgb** [comment]
Ok, my workaound helps.

**Comment by wuzlai** [comment]
Hello, I met a phenomenon about window, see you have met.
On Win10, open the Avalonia application window with occasional flashes. Roughly speaking, I've defined the form to appear in the center of the screen. But it appears first on the top left of the screen, then quickly disappears, and then it appears in the center of the screen. It doesn't happen every time, and I'm confused. My guess is that the form appears on the left side by default under Win10, but due to some kind of exception when you think you've specified where it will appear. Causes this position to flicker. I don't know how to deal with the situation at present. Has anyone ever met it?
