### ISSUE TITLE
Combobox performance with high number of items

### ISSUE THREAD

**Issue by audinowho** [AvaloniaUI/Avalonia#5073]
I'm using Combobox and recently ran into performance issues, with list load lagging at ~3000 items.  WPF solves this by using VirtualizingStackPanel: https://stackoverflow.com/questions/8198645/wpf-combobox-performance-problems-by-binding-a-large-collections

However, the above xaml has no effect when ported directly to AvaloniaUI.  Is there an alternative in this library?

**Comment by maxkatz6** [comment]
Make sure that you set VirtualizationMode="Simple" on the ComboBox. Otherwise it will add all 3000 items to the tree. Default is "None".

@grokys what do you think, should we use ItemsRepeater for controls like ComboBox now (~0.10.1), or should we wait for https://github.com/AvaloniaUI/Avalonia/pull/4779 ?
Right now it will give us better virtualization/performance in the standard controls, but it will cause breaking changes.

**Comment by audinowho** [comment]
Works perfectly and much simpler than the WPF answers.  Thanks!

**Comment by grokys** [comment]
> what do you think, should we use ItemsRepeater for controls like ComboBox now (~0.10.1), or should we wait for #4779 

Not sure there's any simple way to use `ItemsRepeater` for controls like `ComboBox` without something like #4779 and that PR is delayed waiting on fixes to upstream `ItemsRepeater` (https://github.com/microsoft/microsoft-ui-xaml/issues/1829 in particular). And like you say it's going to be a huge breaking change.
