### ISSUE TITLE
Argument Null Exception calling SetVisualParent inside Contract.cs (Caused by popup inside a behviour, inside a carousel)

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#513]
You need the following commit to repro.

https://github.com/VitalElement/AvalonStudio/commit/677bf7ff7508121b0b2791ecea5435b89b392ea6

run AS, then open sample project.

Open a code file and hover mouse over a piece of code that would trigger popup, like a variable name.

You should crash straight away inside Perspex.

**Comment by danwalmsley** [comment]
This is a new commit to repro following rename.
https://github.com/VitalElement/AvalonStudio/commit/a09b267200568aeef450f7ce75474e21fd333348

**Comment by grokys** [comment]
Found the problem here - the problem is that `AvalonStudio.Behaviors.PopupBehavior` is adding a control to two parent controls. Previously there was no check for that in certain situations and so the error manifested itself like this. I've added a check to throw when you try to do this so it should be clearer.
