### ISSUE TITLE
How to get the DataGridRow from DataGrid.SelectedItem？

### ISSUE THREAD

**Issue by protoess1996** [AvaloniaUI/Avalonia#5247]
How to get the DataGridRow from DataGrid.SelectedItem？I searched the api document，but failed to find out.

**Comment by maxkatz6** [comment]
There is no guarantee that SelectedItem has related DataGridRow because of virtualization. So it's kind of similar to another issue: https://github.com/AvaloniaUI/Avalonia/issues/4590 .

Does WPF have related API? It should be possible to port it, but "SelectedRow" should be expected to be "null" even if "SelectedItem" isn't. Same for multiple selection mode.

**Comment by maxkatz6** [comment]
Anyways, why do you want to have "SelectedRow" (or alternative)?
If you need special styling for this, there is ":current" pseudoclass, that can be used.

**Comment by protoess1996** [comment]
I tried to set DataGridRow color according to its content, so I set a style with a value converter for DataGridRow.
`<style selector="DataGridRow"> `
` <Setter Property="Background" Value="{Binding #datagrid.color, Converter={StaticResource myConverter}}
"/> `
` </style> `
By using this converter I set the first row as red. It’s corret when I don’t scroll the datagrid. But when I scroll it, the datagird will set rows to red repeatedly in a fixed intervals.

**Comment by protoess1996** [comment]
I want to get the DataGridRow so I could set the background myself

**Comment by maxkatz6** [comment]
> By using this converter I set the first row as red.

I don't see where you have condition for the first element. But it's not so important I guess.

> But when I scroll it, the datagird will set rows to red repeatedly in a fixed intervals.

DataGrid reuses rows. I.e. if you have 1000 elements, DataGrid will use only 10 rows that will be recycled.

> I want to get the DataGridRow so I could set the background myself

If you want to have some custom logic on rows, you can use LoadingRow event. It's good place for that, because this event is called per each row when it is reloaded with new item.

**Comment by protoess1996** [comment]
I use the datagird to show a subtitle. The content is changed by a TextBox that binded to datagrid selecteditem. When I change the content through the Textbox，loadingrow event will not be fired

**Comment by protoess1996** [comment]
thus I failed to change the background of a Row lively

**Comment by maxkatz6** [comment]
You probably need to create a binding from code behind in the LoadingRow event. In that case don't forget to dispose the binding in the UnloadingRow event.

**Comment by maxkatz6** [comment]
Answered. Feel free to ask to reopen, if not.

**Comment by cornerbowlsoftware** [comment]
@maxkatz6 The DataGridRow is needed so code behind can set the focus when the item is added. Just adding the ViewModel to the list of selected items isn't good enough.  That just selects it both in WPF and Avalonia. My users demand keyboard focus hence the need for code behind.  This is accomplished in WPF like so:

```
if (ItemContainerGenerator.ContainerFromIndex(selectedIndex) is DataGridRow row)
{
    _ = Keyboard.Focus(row);
    _ = row.MoveFocus(new TraversalRequest(FocusNavigationDirection.Next));
}
```
