### ISSUE TITLE
Custom draw in Render() directly vs DrawingContext.Custom(), what difference and which better?

### ISSUE THREAD

**Issue by GF-Huang** [AvaloniaUI/Avalonia#5264]
I had read the demo [CustomSkiaPage.cs](https://github.com/AvaloniaUI/Avalonia/blob/master/samples/RenderDemo/Pages/CustomSkiaPage.cs), I don't understand why not draw in `render()` directly, why need a `ICustomDrawOperation`?

https://github.com/AvaloniaUI/Avalonia/blob/3c22ce5b1b9bd1dd66f9021696427992c11779b2/samples/RenderDemo/Pages/CustomSkiaPage.cs#L109-L117

I want to custom draw something like the follow, which way is better? And Why?

![yXblEzgu1J](https://user-images.githubusercontent.com/4510984/103922852-56797a00-514f-11eb-8e35-86381ac66301.gif)

**Comment by napana** [comment]
Because than Avalonia knows that the component consists of lets say 2x rectange 10x50 and when it needs to repaint the window it doesn't need to "render" (generate ICustomDrawOperation) again. But this is just one part of the story. These days everyone uses GPU for rendering and using it in the way "ok i have rectangle so i will send 4 vertices to gpu and issue call" is not they way you want to do it :) so you buffer all "drawing operations" and you than optimize the entire batch etc..

**Comment by Gillibald** [comment]
Render isn't always called directly to render and instead, the rendering is deferred. That's why there is a drawing operation.

**Comment by GF-Huang** [comment]
So `ICustomDrawOperation` means a buffer for batch draw, then `context.Custom()` to render it?

**Comment by Gillibald** [comment]
`context.Custom()` adds your drawing operation to the scene graph when the ´DeferredRenderer(default)´ is used

**Comment by GF-Huang** [comment]
It sounds `DeferredRenderer` will make a better performance.
