### ISSUE TITLE
Binding to SolidColorBrush.Color from Style

### ISSUE THREAD

**Issue by pr8x** [AvaloniaUI/Avalonia#5286]
**Describe the bug**
It seems that binding to the `Color` of a `SolidColorBrush` isn't working from a style.

```xaml
<Window.Styles>
        <Style Selector="Rectangle">
            <Setter Property="StrokeThickness" Value="2"></Setter>
            <Setter Property="Stroke">
                <SolidColorBrush Color="{Binding}" />
            </Setter>
        </Style>
    </Window.Styles>

    <Rectangle Width="100" Height="100" DataContext="{x:Static Colors.Red}"/>
```

The resulting `Stroke` ends up as `null`. It works when I directly set the brush:

```xaml
    <Rectangle Width="100" Height="100" DataContext="{x:Static Colors.Red}">
        <Rectangle.Stroke>
            <SolidColorBrush Color="{Binding}" />
        </Rectangle.Stroke>
    </Rectangle>
```

**To Reproduce**

[bind_brush_color_xaml.patch.txt](https://github.com/AvaloniaUI/Avalonia/files/5801278/bind_brush_color_xaml.patch.txt)

**Expected behavior**
I would expect it to work :)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: latest master

**Comment by grokys** [comment]
What's happening here is that the binding is being applied to the brush using a non-existent `DataContext` because `SolidColorBrush` doesn't have a `DataContext` and at the point where the binding is applied there's no control to anchor to.

The root of the problem here is that the brush is only created a single time, and the same instance is shared among all the controls that the style is applied to, so even if it _did_ work it'd only be able to bind to a single control's `DataContext`. 

Taking a look at WPF, this does work properly and so it seems that when WPF detects a binding in the brush it knows to create a new instance each time (a brush without a binding is shared it appears). Need to investigate further.

**Comment by grokys** [comment]
Look at WPF, the way this seems to work is:

- A brush without a binding is frozen, a brush with a binding is left unfrozen
- When the style is applied, [this code](https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/StyleHelper.cs#L2967-L2968) clones non-frozen objects and sets the inheritance context

We don't have the concept of `Freezable` (and I don't really want it personally) so we'd have do this a different way if we want to support this. UWP doesn't have `Freezable` either so I wonder how it works there, need to take a look.

**Comment by grokys** [comment]
UWP doesn't support this properly either. The following XAML:

```xml
    <Page.Resources>
        <Style TargetType="Rectangle">
            <Setter Property="StrokeThickness" Value="2"></Setter>
            <Setter Property="Stroke">
                <Setter.Value>
                    <SolidColorBrush Color="{Binding}" />
                </Setter.Value>
            </Setter>
        </Style>
    </Page.Resources>

    <StackPanel>
        <Rectangle x:Name="r1" Width="100" Height="100">
            <Rectangle.DataContext>
                <Color>Red</Color>
            </Rectangle.DataContext>
        </Rectangle>
        <Rectangle x:Name="r2" Width="100" Height="100">
            <Rectangle.DataContext>
                <Color>Green</Color>
            </Rectangle.DataContext>
        </Rectangle>
    </StackPanel>
```

Results in:

![image](https://user-images.githubusercontent.com/1775141/104914486-8155a080-598f-11eb-9bf8-4550d8c23048.png)

This means that although it's finding the `DataContext`, it's not cloning the brush so only a single control's `DataContext` can have effect.

Tempted to say "not supported" here because a) UWP doesn't support it and b) it's a bit of a difficult "special case" for us, in that usually only a single shared value is created for a style setter.

A decent solution might be to relax the constraint on `<Template>` in a setter needing to return a control, so you'd be able to do:

```xml
<Setter Property="Stroke">
    <Template>
        <SolidColorBrush Color="{Binding}" />
    </Template>
</Setter>
```

**Comment by grokys** [comment]
Closing this as there's not much we can do about it. We might be able to enable it in future if we allow `<Template>` to work for non-control content but that throws up a whole load of questions too.
