### ISSUE TITLE
Problem with passing pointer/mouse capture between windows.

### ISSUE THREAD

**Issue by igorstefus** [AvaloniaUI/Avalonia#5425]
There is some kind of problem with pointer capturing when window where capturing originated is closed before capturing was released. As result if user does not release button, capturing can not be set in new window.

I have usecase where I need to undock some tabs which means while user is dragging tab he will hold left mouse button down all the time. When specified threshold is exceeded I need to pick up content of the tab and move it to new window (to undock it) and move capture from previous window to the new one so user can continue with dragging.

To do that I am currently using`IInputRoot MouseDevice.Capture` to move capture from what ever it was before to new window. This works as long as I don't close window where first capture (mouse button down event) originated. If window from which tab was undocked is closed  I am not able to set capture to the new window until I release mouse button. I also tried sending new mouse down input using `MouseHelper` implementation as soon as new window is opened but in that case it seams that new capture can not be set until mouse button is released.

**Comment by grokys** [comment]
This seems to be because when closing a window we indiscriminately release pointer capture, no matter whether the current window has the capture or not. More details to follow...

**Comment by kekekeks** [comment]
Note that mouse capture is hard-bound to the toplevel on some platforms and **cant** be transferred

**Comment by igorstefus** [comment]
> Note that mouse capture is hard-bound to the toplevel on some platforms and **cant** be transferred

So on those platforms you have no way to recapture any other window until user releases the button? I am fine with sending mouse down again from code as long as it captures newly opened window without user actually releasing the button.

**Comment by grokys** [comment]
I've been looking into this under Windows.

The problem seems to be that we create a [new `WindowsMouseDevice` for each window](https://github.com/AvaloniaUI/Avalonia/blob/1a39210febf92e9e87b3ebacca9b56d99e660913/src/Windows/Avalonia.Win32/WindowImpl.cs#L91), and for each of these mouse devices [a new `WindowsMousePointer` is created](https://github.com/AvaloniaUI/Avalonia/blob/1a39210febf92e9e87b3ebacca9b56d99e660913/src/Windows/Avalonia.Win32/Input/WindowsMouseDevice.cs#L11). Each pointer tracks its capture separately, but they all hook into a singular win32 mouse capture.

When we close the window we [dispose the `WindowMouseDevice` ](https://github.com/AvaloniaUI/Avalonia/blob/1a39210febf92e9e87b3ebacca9b56d99e660913/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs#L84) which ends up disposing the pointer which [sets the capture to null](https://github.com/AvaloniaUI/Avalonia/blob/1a39210febf92e9e87b3ebacca9b56d99e660913/src/Avalonia.Input/Pointer.cs#L72). This happens even if another `WindowsMousePointer` has captured the win32 mouse capture.

Seems like we have an mismatch here between our pointer capture (multiple) and the win32 mouse capture (singular).

**Comment by grokys** [comment]
> Note that mouse capture is hard-bound to the toplevel on some platforms and cant be transferred

Which platforms?

**Comment by grokys** [comment]
To fix this I can think of 2 solutions:

- Have a single `Pointer` instance that's shared between windows
- When setting capturing the win32 mouse, also add a handler to notify us that we've lost mouse capture so that the state can be reset in the `Pointer` instance

**Comment by kekekeks** [comment]
>Which platforms?

Wayland, several X11 window managers

>So on those platforms you have no way to recapture any other window until user releases the button?

No

**Comment by kekekeks** [comment]
Mkay, Cocoa doesn't have API for capturing mouse either, all captures are managed automatically on mouse press/release events.

**Comment by grokys** [comment]
I've looked into this and although [this comment](https://github.com/AvaloniaUI/Avalonia/issues/5425#issuecomment-773364447) is true and our code isn't strictly correct, _this is also win32's behavior_. I've repoed without Avalonia over at https://github.com/grokys/CSharpWin32HelloWorld/tree/mouse-capture and it definitely seems that closing a window on win32 releases mouse capture from another window.

Given that 1) we need to refactor all this stuff soon and 2) we accidentally correctly modeled the behavior of the only platform this is relevant to, then I'm going to close this issue.
