### ISSUE TITLE
TextBox.cs OnKeyDown does not respect e.Handled = true

### ISSUE THREAD

**Issue by postrondev** [AvaloniaUI/Avalonia#5753]
After code review i did not found any line that checks if e.Handled == true
on base OnKeyDown function entry.
I have an inhertited TextBox Control (SetStyle).
I overwrite OnKeyDown.
I press a key and set e.Handled = true;
The base TextBox does not check if e.Handled is true;

I circumvent this issue by not calling base.OnKeyDown if i do not
want allow the key being forwarded to base

**Comment by kekekeks** [comment]
Your OnKeyDown handler is most likely called after textbox has already handled the event. You need to subscribe to the event with Tunnel routing strategy (aka PreviewXXX in WPF).

**Comment by maxkatz6** [comment]
Also code example:
https://github.com/AvaloniaUI/Avalonia/issues/5244#issuecomment-753239690

**Comment by postrondev** [comment]
How can the TextBox call OnKeyDown when i overwrite it.
This breaks any rule.
Whe i overwrite OnKeyDown and do not call base.OnKeyDown
then the OnKeyDown of the base class is never allowed to execute.
Or do i miss something in OOP?

regards.

**Comment by maxkatz6** [comment]
If it will help you to understand, [KeyDownEvent property](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Input/InputElement.cs#L87) is the entry-point of this event.
When you subscribe to C#-event ```KeyDown += Control_KeyDown``` it [adds handler](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Input/InputElement.cs#L242) to this KeyDownEvent with Bubble routing strategy (event handling order is from the source where event occurred, textbox in this case, to the root).
When you override OnKeyDown event, it has pretty much the same behavior, because OnKeyDown is invoked also with Bubble routing strategy ([see here](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Input/InputElement.cs#L202), bubble is default strategy, so it's not passed as a parameter explicitly).

So when you want to handle event with Tunnel routing strategy (when event raises handlers in order from the root to the source), you need to use KeyDownEvent property directly, without KeyDown C#-event or OnKeyDown virtual method:
```csharp
var textBox = new TextBox();
textBox.AddHandler(InputElement.KeyDownEvent, TextBox_KeyDown, RoutingStrategies.Tunnel);
```

**Comment by maxkatz6** [comment]
Also this documentation page describes pretty much the same, but in general case: https://avaloniaui.net/docs/input/events

**Comment by postrondev** [comment]
Thank you.
Your reply helped a lot.
