### ISSUE TITLE
Avalonia styling error

### ISSUE THREAD

**Issue by Ewdoc** [AvaloniaUI/Avalonia#5777]
**Describe the bug**
When trying to debug my solution, a "non generated" exception appears : ``System.MissingMethodException : 'Method not found: 'Void Avalonia.Styling.Style.set_Setters(System.Collections.Generic.IList`1<Avalonia.Styling.ISetter>)'.'``

I'm using Avalonia 0.10.0

**To Reproduce**
Steps to reproduce the behaviour:
(0. Create a new Avalonia project)
1. Install the NuGet: CSharpMath.Avalonia v0.4.2
2. Go to your AXAML code and respect this schema: https://github.com/verybadcat/CSharpMath#4-csharpmathavalonia
3. Debug your solution

**Expected behaviour**
It should run the app correctly

**Desktop:**
- OS: Win10

**Comment by grokys** [comment]
Errors like this are usually caused by having mismatched versions of Avalonia packages installed. Check that everything is on the same version.

**Comment by maxkatz6** [comment]
> I'm using Avalonia 0.10.0

and
> CSharpMath.Avalonia v0.4.2 (uses Avalonia 0.9.6)

are not compatible. Breaking changes between major versions are expected and this is the case.


0.5.0-beta uses "0.10.0-preview5" which most likely won't work either because this Avalonia version wasn't yet code signed, and it was preview. Somebody should update CSharpMath to use stable 0.10.0 version.

**Comment by Ewdoc** [comment]
Thanks for your answer.
I guess I have to wait, then :)
