### ISSUE TITLE
Comparison with Xamarin and projects with similar goals

### ISSUE THREAD

**Issue by SoonDead** [AvaloniaUI/Avalonia#587]
I have no experience in cross platform .NET development, I have only tried Xamarin for a 2-3 screen demo app running on Android iOS and WP. Still it seems the .NET world is opening, some things are alpha, some are stable (yet work like some alpha), but it's becoming harder and harder to explore all options.

How is this different from Xamarin.Forms for example? Why would someone choose one and not the other?

I think it would be useful to see a document about the most shiny selling points of this framework.

**Comment by jkoritzinsky** [comment]
Xamarin.Forms uses the native controls on each platform to render instead of drawing customizable controls. Additionally, Xamarin.Forms only works on iOS, Android, WP, and UWP.

Conversely, Avalonia works on Windows, Linux, iOS, Android (may have regressed), UWP (missing glue code though), Mac OS X, and is very easily extensible to embedded platforms that support mono.

Xamarin.Forms is more stable currently. If you're doing mobile then Xamarin.Forms would be more useful right now, but Avalonia will give you more flexibility. However, once we stabilize Android, then Avalonia will be the only UI toolkit that works across both mobile and desktop platforms.

**Comment by weitzhandler** [comment]
For the reference, I've been using XF for about six months now, and I can say it's pretty fast, but it's agenda to stick to least common factor of native controls (e.g. only controls that are natively supported in all platforms is supported), is stupid. For example, no `CheckBox`, `RadioButton`, `ImageButton` and many other elementary controls. You'll have to try finding them online or create them yourself (+ custom renderers times number of platforms you want to support).
Anyway XF has [announced](https://blog.xamarin.com/glimpse-future-xamarin-forms-3-0) to soon support Linux and macOS.

**Comment by JimSEOW** [comment]
Xamarin Forms supports the following OSs
iOS, MacOS
Android
GTK (Linux)
WPF (soon x86/x64)
UWP ( W10, W10M, W10A, IoT Core, IoT Core Pro)

**Comment by weitzhandler** [comment]
@JimSEOW I'm not aware of XF support for WPF, it does support UWP, though not sure WPF. Can you please include any reference for that fact?

**Comment by JimSEOW** [comment]
@weitzhandler 
It was announced in Build 2017, it is expected to come Q4 2017
https://blog.xamarin.com/glimpse-future-xamarin-forms-3-0/

**Comment by weitzhandler** [comment]
Way kewl!

**Comment by JimSEOW** [comment]
@weitzhandler  It is important that the different cross platform WPF efforts learn from each other and help each other!

**Comment by weitzhandler** [comment]
I wish XF is as powerful as WPF/UWP/Silverlight.
At least if they had a toolkit that offers a wider range of controls. I'm working on a XF project, and many elementary controls are missing!

**Comment by juepiezhongren** [comment]
we want ava and xf mixed together

**Comment by jmacato** [comment]
@juepiezhongren that would be kind of pointless, since the two projects are divergent in their goals (Xamarin.Forms focuses with Native Experience in their target platforms, while Avalonia is for devs that want their apps to look uniformly across all platforms). Besides the untold amount of manpower required to merge the two projects would be better focused on other aspects of the project that will be tangibly more beneficial to all.

**Comment by weitzhandler** [comment]
The more I use XF I have a greater desire to look for something else.
Avalonia looks like a better option than XF for me, because I don't give a $hit about native look and feel.
Most important aspect for me is develop once develop everywhere.

That being said, XF's plans towards web (via WebAsm) looks closer than Avalonia's (#1387).

I'm planning to develop our next LoB app using Avalonia.

**Comment by kevmoens** [comment]
> @JimSEOW I'm not aware of XF support for WPF, it does support UWP, though not sure WPF. Can you please include any reference for that fact?
To work with Xamarin Forms with WPF you need to add a new project to your solution for WPF and add the corresponding Xamarin Forms Nuget
https://www.nuget.org/packages/Xamarin.Forms.Platform.WPF/
