### ISSUE TITLE
Adorner drawing delay/lag

### ISSUE THREAD

**Issue by RomanSoloweow** [AvaloniaUI/Avalonia#5878]
When the element is moved, the Adorner has a draw lag.
The movement itself is implemented through TranslateTransform.

![adornerkek](https://user-images.githubusercontent.com/29205560/117289758-a6eeb300-ae75-11eb-9435-c0df7232a17d.gif)

This bug is especially noticeable in this frame:
![image](https://user-images.githubusercontent.com/29205560/117289785-aeae5780-ae75-11eb-9684-a1263f659652.png)

**Comment by RomanSoloweow** [comment]
The error is repeated if you implement movement through Canvas.Left and & Canvas.Top

**Comment by timothyparez** [comment]
I can confirm this as well.
You can also test this with the [AvaloniaBehaviors repository](https://github.com/wieslawsoltes/AvaloniaBehaviors.git) if
you enable Adorners on [this line](https://github.com/wieslawsoltes/AvaloniaBehaviors/blob/b069b05cd5c36d4ce2ad1c9a8b118b09318a012a/src/Avalonia.Xaml.Interactions/Draggable/CanvasDragBehavior.cs#L84)

**Comment by grokys** [comment]
The problem here is that the adorner layer uses the `TransformedBounds` property to calculate the exact position (after transforms, ancestor transforms etc) of the adorner, but this property is only updated on render, meaning that the adorner is a frame behind.

It should be possible to calculate the position without `TransformedBounds` but that would require listening for changes to every property that could affect visual positioning of the whole tree leading up to the adorned control, which doesn't seem like a great idea for performance.

Another (probably better) alternative would be to special-case the adorner layer in the renderer and update it after all other controls have had their `TransformedBounds` set.

**Comment by RomanSoloweow** [comment]
@grokys Are there any plans to work in this direction

**Comment by kvalitetskontrollMarkaryd** [comment]
When can we count on this being fixed?

I have another adorner layer issue. Validation error are shown twice. 

![Skarmbild-fran-2021-07-06-22-31-56](https://user-images.githubusercontent.com/40342638/125076385-23914e00-e0c0-11eb-9b4e-0967bea31e3b.png)

![Skarmbild-fran-2021-07-06-22-32-52](https://user-images.githubusercontent.com/40342638/125076486-43c10d00-e0c0-11eb-80d0-fd27f72ed5b1.png)

The second image shows how it looks after I put a letter in "Project name" TextBox and then remove it again. Then that TextBox is the only one that shows the error twice.
Is this related?

**Comment by maxkatz6** [comment]
@kvalitetskontrollMarkaryd I don't see anything related to adorner layer in your problem. 
Errors duplicating must be caused by actually multiple errors being set in view model and it depends on its implementation, you need to check it. WPF might distinct them though.

**Comment by RomanSoloweow** [comment]
Is there any work planned to fix the AdornerLayout?
If so, which version?

**Comment by kvalitetskontrollMarkaryd** [comment]
@maxkatz6 Are you sure?
I made a small sample project, have a look!

https://github.com/kvalitetskontrollMarkaryd/Avalonia.ValidationTest.git
