### ISSUE TITLE
NativeMenuItems not recovered after closing dialog

### ISSUE THREAD

**Issue by JMano** [AvaloniaUI/Avalonia#6007]
**Describe the bug**
Opening a dialog and, clicking on the owner window, closing the dialog and returning to the owner window does not restore the NativeMenuItems on the owner window.

**To Reproduce**

1. Have a main window with Native Menu defined and with a button to open a dialog
2. Open a dialog
3. While the dialog is open, click on the main window
4. Notice that the main mac window icons (close, minimize, maximize) become "active"
5. Close the dialog
6. Notice that the Native Menu is not recovered

**Expected behavior**
When closing the dialog and returning to the main window, the main window's Native Menu items should be displayed

**Screenshots**
Video:
https://user-images.githubusercontent.com/6922495/120515837-a25ee100-c3c6-11eb-80a3-ec09a160a219.mp4

Repo created with Rider Avalonia template:
https://github.com/JMano/Avalonia-NativeMenusBug

**Desktop (please complete the following information):**

- OS: [Mac]
- Version [0.10.1 - 0.10.6]. I confirmed that on 0.10.0 it was working as intended.

**Additional context**
As stated above in v0.10.0 was working fine but in v0.10.1 it doesn't.

**Comment by grokys** [comment]
Seems to be caused by `activateAppropriateChild` in `window.mm`. What's happening is:

- We show a child window
- Child window becomes key window
- We click parent window
- Parent window becomeKeyWindow is called
- Which calls activateAppropriateChild
- Which calls makeKeyAndOrderFront on the child window
- Which causes both parent and child windows to believe they are the key window

We update menus when windows become the key window, and two windows believing they are the key window completely breaks that logic.

Good news is AFAICS none of that logic is necessary any more, though we'll need a small tweak to prevent the parent of a dialog getting its menus shown.-
