### ISSUE TITLE
Dialog cancel consistency

### ISSUE THREAD

**Issue by nesrak1** [AvaloniaUI/Avalonia#6033]
**Describe the bug**
The file dialogs (`OpenFileDialog`, `SaveFileDialog`, and `OpenFileDialog`) do not have consistent return values when pressing cancel. On windows, I get `OpenFileDialog` returning empty array, `SaveFileDialog` returning null, and `OpenFolderDialog` returning an empty string. On linux, all of these return null when pressing cancel.

**To Reproduce**
Open different dialogs on different platforms, press cancel on them, and look at the return values.

```cs
private async void Test()
{
    OpenFileDialog ofd = new OpenFileDialog();
    string[] ofdRes = await ofd.ShowAsync(this);

    SaveFileDialog sfd = new SaveFileDialog();
    string sfdRes = await sfd.ShowAsync(this);

    OpenFolderDialog old = new OpenFolderDialog();
    string oldRes = await old.ShowAsync(this);

    response = $"openfile: {SetName(ofdRes)}, savefile: {SetName(sfdRes)}, openfolder: {SetName(oldRes)}";
}

private string SetName(string text)
{
    if (text == null)
        return "[null]";
    else if (text == "")
        return "[empty]";
    else
        return $"\"{text}\"";
}

private string SetName(string[] textArr)
{
    if (textArr == null)
        return "[null]";
    else if (textArr.Length == 0)
        return "[empty array]";
    else
        return $"\"{string.Join(", ", textArr)}\"";
}
```

**Expected behavior**
Should be consistent across all platforms. I'm not entirely sure what the cancel values for these dialogs are supposed to be. Maybe all null like on linux?

**Screenshots**

Windows
![windows](https://user-images.githubusercontent.com/12544505/121293990-3d1d5b00-c8b2-11eb-9ab9-97e35acb38ff.png)
Linux
![linux](https://user-images.githubusercontent.com/12544505/121293995-40184b80-c8b2-11eb-9802-4c267f752c93.png)

**Desktop (please complete the following information):**

- OS: Windows, Linux (PopOS w/ XFCE)
- Version 0.10.6

**Additional context**

**Comment by YgorSouza** [comment]
I looked around the code a bit, and I think if the desired behavior is to return null, it's enough to initialize the result to null [here](https://github.com/AvaloniaUI/Avalonia/blob/3e421266c294452cae04e650ce3aad1838fc9e37/src/Windows/Avalonia.Win32/SystemDialogImpl.cs#L22) and [here](https://github.com/AvaloniaUI/Avalonia/blob/3e421266c294452cae04e650ce3aad1838fc9e37/src/Windows/Avalonia.Win32/SystemDialogImpl.cs#L103) in the Windows implementation. If the desired behavior is to return an empty array/string, a null coalescing operator can be added [here](https://github.com/AvaloniaUI/Avalonia/blob/3e421266c294452cae04e650ce3aad1838fc9e37/src/Avalonia.X11/NativeDialogs/GtkNativeFileDialogs.cs#L146) and [here](https://github.com/AvaloniaUI/Avalonia/blob/3e421266c294452cae04e650ce3aad1838fc9e37/src/Avalonia.X11/NativeDialogs/GtkNativeFileDialogs.cs#L164) in the Linux implementation (and also add one [here](https://github.com/AvaloniaUI/Avalonia/blob/3e421266c294452cae04e650ce3aad1838fc9e37/src/Windows/Avalonia.Win32/SystemDialogImpl.cs#L95) for the Windows SaveFileDialog). However, I don't know which option is best. I am also not sure what the macOS implementation is doing, since it's written in Objective-C, but I believe it is returning null [here](https://github.com/AvaloniaUI/Avalonia/blob/3e421266c294452cae04e650ce3aad1838fc9e37/native/Avalonia.Native/src/OSX/SystemDialogs.mm#L65), [here](https://github.com/AvaloniaUI/Avalonia/blob/3e421266c294452cae04e650ce3aad1838fc9e37/native/Avalonia.Native/src/OSX/SystemDialogs.mm#L157) and [here](https://github.com/AvaloniaUI/Avalonia/blob/3e421266c294452cae04e650ce3aad1838fc9e37/native/Avalonia.Native/src/OSX/SystemDialogs.mm#L237).

**Comment by maxkatz6** [comment]
Returning empty array instead of null makes more sense for me.
Although I don't remember what it default value for WPF/UWP. If it's null there, we might prefer it just for compatibility.

> I am also not sure what the macOS implementation is doing

You are right about native objective-c code. But there is also a managed wrapper, which should be easier to modify for such a task.
https://github.com/AvaloniaUI/Avalonia/blob/3e421266c294452cae04e650ce3aad1838fc9e37/src/Avalonia.Native/SystemDialogs.cs

**Comment by nesrak1** [comment]
> Although I don't remember what it default value for WPF/UWP. If it's null there, we might prefer it just for compatibility.

For wpf, its `ShowDialog`s return a success bool and the result is in FileName(s) (which is empty string or empty array).
For uwp, its `PickSingleFileAsync` returns a `StorageFile` which is null if canceled.

I think I prefer null since it's consistent across all dialogs and easier to check for than empty string and empty array, but empty string and empty array would be closer to what wpf does.

**Comment by YgorSouza** [comment]
Thank you for the pointer to the macOS wrapper. So if I am understanding it correctly, [this](https://github.com/AvaloniaUI/Avalonia/blob/3e421266c294452cae04e650ce3aad1838fc9e37/src/Avalonia.Native/SystemDialogs.cs#L45) should return and empty array for the file dialogs, due to it being initialized [here](https://github.com/AvaloniaUI/Avalonia/blob/3e421266c294452cae04e650ce3aad1838fc9e37/src/Avalonia.Native/SystemDialogs.cs#L78). However, the folder dialog calls `FirstOrDefault()` [here](https://github.com/AvaloniaUI/Avalonia/blob/3e421266c294452cae04e650ce3aad1838fc9e37/src/Avalonia.Native/SystemDialogs.cs#L56), so it should return `null` if the array is empty, since that is the default value for string. So one of those has to be changed as well.

**Comment by YgorSouza** [comment]
One argument for returning empty over null is that you wouldn't need to change anything later if you decided to enable nullable reference types, whereas if you return null you have to change the return type to `string?` and `string[]?` and that would be a breaking change.

**Comment by FoggyFinder** [comment]
Any resolution on this?

**Comment by workgroupengineering** [comment]
I would make a PR, but i don't know what is correct  behavior between Window and Linux.

**Comment by maxkatz6** [comment]
Personally I would expect null string as default and empty array as default. Having nullable array is not good practice usually.

**Comment by workgroupengineering** [comment]
> 
> 
> Personally I would expect null string as default and empty array as default. Having nullable array is not good practice usually.

On PR #6160 i used Linux  behavior .

@grokys @kekekeks  What behavior do you recommend?
