### ISSUE TITLE
Flyout IsOpen Not Working

### ISSUE THREAD

**Issue by renrutsirhc** [AvaloniaUI/Avalonia#6081]
**Describe the bug**
When setting the IsOpen property in XAML, the following error occurs:

System.MethodAccessException: 'Attempt by method 'FlyoutTest.Views.MainWindow.!XamlIlPopulate(System.IServiceProvider, FlyoutTest.Views.MainWindow)' to access method 'Avalonia.Controls.Primitives.FlyoutBase.set_IsOpen(Boolean)' failed.'

**To Reproduce**

Create new project.
Add following Xaml to MainWindow:
```
  <TextBlock Text="{Binding Greeting}" HorizontalAlignment="Center" VerticalAlignment="Center">
    <FlyoutBase.AttachedFlyout>
      <Flyout IsOpen="true">
        <TextBlock Text="This is some text in a flyout."  />
      </Flyout>
    </FlyoutBase.AttachedFlyout>
  </TextBlock>
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/12220071/122176881-3063bd00-ced9-11eb-9af2-25085f2ce7ac.png)

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Mac, Linux (State distribution)] WIndows 10
- Version [e.g. 0.10.0-rc1 or 0.9.12] 0.10.6

**Additional context**

**Comment by kekekeks** [comment]
https://github.com/AvaloniaUI/Avalonia/blob/453610836f00198e4f3738ae7aa2484e8be155d2/src/Avalonia.Controls/Flyouts/FlyoutBase.cs#L62 - the property seems to be readonly.

Compiler not complaining about it being readonly is definitely a bug though.

**Comment by maxkatz6** [comment]
You need to use [ShowAttachedFlyout](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Flyouts/FlyoutBase.cs#L110) or [ShowAt](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Flyouts/FlyoutBase.cs#L120).
IsOpen is readonly. Having it settable does not makes much sense since flyout is often shared between controls/different targets.
