### ISSUE TITLE
Implement ItemsControl.IsTextSearchEnabled 

### ISSUE THREAD

**Issue by Royce551** [AvaloniaUI/Avalonia#6086]
**Is your feature request related to a problem? Please describe.**
In WPF and most other Windows apps, you can type in lists to select the first entry that matches what you typed. This doesn't appear to be possible in Avalonia.

**Comment by maxkatz6** [comment]
I think you are looking for AutoCompleteBox, which is basically drop down control with search input.
Simpler ComboBox also has IsTextSearchEnabled property, but it does not provide text input box.

**Comment by Royce551** [comment]
Hi, thanks for the quick response! Sorry, I might not have been clear enough. The feature I'm talking about is a hidden shortcut for quickly navigating long lists, similar to this:

https://user-images.githubusercontent.com/31809541/122317905-e16f5500-cee3-11eb-8e22-811f8a436a4b.mp4

**Comment by maxkatz6** [comment]
Oh, I got it. You need something similar to [ItemsControl.IsTextSearchEnabled](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.itemscontrol.istextsearchenabled?view=net-5.0).
Since we already have it for ComboBox only, it should be easier to add it to abstract ItemsControl.

I don't think it will be easy to add "TextSearch.TextPath" or equivalent though, since we need always prefer compile time properties without using reflection over property name.

**Comment by maxkatz6** [comment]
Meanwhile it shouldn't be hard to implement your own implementation of ListBox that will listen for TextInput
