### ISSUE TITLE
Add Support for Backtick/Backquote key

### ISSUE THREAD

**Issue by CodingFlow** [AvaloniaUI/Avalonia#6148]
**Is your feature request related to a problem? Please describe.**
Wanted to add a keyboard shortcut to a UI using the Backtick "`" key, but Avalonia does not support it: http://reference.avaloniaui.net/api/Avalonia.Input/Key/

**Describe the solution you'd like**
Add support for the Backtick key as for other keys as shown in the docs: http://reference.avaloniaui.net/api/Avalonia.Input/Key/

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by grokys** [comment]
Backtick is mapped to `Oem8` on my machine; because keys such as backtick are OEM specific we can't really provide a definite mapping at this level. A better alternative would be to use the `TextInput`  event because this event is at a higher level and uses the OS facilities to map virtual key codes to characters.
