### ISSUE TITLE
Datagrid - Right click does not select an item

### ISSUE THREAD

**Issue by 0x90d** [AvaloniaUI/Avalonia#6393]
### **Describe the bug**
Right clicking on a Datagrid item does not select it

### **To Reproduce**
In control catalog right click on an item in the Datagrid

### **Expected behavior**
On Listbox etc. the item gets selected on right click so I expect the same on Datagrid.

### **Desktop (please complete the following information):**

- OS: Windows
- Version 0.10.999-cibuild0014036-beta & tested on master branch

**Comment by robloo** [comment]
This is by design but I agree is probably not the best.

This was discussed a few places in the Windows Community Toolkit I'm aware of. I gave some code examples to do what you are trying do and it should work for Avalonia with slight modifications.

(make sure to expand the **View Code** section)
https://github.com/CommunityToolkit/WindowsCommunityToolkit/issues/2249#issuecomment-439667954

https://github.com/CommunityToolkit/WindowsCommunityToolkit/issues/2388#issuecomment-434894891

**Comment by 0x90d** [comment]
I don't know anything about Windows Community Toolkit but I know that the current behavior confuses a lot of users and it's completely inconsistent to the behavior of other Avalonia controls. It is also not what you see if you right click on something in your file explorer. It needs to be changed. I also made a pull request.
