### ISSUE TITLE
Don't repaint window every frame

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/Avalonia#646]
We currently repaint the whole window on every frame. This is obviously not ideal - we should just repaint the dirty regions.

**Comment by nc4rrillo** [comment]
I took a stab at this, by having the `RenderNeeded` stream in the `RenderQueueManager` pass the transformed bounds of the visual, which then got passed to the `Invalidate` method of `ITopLevelImpl`. 

I did this and some things seem to work, anything involving dirtying layout is broken, so I need to look into that. 

This seems like only half the battle though, as the entire Visual Tree still gets walked and rasterized. It seems like the `Paint` callback in `ITopLevelRenderer` passes the top level visual to `IRenderTarget.Render`. So we need a way to go from the bounds that get passed to the callback to the Visual.

**Comment by nc4rrillo** [comment]
I've done some work on my `dirty-region` branch [here](https://github.com/nc4rrillo/Avalonia/tree/dirty-region)

I mark nodes as dirty on `InvalidateVisual` and in `IRenderTarget.Render` I draw only the ones that have been dirtied since the last frame. In `ITopLevelRenderer` the `Paint` callback handles clearing the dirty bits from the visuals once done. 

There are some rendering artifacts, here and there, and I'm certain the dirty rect getting sent for invalidation is off, but maybe it is a start?
