### ISSUE TITLE
Mac App Store sandbox crash

### ISSUE THREAD

**Issue by Mikolaytis** [AvaloniaUI/Avalonia#6529]
**Describe the bug**
sandboxed mac app store package is crashed on NSApplication initialization.

**To Reproduce**

1. Create empty avalonia app
2. Create .app package and publish app into it
3. Sign app package as mac app store install with sandbox enabled entitlement
4. Move app to /Applications folder and launch it

**Expected behavior**
App launches without crash

**Additional context**

Error string:
```
rdar://problem/28724618 Couldn't create connection object
<rdar://problem/28724618> Process unable to create connection because the sandbox denied the right to lookup com.apple.coreservices.launchservicesd and so this process cannot talk to launchservicesd.
XPC_ERROR_CONNECTION_INVALID from launchservice
_RegisterApplication(), unable to get application ASN from launchservicesd, and this application requires an ASN, so aborting.  error=#-1.
```

StackTrace (read from end, it;s starting from osx native library):
```
0   libsystem_kernel.dylib   mach_msg_trap + 10
1   libxpc.dylib             _xpc_pipe_mach_msg + 49
2   libxpc.dylib             _xpc_pipe_routine + 264
3   libxpc.dylib             xpc_pipe_routine_with_flags + 56
4   libxpc.dylib             _xpc_interface_routine + 179
5   libxpc.dylib             _xpc_look_up_endpoint + 231
6   libxpc.dylib             _xpc_connection_bootstrap_look_up_slow + 401
7   libxpc.dylib             _xpc_connection_init + 448
8   libxpc.dylib             _xpc_connection_activate_if_needed + 73
9   LaunchServices           invocation function for block in LSClientToServerConnection::setupServerConnection(int, __CFDictionary const*) + 420
10  libdispatch.dylib        _dispatch_client_callout + 8
11  libdispatch.dylib        _dispatch_once_callout + 20
12  LaunchServices           LSClientToServerConnection::setupServerConnection(int, __CFDictionary const*) + 2908
13  LaunchServices           LSClientToServerConnection::LSClientToServerConnection(int, __CFDictionary const*) + 116
14  LaunchServices           _LSApplicationCheckIn + 2439
15  HIServices               _RegisterApplication + 6632
16  HIServices               GetCurrentProcess + 23
17  HIToolbox                MenuBarInstance::GetAggregateUIMode(unsigned int*, unsigned int*) + 63
18  HIToolbox                MenuBarInstance::IsVisible() + 51
19  AppKit                   _NSInitializeAppContext + 35
20  AppKit                   -[NSApplication init] + 417
21  AppKit                   +[NSApplication sharedApplication] + 120
22  libAvaloniaNative.dylib  InitializeAvnApp(IAvnApplicationEvents*) + 33
23  libAvaloniaNative.dylib  AvaloniaNative::Initialize(IAvnGCHandleDeallocatorCallback*, IAvnApplicationEvents*) + 180
```

MetaData: 
```json
{
  "hardware": "Mac",
  "responsible-process-path": "/Applications/Lunacy.app/Contents/MacOS/Lunacy",
  "apple-internal": false,
  "process": "Lunacy",
  "profile-flags": 0,
  "uid": 501,
  "platform-binary": false,
  "action": "deny",
  "errno": 1,
  "platform_binary": "no",
  "container": "/Users/brutal/Library/Containers/com.icons8.Lunacy/Data",
  "checker-pid": 1,
  "operation": "mach-lookup",
  "pid": 21580,
  "mach_namespace": 1,
  "primary-filter": "global-name",
  "checker": "launchd",
  "flags": 5,
  "team-id": "L87ZGZ3STE",
  "profile-in-collection": false,
  "normalized_target": [
    "com.apple.coreservices.launchservicesd"
  ],
  "summary": "deny(1) mach-lookup com.apple.coreservices.launchservicesd",
  "platform-policy": false,
  "process-path": "/Applications/Lunacy.app/Contents/MacOS/Lunacy",
  "sandbox_checker": "launchd",
  "signing-id": "com.icons8.Lunacy",
  "build": "macOS 11.5.2 (20G95)",
  "target": "com.apple.coreservices.launchservicesd",
  "primary-filter-value": "com.apple.coreservices.launchservicesd",
  "global-name": "com.apple.coreservices.launchservicesd"
}
```

**Comment by Mikolaytis** [comment]
I'm fighting this crash for 2 days already and my energy is lost on this already.
Here is a list what I've tried.

1) I've googled the issue A LOT.
2) I've read all the apple documentation about sandbox 3 times.
3) [I've found the same issue was occurred with WasabiWallet](https://developer.apple.com/forums/thread/127915)
4) I've found the same issue was in electron and I don't understand how they did fix it.
5) I've tries to sign package with tons of entitlements options - no result
6) [I've thought I found a solution - but this was just a typo in entitlement and sandbox was disabled. that was sad a lot, because I've already lost a lot of time writing a wrong guide in avalonia documentation.](https://github.com/AvaloniaUI/Documentation/pull/88)

**Comment by kekekeks** [comment]
I suspect that [SetProcessName](https://github.com/AvaloniaUI/Avalonia/blob/3aa38398ff28012d7d296966a6df7d86e42f1424/native/Avalonia.Native/src/OSX/main.mm#L11) somehow messes the initialization in sandbox mode

**Comment by kekekeks** [comment]
Try a build from this PR once CI finishes https://github.com/AvaloniaUI/Avalonia/pull/6531

**Comment by kekekeks** [comment]
Also try adding `com.apple.security.temporary-exception.mach-lookup.com.apple.coreservices.launchservicesd` entitlement

**Comment by Mikolaytis** [comment]
Wow! Thanks! I've already tried to remove this code yesterday. and a lot of other code that works with menus in native lib. I've thought that these call stack lines are matter's somehow...
```
MenuBarInstance::GetAggregateUIMode(unsigned int*, unsigned int*) + 63
MenuBarInstance::IsVisible() + 51
```
So I'm already using supper cutted native lib. No effect :( 
But another suggestion helps!
```
        <key>com.apple.security.temporary-exception.mach-lookup.global-name</key>
	<array>
		<string>com.apple.coreservices.launchservicesd</string>
	</array>
```
adding this lines are doing it. App launches and I can continue to adopt our app to macOS sandbox. Thanks!
I will not close this issue, because I think that these lines in entitlements can cause problems on app store certification/verification stage. So the best resolution scenario - is find a source of a problem and fix usage of `launcheservicesd`. 
I will play more with it. I will try to restore native lib to it's current state, and check if it's works. Also I will notify about certification/verification result later next week.

**Comment by kekekeks** [comment]
Note that temporary exceptions have to be approved by apple through some procedure. See the docs about them. 

So it's a temporary measure until we figure out what's wrong

**Comment by Mikolaytis** [comment]
Test results:

Your PR with entitlements edit = works.
Your PR without entitlements edit = do not work.
0.10.7 with entitlements edit = works.
0.10.7 without entitlements edit = do not work, obviously.

So PR has no effect. And it's 100% this method not the source of the issue, but will be a problem if the source of the issue will be fixed. 

Also I've tried to remove all redundant includes in `.h` `.mm`, because it's maybe a code in include caused a problem - no effect. I did not tried to cut all COM related code... I don't think this is the source of the issue.

**Comment by Mikolaytis** [comment]
App is declined. Here is a reason.

> ### Guideline 2.4.5(i) - Performance
> We've determined that one or more temporary entitlement exceptions requested for this app are not appropriate and will not be granted:
> * com.apple.security.temporary-exception.mach-lookup.global-name
> * com.apple.coreservices.launchservicesd
>
> We understand this may prevent the app from being approved for the Mac App Store. We encourage you to investigate other ways of implementing the desired functionality.

I will look more into this later. Maybe I will find a solution. Also I will try to get apple support on this. Maybe they can help.

**Comment by Mikolaytis** [comment]
Solution is already in Avalonia documentation. Just use .net 6 single exe publish.

**Comment by emayevski** [comment]
Unfortunately, 5 years later, the same problem exists. A single-exe publish is not a solution because single-exe applications start about 100% slower (and slow startup is already a problem for Avalonia).

**Comment by maxkatz6** [comment]
> A single-exe publish is not a solution because single-exe applications start about 100% slower.

Single file is not a solution, it's a requirement. It makes signing much more difficult without.
Note, it shouldn't really slow down the startup significantly, unless you also set `IncludeNativeLibrariesForSelfExtract` (which adds an overhead of self-extracting archive, and generally not recommended, especially for Apple).

> and slow startup is already a problem for Avalonia

We are aware of JIT compilation slowing down Avalonia startup. But it's a common issue with .NET applications, often solvable by ReadyToRun or PublishAot, which you prefer. 
Other than that, if you have any measurable startup issues - please report them.

**Comment by emayevski** [comment]
> > A single-exe publish is not a solution because single-exe applications start about 100% slower.
> Single file is not a solution, it's a requirement. It makes signing much more difficult without. 

Signing is a non-issue, and the application works perfectly without a single-exe. It works fine in direct distribution and in app store mode (if the entitlement is included). The only problem is the dependency on the entitlement, which Apple denies. And the question is that it is not .NET but Avalonia (via specific calls) that requires that entitlement for store apps.  

> Note, it shouldn't really slow down the startup significantly, unless you also set `IncludeNativeLibrariesForSelfExtract` (which adds an overhead of self-extracting archive, and generally not recommended, especially for Apple).

The last time I tried, the difference was about 2 seconds. This may be nothing for a longer-term application, but for an application that may be called for one small operation (e.g., a calculator), this is a deal breaker. 

> > and slow startup is already a problem for Avalonia
> We are aware of JIT compilation slowing down Avalonia startup. But it's a common issue with .NET applications, often solvable by 

It's not JIT, I think, but the number of layers in UI controls - the UI elements are to be created, initialized, positioned... This can be measured, but this thread is not about loading speed. 

> ReadyToRun or PublishAot, which you prefer. 

The last time I tried them, the UI was not rendered properly, and there were other artifacts in the behavior, so I gave up on this idea. 

> Other than that, if you have any measurable startup issues - please report them.

If I can't convince Apple to grant the exclusion, I will have to revert to single-file distribution (or say f.u. apple and forget about appstore). Then, I'll do the measurements.

**Comment by maxkatz6** [comment]
`ReadyToRun` should not affect rendering - it's a JIT pre-compilation, it doesn't remove code or change how it's executed.
But `PublishAOT` might break stuff. Avalonia itself is compatible with AOT, but user apps might need adaptation. 

> The last time I tried, the difference was about 2 seconds

2 seconds is a lot, especially if it's not JIT. Something like this should be measured. Please let us know, if you find something.

**Comment by emayevski** [comment]
@maxkatz6  Yes, I have imagined a way to easily make cross-platform tests, so I will do this and update you.

**Comment by emayevski** [comment]
@maxkatz6 My data were outdated. Probably,  I experienced the slowdown while the application was using .NET 9 (now it's on .NET 10). I can only guess at the moment, but my rather extensive tests (of the unsigned modules - signature verification can affect load time, but that's a different story) do not expose any significant difference in the loading time. The difference is within 200 msec, and even sometimes, the single-file variants even win. So, I guess I will not bother with appeals and will build a single-file application for apple app store. Thank you for motivating me to do the tests.

**Comment by DSDTECH-co** [comment]
Same crash here, and we managed to narrow it down. Short version: this is not an Avalonia bug — it reproduces with no Avalonia at all, and NativeAOT avoids it entirely.

Environment: macOS 26.6.1 (Apple Silicon), .NET 10.0.11, Avalonia 12.1.0, signed with a Mac Development certificate plus a development provisioning profile, App Sandbox enabled.

## The failure

```
Sandbox: MyApp(61975) deny(1) mach-lookup com.apple.coreservices.launchservicesd
HIServices: _RegisterApplication(), unable to get application ASN from launchservicesd,
            and this application requires an ASN, so aborting.
```

Only that one service is denied. In the same process `cfprefsd`, `tccd`, `com.apple.fonts` and `pasteboard` all connect fine, so this is not a wholesale sandbox restriction.

## It is not Avalonia

A ~15-line .NET console app that only `dlopen`s AppKit and calls `[NSApplication sharedApplication]` — no Avalonia, no XAML — aborts with exactly the same stack.

Conversely, replacing **only the main binary** of the *same* `.app` bundle (same signature, same entitlements, same launch path) with a small Swift program registers fine.

## What we ruled out

Each of these was measured, not reasoned about:

- **Entitlements.** `app-sandbox` alone; plus `allow-jit` / `allow-unsigned-executable-memory` / `disable-library-validation`; with and without `application-identifier`. No difference.
- **Bundle contents, Info.plist, signing flow.** Swapping just the main binary flips the result.
- **Launch path.** `open` (launchd) and direct exec from a terminal both fail.
- **Timing.** Sleeping 5 s before touching AppKit still fails.
- **JIT.** A Swift probe that writes and executes code in `MAP_JIT` memory still registers fine.
- **Code-signing state.** `csops(CS_OPS_STATUS)` returns an identical status word (`0x62014301`, `CS_VALID` set) for the working Swift process and the failing .NET one.
- **Deployment target.** Rebuilding the Swift probe with `-target arm64-apple-macos12`, matching the apphost's `minos`, still works.
- **Merely loading the runtime.** `dlopen`ing `libcoreclr` / `libclrjit` / `libhostfxr` from the Swift probe and then touching AppKit still works.
- **exec/spawn indirection.** The pid LaunchServices launches is the pid that aborts; there is no intermediate process.

So it is something CoreCLR does *while running*, not a property of the binaries themselves. We did not get further than that.

## NativeAOT does not hit it

The same minimal program published with `PublishAot=true` registers fine.

More usefully: a minimal **Avalonia 12.1.0** app (window built in code, no XAML) published with NativeAOT opens its window under App Sandbox with only

```
com.apple.security.app-sandbox
com.apple.application-identifier
com.apple.developer.team-identifier
```

that is, **none** of the `cs.*` entitlements.

Three things that bit us on the way, in case they save someone else time:

1. NativeAOT links `-lssl -lcrypto -lbrotli*`. If those resolve to Homebrew **dylibs**, the app dies at launch under sandbox + hardened runtime with `code signature ... not valid for use in process: ... different Team IDs`. Point `-L` at a directory containing only the `.a` files so they link statically.
2. `libSkiaSharp` / `libHarfBuzzSharp` / `libAvaloniaNative` must sit inside the bundle and be signed by you. Otherwise the loader reports `relative path not allowed in hardened program`.
3. Signing with a certificate that the embedded provisioning profile does not list fails as `Launchd job spawn failed` (POSIX 163), which looks like a broken binary. The real reason shows up only in the system log: `taskgated-helper: Unsatisfied entitlements: com.apple.developer.team-identifier`.

**Update (2026-08-19): it shipped.** The NativeAOT build is signed with the store certificates (`3rd Party Mac Developer Application` + `Mac Installer Distribution`), packaged as a `.pkg`, and is now live on the Mac App Store.

App Review raised nothing about any of the above. We did get one rejection, `Guideline 2.1 - Information Needed`, and it was our own doing — the review notes had been pasted in truncated. Resubmitting with complete notes passed.

So this is not just a local workaround: **NativeAOT + App Sandbox passes review and ships**. CoreCLR still aborts exactly as described above.
