### ISSUE TITLE
Popup menu follows TextBox font (it shouldn't)

### ISSUE THREAD

**Issue by kuiperzone** [AvaloniaUI/Avalonia#6568]
**Describe the bug**
I am using a TextBox control to show code and, thus, and have set the box to a monospace font. Right-clicking on it shows a pop-up with Copy, Paste etc. However, the popup menu also displays in monospace font. Popup menu fonts seem to follow the parent control.

**Expected behavior**
Popup menus should follow the window or theme font, not the parent control font.

**Desktop (please complete the following information):**
- OS: Linux (PopOS 21)
- Version 0.10.7

**Screenshot
Seems impossible to capture popup menu on Linux. Could provide photo of screen if necessary.

PS. Avalonia is great by the way! Thanks

**Comment by maxkatz6** [comment]
@grokys popup inherits properties from its parent. Including font properties. Is it expected behavior to do so?
It would be nice to have a way to ignore inherited values (css has it, see discussion https://github.com/AvaloniaUI/Avalonia/discussions/6163#discussioncomment-958814).
For now, we can either disable all values inheriting for the popup (not sure how to do so). Or override specific property values with default values (easiest way and app develop can do it on their side as a workaround).

**Comment by kuiperzone** [comment]
>popup inherits properties from its parent. Including font properties. Is it expected behavior to do so?

I'm not sure it makes sense in the context I describe. Although I understand there may be bigger issues than this. My initial thought is that it should follow the window, or perhaps be set in a (default) theme.

![image](https://user-images.githubusercontent.com/17156238/132813786-366ae33e-0027-47fe-aa5e-ec9d78d164e7.png)
