### ISSUE TITLE
Contextmenu subitems are cut off in width

### ISSUE THREAD

**Issue by 0x90d** [AvaloniaUI/Avalonia#6674]
**Describe the bug**
A subitem of a context menu is cut off in width although there is enough space to fully show the menu item.

**To Reproduce**

See additional context below

**Expected behavior**
There is enough width to fully show the context menu item.

**Screenshots**
![image](https://user-images.githubusercontent.com/46010672/135800907-0dbd059d-45d5-470a-b980-33c9791c32ee.png)

**Desktop (please complete the following information):**

- OS: Windows
- Version 0.10.999-cibuild0014036-beta

**Additional context**
Item header is set this way, it may be the stackpanel causing it?:
```XAML
<MenuItem Command="{Binding CreateSymbolLinksForSelectedItemsAndBlacklistCommand}"  ToolTip.Tip="Links all selected items to the first unselected item in each group.">
	<MenuItem.Header>
		<StackPanel Orientation="Horizontal">
			<Viewbox Width="16" Height="16">
				<Canvas Width="24" Height="24">
					<Path Data="M19,4H15.5L14.5,3H9.5L8.5,4H5V6H19M6,19A2,2 0 0,0 8,21H16A2,2 0 0,0 18,19V7H6V19Z" Fill="Red" />
				</Canvas>
			</Viewbox>
			<TextBlock
				Margin="5,0,0,0"
				VerticalAlignment="Center"
				Text="Remove from list only + create symbol links and exclude from future scans" />
		</StackPanel>
	</MenuItem.Header>
<MenuItem/>
```

**Comment by maxkatz6** [comment]
Probably that's the reason:
https://github.com/AvaloniaUI/Avalonia/blob/845dc90906c441e5b38ae0c7ccac390192023eb4/src/Avalonia.Themes.Fluent/Controls/MenuItem.xaml#L121
https://github.com/AvaloniaUI/Avalonia/blob/845dc90906c441e5b38ae0c7ccac390192023eb4/src/Avalonia.Themes.Fluent/Accents/BaseLight.xaml#L164

> Item header is set this way, it may be the stackpanel causing it?:

Stackpanel text blocks text wrapping there, if you set it. 

Not sure if it's a bug, because your menu is too wide as for usual menu item, and users might expect text wrapping there (or better less text). Also you can globally override FlyoutThemeMaxWidth with your own value.
