### ISSUE TITLE
Style Classes as Dictionary

### ISSUE THREAD

**Issue by RomanSoloweow** [AvaloniaUI/Avalonia#6835]
In Avalonia, the VisualStateManager is implemented through Style Classes.

With the current implementation, you have to write similar constructions:
```c#
Classes.RemoveAll (Classes.Where (c => c.StartsWith ("state-")));
Classes.Set($"state-{MyState}");
```

I suggest using a dictionary inside [Classes](https://github.com/AvaloniaUI/Avalonia/blob/efdacaf1d117516c9a7035dd7199883e47e1742f/src/Avalonia.Styling/Controls/Classes.cs).

Then working with states will look like this
```c#
Classes.RemoveByKey("State");
Classes.AddByKey("State", MyState);
```

**Comment by PieroCastillo** [comment]
that's the reason of the existence of ````Pseudoclasses``` 
here I had a minimal funcional example:
https://github.com/PieroCastillo/AnimationOnTabControlChange/blob/d6a09baead3e3a01d2ab56295e6eee12b1d11f13/AnimationOnTabControlChange/AnimateTabControl.cs

**Comment by maxkatz6** [comment]
You technically can create these two methods as extension methods, and format classes like $"State-{MyState}", which can be used later in selectors. 
If we even consider classes as a dictionary internally, it will require revisiting how class selectors should work at all, because you can't just write "Control.State=MyState". Property selector is expected for that.
