### ISSUE TITLE
Add Monodevelop Addin

### ISSUE THREAD

**Issue by SiNeumann** [AvaloniaUI/Avalonia#687]
I don't know if something like this is planned or anyone did it . Building Avalonia and working with sample projects works great, but creating a new project from scratch and get everything righ is not straightforward.  Actually just adding xaml + xaml.cs files forces you to manually edit .csproj file. So if it is ok I would start with an Addin for Monodevelop, first version would just add the right NuGetVersion, hand have a project and file template. Later on maybe SyntaxHighlighting for Xaml files.

**Comment by grokys** [comment]
Hi @SiNeumann - sorry for the delay; I was on vacation when you posted this. Yes, go for it! It's definitely something we'd like.

**Comment by kekekeks** [comment]
Since MonoDevelop doesn't have .NET Core debugging support and their way of distribution via flatpak doesn't allow apps to use GTK3, we no longer view it as a viable IDE to develop Avalonia-based apps.

**Comment by aaronfranke** [comment]
@kekekeks Are there alternative IDEs that you recommend for developing Avalonia apps on Linux?

**Comment by jmacato** [comment]
@aaronfranke https://github.com/VitalElement/AvalonStudio/ could try that? :) And although i dont see any technical issues with mono, we highly recommend you using .NET Core instead.

**Comment by michieal** [comment]
... Except for the fact that in MonoDevelop, under New Project, in the "Choose a template for your new project" it has .NET Core listed... with templates... So, this really should be reopened and considered, unless there's another issue preventing Mono from having access to the coolest UI around...

Also, per Dan Walmsley, he simply doesn't have the time to maintain Avalon Studio. Which is really sad, because if the couple of little bugs were fixed... it would be an epic IDE that is cross platform... And, as someone that misses his Visual Studio, that thinks VS Code is a text editor on meth (and not in a good way, if that's even possible), and no longer uses windows except for in a VM. I'd love to have a REAL IDE that just works natively in Ubuntu Linux.

**Comment by kekekeks** [comment]
>has .NET Core listed... with templates... 

Debugger does not work and won't work due to licensing.

**Comment by kekekeks** [comment]
>I'd love to have a REAL IDE that just works natively in Ubuntu Linux.

https://www.jetbrains.com/rider/ comes with first class support for Avalonia

**Comment by michieal** [comment]
> > has .NET Core listed... with templates...
> 
> Debugger does not work and won't work due to licensing.

I did not know that. Interesting. I assume that it's a licensing issue with Microsoft; them not wanting too much competition with VS?

> > I'd love to have a REAL IDE that just works natively in Ubuntu Linux.
> 
> https://www.jetbrains.com/rider/ comes with first class support for Avalonia

I always forget about jetbrains. After an incident with their billing system over PHPStorm, I mentally block them out. (They don't allow, or didn't at that time, to buy the subscriptions in multiple months... I hate automatic monthly bills to rent software.)

Okay. Thank you for the info!

**Comment by danwalmsley** [comment]
The give free licenses for open source projects, if you doing a lot of .net development, even a personal license is worth it and very reasonable pricing now.

**Comment by michieal** [comment]
> The give free licenses for open source projects, if you doing a lot of .net development, even a personal license is worth it and very reasonable pricing now.

That too, I didn't know. I'd still love to use Avalon Studio... Hell, if I had more time to go through the source and see what's what... I'd offer to take up the mantle of bring new life into it.
