### ISSUE TITLE
Implement  Password Char on TextBox

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#690]

**Comment by nc4rrillo** [comment]
In WPF this is on PasswordBox, and in WinForms its on TextBox. Should we go the WPF route?

**Comment by danwalmsley** [comment]
@nc4rrillo is there a good reason to have it separate? Perhaps PasswordBox is more secure, I.e. encrypts underlying data and prevents copy / paste?

**Comment by nc4rrillo** [comment]
@danwalmsley Yes, it seems to have optional in memory encryption. 
https://msdn.microsoft.com/en-us/library/system.windows.controls.passwordbox.securepassword(v=vs.110).aspx

**Comment by grokys** [comment]
I've always found the WPF `PasswordBox` to be a real PITA - it doesn't support binding and i've never really cared about in-memory encryption. It would be nice to have the *option* of WinForms' way of doing it,

**Comment by zezba9000** [comment]
Personally I never liked how WPF had a separate type the way it did (.password instead of .text was needed etc). Normally you don't need encryption, you just don't want the world to know your password when you're looking at your settings of an app/account. Also the TextBox could just support other "password" like feature if needed in the future. Even if there was a separate "PasswordBox" type it would just be derived of TextBox in my mind.... so not a big deal either way.

**Comment by BlackDragonBE** [comment]
Is there any news on this or a workaround? I don't need encryption, but I want the visible characters to be replaced with a certain character.

**Comment by tiberiumdvk** [comment]
Right now you can't even implement it yourself using TextBox, because it doesn't even check for e.Handled in default OnTextInput. Kinda defeats the purpose of keeping track of events handled property if you don't check against it.

**Comment by danwalmsley** [comment]
If another control sets e.Handled it won't reach the TextBox right?

**Comment by danwalmsley** [comment]
There is now a PR ready to merge implementing this.

**Comment by danwalmsley** [comment]
This is finally implemented.

**Comment by markmercer10** [comment]
> This is finally implemented.
Care to tell us how????

**Comment by LazaroOnline** [comment]
Here is an example of how to do it:
```xaml
<TextBox Classes="revealPasswordButton" PasswordChar="•" />
```
