### ISSUE TITLE
ListBox strange behavior

### ISSUE THREAD

**Issue by RomanSoloweow** [AvaloniaUI/Avalonia#6901]
I have a list of items, the parts of which I set IsVisible = false, depending on the current item type.
Items are displayed in the Popup.

If I display them in a ListBox, then the popup behaves strangely. Some of the elements are not visible at all
![Listboxinpopup](https://user-images.githubusercontent.com/29205560/140963442-f6081ad0-1286-43be-9f37-c472c1cc1d66.gif)

I tried to expose:
```Xaml
ScrollViewer.HorizontalScrollBarVisibility = "Disabled"
ScrollViewer.VerticalScrollBarVisibility = "Disabled"
```
**but it did not help**

If I display them in an ItemControl then everything works as expected:
![itemControl in popup](https://user-images.githubusercontent.com/29205560/140963422-b4a9b4cb-4c15-4c81-9dec-06aee2a1b4bd.gif)

**Comment by RomanSoloweow** [comment]
When I set 
```XAML
ScrollViewer.HorizontalScrollBarVisibility = "Disabled"
ScrollViewer.VerticalScrollBarVisibility = "Disabled"
```
![Listboxinpopupwithdisabledscroll](https://user-images.githubusercontent.com/29205560/140966401-da1a3605-a33d-4bbc-9e63-64e6b91c145b.gif)

**Comment by timunie** [comment]
Hi @RomanSoloweow 

I saw the same with `DataGrid`. Instead of hiding the items I ended up adding / removing them on demand, eg. via a filtered Collection (I use [DynamicData](https://www.reactiveui.net/docs/handbook/collections/)). I've heared that ItemsRepeater handles this in a better way, but I cannot promise. 

Happy coding 
Tim
