### ISSUE TITLE
Wrong popup position when working with multiple monitors

### ISSUE THREAD

**Issue by danipen** [AvaloniaUI/Avalonia#7164]
**Describe the bug**
We're experiencing an issue positioning a context menu, when the Avalonia window is between two screens with different DPI configuration. Please, see the following video for a detailed explanation:

https://www.loom.com/share/e30aea24416b4209aacccdbb85e0c51d

**To Reproduce**
Minimal repro case repository: https://github.com/danipen/ContextMenuPlacementBug

1. Execute the example.
2. Maximize the window.
3. Click the button to show the context menu.

**Desktop**

- OS: Windows
- Version: 0.10.1

**Comment by grokys** [comment]
First part of the problem seems to be this code:

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Primitives/PopupPositioning/ManagedPopupPositioner.cs#L109-L113

Which uses `Rect.Contains` which is inclusive of the right/bottom edge (confusingly, but taken from WPF). This means that if you have two screens with bounds:

- `-1000,0,1000,1000`
- `0,0,1000,1000`

Then the first screen is matched as having the point 0,0 instead of the second, and causes the menu to show on the wrong screen.

**Comment by grokys** [comment]
The second part of the problem is that popups take their DPI from the screen which they're on, but in this case that screen is different to the screen that the parent window is judged to be on.
