### ISSUE TITLE
ShowDialog forces ownership

### ISSUE THREAD

**Issue by rusoaica** [AvaloniaUI/Avalonia#7216]
**Describe the bug**
In WinForms and WPF, one can call ```ShowDialog()``` on a window instance without specifying the owner window. The new dialog is displayed on top of all the other opened windows of the application, which all become blocked until the dialog is closed.

**To Reproduce**
Call ```ShowDialog()``` on a window instance, without specifying a parent window as argument.

**Expected behavior**
As all the other UI frameworks work, a parent owner window should not be mandatory when displaying a dialog. This becomes important in situations like an abstract factory for views used in conjunction with a Dependency Injection system, when the DI system resolves a window from an interface, from a project that has no references to any view-related code, ie: business model in domain driven design. At the moment of using the abstract view factory to display a window, all info regarding window ownership is not available without adding a reference to Avalonia.Controls (where Window type is defined) or hacky workarounds.

**Comment by kekekeks** [comment]
>As all the other UI frameworks work, a parent owner window should not be mandatory when displaying a dialog

As years pass modern desktops allow applications less and less control over the active window and focus. That causes application-modal dialogs to cause confusing interactions like some window being disabling for no apparent reason.

Even with desktops that do allow full control app-modal dialogs cause issues with multi-monitor configurations.

When dialog has a parent the desktop environment has explicit window stacking order and can act accordingly.

That's why we consider application-modal dialogs to be not cross-platform and not portable.

**Comment by rusoaica** [comment]
OK, if the decision is not to port it, what workaround can be used? What is the effect of having the initial opened window of the application be exposed as singleton, when any subsequent modal dialog sets it as parent? 
Or, better said, what is the alternative/recommendation when the ownership is no longer known/available at the moment of displaying the dialog?

**Comment by code-mantis** [comment]
What if it is the starting window? what is the owner window?
ShowDialog offers a way to prompt for a result that according to it decision making in code, Something like OpenFolderDialog.
Thanks in advance.

**Comment by maxkatz6** [comment]
@code-mantis personal opinion, having a dialog result was a mistake in wpf/avalonia design. In fact you can do the same with any window by setting public readable property a value on user action (or better to go with mvvm).

**Comment by kekekeks** [comment]
@rusoaica if your app is guaranteed to have only one toplevel window with everything else being a dialog, then it's fine to keep it as a singleton on the UI layer. 

Otherwise I'd suggest to use a technique that tracks active views for a particular view model. 
For example you could have a base class for your views that would keep a shared `Dictionary<ViewModelBase, List<ViewBase>>` and update its contents in `OnAttachedToVisualTree`, `OnDetachedFromVisualTree` and on `DataContext` changes. That way your UI layer will know which visible controls are currently associated with a particular view model, so you could get the appropriate toplevel Window to use as a parent.

**Comment by rusoaica** [comment]
@kekekeks the workaround I ended up using is to store the hash code of each window inside its view model, and pass that as argument.. when displaying a dialog, I am iterating all opened windows of the application, and set as parent the one that matches the provided hash code. As I said, looks hackish, but works:

For the DI container registration:

```
builder.RegisterType<StartupV>().OnActivating(e =>
{
    e.Instance.DataContext = e.Context.Resolve<IStartupVM>();
    (e.Instance.DataContext as IBaseModel).ParentHashCode = e.Instance.GetHashCode(); // store window hash code inside viewmodel
}).As<IStartupView>().InstancePerDependency();
```          

After that:

```
public async Task<bool?> ShowDialogAsync(int parentHashCode)
{
    if (parentHashCode != 0)
    {
        IReadOnlyList<Window>? windows = ((IClassicDesktopStyleApplicationLifetime)Application.Current.ApplicationLifetime).Windows;
        Window? parent = windows.Where(w => w.GetHashCode() == parentHashCode).First();
        return await ShowDialog<bool?>(parent);
    }
    else
        return await ShowDialog<bool?>(StartupV.Instance); // use first application window as singleton, if no hashcode is provided
}
```
