### ISSUE TITLE
Pointer events are lost if the UI thread is slow

### ISSUE THREAD

**Issue by Jeremy-Price** [AvaloniaUI/Avalonia#7338]
Windows will "coalesce" pointer events if they are not handled by the time the next pointer event arrives, removing the old event from the queue and replacing it with the newest one. This results in lost events, which is not desired behavior when handling high-frequency inputs when high fidelity is also wanted (e.g., inking).

See https://github.com/Jeremy-Price/AvaloniaEventCoalescing/blob/main/AvaloniaEventCoalescing/Program.cs for a repro. A Thread.Sleep is introduced into a simple drawing app. If you move the mouse or touch pointer quickly, you can see that points are lost.

An ideal solution would be either a method on the pointer event args to get the missing points when needed, or a way to configure the app to not coalesce, and to receive each message individually.

See also
https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.pointerpoint.getintermediatepoints?view=winrt-22000
https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.input.pointereventargs.getintermediatepoints?view=winui-3.0

**Comment by kekekeks** [comment]
`GetIntermediatePoints` is planned to be implemented, but it requires switching to [WM_POINTER-based input on Windows](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/inputmsg/wmpointer-reference) which is quite huge and requires either dropping Windows 7 support or supporting two input event sources separately.

**Comment by Symbai** [comment]
> dropping Windows 7 support

Go for it. It's dropped literally everywhere, by Microsoft itself. By hardware manufacturers (like Nvidia). In addition most recent statistics I've seen ([example](https://store.steampowered.com/hwsurvey/steam-hardware-software-survey-welcome-to-steam), Windows 7 is only at 3% anymore) shows that a great majority has switched to Windows 10 already (excluding Chinese market).

**Comment by kekekeks** [comment]
We have customers that still require Win7 support

**Comment by Symbai** [comment]
And they still can use an older/current version of Avalonia. As a customer you cannot expect that all your software provides support for a 13 years old OS where 3 major OS upgrades are already released, for as long as you (customer) want. Especially when you belong to 3% of market share only. In the end its your decision, but if everyone would doing this split all the time to make sure a tiny minority of customers don't have a little extra work, software and hardware would have been 20 years behind. I mean you basically said it yourself in your first post. Its planned but it's not there NOW because it means your 3% customers have to upgrade their 13 years old OS. Which means 97% of the rest has to wait.

**Comment by kekekeks** [comment]
> Its planned but it's not there NOW

It's not there now because we didn't allocate resources to implement it. It's not just changing 2 lines of code, you know.

**Comment by maxkatz6** [comment]
Done for Linux by @kekekeks.

And was merged for Windows (11.0+) as well for touch and pen events (WM_POINTER historical points of a mouse are not supported by Win32 API). 

On macOS there are no proper API for that.

Closing.
