### ISSUE TITLE
NumericUpDown - Issue when decreasing value below 1

### ISSUE THREAD

**Issue by tarun06** [AvaloniaUI/Avalonia#7386]
**Describe the bug**
The issue if found when numericupdown is used with value 1 and increment set ro 0.1.
	<NumericUpDown Value="1" Increment="0.1" />

**To Reproduce**
STR:
1) Add numericupdown as 
	<NumericUpDown Value="1" Increment="0.1" />
2) Decrease the value til 0.7

Actual result - The value change to 0.7000000...

**Screenshots**
![image](https://user-images.githubusercontent.com/2249775/149930020-db91fd01-f7da-464d-9683-4dc2e99aad0b.png)

Avalonia - Version - 0.10.11

The issue was not seen in version 0.10.11-rc.1

**Comment by maxkatz6** [comment]
Dup https://github.com/AvaloniaUI/Avalonia/issues/5318

I can reproduce this issue in 0.10.11-rc.1 as well.
![image](https://user-images.githubusercontent.com/3163374/149938829-0aeb2e37-281f-41f7-a32d-23f490ca396f.png)

It also was fixed with a breaking change (by switching from Value double to decimal) in https://github.com/AvaloniaUI/Avalonia/pull/5981, which wasn't backported to the stable 0.10.x branch.
Another workaround for the stable branch - use FormatString="0.#" or something.

**Comment by tarun06** [comment]
@maxkatz6 Thanks maks
