### ISSUE TITLE
Setting DataContext breaks Template Bindings

### ISSUE THREAD

**Issue by DarthSpot** [AvaloniaUI/Avalonia#7503]
**Describe the bug**
When setting the DataContext in a custom ContentControl, TemplateBindings don't work anymore. 

**To Reproduce**
Create a custom ContentControl with Styled and/or Direct properties.
Set a DataContext for the ContentControl class (in constructor or via Style).

Any {TemplateBinding} Element won't work anymore.
Here is a small example that showcases this behavior: https://github.com/DarthSpot/Avalonia.TemplateBindingBug    

**Expected behavior**
TemplateBindings should still work and "normal" Bindings should use the DataContext

**Desktop (please complete the following information):**

- OS: Linux (EndeavourOS)
- Version: Kernel 5.16.4-arch1-1

**Comment by maxkatz6** [comment]
Looks not very obvious but expected for me.
Binding gets listens for values from DataContext.
If you don't set data context on the control, it will be inherited from parent. That's why it works with first control.
If you set data context on the control, binding will try to get values from it and ignore parents one.

There is nothing really to do with styles nor template binding, they work as expected. StringDirect and StringStyled properties don't have any value on BindingTestControlWithDataContext itself (you can check it with dev tools). Also, if you add StringTest property to the TestViewModel, it will be used, and value will be set.

**Comment by MarcusRiemer** [comment]
Is this behavior documented anywhere? If I understand this correctly, it's at least a minor annoyance for people who were expecting that it's possible to mix ways to pass on data. But from what I understand now it's basicly "Pass via DataContext" XOR "Pass via Properties"?

**Comment by maxkatz6** [comment]
Yes, normal rules of data context are applied there
https://docs.avaloniaui.net/docs/data-binding/the-datacontext
