### ISSUE TITLE
Not input the key that were key-binding on text box after updated 0.10.12

### ISSUE THREAD

**Issue by xingxing21** [AvaloniaUI/Avalonia#7557]
Hi
There is an app that has some numeric keys that were key-binding on Main Window.
It is not inputted these keys on the text box after updating.
It was good working before updating.

**Comment by xingxing21** [comment]
![image](https://user-images.githubusercontent.com/39619359/152979253-89500d34-ff49-449a-bc41-8ddcf2b783ea.png)

**Comment by robloo** [comment]
I think you need to let everyone know the version of Avalonia you are using. If it is the latest builds from master this probably should be added to *Text processing bugs* #7502. This is very likely a result of TextFormatting/TextBox changes.

**Comment by xingxing21** [comment]
The example app is good working on 0.10.11
![image](https://user-images.githubusercontent.com/39619359/153137928-a92f2568-90ad-4531-ab6c-364ee1a47756.png)

**Comment by amwx** [comment]
I realize this probably shouldn't have been a change in a non-breaking change release, but to me at least, it seems the 0.10.12 behavior is more correct. Personally I would expect a keybinding to not continue propagating through the tree. Maybe it would make sense to follow UWP's KeyboardAccelerators and use a RoutedEvent instead of a Command - making it optional if the key continues propagating by not handling the event? Not sure what else that would break though.

As a side note, I didn't even know about the KeyBindings property on controls - super useful to know.

**Comment by amwx** [comment]
> Porting KeyboardAccelerators (or having another alternative) is yet another huge task on which we don't have time for next major release, unfortunately.

I think the only difference between KeyBinding here and KeyboardAccelerator is Command vs Invoked event, and KeyboardAccelerators can set a scope in which it works - at least at its core. (also verbosity) I wasn't suggesting bring that over entirely, I was just thinking aloud an event may be better than a command since it's known whether its handled. Command has more ambiguity.

**Comment by grokys** [comment]
Hi @xingxing21 - yes you're right this behavior changed, but I think the old behavior was a bug as it _only_ happened on win32 - macOS and X11 as far as I know have the behavior you're seeing here.

There is a workaround you could try to bring back the old behavior. Try adding this to the codebehind of the control which defines the `KeyBinding`s - (`MainWindow.axaml.cs` in your example):

```csharp
        public MainWindow()
        {
            InitializeComponent();
#if DEBUG
            this.AttachDevTools();
#endif

            // Try adding this.
            this.AddHandler(
                InputElement.KeyDownEvent,
                (s, e) => e.Handled = false,
                handledEventsToo: true);
        }

```

**Comment by xingxing21** [comment]
Hi @grokys
I added the method in my code and good working now.
Thanks.
And I have trouble. I have many text boxes on my app and when I input the text on that boxes, I should add the extra code to not call the key-binding function like follow:

`private void _searchBox_LostFocus(object sender, Avalonia.Interactivity.RoutedEventArgs e)
{
    Utils.HasFocus = false;
}

private void _searchBox_GotFocus(object sender, Avalonia.Input.GotFocusEventArgs e)
{
    Utils.HasFocus = true;
}`

I don't know how many text boxes and Key-binding can be added to my app in the future.
Is there a way to avoid it?
Thank you again.

**Comment by Gillibald** [comment]
Try to use a behavior and attach it via a style

**Comment by xingxing21** [comment]
Can you give me an example?

**Comment by Gillibald** [comment]
https://github.com/wieslawsoltes/AvaloniaBehaviors/blob/master/samples/DragAndDropSample/Views/MainWindow.axaml#L25

Implementing the behavior itself should be trivial

**Comment by FlatlinerDOA** [comment]
So to get this straight basically at the moment HotKey anywhere in a Window's visual tree will disable text inputs for that key globally. From my perspective this is 100% a bug in how Avalonia handles keyboard input, the original behaviour is objectively correct when a textbox is focused. If this isn't going to be fixed, can we at least get the documentation on [HotKeys](https://docs.avaloniaui.net/docs/concepts/input/hotkeys) updated to give an example of the recommended workaround?
