### ISSUE TITLE
NumericUpDown should accept null as Value

### ISSUE THREAD

**Issue by timunie** [AvaloniaUI/Avalonia#7725]
**Is your feature request related to a problem? Please describe.**
I have a form where "0" is a total valid value, but I want to make sure the user inserted this and does not use the "default" value provided by the system. In WPF I just left the field empty ('null') and checked if the field is not null on save

**Describe the solution you'd like**
make `Value` nullable

**Describe alternatives you've considered**
Create my own control 

**Additional context**
![image](https://user-images.githubusercontent.com/47110241/155996063-fbb6c093-2b1c-4764-abe2-fdc9cc2bde6c.png)
*Fields should be empty*

If you are OK with this change, I can provide a PR for this.

**Comment by Gillibald** [comment]
These kind of controls usually have a NullValue property that is used for a visual representation of null values might be good to add that as well.

**Comment by robloo** [comment]
This was discussed in the WinUI repo. https://github.com/microsoft/microsoft-ui-xaml/issues/1736#issuecomment-575388191 There it was eventually agreed that `double.NaN` represents null just fine. However, after the switch from `double` to `decimal` (for rounding errors) in Avalonia, `double.NaN` is no longer possible. So the real issue here is that `decimal.NaN` doesn't exist...

I think having a nullable Value property is a better solution to this than a sentinel value. Other controls have two properties as well like the DatePicker (Date and nullable SelectedDate).

**Comment by timunie** [comment]
> This was discussed in the WinUI repo. [microsoft/microsoft-ui-xaml#1736 (comment)](https://github.com/microsoft/microsoft-ui-xaml/issues/1736#issuecomment-575388191) There it was eventually agreed that `double.NaN` represents null just fine. However, after the switch from `double` to `decimal` (for rounding errors) in Avalonia, `double.NaN` is no longer possible. So the real issue here is that `decimal.NaN` doesn't exist...
> 
> I think having a nullable Value property is a better solution to this than a sentinel value. Other controls have two properties as well like the DatePicker (Date and nullable SelectedDate).

*/ Off-topic: /*
In a world where everything is possible this control would be generic and can handle any numeric type. I had a discussion about this in MahApps and there decimal was judged as not a good replacement for double, but a generic control would be an option. Here is the link to the issue if someone is interested.  https://github.com/MahApps/MahApps.Metro/issues/3673
*/ Off-topic end /*

If I find a free minute I will provide a PR to chnage this, as the first feedback was positive. 

Happy coding 
Tim

**Comment by robloo** [comment]
> In a world where everything is possible this control would be generic and can handle any numeric type.

This will be possible in .NET 7. https://devblogs.microsoft.com/dotnet/preview-features-in-net-6-generic-math/.
Each instance of a NumberBox would have to have a type. NumberBox<double> or something. That however would require foundational changes in the way controls work internally.

> was judged as not a good replacement for double

The reasons in the linked issue don't really matter. This is a user-input control. Theoretical differences in min/max/precision are irrelevant when the user has to type it in. A user should never be presented with a number larger than they can understand/manage. Decimal is actually BETTER than double for this purpose and for precision.

**Comment by timunie** [comment]
This idea was rejected, So I'll close this issue as unresolved for me. 

You can still roll your own control which implement this. 

Have a great weekend all of you
Tim

**Comment by timunie** [comment]
@danwalmsley discussed it today with the core team. I haven't deleted the branch yet, so we can still reopen this if the decision changes.

**Comment by robloo** [comment]
@danwalmsley There are many scenario where apps need to know if a user has/has-not made a selection. Zero in the case of a NumericUpDown is a valid number and is not enough to indicate no user-selection. This type of functionality is common in LOB apps where form field values are being entered. In fact every single control I am aware of has some way of keeping 'null/empty values for no user-selection.

When the NumberBox spec was widely discussed with Microsoft this was also a valid scenario. However double.NaN could be used to add this functionality. With the switch to decimal in Avalonia that was overlooked and it needs to be added back somehow.

There are two standardized ways of doing this:

 1. Add a nullable SelectedValue property along with Value. This is the strategy used in DatePicker where the underlying type doesnt support empty/null.
 2. In something like TextBox, null has historically been supported for this but string itself has an Empty state so can be used for this info as well. So these controls don't need a special case and additional property because the underlying type supports it.

**Comment by robloo** [comment]
I just checked TextBox too. The Text property is still nullable even after the switch to nullable ref types. I'm very surprised it was stated this isn't common. In fact every other input control i'm aware of supports this functionality.

**Comment by timunie** [comment]
Reopening the issue due to feedback from the community.

**Comment by timunie** [comment]
Let me add one more thing. I noticed that NumericUpDown support `Watermark`. But as the value can never be `null`, one can't see the `Watermark`. It works in my proposal.
