### ISSUE TITLE
[Content] Demo as executable file

### ISSUE THREAD

**Issue by damat** [AvaloniaUI/Avalonia#777]
It would be great to have compiled executable file of Demo project. I mean video is great, but clickable version is always better.

**Comment by 0xFireball** [comment]
Why not just clone the source and compile it on your computer?

**Comment by DraTeots** [comment]
Because it is not really straight forward to build it. 

At least the last time I built it, it required some attention and time. While, as I see it, a lot of people just need something quick to evaluate what AvaloniaUI can do right now. 

At the same time, I feel strange about releasing exe. The MUCH better way would be to have something like [gemini](https://github.com/tgjones/gemini) but with avalonia. Especially because there IS a great looking (was unable to compile it though) IDE using AvaloniaUI

**Comment by 0xFireball** [comment]
The bleeding edge build of AvalonStudio: https://github.com/VitalElement/AvalonStudio/wiki
My Pull request to add it to the readme:  https://github.com/VitalElement/AvalonStudio/pull/202/commits/62dc2322e2492ff104e76dc76c340519891c3db0

You can download a ZIP with the full AvalonStudio IDE and run it

**Comment by damat** [comment]
If there's a demo, it would be much easier to share with the team as an exe file, not just as source.

**Comment by wieslawsoltes** [comment]
You can get latest demo app from AppVeyor build artifacts: https://ci.appveyor.com/project/AvaloniaUI/Avalonia/branch/master/artifacts

**Comment by danwalmsley** [comment]
i'll add a link to the wiki !
