### ISSUE TITLE
Raspberry pi 3 gpu not used or poor performance

### ISSUE THREAD

**Issue by ahopper** [AvaloniaUI/Avalonia#7833]
**Describe the bug**
My app updates a significant part of its window at 60fps, on a raspberry pi 4 with the current raspberry pi os it uses 10% cpu as reported by task manager (% of all cores) , 5% of that is dsp code and it appears to use the gpu indicated by (AvaloniaLocator.Current.GetService<IPlatformOpenGlInterface>() != null) and the frame rate is good, so Avalonia is working well.

On the rpi 3 it uses 60% cpu if useEGL is set true and the test for gpu use returns true, framerate is low.
On startup this is printed :- LibEGL warning: DRI2: failed to authenticate .
If just UseGpu is set true the cpu use is 30% (7%dsp) and the gpu test returns false and frame rate is low, no warning is displayed.

This is on a clean install both with the gl desktop on or off on the rpi3.
I tried https://github.com/AvaloniaUI/Avalonia/pull/7749 just on the off chance but no change.

**Comment by ahopper** [comment]
[glxinfo.txt](https://github.com/AvaloniaUI/Avalonia/files/8305406/glxinfo.txt)

**Comment by Geektoolkit** [comment]
Thankyou for this! I'd seen poor performance on pi3 and saw high cpu usage and didn't understand why. Hoping this turns out to be something Avalonia can fix, I have a lot of people for my Dynaframe project that'd like to run it on old pi3s (esp. given the price of pis right now). If there's any additional info I can provide please let me know, or if testing of a fix is needed.

**Comment by kekekeks** [comment]
If GPU is actually being utilized, there is not much we can do. We certainly don't have resources to improve Skia performance with RPi GPU/drivers
