### ISSUE TITLE
Using Compiled Bindings disables Design.DataContext

### ISSUE THREAD

**Issue by SuperJMN** [AvaloniaUI/Avalonia#7868]
**Describe the bug**

**To Reproduce**

1. Create 2 ViewModels. One for design-time an another for run-time. Obviously, properties should match.
2. Set the `Design.DataContext` in the view to the design-time ViewModel.
3. Set the `x:DataType` in the view to the run-time ViewModel
4. Make some bindings
5. The designer view should reflect the sample data (from the design-time VM)
6. Now, set `x:CompileBindings="True"` to the view
7. You'll notice that the design-time data will disappear.

**Expected behavior**
The Design.DataContext should work using either value of `CompileBindings`

**Screenshots**
I'm attaching a video with the behavior

https://user-images.githubusercontent.com/3109851/159948325-265d4e16-e595-4039-a7a8-db7a5115c760.mp4

**Desktop (please complete the following information):**

- OS: Windows 11

**Comment by maxkatz6** [comment]
Yes, this is by design. DataType is SearchBarViewModel when DataContext is type of SearchBarDesignViewModel. 
I checked the source code https://github.com/zkSNACKs/WalletWasabi/blob/a774847a586d5b3847773f68ba119fb16f476015/WalletWasabi.Fluent/ViewModels/SearchBar/SearchBarDesignViewModel.cs and it seems SearchBarDesignViewModel doesn't inherit SearchBarViewModel  type. So compiler can't do anything.
