### ISSUE TITLE
FontSize inconsistent

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia#811]
If I use Consolas font, and set font size 10 (like the default in visual studio)

The font size is much smaller that it is in visual studio.

Perhaps we have the font scale wrong, to compensate I have to use fontsize = 14

however because of this it looks bolder than it should.

**Comment by grokys** [comment]
Is the font size in VS in points? Our font sizes are in DIPs.

[WPF also uses DIPs for font sizes](https://msdn.microsoft.com/en-us/library/system.windows.controls.textblock.fontsize(v=vs.110).aspx) however it is also possible in WPF [to supply a point size in markup](http://stackoverflow.com/questions/5713466/how-to-specify-font-units-in-wpf). Maybe we just need to add this feature?

**Comment by danwalmsley** [comment]
I don't realise they were in DIPs, ok so that explains it. we could add support for point size.

However I am struggling to get like for like font rendering, let me post a quick example

**Comment by danwalmsley** [comment]
![image](https://cloud.githubusercontent.com/assets/4672627/20564076/620f22ae-b183-11e6-9463-19e1b5ebd9bc.png)

**Comment by danwalmsley** [comment]
Ok turns out I was on skia backend, which I can take a look at, to fix ;)
However there is an issue on the direct2d backend

you need to click on image to get full res version to be able to see.

On left is Avalon studio (direct2d backend) and right is visual studio.
look at line 1...

the '*' characters, as you move left to right, you get the odd ones that are blurred.

Any ideas what the cause is?

**Comment by soerendd** [comment]
I think the cause is that we need to set the TextAntialiasMode of the renderTarget to SharpDX.Direct2D1.TextAntialiasMode.Cleartype. Furthermore we should assign the TextRenderingParams to something like  new RenderingParams(directWriteFactory, 1.8f, 1.5f, 0.0f, PixelGeometry.Bgr, RenderingMode.CleartypeGdiNatural). Especially the RenderingMode is important. This is what MSFT has done to get a better rendering of fonts in VS and WPF. But i dont know what values they use for TextAntialiasMode and the RenderingMode.

**Comment by danwalmsley** [comment]
Closing as font size now seems to be consistent.
