### ISSUE TITLE
Memory consumption is way too high.

### ISSUE THREAD

**Issue by Nemirtingas** [AvaloniaUI/Avalonia#8129]
**Describe the bug**
The memory consumption can go higher than 2GB with this simple app.

**To Reproduce**
Run the provided project.

**Expected behavior**
Not a so high memory usage.

- OS: Windows
- Version 0.10.2

[AvaloniaMemoryBug.zip](https://github.com/AvaloniaUI/Avalonia/files/8688724/AvaloniaMemoryBug.zip)

**Comment by timunie** [comment]
See the other issue you posted. Looks like virtualization is broken due to StackPanel around ListBox which will force Avalonia to keep all items in memory

**Comment by Nemirtingas** [comment]
Hi, I'll take a look. Thanks for the quick answer.

**Comment by maxkatz6** [comment]
@Nemirtingas I don't think WrapPanel supports virtualization.

> Whats the best way to display a list of nodes that I could collapse then ?

The best would be to use TreeDataGrid control, but you probably would need to restyle expander rows.

Without TreeDataGrid you have a choice between ItemsPresenter (used inside of ItemsControl) and ItemsRepeater.
First one should be enough if you use ```VirtualizationMode=Simple``` with stack panel (instead of wrap panel).
With second you can set virtualized WrapLayout, but it might be buggy.

**Comment by Nemirtingas** [comment]
I used a ListBox with a DataTemplate, seems fine now. As collapsible container, I used an Expander.
The only remaining issue is that the ListBox doesn't resize when openning the Expander and if I open 1 Expander and then scroll in the ListBox, it will open the next Expander available.

**Comment by maxkatz6** [comment]
> I open 1 Expander and then scroll in the ListBox, it will open the next Expander available

Because containers are reused. You can use bindings to the view model to remember correct state of the expanders.
