### ISSUE TITLE
Unable to create a TemplatedControl in a library project

### ISSUE THREAD

**Issue by sam-wheat** [AvaloniaUI/Avalonia#8138]
Expected behavior - Create an application project and a library project. Create a TemplatedControl in the lib project.  Reference the lib from the app and use the app.  

I am unable to guess how the above process works in Avalonia.  Another user in one of the links below requested a tutorial also.  I am unable to locate the tutorial.  

https://github.com/AvaloniaUI/Avalonia/issues/2516
https://github.com/AvaloniaUI/Avalonia/issues/6475
https://github.com/AvaloniaUI/Avalonia/issues/6924
https://github.com/AvaloniaUI/Avalonia/issues/4456

Attached project is pretty much out-of-the-box and results in this error msg:

> Avalonia.Markup.Xaml.XamlLoadException
  HResult=0x80131500
  Message=No precompiled XAML found for make sure to specify x:Class and include your XAML file as AvaloniaResource
  Source=Avalonia.Markup.Xaml
 
Adding this:

	<ItemGroup>
		<Folder Include="Models\" />
		<AvaloniaResource Include="Assets\**" />
		<Compile Update="**\*.axaml.cs">
			<DependentUpon>%(Filename)</DependentUpon>
		</Compile>
		<AvaloniaResource Include="**\*.axa
[AvaloniaApp2.zip](https://github.com/AvaloniaUI/Avalonia/files/8695250/AvaloniaApp2.zip)
ml">
			<SubType>Designer</SubType>
		</AvaloniaResource>
	</ItemGroup>

Results in this:

> Error	AVLN:0002	Duplicate x:Class directive, AvaloniaLibrary2.App is already used in /App.axaml	AvaloniaLibrary2

**Comment by maxkatz6** [comment]
Hi! I see couple of problems with your project:
1. You don't need ```<AvaloniaResource Include="**\*.axaml" />``` because Avalonia already adds "axaml" files to the resources. You basically make it duplicate; exactly what error says to you "Duplicate x:Class directive".
2. You TemplatedControl1 has InitializeComponent method. That's wrong, because for templated controls "xaml" markup is detached from the codebehind. You could use our templates for [VS](https://github.com/AvaloniaUI/AvaloniaVS/blob/master/templates/AvaloniaTemplatedControlTemplate/TemplatedControl.axaml.cs) or [Rider/dotnet](https://github.com/AvaloniaUI/avalonia-dotnet-templates/blob/master/templates/csharp/templatedcontrol/NewTemplatedControl.axaml.cs), which are defined properly. Because of InitializeComponent app tried to get non-existed xaml file (not a style, but base markup for the control) and said "No precompiled XAML found".
3. Your AvaloniaLibrary2 project has yet another App.axaml and MainWindow.axaml. It won't cause any problems in compilation and running the project, namespace is different, but you probably don't need it there.

**Comment by leaderanalytics** [comment]
Thank you @maxkatz6.  I implemented your recommended changes and the errors I was encountering are gone.
The new error (which is what I started with) is:

> HResult=0x80131500
  Message=No precompiled XAML found for controls:TemplatedControl1.axaml (baseUri: avares://AvaloniaApp2/App.axaml), make sure to specify x:Class and include your XAML file as AvaloniaResource
  Source=Avalonia.Markup.Xaml

Modified app attached.

[AvaloniaApp2.zip](https://github.com/AvaloniaUI/Avalonia/files/8695960/AvaloniaApp2.zip)

**Comment by maxkatz6** [comment]
Wrong StyleInclude syntax, the error tells you what can't be found and where it was defined (App.axaml). 
```xaml
<StyleInclude Source="avares://AvaloniaLibrary2/TemplatedControl1.axaml" />
```

![image](https://user-images.githubusercontent.com/3163374/168499595-7115628c-fe55-4344-9e96-b850af89c5a4.png)

**Comment by sam-wheat** [comment]
Of course!  What was I thinking! 
Thanks for the assist.
