### ISSUE TITLE
Scrolling issues when using WpfAvaloniaHost

### ISSUE THREAD

**Issue by teocomi** [AvaloniaUI/Avalonia#8198]
**Describe the bug**
Scrollbars are not working as expected when embedding Avalonia controls in WPF via `WpfAvaloniaHost`

**To Reproduce**
Please check this repo: https://github.com/teocomi/avalonia-issues

**Expected behavior**
The first issue I noticed is that when using a `ListBox` or a `ScrollViewer` in my Avalonia UserControl (which is embedded inside a WPF window via `WpfAvaloniaHost`) no scrollbars appeared as if the Height of the component wasn't correctly inherited from the parent ones. I got around this by explicitly setting it via `Height="{Binding $parent[Grid].Bounds.Height}"`.

The second issue is that once the scrollbars show up, the scrolling is not gradual as I'd expect, just by spinning the mouse wheel a bit the entire content scrolls all the way to the bottom.
You can test this behavior in the repo linked above.

![scroll](https://user-images.githubusercontent.com/2679513/170320419-cb487c7e-e30c-4aaa-a78e-4307f5005800.gif)

Maybe I'm missing something?

**Comment by maxkatz6** [comment]
You might try this AvaloniaHwndHost as an alternative https://github.com/maxkatz6/AvaloniaHwndHostSample/blob/main/AvaloniaHwndHost/AvaloniaHwndHost.cs

**Comment by teocomi** [comment]
Thanks @maxkatz6 ! I can confirm that it  solves the issue inside a standard WPF window!
Our UI loads inside an external application as a plugin, and there I'll need to play with the `BuildWindowCore` method to make it work too, but I'm on the right track :)

Cheers!

**Comment by teocomi** [comment]
Hey @maxkatz6,

Your [AvaloniaHwndHost.cs](https://github.com/maxkatz6/AvaloniaHwndHostSample/blob/main/AvaloniaHwndHost/AvaloniaHwndHost.cs) has been super useful, but we just found an issue we can't get around, hope you have any ideas or pointers as we're blank in regards to Win32 stuff.

In one of the Windows-based host applications we're embedding the Avalonia UI (called [Revit](https://www.autodesk.com/products/revit/overview)), no Text Input is working. Copy/Paste works, and as well I can see that a KeyDown event is triggered, but no text is shown in the controls when typing.
In another host application, everything works correctly, so I understand this might be related to how Revit's Dockable Panes handle FrameworkElements, but maybe there's something we can try inside the `AvaloniaHwndHost` class?

As an additional hint, when using `WpfAvaloniaHost` the text inputs work just fine.

Thanks a lot in advance!

**Comment by maxkatz6** [comment]
@teocomi I don't know if I can help much, but at least I can point on difference how these two controls handle text. Maybe, it will help.

WpfAvaloniaHost uses FrameworkElement directly as a host for Avalonia content. And  redirects from WPF keyboard events to Avalonia raw events (topLevel.Input.Invoke). 
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Windows/Avalonia.Win32.Interop/Wpf/WpfTopLevelImpl.cs#L227
Similarly many other backend-specific features, like mouse input, are redirected from WPF events to Avalonia. Avalonia renders to a bitmap which later rendered to a WPF window. 

When AvaloniaHwndHost is different. It creates win32 window and sets it as a child to a WPF window. And handles win32 events directly. 
So I assume, the problem is that WPF always handles win32 text input events, and they can't reach avalonia child window.
If the way how wpf handles text input can't be solved by itself, you can possibly try to redirect text input from WPF to avalonia. Similarly how it's done in WpfAvaloniaHost.

**Comment by teocomi** [comment]
Thanks so much @maxkatz6 , you did indeed point me in the right direction. 
With the help of [this thread](https://stackoverflow.com/questions/32528006/how-to-host-a-wpf-usercontrol-in-elementhost-without-window-with-keypresses), I was able to resolve my issue as follows:

```
 public Panel()
    {
      InitializeComponent();
      AvaloniaHost.Content = new MainUserControl();
      AvaloniaHost.MessageHook += AvaloniaHost_MessageHook;
    }

    private const UInt32 DLGC_WANTARROWS = 0x0001;
    private const UInt32 DLGC_HASSETSEL = 0x0008;
    private const UInt32 DLGC_WANTCHARS = 0x0080;
    private const UInt32 WM_GETDLGCODE = 0x0087;

    private IntPtr AvaloniaHost_MessageHook(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
    {
      if (msg != WM_GETDLGCODE) return IntPtr.Zero;
      handled = true;
      return new IntPtr(DLGC_WANTCHARS | DLGC_WANTARROWS | DLGC_HASSETSEL);
    }

```
