### ISSUE TITLE
ListBox - System.StackOverflowException: 'Exception_WasThrown'

### ISSUE THREAD

**Issue by alex6dj** [AvaloniaUI/Avalonia#8201]
**Describe the bug**
When ListBox contains some buttons in DataTemplate application fail with an StackOverflowException.

**To Reproduce**
See attached project.
[ListBox Exception.zip](https://github.com/AvaloniaUI/Avalonia/files/8775914/ListBox.Exception.zip)

- Execute and fail
- Remove only TextBlocks from DataTemplate and fails
- Remove all Buttons from DataTemplate and it works

**Expected behavior**
It should work

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10 1903
- Version 0.10.14 - latest

**Additional context**

**Comment by maxkatz6** [comment]
You got a combination of these two issues:
https://github.com/AvaloniaUI/Avalonia/issues/724
https://github.com/AvaloniaUI/Avalonia/issues/5726

Basically, DataType is required on a DataTemplate, otherwise it will be applied on everything (thus, stack overflow). That's by design.
CompiledBindings use x:DataType property from a different namespace. And while they should be the same, they are two different properties. That's the issue.

**Comment by maxkatz6** [comment]
I will close it as a duplicate of https://github.com/AvaloniaUI/Avalonia/issues/5726

As a workaround, you need to use both properties or even better use ```<ListBox.ItemTemplate>```. ```<ListBox.DataTempates>``` is useful, when you want to have two or more different templates for different types.
