### ISSUE TITLE
Setting the design time datacontext making the designer stop responding

### ISSUE THREAD

**Issue by ahmedmohammedfawzy** [AvaloniaUI/Avalonia#8295]
I followed the Avalonia docs to set the datacontext but whenever I set it the designer suddenly stops responding to changes and hangs up until I remove the datacontext: 
I tried setting it using: `d:DataContext="{x:Static dd:McalUiViewModelDesignData.ViewModel}"` and  
`   <Design.DataContext>
        <viewModels:ViewModel />
 </Design.DataContext>`
and both doesn't work

NOTES: I am using jetbrains rider IDE version "2022.1.1" and avaloniaRider version "1.0.0.2140933515"

**Comment by maxkatz6** [comment]
I am not sure about Rider, but there must be a previewer log somewhere. Probably Rider plugin github page has some information how to find them. 
Without these logs it's hard to answer correctly. 

But in general you need to remember, that previewer needs to execute your program with fake window inside of the IDE. So if you code will fail with any exception, previewer will fail to display anything too.

**Comment by maxkatz6** [comment]
@ahmedmohammedfawzy there should be "Avalonia Designer" tool window opened per each tab - https://github.com/ForNeVeR/AvaloniaRider/issues/39#issuecomment-719958718
App exceptions are usually written there as well.

If you need more detailed logs, better to check/ask on this previewer repository directly. I don't have this answer.

**Comment by EricEzaM** [comment]
Having the same issue. Unfortunately nothing additional is being logged in the Avalonia designer tab. 

I created an issue in the plugin repo.
https://github.com/ForNeVeR/AvaloniaRider/issues/209

**Comment by hhyyrylainen** [comment]
I just had a bug like this where my data context constructor was running into an exception. This unhandled exception doesn't seem to be logged anywhere. After a lot of looking I realized what the problem was for me (I specifically removed the initialization of a component that is actually needed in design mode). I'm not 100% sure it was an exception, only just pretty sure based on the fact I was using a `IServiceProvider` that had a missing service and the preview started working once I added the service I realized was missing.

So it would be very nice if the rider avalonia output would show something more than:
```
System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.ReadExact(Byte[] buffer) in /_/src/Avalonia.Remote.Protocol/BsonStreamTransport.cs:line 59
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.Reader() in /_/src/Avalonia.Remote.Protocol/BsonStreamTransport.cs:line 71
```
when there are problems like this.

**Comment by maxkatz6** [comment]
Closing as it seems to be plugin issue

**Comment by WilbertOnGithub** [comment]
Just leaving this here in case someone else stumbles into this problem. I encountered the same issue as described by @hhyyrylainen where the logfile of the designer showed the following:

```
System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.ReadExact(Byte[] buffer) in /_/src/Avalonia.Remote.Protocol/BsonStreamTransport.cs:line 59
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.Reader() in /_/src/Avalonia.Remote.Protocol/BsonStreamTransport.cs:line 71
```

In my case, I'm using the MVVM toolkit and inject the viewmodel into the view using the following 

```
public partial class ApartmentConfigurationView : UserControl
{
    public ApartmentConfigurationView()
    {
        InitializeComponent();
        DataContext = Ioc.Default.GetRequiredService<ApartmentConfigurationViewModel>();
    }

    private void InitializeComponent()
    {
        AvaloniaXamlLoader.Load(this);
    }
}
```

Then I added a design time reference to the view to preview my data:

```
   <Design.DataContext>
        <viewModels:ApartmentConfigurationViewModel/>
    </Design.DataContext>
```

Turns out that I forgot to register the viewmodel for usage with dependency injection. After registering it, the preview started working.
