### ISSUE TITLE
Should PointerPointProperties be public in PointerEventArgs?

### ISSUE THREAD

**Issue by Joe-houghton** [AvaloniaUI/Avalonia#8369]
**Describe the bug**
I am trying to find out whether the left button is down whilst the mouse/pointer is moved within a Templated Control

**To Reproduce**
```
    public class ArrowAngleControl : TemplatedControl
    {
        public ArrowAngleControl()
        {
            PointerMoved += ArrowAngleControl_PointerMoved;
        }

        private void ArrowAngleControl_PointerMoved(object? sender, global::Avalonia.Input.PointerEventArgs e)
        {
            bool isMouseDown = e.Properties.IsLeftButtonPressed; // e.Properties does not exist
        }
    }
```

**Expected behavior**
The API describes the PointerPointProperties here [http://reference.avaloniaui.net/api/Avalonia.Input/PointerEventArgs/](http://reference.avaloniaui.net/api/Avalonia.Input/PointerEventArgs/), however it is not accessible as it is set to protected [https://github.com/AvaloniaUI/Avalonia/blob/6314f4f34a0fad3d5bc46d40165beb0f7c4693fe/src/Avalonia.Base/Input/PointerEventArgs.cs#L143](https://github.com/AvaloniaUI/Avalonia/blob/6314f4f34a0fad3d5bc46d40165beb0f7c4693fe/src/Avalonia.Base/Input/PointerEventArgs.cs#L143)
Furthermore the comment for the e.InputModifiers deprecated, says to use PointerPointProperties

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Mac, Linux (State distribution)]
- Version 0.10.15

**Comment by Rekkonnect** [comment]
Bumping this because I also had to explicitly find this issue to see the intended approach. Perhaps this should be documented somewhere.

And if I see a protected `Properties` property on the event args because it's useful for some implementation, it's probably a better design for everyone to have access to this property because it could be useful for their implementation too. Simple things like left/middle/right mouse buttons being pressed are hidden behind invoking a method, whereas `KeyModifiers` is directly visible. So if I want to evaluate the combination `Ctrl` + right click, I have to refer to two different properties with two different sources (`PointerEventArgs.GetCurrentPoint(this)` and `PointerEventArgs` directly).
