### ISSUE TITLE
Button.Flyout should toggle on/off

### ISSUE THREAD

**Issue by pr8x** [AvaloniaUI/Avalonia#8379]
In Avalonia pressing on the button that shows the flyout will close and open the flyout right again. That is because the underlying `Popup` is passing the click event through the button (due to setting `OverlayDismissEventPassThrough`) leading to the flyout being opened again. In UWP this works differently. Dismissing a flyout by pressing outside will not pass any events.

UWP:
![uwp_flyout_dismiss](https://user-images.githubusercontent.com/4670166/175530145-44509936-52f6-42b9-86b6-1209bc4cab9b.gif)

I think we need to expose `OverlayDismissEventPassThrough` on `Flyout` to control the behaviour for button flyouts. We could also think about generally disabling it inside `FlyoutBase`; the behaviour should be the same for `ContextFlyout` as well.

CC: @maxkatz6

**Comment by Tetedeiench** [comment]
Was going to report it here as it feels counterintuitive. I mentioned it here : https://github.com/AvaloniaUI/Avalonia/issues/8367 

My workaround is to ignore the flyout open event if a close occured less than 100ms ago.  The flyout will close, but the opening will be ignored, achieving the goal in a dirty way.

Couldn't find a better way sadly.

**Comment by maxkatz6** [comment]
> That is because the underlying Popup is passing the click event through the button (due to setting OverlayDismissEventPassThrough) leading to the flyout being opened again.

I don't think it's true. At least in current master. OverlayDismissEventPassThrough is null on the popup when flyout is opened.

Instead, it seems like `PointerPressed` triggers light dismiss layer to close the popup. And same click `PointerReleased` triggers button to open the popup. Default ClickMode is Release.

So, to solve it, we can actually set OverlayDismissEventPassThrough to be placementTarget (and remove it on Hide). This way same `PointerPressed` will reach the button instead of closing popup by light dismiss layer.
Additionally, OpenFlyout method can be replaced with ToggleFlyout to properly close it on click if it was opened before. Or second method created.
