### ISSUE TITLE
Composition Renderer does not handle dirty rects correctly

### ISSUE THREAD

**Issue by timunie** [AvaloniaUI/Avalonia#8527]
**Describe the bug**
Somehow after #8105 not all dirty rects are handled correctly, i.e. there are visuals left that should not be there. 

**To Reproduce**
There are several ways to do. 

Way 1: Open the control catalog on DataGrid page and select more than one row with [Ctrl] pressed. Notice that the current cell adorner gets not cleared. It will be cleared once you move your mouse over the row. See screenshot 1

Way 2: Open Dev tools and move your mouse fast over the rows. See that the hover brush does not always disappear. See screenshot 2

**Expected behavior**
Visuals should be updated correctly

**Screenshots**
![Animation](https://user-images.githubusercontent.com/47110241/179363121-17e9269e-5933-45c8-9b8a-d056ead51fda.png)

![Animation2](https://user-images.githubusercontent.com/47110241/179363132-f5b2827d-7056-4367-a9df-8771d49313c0.png)

**Desktop (please complete the following information):**

- OS: Windows
- Version: latest master

**Additional context**
@robloo  saw similar issues and reported them on telegram channel. 

Unfortunately I have no idea where to look. So I think I'm not able to fix it on my own. 

One more hint: I only saw the issues related to the DataGrid, but it may be also an issue for other controls. 

/cc @kekekeks

**Comment by timunie** [comment]
Just noticed that the DatePicker has similar issues. I can record a video if that helps further, but tbh I think it's related.

**Comment by robloo** [comment]
The new ColorPreviewer combined with property editing in DevTools is another good example of this.

https://user-images.githubusercontent.com/17993847/179367080-2e887bf5-0289-40f4-89a8-b6f67149828a.mp4

 1. In ControlCatalog navigate to the ColorPicker page and select the far right previewer (stand-alone one)
 2. Open DevTools with the ColorPreviewer selected
 3. Change the property IsAccentColorsVisible from True to False
 4. Notice that the drop shadow persists while the control otherwise properly updates (shown in above screen recording)
 5. Change the property IsAccentColorsVisible from False to True
 6. The control doesn't update at all

This was all working yesterday before the composition branch was merged in.
