### ISSUE TITLE
StackOverflowException in binding

### ISSUE THREAD

**Issue by donandren** [AvaloniaUI/Avalonia#855]
StackOverflowException in binding when property is changed in setter before raise property changed.
That's probably the root reason for problem in #824

Example if you bind a listbox selected Item to property selected item and property is like:

```csharp
            set
            {
                if (_selectedItem != value)
                {
                    int index = Items.IndexOf(value);
                    if (index > 1)//or some other logic that's changing the current value
                    {
                        _selectedItem = Items[index - 1];
                    }
                    else
                    {
                        _selectedItem = value;
                        
                    }
                    this.RaisePropertyChanged();
                }
            }
```

**Comment by donandren** [comment]
easy repro can be found in branch https://github.com/donandren/Avalonia/tree/issues/855

Repro steps:
1.Start Virtualization Application
2.Select Item after the first and StackOverflowException will occur

**Comment by jkoritzinsky** [comment]
I've finally figured out why this causes a stack overflow. Below is the order of events that cause it.

Objects required: A, B are `AvaloniaObject`s, and C is an object that implements INPC and changes the current value before setting setting it and raising `PropertyChanged`.

Two-way bind A.Prop <---> C.Prop. Then bind B.Prop <---> A.Prop. 
### Order of events:

1.  Set a value on A.Prop that C.Prop will change before it sets. Lets call this value X.
2.  A raises AvaloniaPropertyChanged event for Prop with value X
3.  A sends an update to its binding to update to value X.
  a.  Value X is set on C.
  b.  C changes value X to value Y before raising `PropertyChanged`
  c.  C raises `PropertyChanged` after setting `Prop` to Y
  d.  Because A.Prop <--> C.Prop is two-way, A.Prop is set to Y
  e.  Because B.Prop <--> A.Prop is two-way, B.Prop is set to Y
  f.  At this point, A.Prop, B.Prop, C.Prop all equal Y.
4. Because B.Prop <--> A.Prop is two-way, B.Prop is set to X
5. Because B.Prop <--> A.Prop is two-way, A.Prop is set to X
6. Go to step 2.

Now I have no idea how to fix this, but at least we have the execution path to work with.

**Comment by jkoritzinsky** [comment]
In this case it looks like we can just make B update A before C, since that will lead us to a steady-state. However, that does not work in all cases. Let's look at the situation below:
