### ISSUE TITLE
Error while compiling application

### ISSUE THREAD

**Issue by Slupy** [AvaloniaUI/Avalonia#8576]
When the application starts, it starts and freezes, and an error is written in the debug console:
[Visual] Exception in render loop: 'System.Runtime.InteropServices.COMException (0x80070057): Resize failed

**Comment by maxkatz6** [comment]
@Slupy it's not possible to help without being able to reproduce it. Do you have anything that might help?

**Comment by Slupy** [comment]
@maxkatz6 I don't even know what can help.

Here's what I'm using:
4GB RAM
Windows 10
VSC Preview (latest)

**Comment by timunie** [comment]
In that case it can help to upload your entire solution to a new github repo. I think there's smth broken in your code.

**Comment by Slupy** [comment]
@timunie which version dotNET should be used?

**Comment by Slupy** [comment]
I'm using 6.0

**Comment by timunie** [comment]
I use also net 6.0

**Comment by timunie** [comment]
But again, if you show us what you have so far we may be able to help. 

Do.you have any custom control or something like this?

**Comment by Slupy** [comment]
@timunie I didn't change anything there. Just took a sample

**Comment by timunie** [comment]
That's very strange.

**Comment by timunie** [comment]
Please upload your sample here. There must be anything wrong. 

Also which Avalonia version are you using?

**Comment by Slupy** [comment]
How to check the version?

**Comment by timunie** [comment]
> How to check the version?

In your nuget package manager.

**Comment by tkefauver** [comment]
I got this same error today and also months ago around when @Slupy posted this if I recall correctly. So its definitely intermittent because re-running started fine.

I'm using .net 6 on Windows:

Edition	Windows 11 Pro
Version	22H2
Installed on	‎10/‎4/‎2022
OS build	22621.1105
Experience	Windows Feature Experience Pack 1000.22638.1000.0

Pretty much the same console message:
`[Visual] Exception in render loop: 'System.Runtime.InteropServices.COMException (0x887A0005): Resize failed`

In Windows Event Viewer my system log shows a 'Display' Warning w/ Event ID '4101':
`Display driver igfx stopped responding and has successfully recovered.`

So its probably graphics hw related...My cards are:
 Nvidia quadro m1200 | Intel HD Graphics 630

**Comment by maxkatz6** [comment]
In this case this issue can be closed, as latest nightly does restart the rendering loop after driver has crashed.
