### ISSUE TITLE
Stackoverflow Exception when using some controls in ItemsControl with a data-bound Items property

### ISSUE THREAD

**Issue by DevJohnC** [AvaloniaUI/Avalonia#8760]
**Describe the bug**
When adding some controls (eg: ToggleSwitch) to a DataTemplate on ItemsControl it will cause a Stackoverflow Exception in a recursive measure call.

**To Reproduce**

Reproduced in full here: https://github.com/DevJohnC/ItemsControlStackOverflowReproduction

1. Create a new Avalonia project
2. Add an array or other list to the `MainViewModel`
3. Create an `ItemsControl` in `MainView.axml` and bind the Items property to the list you just created on `MainViewModel`
4. Create a `DataTemplate` for the bound items and add a `ToggleSwitch`
5. Run a debug session and observe the Stackoverflow exception

**Expected behavior**
Controls render as appropriate without causing a crash

**Desktop (please complete the following information):**

- OS: Windows10, macOS 12.5 (Monterey)
- Version: 0.10.18

**Additional context**
The issue isn't exclusive to `ToggleSwitch`; `TextBlock` is known to be exempt from the issue however.

Assigning a fixed size to either a container like `Panel` nor `ToggleSwitch` directly fixed the issue.

**Comment by jp2masa** [comment]
It's probably this: https://github.com/AvaloniaUI/Avalonia/issues/7985#issuecomment-1099696016.

**Comment by maxkatz6** [comment]
@jp2masa yes. DataTemplates.DataTemplate without x:DataType in it will be applied to literally everything that doesn't have any other template. Which very likely can cause stack overflow.
While that's by design:
- you can assign multiple templates inside of the DataTemplates and **it will be inherited**
- you can create DataTemplate without DataType, so it can be applied on any object type
Together these features work badly. It was restricted with additional validation before, but only for 11.0, as it's technically a breaking change - https://github.com/AvaloniaUI/Avalonia/pull/8221

Solution:
- Replace DataTemplates with single ItemTemplate. ItemTemplate is not inherited and isolated on the items control, that's why empty DataType will work fine.
- Set DataType to a specific one.

**Comment by maxkatz6** [comment]
Duplicate of #7985
