### ISSUE TITLE
Update ComboBox and it's Fluent theme

### ISSUE THREAD

**Issue by rabbitism** [AvaloniaUI/Avalonia#9052]
**Is your feature request related to a problem? Please describe.**
1. Fluent theme template has a `Header` part in it, but not applicable in Avalonia. This should be removed.
2. Consider adding a pseudo class `:popupopen` to control the style when popup is open. Of course, I can use PropertyEqual selector, but I think pseudo class is more reasonable. 
3. ComboBox never goes to `:pressed` (I don't know how to fix this)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
I can start to work on it if it's reasonable.

**Comment by robloo** [comment]
This makes sense to me.

I would however use ":flyout-open" pseudoclass which is the standard for other controls. It was added with the flyouts from WinUI which is more modern and higher level than popups.

**Comment by maxkatz6** [comment]
AutoCompleteBox has `:dropdownopen`.
And buttons with flyout property (including DropDownButton) have `:flyout-open`.
It can be explained with "Buttons have a Flyout property, so pseudoclass is about flyouts", but it's still something we missed.

Regardless of naming, this proposal is reasonable.

**Comment by robloo** [comment]
Good point about `:dropdownopen` pseudoclass. A few comments:

 1. This makes sense for controls such as `AutoCompleteBox`, `ComboBox` and even `DropDownButton` because these controls have clear drop-downs which are slightly conceptually different than flyout. HOWEVER,
 2. `DropDownButton` really can't change from `:flyout-open` because, as you said, it's a button and inherits this.

So it might be the lesser of two evils to standardize ALL controls to the `:flyout-open` pseudoclass -- even `AutoCompleteBox`. Alternatively, we could just add `:dropdownopen` to `DropDownButton` in addition to `:flyout-open`. What do you think?

The name might need a dash as well `:dropdown-open`.
