### ISSUE TITLE
FreeDesktop folder picker doesn't work

### ISSUE THREAD

**Issue by int21h-dz** [AvaloniaUI/Avalonia#9383]
**Describe the bug**
Instead of OpenFolderDialog shows OpenFileDialog and in resalt returns null

**To Reproduce**
var window = this.GetVisualRoot() as Window;
var dial = new OpenFolderDialog();
var rez = dial.ShowAsync(window);

**Desktop**

- OS: Linux 
- Version 11.0.0-preview2, 11.0.0-preview3

**Comment by int21h-dz** [comment]
But OpenFileDialog work fine. 

    private async void Button_OnClick(object? sender, RoutedEventArgs e)
    {
        var folders = await GetStorageProvider().OpenFolderPickerAsync(new FolderPickerOpenOptions()
        {
            Title = "Folder file",
            //SuggestedStartLocation = lastSelectedDirectory,
            AllowMultiple = false
        });

    }
    Window GetWindow() => this.VisualRoot as Window ?? throw new NullReferenceException("Invalid Owner");
    TopLevel GetTopLevel() => this.VisualRoot as TopLevel ?? throw new NullReferenceException("Invalid Owner");
    private IStorageProvider GetStorageProvider()
    {
        var forceManaged = this.Get<CheckBox>("ForceManaged").IsChecked ?? false;
        return forceManaged
            ? new ManagedStorageProvider<Window>(GetWindow(), null)
            : GetTopLevel().StorageProvider;
    }
Looks strange and falldown with error on BuildAvaloniaApp().StartWithClassicDesktopLifetime(args): System.Collections.Generic.KeyNotFoundException: Could not find control 'ForceManaged'.

**Comment by int21h-dz** [comment]
It is show Open_File_Dialog too ;(

**Comment by timunie** [comment]
@int21h-dz which Linux exactly do you use?

**Comment by int21h-dz** [comment]
@timunie Astra Linux - its fork of Debian

**Comment by maxkatz6** [comment]
@int21h-dz you don't need to use ManagedStorageProvider explicitly unless you want to.
Normally this API is accessed with `window.StorageProvider.OpenFolderPickerAsync`.

**Comment by maxkatz6** [comment]
But OpenFolderDialog and OpenFileDialog should also work on desktop even being deprecated.

**Comment by int21h-dz** [comment]
@maxkatz6 
![Screenshot_20221109_100526](https://user-images.githubusercontent.com/7300707/200762366-cd251b57-72a4-45a8-866e-27ab5d0b8d96.png)
Everything broke overnight. Yesterday OpenFolderPickerAsync worked.
Жесть какая

**Comment by maxkatz6** [comment]
@int21h-dz it might be something distro specific. On linux there are many implementations for the dialogs, and by default it is prioritized by this order: FreeDekstop pickers, GTK pickers, and managed (Avalonia impl) pickers.
FreeDesktop was added in 11.0. It is used with old and new APIs.

On your screenshot it seems to be FreeDesktop one. Specifically, [org.freedesktop.portal.FileChooser](https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.FileChooser). As you can see there in the docs: `directory b: Whether to select for folders instead of files. Default is to select files. This option was added in version 3.`.
I am not an expert in linux distros, but could it be that yours doesn't support directory parameter? Can you possibly debug pickers avalonia source code? I also wonder what version would be returned from `fileChooser.GetVersionAsync`.

Also, you can disable FreeDesktop using this `With` options in your `BuildAvaloniaApp`:
```
public static AppBuilder BuildAvaloniaApp()
    => AppBuilder.Configure<App>()
        .UsePlatformDetect()
        .With(new X11PlatformOptions
        {
            UseDBusFilePicker = false // to disable FreeDesktop file picker
        })
```

**Comment by int21h-dz** [comment]
@maxkatz6 Sorry, my knowledge is not enough to debug avalonia. But the solution with UseDBusFilePicker = false worked. Thanks.

**Comment by ds5678** [comment]
I think this may be affecting my application, too. I received a report for similar behavior with Ubuntu 20.04.

**Comment by maxkatz6** [comment]
I am going to close this issue as it doesn't seem to be related to Avalonia, but rather to a specific setup of the distributive.
For the linux setup it is possible to choose one of the three different file pickers.

By default, FreeDesktop DBus one is used (starting with 11.0).
It can be disabled with:
```
public static AppBuilder BuildAvaloniaApp()
    => AppBuilder.Configure<App>()
        .UsePlatformDetect()
        .With(new X11PlatformOptions
        {
            UseDBusFilePicker = false // to disable FreeDesktop file picker
        })
```

Next by priority is GTK file picker, but it was known to be even less stable. It will be used when UseDBusFilePicker is disabled.

Also, it's possible to enable Managed File Picker:
```
public static AppBuilder BuildAvaloniaApp()
    => AppBuilder.Configure<App>()
        .UsePlatformDetect()
        .UseManagedSystemDialogs()
```
Instead of using native file picker, with this configuration managed avalonia window will be opened, assuming there is full access to the file system.

Legacy file picker dialogs use new ones internally, so same configuration is applied there.

This also will be added to the documentation of the new file pickers, when we will have documentation for the 11.0.
