### ISSUE TITLE
AvaloniaProperty.RegisterAttached doesn't work when THost is an interface

### ISSUE THREAD

**Issue by aelij** [AvaloniaUI/Avalonia#959]
`SetValue` throws "Property 'MyProperty not registered on 'MyControl".

**Comment by grokys** [comment]
Yeah, this is the case with WPF as well I think. I would like to make `AvaloniaProperty` registration work on interfaces but it's not been a priority so far, and it makes resolving properties more difficult: every interface implemented by a class needs to be searched instead of just the class and its base classes.

**Comment by aelij** [comment]
I think the check could be as simple as a `Type.IsAssignableFrom()` call, but I may be wrong.

**Comment by aelij** [comment]
While interfaces are not supported, we should throw during registration.
