### ISSUE TITLE
TextBlock and resetting _textLayout in Arrange and Measure

### ISSUE THREAD

**Issue by Gillibald** [AvaloniaUI/Avalonia#9849]
### Discussed in https://github.com/AvaloniaUI/Avalonia/discussions/9826

<div type='discussions-op-text'>

<sup>Originally posted by **msneijders** December 31, 2022</sup>
I profiled a DataGrid (with only TextBlocks in cells) and a simple ItemsRepeater with 3 TextBlocks per item.

A big part of cpu time is, not surprisingly, in `TextBlock.CreateTextLayout(string? text)`. What did surprise me was it looked like it was doing this two times for each TextBlock that needed painting (while scrolling).

Question: does anyone know the reason this textlayout cache is reset in:
- https://github.com/AvaloniaUI/Avalonia/blob/740f6afffc6a5b8cd2bc4113081b0285ac3844a0/src/Avalonia.Controls/TextBlock.cs#L729
- https://github.com/AvaloniaUI/Avalonia/blob/740f6afffc6a5b8cd2bc4113081b0285ac3844a0/src/Avalonia.Controls/TextBlock.cs#L666

I removed those lines, and got about 29% increase in frames per second in my tests. All avaloniaui unit tests still run. But those resets probably exists for a reason?</div>

**Comment by MrJul** [comment]
I *think* the `_textLayout` reset in `ArrangeOverride` can be removed without consequences, I can't imagine a scenario where it would matter and where it wouldn't be the responsibility of the parent to re-measure its child `TextBlock` (for example, because the requested size couldn't be granted).

That said, it's not because I can't think of a scenario that none exist :) That's typically the type of change that will break someone somewhere with a very specific layout... Imho, it's still worth a shot. What do you think @Gillibald?

For comparison, for simple content (no inlines) [WPF doesn't do much in `ArrangeOverride`](https://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Controls/TextBlock.cs,1464) .

The reset in `MeasureOverride` is definitely needed to correctly propagate size changes, but some optimizations can probably be added. In `MeasureOverride`, [WPF tries to avoid doing anything](https://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Controls/TextBlock.cs,1281) if some conditions are true:

> // Assuming that all of above conditions are true, Measure can be
> // skipped in following situations:
> // 1) TextTrimming == None and:
> //      a) Width is the same, or
> //      b) TextWrapping == NoWrap
> // 2) Width is the same and TextWrapping == NoWrap

**Comment by Gillibald** [comment]
We can try to remove it but we need to make sure panels like Grid etc. still work properly in combination with a TextBlock etc. 

I can't remember exactly what corner cases needed this. Maybe it is no longer needed.

This is definitely worth a try.

**Comment by Gillibald** [comment]
I have already made this change: https://github.com/AvaloniaUI/Avalonia/blob/2b123edbcded4e67bf788fcbc50415b44cc9bb45/src/Avalonia.Controls/TextBlock.cs#L728

But the check might not be needed and we just have to arrange embedded control

**Comment by Gillibald** [comment]
We can't remove the TextLayout entirely but I could reduce it to a minimum
